### ISSUE TITLE
deleting API keys

### ISSUE THREAD

**Issue by JackHayson** [exodus4d/pathfinder#10]
Deleting your API key in the Eve-Account Management seems to break stuff in PF.

You can't delete the old key in PF and adding a new one causes a 500 internal server error. (even though it seems to get added)
It also causes character selection and tracking to break.

**Comment by exodus4d** [comment]
Thanks for reporting! Ill check it.

**Comment by exodus4d** [comment]
This will be fixed with SHA: 67861c278d0cf9e00c83dcedca51f2911c9b9759
