### ISSUE TITLE
Not usable on HiDPI screens (4k monitors) using In-Game Browser

### ISSUE THREAD

**Issue by proycon** [exodus4d/pathfinder#101]
Although the interface looks really nice (great work on that!), it is unfortunately not usable on 4k screens using the in-game browser. The in-game browser has, as far as I could find, no way to zoom, so everything is way too small to be usable on my screen (3840x2160). A zoom function for the map and the entire interface (mainly font-size) would solve this.

**Comment by exodus4d** [comment]
I have a 4k screen as well. The whole project was developed and tested in a
4k screen. It is small thats right but i havent seen any problems. The IGB
has no options for zooming. There are no plans for now to increase the font
size. IgB support is deprecated anyways and Ccp does not update the
browser.

Maarten van Gompel <notifications@github.com> schrieb am Fr., 19. Feb. 2016
18:15:
