### ISSUE TITLE
Pathfinder denied access by ESI?

### ISSUE THREAD

**Issue by dkovar** [exodus4d/pathfinder#1010]
Some of our users cannot log into Pathfinder. The ones who can login aren't being tracked. While trying to manage PF we got a 401 error - "You have been banned from using ESI".

This is clearly an issue. Any ETA?

Thanks for a great tool!
![Untitled](https://user-images.githubusercontent.com/2086992/102626506-e3af4d00-4114-11eb-8a9a-71ce67f78cc7.jpg)

**Comment by nightf0x0012** [comment]
I'm pretty sure that this goes with the ticket that I opened a few hours ago. Hopefully it can be fixed quickly.

**Comment by dkovar** [comment]
Agreed!

**Comment by theshankyinstitute** [comment]
> I'm pretty sure that this goes with the ticket that I opened a few hours ago. Hopefully it can be fixed quickly.

Yep, I commented on that one too, having the exact same issue in nightf0x0012's bug report. I can login to esi.evetech.net just fine, but public pathfinder is showing Tranq and ESI are down and not let me authenticate. Some corp mates can authenticate but PF is not auto-updating as they jump systems.

For a test, I temporarily setup my own private instance of PF. When I land on the homepage it shows Tranq and ESI as being ONLINE, unlike the public PF instance. I'm able to authenticate here just fine, unlike the public PF instance. But of course I can't access my corporation's map on the public server this way so I'm pretty much boned.

**Comment by GQuantrill** [comment]
The error from the getServerStatus reads as...

`You have been banned from using ESI. Please come chat with us in #esi on tweetfleet slack and we can work to a (truncated...)`

I've run pathfinder as a docker image and it worked fine locally

**Comment by dkovar** [comment]
I think the public PathFinder instance was making too many ESI calls and
was banned. I think private instances are OK.

**Comment by ion9** [comment]
they are on the same code base.... from what i'm seeing PF did not make a update for esi changes. and now PF instances are generating calls to old endpoints, making errors.

**Comment by dkovar** [comment]
It isn’t the code base, it is who is using it and the volume if calls they are making to ESI

**Comment by dkovar** [comment]
Closing this issue. Tracked elsewhere, not a code problem, solution is to set up a private instance.
