### ISSUE TITLE
[Feature Request] Ability to set destination to trade hub/routes

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#102]
I can set destinations by right clicking on systems in the map, but if i'm looking at a k-space system in the routes frame, I can only see the route path. Right clicking on Jita or Dodixie does not give me an option to set a destination, this would be very helpful, especially if it could be any system that we search a route for and not just hubs.

Can something like this be added?

**Comment by exodus4d** [comment]
Yeah good idea! it is not hard to implement something like this. Ill think about it

**Comment by atkinsj** [comment]
It would be great to include an 'exit finder' on this similar to Siggy -- just a 'what exit will get me to this specific k-space system the quickest?'

**Comment by exodus4d** [comment]
I added a new context menu to the "routes module". This is coming with the next release:

![route_waypoint](https://cloud.githubusercontent.com/assets/9299033/16199792/3dececdc-370b-11e6-93f4-bdce4ae6c9d7.png)
