### ISSUE TITLE
Unable to change number fo alliances allowed for Alliance Map 

### ISSUE THREAD

**Issue by eboaen** [exodus4d/pathfinder#1028]
Setting in pathfinder.ini is set for 5 alliances for PATHFINDER.MAP.ALLIANCE, but the UI in the Alliance Map GUI is telling me only 2 are allowed on existing maps.

Rebooted to apply settings, no change.

Do I need to make a change somewhere else?

**Comment by mekhami** [comment]
@eboaen Did you find a solve for this?

**Comment by eboaen** [comment]
It seemed to fix itself after about 2-3 hours?  I'm guessing I didn't restart a process that I needed to for this to take effect.
