### ISSUE TITLE
Adding systems to map does not update the map

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#103]
There's a pretty critical bug at the moment where if you create a new map then add a system to it, the dialog does not close and the map does not update. Attempting to add the same system again results in an Error 500 and if you check the logs you will see:

> [Mon Feb 29 20:51:23.196348 2016] [:error] [pid 48631] [client 127.0.0.1:65325] PDOStatement: Duplicate entry '7-30002036' for key 'system___mapId__systemId', referer: http://pathfinder.dev/map

The system is in the database and has been added but the map is not updating, this does not seem to be due to cache control. I've reproduced this on my local developer box, my hosted copy and on https://www.pathfinder-w.space.

I'm unsure if this is related but it appears once the bug is triggered, selecting the 'Add button' to add a new map results in the attached. This is on Chrome 48 on OSX 10.11.

The JavaScript console shows: Uncaught TypeError: Cannot read property 'updated' of undefined map.js:601

![brokenadd](https://cloud.githubusercontent.com/assets/10431664/13391248/68e11814-df27-11e5-9b08-bdbfb6a516c7.jpg)

**Comment by atkinsj** [comment]
Looks like a rename snafu in js/app/map/map.js -- 'data.updated.updated' instead of 'data.updated'.

**Comment by exodus4d** [comment]
Thanks for reporting!

This should be fixed with #114 (users are no longer able to store same system multiple times)
The error is thrown by the DB, (combination of `mapId` and `systemId` is a `unique`key) - which is OK

I checked the code again, and there is still something to improve ;)
