### ISSUE TITLE
Sign in issue: Access denied. CCP SSO service timeout (4s). Try again later

### ISSUE THREAD

**Issue by EdwardGaddfree** [exodus4d/pathfinder#1034]
![image](https://user-images.githubusercontent.com/5840127/132238007-762b79ab-8074-4fe2-be22-7b82f810c3a4.png)

Pathfinder worked fine up to today. I have tried logging in multiple times today, but I keep getting the error above.  I've tried waiting an hour like it says, but got the same issue again.

To add more detail, I get the above screen after trying to log in, going through the EVE SSO process, selecting my character, and clicking "Authorize".

**Comment by mswolters** [comment]
> CCP Ghostrider  6:01 PM
> Ahhh, you can't send this as JSON
> 6:02
> it should be form-data
> Prometheus Satyen  6:02 PM
> It's worked as JSON for over a year, is this a change?
> CCP Ghostrider  6:02 PM
> I've been saying it for years, it working as JSON was an error really and not in accordance with the OAuth spec :slight_smile:

**Comment by Ricaz** [comment]
So it seems the API no longer supports JSON suddenly?

The change would have to be in the [pathfinder_esi repo](https://github.com/exodus4d/pathfinder_esi/blob/master/app/Client/Ccp/Sso/Sso.php), I think.

**Comment by jrhigueras** [comment]
Changing `json` to `form_params` in **line 60** of the **Sso.php** file, fixes the issue.
[https://github.com/exodus4d/pathfinder_esi/pull/19](https://github.com/exodus4d/pathfinder_esi/pull/19)

**Comment by sexysback** [comment]
so what do i need to do to fix this issue

**Comment by jrhigueras** [comment]
> so what do i need to do to fix this issue

Just open the file `vendor/exodus4d/pathfinder_esi/app/Client/Ccp/Sso/Sso.php` under your installation path with a text editor. Then go to line 60, you should see something like:
```php
$requestOptions = [
    'json' => $requestParams,
    'auth' => $credentials
];
```

Change it to:
```php
$requestOptions = [
    'form_params' => $requestParams,
    'auth' => $credentials
];
```

It should work now.

**Comment by SirVulcanoWydro** [comment]
>Sorry but instalation of what ?? Pathfinder ? This APP have no instalation. I open it direct from web site.  I can't find these files on my computer:(
> 
> > so what do i need to do to fix this issue
> 
> Just open the file `vendor/exodus4d/pathfinder_esi/app/Client/Ccp/Sso/Sso.php` under your installation path with a text editor. Then go to line 60, you should see something like:
> 
> ```
> $requestOptions = [
>     'json' => $requestParams,
>     'auth' => $credentials
> ];
> ```
> 
> Change it to:
> 
> ```
> $requestOptions = [
>     'form_params' => $requestParams,
>     'auth' => $credentials
> ];
> ```
> 
> It should work now.

**Comment by mswolters** [comment]
Then ask whoever hosts that to apply this fix

**Comment by Ricaz** [comment]
@SirVulcanoWydro you would have to install Pathfinder yourself to apply the fix.
The author has been silent for a while and it seems the project might only survive on community contributions from now on.

**Comment by SirVulcanoWydro** [comment]
Maybe some link to the instalation this App on PC ?? 

> @SirVulcanoWydro you would have to install Pathfinder yourself to apply the fix.
> The author has been silent for a while and it seems the project might only survive on community contributions from now on.

**Comment by jrhigueras** [comment]
> Maybe some link to the instalation this App on PC ??
> 
> > @SirVulcanoWydro you would have to install Pathfinder yourself to apply the fix.
> > The author has been silent for a while and it seems the project might only survive on community contributions from now on.

See https://github.com/exodus4d/pathfinder/wiki

**Comment by terencevs** [comment]
@SirVulcanoWydro corps host Pathfinder themselves, from the sounds of it, you are in the same situation as me. We both use https://www.pathfinder-w.space/ and are waiting on the fix to be applied...

**Comment by Ricaz** [comment]
I know this is off-topic, but I would highly recommend everyone to host it themselves. It will be much more reactive and snappy. Also you get unlimited everything.

**Comment by SirVulcanoWydro** [comment]
> 
> 
But 2 month ago that was fully functionally. My new corporation link to Pathfinder working teh same as this from web site . Logging is correct but later "Akcess denied ":( 

> @SirVulcanoWydro corps host Pathfinder themselves, from the sounds of it, you are in the same situation as me. We both use https://www.pathfinder-w.space/ and are waiting on the fix to be applied...

**Comment by terencevs** [comment]
> I know this is off-topic, but I would highly recommend everyone to host it themselves. It will be much more reactive and snappy. Also you get unlimited everything.

I am investigating my options now, would prefer on docker.

**Comment by Ricaz** [comment]
It will require a bit of work to pack it into Docker, but still easier than manually installing everything.

Remember you need the WebSocket part for it to have instant updates instead of 5s polling.

**Comment by terencevs** [comment]
> > 
> 
> But 2 month ago that was fully functionally. My new corporation link to Pathfinder working teh same as this from web site . Logging is correct but later "Akcess denied ":(
> 
> > @SirVulcanoWydro corps host Pathfinder themselves, from the sounds of it, you are in the same situation as me. We both use https://www.pathfinder-w.space/ and are waiting on the fix to be applied...

send your corp to this page to see the fix that they need to apply.

**Comment by Tupsi** [comment]
> It will require a bit of work to pack it into Docker, but still easier than manually installing everything.
> 
> Remember you need the WebSocket part for it to have instant updates instead of 5s polling.

there are some docker builds out there, I did one myself long ago, but that is most likely not functioning now with all that is happening. You can check out the slack server of pf, its still active with developers and ask there for a working one. I just hotfixed my installation with this and had to pull out the vendor directory for it, but at leasts its working again, so thanks for this @jrhigueras !

**Comment by terencevs** [comment]
FYI https://www.pathfinder-w.space/ seems to be working now.

**Comment by SirVulcanoWydro** [comment]
> 
>  You are right . What's changing ??
> FYI https://www.pathfinder-w.space/ seems to be working now.

**Comment by EdwardGaddfree** [comment]
> FYI https://www.pathfinder-w.space/ seems to be working now.

Agreed, the issue is now resolved from what I can see on my end.  No idea what changed but I can now log in again.
