### ISSUE TITLE
Password reset/recovery

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#104]
This might be local to your deployment at pathfinder-w.space, but if someone does not remember their password/username, they can never log in again.  Is there a reset password or recovery of username that is in the works or is it already there and i'm just missing it?

**Comment by exodus4d** [comment]
Unfortunately this was never implemented :(

But, the login system is deprecated anyways and will be removed with the next release. ;)
Im working hard on the SSO login using CCPs CREST API. There is no need to store login informations in *Pathfinder*. The login process is completely handled by CCPs API. - `password` column was removed from the DB.
