### ISSUE TITLE
Packets out of order

### ISSUE THREAD

**Issue by oSkrobuk** [exodus4d/pathfinder#1041]
> 2021/10/24 10:17:32 [error] 612466#612466: *2228500 FastCGI sent in stderr: "PHP message: Packets out of order. Expected 1 received 16. Packet size=3195406PHP message: [vendor/bcosca/fatfree-core/db/sql.php:519] PDO->__construct()PHP message: [app/Lib/Db/Sql.php:19] DB\SQL->__construct()PHP message: [app/Lib/Db/Pool.php:185] Exodus4D\Pathfinder\Lib\Db\Sql->__construct()PHP message: [app/Lib/Db/Pool.php:142] Exodus4D\Pathfinder\Lib\Db\Pool->newDB()PHP message: [app/Model/AbstractModell.php:152] Exodus4D\Pathfinder\Lib\Db\Pool->getDB()PHP message: [app/Model/AbstractModell.php:1118] Exodus4D\Pathfinder\Model\AbstractModel->__construct()PHP message: [app/Controller/Ccp/Sso.php:468] Exodus4D\Pathfinder\Model\AbstractModel::getNew()PHP message: [app/Controller/Ccp/Sso.php:199] Exodus4D\Pathfinder\Controller\Ccp\Sso->getCharacterData()PHP message: [index.php:27] Base->run()" while reading response header from upstream, client: IP, server: hostname, request: "GET /sso/callbackAuthorization?code=..... HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:"

Hi. Please tell how to fix this problem? Sometimes there is error:

> 2021/10/24 10:17:29 [error] 612466#612466: *2228500 FastCGI sent in stderr: "PHP message: Packets out of order. Expected 1 received 49. Packet size=9190812PHP message: [vendor/bcosca/fatfree-core/db/sql.php:519] PDO->__construct()PHP message: [app/Lib/Db/Sql.php:19] DB\SQL->__construct()PHP message: [app/Lib/Db/Pool.php:185] Exodus4D\Pathfinder\Lib\Db\Sql->__construct()PHP message: [app/Lib/Db/Pool.php:142] Exodus4D\Pathfinder\Lib\Db\Pool->newDB()PHP message: [app/Model/AbstractModell.php:152] Exodus4D\Pathfinder\Lib\Db\Pool->getDB()PHP message: [app/Model/AbstractModell.php:1118] Exodus4D\Pathfinder\Model\AbstractModel->__construct()PHP message: [app/Controller/Controllerr.php:313] Exodus4D\Pathfinder\Model\AbstractModel::getNew()PHP message: [app/Controller/Api/User.php:129] Exodus4D\Pathfinder\Controller\Controller->getCookieCharacters()PHP message: [index.php:27] Base->run()" while reading response header from upstream, client: IP, server: hostname, request: "POST /api/User/getCookieCharacter HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:"

Restart mysql doesn't help. Only restart of the php7.4-fpm helps

**Comment by TyrHeimdalEVE** [comment]
Could be that you need to expand the allowed packet size or max connections to the Database.

Also please see https://github.com/exodus4d/pathfinder/issues/1039

**Comment by oSkrobuk** [comment]
> Could be that you need to expand the allowed packet size or max connections to the Database.
> 
> Also please see #1039

Thx!
