### ISSUE TITLE
Routing does not work

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#105]
Returns a "route not found" on every route. Unable to verify this on your pathfinder-w.space instance as I'm still getting the 'error 500 save system' error when trying to add a system to a map.

**Comment by seandsanders** [comment]
Have you seen #100? In addition to fixing the shattered/no statics problem, it also fixed this issue for me. After importing it, I had to clear the cache folder for it to update.

**Comment by atkinsj** [comment]
Yeah, static data export is in and cache is cleared. The static data seems to be working elsewhere as well because I can select systems from the drop down to add to the map.

**Comment by atkinsj** [comment]
Okay scratch that I am retarded -- I did not see that this is a third set of files (SDE, Pathfinder, this new one). My bad.
