### ISSUE TITLE
Mass adding signatures overrides the ones already present

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#108]
I would be nice, if the mass adding of signatures ignores the one who are already present. Currently a CTRL-A, CTRL-C, CTRL-V sequence overrides all data currently present, so for instance if you already have two sigs fully scanned in there, and the next person comes with the "lets paste everything in first before I start scanning" brute force method, that person overrides the two scanned sigs with the innitial "unknown".

Would be nice if the paste would ignore sigs already present.

Or if people actually like the current behavior make it a switch in settings for people which version they want.

So I am a bit unsure myself if I would actually consider this being a "bug" or a "feature" who it is implemented currently. Guess we will find people for both options :-)

**Comment by Drisker** [comment]
This is mentioned in #81 and considered a bug.

**Comment by Tupsi** [comment]
thanks for mentioning it. So I close this one. But good to see, that my guys arent the only one thinking this isnt minor!

**Comment by exodus4d** [comment]
Thanks for reporting!

This is fixed in #81
