### ISSUE TITLE
Database Schemas not released.

### ISSUE THREAD

**Issue by IvandaNothabeer** [exodus4d/pathfinder#11]
Hi. yes, I know you have not released these on purpose. But really, they are badly needed before we can offer any feedback or development assistance.

**Comment by mglinski** [comment]
See #6, I will be releasing some base schema there "soon"^tm

**Comment by mglinski** [comment]
I made a wiki article to help with setting this app up for people who might not know 100% what to do.

The DB Dump is in there: https://github.com/exodus4d/pathfinder/wiki/beta

**Comment by exodus4d** [comment]
A Clean Database Export [CDE] is now awailable. Linked in the [wiki](https://github.com/exodus4d/pathfinder/wiki)
More information for installation will be available with v.0.0.10

Thanks @mglinski for kick off!

**Comment by mglinski** [comment]
I would very much recommend that you put the db schema in the repo as a .sql file. As the application changes, the tables will likely change and having a version history will be nice. Also have the sql ready to go when your clone the repo is handy.

**Comment by exodus4d** [comment]
Yeah that is still on my "TODO" list. ;)
