### ISSUE TITLE
Statics gets messed up

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#110]
Sometimes pathfinders seems to make an error in looking up the correct static. For instance you have a C5 static C5, so it should display H296. If you now add a wh sig to the system table you can only select a M267 - C3 as static, although the system info window clearly states that this system has a H296 as static. 
At some point in time it fixes itself though, but I can not give you exact "whens" and "whys".
(trying to upload a screenshot but git doesnt like me tonight it seems).
![Uploading StaticMixup.jpg…]()

**Comment by Tupsi** [comment]
![staticmixup](https://cloud.githubusercontent.com/assets/3730499/13756081/7b24a070-ea1e-11e5-952d-4cbcdf89b829.jpg)

**Comment by Tupsi** [comment]
ohh, that worked at least.

**Comment by Tupsi** [comment]
ok, forcing a few reloads with the browser, at some point the dropdown now shows the H296 as it should be and you can select and save it.
This is not a one time thing, it happens here regularly, so something odd still must be in there. :-)

**Comment by Tupsi** [comment]
a bit more testing reveals the following:

setup:
a) C5 wh system with a static C5
b) C5 connected to a) and having a C3 static itself

set static sigs for both systems. You will see that you can only either have a Static C3 in the dropdown in both systems OR a Static C5 options. Whatever it is you save, the moment you hit refresh it changes to the correct value for the system you have currently selected, BUT if you select the other system, you will see that the static there has changed now to the value of the other system.
From the looks of it, it seems that the application leaves only room for one static value per system type (both here are C5 but with different static types), because if I add another system to that chain (which would have to be a C3 in the example) and that system has a static low for instance, this one seems fixed correctly.

**Comment by Tupsi** [comment]
still more testing it seems to be "only" a browser cache thing. If you switch from a) to b) or vice versa the static always wrong until you hit a hard F5 refresh in the browser. Then the current system you have selected shows the correct static, but selecting the other system now (without F5 refreshing) shows you the wrong one. Hitting F5 gives you the right and so on.

Tested with current versions of Firefox, Chrome and Edge. All the same. So it seems, something is just cached bad at the client end and the db entries itself or correct.

**Comment by exodus4d** [comment]
Thanks for reporting! 

This bug is already fixed (#119) and will be shipped with the next release (coming soon!).
It was in fact a client cache problem.

**Comment by exodus4d** [comment]
Issue resolved in `master` branch
