### ISSUE TITLE
date is one month off

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#111]
Every sig you put into pathfinder is off by one month. For instance stuff you enter right now gets show as 14.02.2016 20:32

**Comment by sn0opy** [comment]
Is your server time even correct?

**Comment by Tupsi** [comment]
Is that a serious question? Of course it is. Wrong server time is usually of by hours if set to wrong time zones are completly off it not set at all, but NOT off by exactly one MONTH.

**Comment by sn0opy** [comment]
Check the `system_signature` table in the DB if the date is also off by 1 month. I just set it up yesterday and it works for me.

How did you add the signature? Manually or or through the signature reader from you clipboard?

**Comment by Tupsi** [comment]
they are correctly dated in the database, strange:

2016-03-15 20:31:28 	2016-03-15 20:34:18

but when I mouseover the ? in the sig row the mouseover shows the 15.02.2016 19:34, which is correct as its -1 to CET.

Server is set to CET, date shows:
date
Tue Mar 15 20:34:47 CET 2016

I tried both adding manuelly and c&p stuff.

Dont get it. Where does even the german date formating comes from? Does the IGB pulls that out of my windows installation? Can it even do that? Because ingame if you hover over the time in the lower left corner you see the date listed as 2016.03.15.

**Comment by exodus4d** [comment]
Could you fix it?

If not, please consider the following:
- Pathfinder should always display and store *EVE Time* time stamps.
- The timezone (used by any PHP script) can be defined in config.ini (default: UTC - should be fine)
- The timezone (used by the DB) is automatically set to UTC for the current session ([database.php L.53](https://github.com/exodus4d/pathfinder/blob/master/app/main/db/database.php#L53))
- The current Server time can be checked on the setup page (http://[YOUR_DOMAIN]/setup)
- The German date format in the Sig-table is my fault :( ( Ill change the display format )

**Comment by Tupsi** [comment]
no I could not. Frankly I have no idea how this can happen in the first place as we are talking -1 month instead of the usual +-1 hour thing. Just created a sig and it says 10.03.2016. Server time is
# date
Sun Apr 10 19:35:27 CEST 2016


the time itself is fine (-2 currently to germany as eve itself is), its the month which gives me headaches, NOT the hours.
![wrongmonth](https://cloud.githubusercontent.com/assets/3730499/14411828/db5f50f8-ff53-11e5-9f23-95a06cbf1862.png)

**Comment by Tupsi** [comment]
ok, I just added another sig from ingame to verify (up this one came from Firefox), but its still saying 19 for the hour. So you are in fact not writing eve time, but server time instead. So maybe this is the problem, that my server is set to CEST instead of UTC?

**Comment by Tupsi** [comment]
ok, I am confused now. For testing and to risk the wrath of Bob I changed the timezone of the server to UTC (dont ask my why I set it to Berlin in the first place please) which it should have be from the beginning of time anyway. All entries in the db now show -2 hours which means eve time, so whatever cool mysql wizz is going on there, it can apparently survive a dpkg-reconfigure tzdata.

While the hours now show eve time, the month is STILL one month off, which does not make sense at all. (In the browser only as you can see in the screenshots, the db has april in it as it should.)

**Comment by exodus4d** [comment]
Problem solved :)

it was in fact a client-side (javascript) bug in one of the "date convert" function.
The `new Date();` javascript Class constructor requires the current month as constructor param. ([util.js L1682](https://github.com/exodus4d/pathfinder/blob/01f91c4d58b263a9a1f15732a444a4f58de7d522/js/app/util.js#L1682))
The index of January = 1, February = 2,...

The `getUTCMonth();` return month indexes, started by 0: January = 0, February = 1,...

Therefore we have to add `+1` for each month.
