### ISSUE TITLE
DataTables Error when creating first sig

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#112]
I sometimes get the following JaveScript Alert box

DataTables warning: table id=DataTables_Table_3 - Requested unknown parameter 'status' for row 0. For more information about this error, please see http://datatables.net/tn/4

when creating a first sig manually. Didnt come up with a solid way to reproduce it so far, but it already happened more then once.

**Comment by exodus4d** [comment]
Thanks for reporting! - Very interesting bug... I did my best to reproduce this but i could not :(

Error Description: https://datatables.net/manual/tech-notes/4

I know exactly what that error means, but i could not find a way to reproduce. I checked all the related code for saving a new Signature. The changes a made will hopefully make the *saveSignature* endpoint saver for this kind of errors.

Could you provide any additional information that could help reproducing this? 

- How many users where active on this map?
- Was it you or someone else who created the first signature?
- Have you switched between systems a lot before this bug appears?

##### Error Description

- The "status" of a signature represents the **first** column in the table, which is in fact a colored "dot".
- The "status" is determined by the character who updated/created a signature and its relation to the character who is currently viewing the map:
-- green dot -> characters are in same corporation
-- blue dot -> characters are in same alliance
-- red dot -> characters have no relation to each other
