### ISSUE TITLE
Map connections should be straight line not bezier curves

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#115]
The curves look pretty and are impressive engineer but they really hurt the UI/UX and make pathfinder next to unusable on large maps.

At the very least this should be an option.

**Comment by exodus4d** [comment]
Thanks for your suggestion for improvement. There are no plans to make connection types  customizable :(

- Stargates -> "angled lines"
- Wormholes -> "curved lines"
- jumpbridges -> "straight lines"

If you you really want to change the styling (which I do not recommend ):

1. Edit `connection_scope` table data for those connection types
2. Edit (and generate) CSS styles for those connection types [_map.scss L359](https://github.com/exodus4d/pathfinder/blob/master/sass/layout/_map.scss#L359)
3. Edit (and build) JS for "default" connection styles [map.js L3359](https://github.com/exodus4d/pathfinder/blob/master/js/app/map/map.js#L3359)

So it is not that easy to change this. sorry
