### ISSUE TITLE
[Feature] Add the ability to set a map as the default

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#117]
If you have many maps (either from your corporation, alliance or yourself) then it can be frustrating to have to pick the map each time. Each account should be able to set a default map.

**Comment by exodus4d** [comment]
This is now in development and will be shipped with the next release.

**Comment by exodus4d** [comment]
Pathfinder now remembers your last open Map.
When you come back and this map is still available it will be insta-loaded and tab becomes active.

**Comment by rmcginnis** [comment]
totally awesome!
