### ISSUE TITLE
Can't select K162 - C1/2/3 (Unknown) in IGB

### ISSUE THREAD

**Issue by curiousstranger** [exodus4d/pathfinder#119]
When I attempt to set a wormhole type to K162 - C1/2/3 in the IGB, it ends up as S199 instead.

http://i.imgur.com/t0joxyj.png
http://i.imgur.com/YuF0mn1.png

**Comment by resinneublem** [comment]
Same happens out of game too.

**Comment by exodus4d** [comment]
Thanks for reporting, sorry for the late response (I was busy with the new CREST login process, coming in the next release).

This was a bug with the auto-generated signature-type IDs. Multiple select options with the same ID, does not work. IDs should be fixed now (coming with the next release)
