### ISSUE TITLE
Any frigate hole in a WH seems to restrict available types

### ISSUE THREAD

**Issue by curiousstranger** [exodus4d/pathfinder#121]
I select a Q003 type for a wormhole in a C2.  Once I do that, it restricts the other types of WH I can select in the type menu for all the other wormholes in the system http://i.imgur.com/vrEfEeA.png

**Comment by exodus4d** [comment]
Thanks for reporting, sorry for the late response (I was busy with the new CREST login process, coming in the next release).

Bug is fixed. This was a client-side (javascript) caching problem. Signatures were cached by `systemType`e.g. C2,  - Which, in turn is not correct.
Static WHs are not the same for each C2. So i excluded them from beeing cached.

**Comment by Tupsi** [comment]
This is fixed in develop, you should close it exodus
