### ISSUE TITLE
Losing maps?

### ISSUE THREAD

**Issue by resinneublem** [exodus4d/pathfinder#123]
Hi there,

I've gotta ask, are you resetting the database or intentionally deleting maps after a period of inactivity? I've logged in twice (after absences) and both times the previous map I created was gone and it prompted me to create a new one.

**Comment by exodus4d** [comment]
Ups totally forget about that issue :(

Yes `private` maps are deleted after a period of 7 days. 
check: https://www.pathfinder-w.space#pf-landing-maps
