### ISSUE TITLE
Automatically timeout wormholes based on their lifetime

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#124]
All wormholes have a predictable and known duration based on their lifetime; we should automatically age them out so that users don't have to mark them EoL.

**Comment by exodus4d** [comment]
Yeah we could :) I thought about this a couple of times. it´s not hard to implement that but I came to the end, that this could also bring some kind of confusion with it.

- Even if the lifetime is known for each wormhole. there is a +/- 10% variation 
- If the EVE-Server shuts down for some hours (e.g. patch-day... :) ) this will mess up everything, timestamps are not in-sync anymore. Wormholes are still stable, but become EOL in Pathfinder,...
- To make this feature real, we nee a mapping between (wormhole)-connections on the map and their known signature in the sig-table. wich makes it more complex for Scouts, mapping each signature to a wormhole...

Therefore there are no plans to implement something like this. :(

**Comment by atkinsj** [comment]
Hmm, I really think that having them removed off the map and not updating the the signature table is a valid way to approach this.

That's fine though I'm sure I can implement this as a cron on our instance. Thanks!
