### ISSUE TITLE
Standalone pathfinder.sql merged in to /setup

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#125]
At the moment new set-ups have to remember to bring in the standalone pathfinder.sql from the repo via a msyql import -- can we get this static data chucked in to /setup?

**Comment by exodus4d** [comment]
#####  The first  SQL query was moved to `/setup` route
Bootstrapping for `system_neightbour` table was moved to `/setup` route.
I added a new UI-panel for that.

- This *trunkates* `system_neightbour` table and (re)build the index for all systems in *EVE* (>5k).
- There are **two** reasons why you should use this new function:
  1. When you set up your database for the first time.
  2. When CCP added or removed solarsystems from *EVE*

> **Important:** The Index build function takes some seconds. Be sure to increase `max_execution_time` to ~30s! 

![setup_index](https://cloud.githubusercontent.com/assets/9299033/16884415/86754bb2-4ac9-11e6-8fe9-3efde911beb1.png)

**Comment by exodus4d** [comment]
##### ... and the remaining SQL data can now be im/exported as `*.csv` files

Tables with static data:
- `wormhole` - wormhole data (lifetime, ...)
- `constellation_wormhole` - static wormhole data for systems [by `constellationId`]
- `system_wormhole` - static wormhole data for a *specific* system (shattered wormholes) [by `systemId`]

Dump files for those tables are located under `export/csv`. I added new **im/export** buttons to `/setup` page. They can be used es an *alternative* to the `pathfinder.sql` import for those tables.

> **Important:** The table/column structure has changed for those tables! If you have a private installation running, you have to rebuild (drop/create) those **3** tables with the upcoming version. ->  **clear cache** afterwards!

![setup_index](https://cloud.githubusercontent.com/assets/9299033/16896348/3a133d42-4b91-11e6-99a3-eef1f15a4389.png)
