### ISSUE TITLE
Develop branch has a typo in model/charactermodel.php line 421

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#129]
getMaps is declared as `public function getMap(int $mapId){`. This causes an error any time a map is loaded and prevents the application being used at all -- you have the int specifier on the function and mapId is a string passed from api/map.php.

Sorry for spamming up your issues; wasn't sure how you wanted these things reported.

**Comment by exodus4d** [comment]
Interesting I didn´t got any error -_- Type casting on Scalar values is not supported in PHP: http://stackoverflow.com/a/5724696/4329969

**Comment by exodus4d** [comment]
Adding Issues for valid bugs (even on `develop` branch) is fine. But do not expect the branch to be very stable. ;)
