### ISSUE TITLE
Registration/Sign up - failure

### ISSUE THREAD

**Issue by gruender** [exodus4d/pathfinder#13]
Step 2 of the registration (API Key), 
link for API key setup did bring me to API Key Management but not to the "update page" (     Home > Support > API Key Management > Update )  where there would be adjustments selected.

while trying to find the information for the correct minimum API key adjustments I either got auto logged off or missklicked and closed the Pathfinder registration-page, which resulted in not finishing the registration.

After trying to register again I get a "500: save config error internal Server Error" and "Error email already exists" message. Seams like my email is saved although the registration is not finished/valid.

Login with the first selected name and password is not working ("wrong name and password" message).
Last thing I would have tried was to request a new password (might be i misswrote the name?), but I could not find any "forrgot/request password" button.

**Comment by exodus4d** [comment]
For now,  a new accound is saved successfully if the first registration
step is done. You should be able to log in even witbout entering any api
information. You should get a message after login that you api infirmation
is missing.

Request es new registration key is possible with an other mail address. If
you enter the same mail address twice you should geht the same key as
before. If you have successfully completed step1 your new account is stored
with your email. You can not create multiple accounts with the same email.

But yeah there are some problems witg api registration (step2). ill try to
fix them this weekend with.v.0.0.9.

Planned improvements.
- Confirmatiin mail with you account data after finishing step 1.
- fixing some bugs with api changing
- account delete option

gruender <notifications@github.com> schrieb am Sa., 12. Sep. 2015 06:44:

**Comment by exodus4d** [comment]
For now,  a new accound is saved successfully if the first registration step is done. You should be able to log in even witbout entering any api information. You should get a message after login that you api infirmation is missing. 

Request es new registration key is possible with an other mail address. If you enter the same mail address twice you should geht the same key as before. If you have successfully completed step1 your new account is stored with your email. You can not create multiple accounts with the same email. 

But yeah there are some problems witg api registration (step2). ill try to fix them this weekend with.v.0.0.9.

Planned improvements. 
- Confirmatiin mail with you account data after finishing step 1.
- fixing some bugs with api changing 
- account delete option

**Comment by gruender** [comment]
Thanks

**Comment by gruender** [comment]
is there somewhere i could look up the API key information which are required?

**Comment by mglinski** [comment]
The API key requires no permissions, it is just used to get a list of characters. You can use a key with a 0 mask.

**Comment by exodus4d** [comment]
That is correct :)
