### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by Hightech1011** [exodus4d/pathfinder#130]
Is there an admin interface where you can manage users?

Having an interface where you can add/modify/remove user from within the system.

**Comment by exodus4d** [comment]
With the next release, character login is handled by CCPs CREST API. You can set up a *white liste* for allowed corporations/alliances to login.

There is no Admin GUI available for now. But It is maybe coming in future :)

**Comment by Hightech1011** [comment]
Any suggestions on how to reset a users password if they have a derp moment?

**Comment by Bingmano** [comment]
> Any suggestions on how to reset a users password if they have a derp moment?

This was answered in issue #104 will be obsolete in SSO implementation.

**Comment by exodus4d** [comment]
The current release has a way to restrict login to certain corps/allys. As @Bingmano said before, the login process is now handled by CCPs SSO.
