### ISSUE TITLE
Signature reader spawns at the top of the window even if you are scrolled down

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#135]
This is not particularly important with the OGB but in the IGB if you have the Pathfinder window vertical and thin, so it falls in to the vertical layout, the signature reader always spawns at the top and you have to scroll back up looking for it.

It'd be great if it spawned where the viewport is currently looking.

**Comment by exodus4d** [comment]
This just occurs in the *IGB*. *IGB* is no longer supported :(
