### ISSUE TITLE
CREST end-points don't work if you aren't logged in via the website first

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#136]
Updated and re-wrote this after some more debugging; apologies for the e-mail spam.

So it appears that in order for CREST SSO to work you must login to Pathfinder via the OGB _first_. If you attempt to login via the IGB you will get an Error 502 bad gateway spat back. FoxFour hinted that this is a [bug in CREST.](https://forums.eveonline.com/default.aspx?g=posts&m=6437989#post6437989) but is rather unclear.

I'm not sure if there is a work around we can implement on the Pathfinder side or if we're handling the auth incorrectly but we should investigate.

**Comment by exodus4d** [comment]
Yeah, I don´t want to investigate to much time in developing "workarounds" or "polyfills" for the outdated IGB (based on a Chromium 3.0 Engine from 2006) if it is not necessary for some basic features. I´m pretty sure CCP will remove IGB from EVE at the point all EVE specific HTTP-Header data was moved into CREST. 
The only thing, IGB is still better than OBG is "ship tracking". There is no way to get the current ship(-name/-id) from a character over CREST.

CREST-API Caching is implemented and should work. Any request is cached by their corresponding response Header. [web.php#L103](https://github.com/exodus4d/pathfinder/blob/develop/app/main/lib/web.php#L103). This works pretty nice in all my tests. Any additional character generates about 0.2 CREST requests/second. The request limit is (as far as I know) 150 requests/second. Im pretty sure, before you hit the CREST Limit (about 750 active users) you will run into other problems before :) )

**Comment by atkinsj** [comment]
Whoops sorry for being unclear -- if the user is logged in to the EVE
client they can't login to Pathfinder via CREST in either the OGB of IGB.
This happens about 50% of the time in my tests.

It's pretty strange. Hopefully FoxFour can confirm this is a bug on their
end.

**Comment by atkinsj** [comment]
Update on this one: FoxFour can't reproduce and said this shouldn't a bug but I get this on your website, on my fork and on your original developer branch. I can poke around your source and try and figure it out but do you have any ideas off the top of your head?

https://forums.eveonline.com/default.aspx?g=posts&m=6455053#post6455053

**Comment by atkinsj** [comment]
Cool, this is fixed as at https://forums.eveonline.com/default.aspx?g=posts&m=6467479#post6467479.

CCP pushed the fix to TQ last night.
