### ISSUE TITLE
Types in the signature selection box aren't accurate

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#141]
In a C2 wormhole, a relic site can only be selected as 'Forgotten Perimter Gateway' or 'Forgotten Perimeter Habitation Coils' which is not correct; nullsec sites can spawn in C1-C3 holes. This means that it can't extract 'Ruined Angel Monument Site' as a type for example.

Similarly on a wormhole in a C2 I cannot select D382 as a valid wormhole signature type.

**Comment by exodus4d** [comment]
My bad, wrong commit message... Data/Relic sites should be added with this commit:https://github.com/exodus4d/pathfinder/commit/72f01b153d96a672e67dfef7242da8d28f3b4ca4

- Signature names are alphabetically sorted now.

**Comment by exodus4d** [comment]
Issue resolved in `master` branch
