### ISSUE TITLE
CREST tracking broken on develop

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#143]
The new framework base changes have broken CREST tracking.

I can't see any messages in any of the logs but I haven't had a chance to look in to it yet.

**Comment by VivianMeally** [comment]
Its CCP who has Broke characterLocationRead for about 5 days now.
So its not pathfinder Developers fault. 
https://forums.eveonline.com/default.aspx?g=posts&t=480278&find=unread

**Comment by exodus4d** [comment]
@VivianMeally: Awesome timing :) I was just about to start checking what was wrong with this...

To be honest, I haven´t tested **any** TQ-CREST endpoint so far. I even haven´t logged in to TQ for month :( All the developing and testing is done on SISI so far.

But what I can say from SISI´s CREST is, that I had a wide variety of problems/errors from time to time:
- Multiple down-times each day (SISI CREST is probably running in a CI build job without "fallback")
- The socket timeout sometimes exceeds the limit of **3seconds** (which should be more then enough)
- Sometimes I get a *HTTP 401* "Unauthorized" response even if all access data are valid
- Sometimes i get *HTTP 5xx*, Everything is fine (HTTP 200)

Most of these errors should be automatically logged in `log/error.log` anyways.

I really hope TQ CREST is more stable...
