### ISSUE TITLE
Signature shouldn't be independent of the map

### ISSUE THREAD

**Issue by w9jds** [exodus4d/pathfinder#146]
If you scan signatures for your system, I think that the wormholes should be auto added to the map. Even if they are just as a ? until the scan is 100% and the user goes through.

**Comment by exodus4d** [comment]
@w9jds  Sorry, unfortunately I didn´t get your point :( 
Do you think of wormhole signatures (e.g. static wormholes) that are auto-added to the signature table when you first enter a new wormhole? - Or do you want "independent signatures" (as the title says)? (e.g. if you have the same system on multiple active maps, signatures are shared between them).

**Comment by w9jds** [comment]
What I meant was that if you copy in the signature data from the system, and one of them is a wormhole. The map should automatically add a new node for that wormhole, even if you haven't warped to and jumped through it yet. Seems kind of odd that the system scans and the map above are kind of disconnected in that matter.

**Comment by Tupsi** [comment]
How would PF now which system the wormhole is to? This can only work by jumping or manually adding the system, but not from importing a scan (as the scan is missing this information).

**Comment by exodus4d** [comment]
Yeah thats the point. You could add a wormhole without any J-Number just from checking the D-scan, but you can´t know which hole it it. It could be a HS/LS/0.0 as well. But, to be honest, I don´t think adding systems without any information will help anyone. In some cases it could be a loop connection and the target system is aleady on the map... I think this would be realy confusing. 
Pathfinder should not "guessing" what could be the next system. All information you see on a map should be proofed or at least active added ba someone.

**Comment by exodus4d** [comment]
Sorry, I´ll close this. This is nothing that could be implemented or stay on my "TODO" list for the feature. This might change, in case *CCP* gives us more control or information about signatures.

Thanks for the suggestion anyways :)
