### ISSUE TITLE
PHP message: Validation failed: "name"" while reading response header from upstream

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#147]
Currently trying out the development branch. It seems that every (insert poor or stupid here) user who had the idea to use a ' in his eve character name can not login via SSO. I guess the character name needs to be properly escaped somewhere?

Full message reads:

2016/05/13 13:27:00 [error] 11392#11392: *6681 FastCGI sent in stderr: "PHP message: Validation failed: "name"" while reading response header from upstream, client: xxx.xxx.xxx.xxx, serve
r: our.thing.net, request: "GET /sso/callbackAuthorization?code=blablacode HTTP/2.0", upstrea
m: "fastcgi://whereIputit.com", host: "our.thing.net", referrer: "https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=htps..."

**Comment by exodus4d** [comment]
Very interesting! I spend some time searching for an explanation for this. I figured out multiple possible code blocks where where this could happen. 

Could you please provide a more detailed error log (set `DEBUG = 3` in `app/config.ini`). So we have a backtrace to worke with.

**Comment by Tupsi** [comment]
where would I find that extra debug info? The error.log seems as before, same with the nginx log.

**Comment by Tupsi** [comment]
forget my last remark, for whatever reason the debugging is on now and there are more strange new lines in the nginx error log. Trying to get a hold on the person with he ' in the character names now to give you anything usefull.

**Comment by Tupsi** [comment]
btw, is there anyway we can have a chat instead of this constant github mailing in between? Your hanging out on any irc channels or something more modern?

**Comment by exodus4d** [comment]
@Tupsi yeah sure. Send me an Email to pathfinder@exodus4d.de . Ill invite you to *Slack*:

https://pathfinder-eve-online.slack.com

**Comment by exodus4d** [comment]
Found the error: It has nothing to do with " ' " in the character name. It is the length of the name. The character name length must be <= 25 characters. Ill remove/adjust this validation rule and pull my changed when Im back home.

**Comment by exodus4d** [comment]
User names can now be up to 50 characters long
