### ISSUE TITLE
Redirection issue.

### ISSUE THREAD

**Issue by Drisker** [exodus4d/pathfinder#148]
I have a slight issue with current dev. There seems to be a redirection issue, probably on my end.
https://map.example.com > login by sso > choose character, accept > https://map.example.com/var/www/pathfinder//map.

If i cut the URL manually to https://map.example.com/map it goes through and works. 

Possible cause/solution ?

**Comment by exodus4d** [comment]
Yeah: Change `BASE  =   var/www/pathfinder/` to `BASE = ` (leave blank) in `environment.ini`.

**BASE** is **not** the root directory (server path) for Pathfinder. It is the **BASE** path to your index.php.

Leave blank means "auto detect" which is fine for 99% of all installations. If your installation is somewhere in a subDir (e.g. http\://www.[DOMAIN]/subDir/) you probably have to change it to `/subDir`.
