### ISSUE TITLE
unknown HTTP status: '415'

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#150]
I am getting a lot of 

HTTP response - unknown HTTP status: '415'. url: 'https://crest-tq.eveonline.com/characters/94473741/location/'

for various characters. At first we thought it is linked to the current ccp problem that you get CREST errors when docked in a citadel, but it turned out that we also get the error for people running around in wh systems.

That error also always seems to lead to a server 500 emergency shutdown message at the client and the person is forced to log back in.

**Comment by exodus4d** [comment]
Ah interesting. This is not a bug in *Pathfinder*.

CREST is like a "black box" API. The API documentation is very limited. Return HTTP status codes are not documented at all. 
Therefore I implemented some kind of "wrapper" class for those cURL requests. It also analysis all CREST responses, handle all the caching (based on the response `Cache-Control` Headers) and do some basic logging:

https://github.com/exodus4d/pathfinder/blob/develop/app/main/lib/web.php#L108

The 415 response status is "unknown" so far. I have never seen a 415 before. Therefore any unknown HTTP status codes are logged automatically. This is what you see in your `error.log`. I made this to collect some more information about how CREST behaves in different situations.

Now we can add this new status to it and think about a proper response handling.... When its done, we can remove 415 CREST status from being logged.

**Comment by Tupsi** [comment]
just pulled your latest changes, and the errors showing up get a little more talketive:

Sun, 15 May 2016 20:03:02 +0000 [2601:0:e84:ed0:78bc:eba0:6bea:8303] HTTP 415: 'Failed to parse response with provided accept type: application/vnd.ccp.eve.CharacterLocation-v1+json error Data for Long (application/vnd.ccp.eve.CharacterLocation-v1+json structure) is not a int or long but a <type 'dict'>' | url: GET 'https://crest-tq.eveonline.com/characters/2042856607/location/' | body: stdClass Object
(
    [message] => Failed to parse response with provided accept type: application/vnd.ccp.eve.CharacterLocation-v1+json error Data for Long (application/vnd.ccp.eve.CharacterLocation-v1+json structure) is not a int or long but a <type 'dict'>
    [key] => badServerContent
    [exceptionType] => UnsupportedMediaTypeError
)

**Comment by Tupsi** [comment]
fixed in the latest develop release
