### ISSUE TITLE
Constant emergency shutdown because of 500 error on pathfinder

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#156]
Keep getting 500 error on pathfinder, in my console it's complaining about this
`POST https://www.pathfinder-w.space/api/map/updateUserData 500 ()`

**Comment by exodus4d** [comment]
Thanks for reporting. Ill check this. But there is a good chance that is is already fixed in the current `develop` branch. Ill provide you feedback soon.

**Comment by Myrgon** [comment]
Getting the same Emergency Shutdown 500 error, even running the app off the website. Both in game and out. Happens within a couple minutes of logging in, at most. Has made the app mostly unusable.

**Comment by Siefer913** [comment]
Same issue on my end, system completely unusable.

**Comment by exodus4d** [comment]
Sorry, please retry. We had a massiv memory leak since last week :) I forgot to restart all *php-fpm* processes after last PHP version upgrade `v7.0.3` -> `v7.0.6`

**Comment by exodus4d** [comment]
I think we can close this. Please reopen if you still have problemens.

**Comment by Dessix** [comment]
I'm having this on a fresh install of Develop.

**Comment by Gavin-Tremlor** [comment]
Take a look and your NGINX error.log file and paste in here what the last line is.

**Comment by Dessix** [comment]
```
[Sat May 21 23:33:34.097261 2016] [:error] [pid 9997] [client XXX.XX.XXX.XX:57101] HTTP 500: 'Internal Server Error' | url: GET 'https://crest-tq.eveonline.com/characters/XXXXXXXX/location/', referer: https://www.XXXXXXXXX.XXX/map
```

**Comment by Gavin-Tremlor** [comment]
hmm, can you tell me what process 9997 is?

**Comment by Dessix** [comment]
Oh, sorry, I'm on Apache by the way.
