### ISSUE TITLE
subdomain setup

### ISSUE THREAD

**Issue by CokkocZateki** [exodus4d/pathfinder#157]
Hi Folks.

Just a quick question. im trying to install this on my server. however having trouble setting up a subdomain without a control panel. anyone have the patience to make help me setup a sub domain to get this installed would be of great assistance. Im using ubuntu 14.04 with apache 2.4 installed.

Thanks

**Comment by exodus4d** [comment]
Sorry, I´m Nginx user :( -  But this is probably not the right place to ask for general server questions
