### ISSUE TITLE
Ubuntu 14.04 install nginx config check fail

### ISSUE THREAD

**Issue by hybrid1969** [exodus4d/pathfinder#162]
I have followed the Ubuntu install guide but am getting a fail at the 'sudo service nginx restart' part

i get the error -
[emerg] 4246#4246: getgrnam("wwww-data") failed in /etc/nginx/nginx.conf:5

**Comment by Gavin-Tremlor** [comment]
Open your nginx logs (they are at /var/log/nginx/error.log) and put in here what the last line says.  I just set this up yesterday, so I may be able to help ya out.  I'm in game as Gavin Tremlor if you want to chat.

**Comment by exodus4d** [comment]
@Gavin-Tremlor thanks for your help out!

> **Hint:** If you are planning to set up a new installation, I prefer going with the current `develop` branch. It is about to be released soon. It is already tested and in use by a couple of installaions. A ton of bugs were fixed in there and some new features (e.g. *SSO/CREST* support/login) were implemented. This requires some basic knowledge about the build process in order to build some sources (check out the wiki for more information about that).

-

> **Hint2:** If you have general questions like this one, you can ask me for access to our new *Slack* developer chat [German/English]
- https://pathfinder-eve-online.slack.com
- Please send me a mail for invite: pathfinder@exodus4d.de

**Comment by Gavin-Tremlor** [comment]
Email for invite sent.  

You can close this issue.  I am helping him live in game chat.

**Comment by hybrid1969** [comment]
as nginx seems to simply stop working at the slightest issue I am seeking out an apache setup which should a lot more stable
