### ISSUE TITLE
[NEW] CREST waypoints

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#163]
With the upcoming release, which adds *CREST* support to *Pathfinder* (#84), and the knowledge that *CCP* will no longer support the *IGB* (in game browser), I will refactor some functions in order to use *CREST* instead of the deprecated IGB javascript functions.

The first step has been taken: "**Waypoints**"

##### What´s new?
- System waypoints can now be set from the *OGB* (off game browser) as well.
- New wapoint set options were added:
  - "**set destination**": (clear all existing waypoints and add a new one)
  - "**add new [start]**": (add a new waypoint  to the **front** of the waypoint list)
  - "**add new [end]**": (add a new waypoint  to the **end** of the waypoint list)

![waypoints_context2](https://cloud.githubusercontent.com/assets/9299033/15451271/5813076c-1fba-11e6-983b-eb34c736e5b9.png)

##### Information:
- *CREST endpoint api [documentation](https://eveonline-third-party-documentation.readthedocs.io/en/latest/crest/character/char_waypoints.html)
- New *CREST* [scope](https://eveonline-third-party-documentation.readthedocs.io/en/latest/crest/authentication.html#scopes) is required: "**characterNavigationWrite**"
  - Check your [application configuration](https://developers.eveonline.com/) and add this
- I tested this on SISI and TQ - *CREST*. Both work fine for me

##### The future:
- The new waypoint functions in *Pathfinder* are already prepared for "bulk" waypoint changes and accept an array of **systemIds**. This is not used yet, but this might become interesting in the future.
- "Clear waypoints" is not supported by *CREST*, this is hopefully coming soon.
- The waypoint options should be added to the "route search" module as well. This will enable you to right-click each system on a route and set waypoints.

**Comment by Tupsi** [comment]
would be awesome if you can implement that right click menu for the systems in the "route" section of pf, so that someone can easily set destination to one of the trade hubs or the system entered manually there.

**Comment by exodus4d** [comment]
Yeah agree, this would be nice. I think Ill implement this soon. The "routes" module offers a lot nice options that could be implemented as well. Some suggestions about that. Maybe Ill start a poll, where users can vote for a new feature that they really want to be implemented:

We could...
-  ... add a "draw route" button to each route, that automatically adds all systems for a route to a map. This could be restricted to "private" maps, to prevent "spamming" corp/ally maps:
 - Users can check each system for recent kills to find a secure route (e.g. for hauling)
 - This could be done automatically by querying *zKillboard´s* API for recent kills, send system-warnings to users or propose a more saver route.
- ... add the ability to exclude some systems from a search
- ... add a feature that automatically adds multiple waypoints for a searched route to the client.
  - the autopilot will exactly follow this root
- ... add a new filter option, to exclude Null-Sec or Low-Sec systems from a route search
- ... add a "mass-waypoint" feature, which sets (multiple) waypoints to some pilots (e.g. all in a fleet/wing, or everyone in a current system)
 - you don´t have to ask the FC for a destination. The FC could set the destination for each pilot

**Comment by Dessix** [comment]
> you don´t have to ask the FC for a destination. The FC could set the destination for each pilot
That sounds absolutely _amazing_ from a utility perspective!
