### ISSUE TITLE
Maps should be able to specify owner users/characters

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#164]
At the moment if a map is opened up to a corp/alliance, anyone can expand the permissions without it being tracked or immediately obvious -- this is bad for opsec.

You should be able to specify owners and have it so only owners can change map permissions.

**Comment by Gavin-Tremlor** [comment]
Can't you control scope with the the pathfinder.ini file?  Meaning if you only allow corp access (by putting a corp into the ini) and then you open the map to that corporation .. who would they be expanding the scope to?

**Comment by atkinsj** [comment]
When someone creates a map of privacy type 'Corporation' then goes to the last tab, you can specify the corporations that have access to that map. By default it is only the users corporation but you can add more; that means that anyone in the original corporation can add an entire second corporation to the map.

Even worse they could delete the map or set it to private and remove access for everyone but themselves.

In pathfinder.ini you can limit the maximum number of corporations that can be added to one map so you could in theory set this to 1, but there are legitimate use cases where adding more than 1 corp is completely valid. You can also restrict login to one corp but the same problem applies.

**Comment by Gavin-Tremlor** [comment]
; restrict login to specific corporations/alliances by id (e.g. 1000166,1000080)
CORPORATION                 = 
ALLIANCE                    =

You put the ID of the corp in there, and only those corps can log in

**Comment by atkinsj** [comment]
Yes but you may want an entire alliance to have access to Pathfinder but still want to allow corporations within that alliance to have their own private maps. If Corp A and Corp B are members of Alliance A and Pathfinder is limited to Alliance A in the login restrictions, someone from Corp A could add Corp B to Corp A's map, even though you don't want them to have access.

Even if you took the overly restrictive approach and had one pathfinder per corporation or something silly, it still means that in a 10,000 person corporation -- all it takes is one spy to delete the entire corporations map. You should be able to restrict map deletion/permission changes to a small group of people.

**Comment by Gavin-Tremlor** [comment]
ah, got it.  Carry on then.  :-)

**Comment by exodus4d** [comment]
Yeah, would be nice but requires some kind of "role" management. 
- Who is allowed to set map invites, who is not?

If a map is shared between corporations/alliances there is a "share icon" next to the map tab. This should help to identify shared maps. But seriously, if someone already has access to a map and want to share those information with an enemy. There is nothing you can do against that. - Share screenshots is always an option...

**Comment by atkinsj** [comment]
It is but this is just as much about protecting from accidental deletion as
much as opsec. For example we had a user think that the settings permission
boxes were for them to set what Corp they were in -- you'll always have
dumb users but it would be nice to raise the bar a little bit in the
technology.

I was thinking a second box in the sharing settings where you can just list
additional characters that have 'owner' permissions in the map.

**Comment by exodus4d** [comment]
Ok, sounds good! 

- When you create a map for the first time, you will be the only one who can add other owners.
- Everyone who is added added as "owner" can invite other owners and edit share settings.

There is still a problem:
Everyone in a corporation is able to create corporation maps as well. In case there is a spy, he can create a corporation map and invite others. If we bind "map delete" option to owners as well, no one will be able to delete this map. I think we need some kind of "corp/ally" leaders with "admin" rights who always have "owner permission" for a corporation/ally map. But there is no way to automatically get "managers" from CREST.

**Comment by atkinsj** [comment]
I agree it would be nice if for a corporation we could have people
pre-identified as the owners for that corporation but that does seem like
something better solved with a more extensive role framework.

I would be inclined toward accepting that we could end up with some Corp
maps littered and inaccessible for the moment and look toward implementing
something more extensive in the future.

Curious on other peoples thoughs on this though!

**Comment by exodus4d** [comment]
I´ll think about an acceptable solution for this problem :)

For self-hosting installations we could think about a configuration form within the `/setup` path, where you can add "admin" characters for corporations. 

But this will not work on "shared-installations" like mine. There are currently 253 alliances and 948 corporations with registered users.

**Comment by atkinsj** [comment]
Agreed. I was thinking more about this and the permissions systems in general -- I'm wondering if it would be better for maps not to be private/corp/alliance but just to be 'private' and the settings window allow you to specify which of the ones you want. I can see situations where people want 1 alliance, 2 non-corporation alliances and 1 character not in any corp or alliance to have access to a map.

Random side thought anyway -- I'll keep thinking on the ownership front.

**Comment by garemoko** [comment]
I'm planning on forking this repo and putting some time into addressing the permissions issue. 

I like the idea of map owners and map based permissions. Map permissions include: permission/role assignment, edit map, add to map by jumping, view map, view player locations on map.

  I think also users should have ownership of their location data and be able to choose which maps to share that data with. You're then trusting the map owner to share that data with the right people so individuals don't have to micromanage this themselves.

**Comment by Betriebsrat** [comment]
+1

**Comment by dnolen** [comment]
Can you please confirm if you are able to correct the ability to access and share out corp maps with other groups via the search field. At this time the function of the map owner sharing out the map to groups will no populate the corp names if searching via atleast 3 characters in version 1.1.7.

**Comment by Judahmeek** [comment]
I can confirm that searching for characters to add to a private map does not work, even if the character searched for is the original owner (after having removed the owner, of course). My guess would be a parsing error from reading EVE's entity data.

**Comment by exodus4d** [comment]
@Judahmeek have you read the manual? the character you are searching for needs to activate "map sharing" before he can be found by others. This should prevent map invite spamming.

**Comment by exodus4d** [comment]
#### What is new in `v1.3.3` ?
- **Any** character needs to re-auth their chars and accept the new `esi-corporations.read_corporation_membership` _ESI scope_ , which previously was available on the admin login page `/admin`.
![16suaaq](https://user-images.githubusercontent.com/9299033/36321260-7fe0b800-1349-11e8-9915-3b0325372173.png)

- Based their _EVE_ **in game roles** and _Pathfinders_ *`*.ini`* configuration, each character gets one of these **3** roles assigned:
  - MEMBER - default role
  - MANAGER - corporation admin
  - ADMIN - server admin
![hadx1up](https://user-images.githubusercontent.com/9299033/36321283-8f8adbfa-1349-11e8-9af4-e50a56823703.png)

- Characters with **MANAGER** or **ADMIN** roles have access to the new `admin/settings` page.  They can change the required role, a char must have, for some new map rights:
  - update map
  - delete map
  - import map
  - export map
![wqfxuuh](https://user-images.githubusercontent.com/9299033/36321293-9757df7c-1349-11e8-9d7a-8ce6aa4d3da3.png)

- Characters that don´t have the required role for a _map action_ (e.g. "delete map") get see some warnings on their UI
![by39uej](https://user-images.githubusercontent.com/9299033/36321295-9a508594-1349-11e8-8d47-e79b8e5efbb3.png)
