### ISSUE TITLE
Ability to manually sync map layout

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#165]
If multiple people are viewing the same map and one person reorganises it, the changes aren't available to the other viewers until they refresh the page.

It would be nice to add a button to force a re-draw or perhaps even trigger a redraw if a change is detected.

**Comment by exodus4d** [comment]
Agree this would be very nice! But It requires some larger refactoring work :) 
But It is definitely something we should think about in future.

**Comment by exodus4d** [comment]
duplicate #185 (we close this)
