### ISSUE TITLE
Zkillboard API change has broken recent kills

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#166]
I'm getting the following:

`XMLHttpRequest cannot load https://zkillboard.com/api/no-items/no-attackers/solarSystemID/30003187/pastSeconds/86400/. No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by exodus4d** [comment]
is alrady fixed in the develop branch. https://www.dev.pathfinder-w.space/

**Comment by atkinsj** [comment]
I'm getting the same error on your dev branch.

`XMLHttpRequest cannot load https://zkillboard.com/api/no-items/no-attackers/solarSystemID/30000142/pastSeconds/86400/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.dev.pathfinder-w.space' is therefore not allowed access.`

**Comment by exodus4d** [comment]
Interesting I'll check.

**Comment by exodus4d** [comment]
Sorry, I can not reproduce this on my dev server. Looks like your JS which is cached by the browser is outdated. Is this happening for any specific system, or for all systems you click at?

**Comment by atkinsj** [comment]
Yeah, looks like cache busting wasn't working; refreshing with the chrome dev console and ignore cache on seems to have fixed it. Sorry for the false positive.
