### ISSUE TITLE
alliance restriction not working in pathfinder.ini on develop

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#167]
most likely because we switched to CREST and the CREST data only shows you what Corp you are in, but not the alliance, so that check fails.

Steps to verfiy:
1) install develop branch
2) enter alliance ID in pathfinder.ini restriction section
3) try to login with a character of that alliance. (you will already see that your cached chars are thrown away at this point)

PS: corp restrictions at this point work.

**Comment by exodus4d** [comment]
Yeah this should work now. fixed: ceb6ab5775fdeb73172687398c17c29b6b3d74fb
