### ISSUE TITLE
[Question] Can you add POS and d-scan information to each system?

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#168]
Before I start installing this, I just wanted to ask if this is possible, like it is in Siggy.

We use this feature a lot as it easily gives us an overview of who we're connected to.

**Comment by Tupsi** [comment]
Not as nicely. Atm there is only a single info box (, think note pad)

**Comment by exodus4d** [comment]
Yeah, It´s not implemented yet. This is maybe coming in future releases.
There is already a feature request open #146 .
