### ISSUE TITLE
JS Cache busting not working as expected

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#17]
Cache-Busting for production (build) *.js files is not working as expected.

TODO: 
- remove mod_expire for *.js files from .htaccess
- implement a new cache-busting strategy for *.js files. 
 - unique file name (add version param [main.js?v=x.x.x]
 - as result stronger Cache-Headers should be possible

**Comment by mglinski** [comment]
I would highly recommend not relying on apache modules and .htaccess configurations for managing things like cache, access restrictions, etc. Cache busting should never even be needed if your server is setup correctly. 

If you still need a cache busting setup, use gulp-rev and load the manifest file into your app and use that to link to the renamed files.

**Comment by Zumochi** [comment]
I would be nice if Pathfinder would be as easily setup for nginx and other webservers besides apache and IIS.

**Comment by mglinski** [comment]
I run it on nginx currently with some very minor modifications, mainly the eve headers code I mentioned in another ticket. Its not that terrible to setup.

**Comment by exodus4d** [comment]
Im currently working on two main Gulp (http://gulpjs.com/) tasks:

#### default
- task for continuous development (default task)
- watching *.js *.sass files for changes
 - running jshint on *.js changes
 - running "compass watch" on *.scss changes

#### production
- task for release deployment
 - running requireJS build + optimizer (generate source maps, minify, uglify
- running "compass" (generate CSS)
- copy new build *.js files into "public/js/X.X.X/*" (Any release has its own JS folder) This should solve the caching problem

**Comment by exodus4d** [comment]
Issue will be fixed with e452adb597e326330929914c09aece282b66a826
