### ISSUE TITLE
[Feature Request] Timestamp on EOL wh connection

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#172]
When you set a connection EOL pathfinder should mark the time into the db and show it (maybe as mouseover), so people get an idea about "how long" this thing is already EOL.

**Comment by Bingmano** [comment]
Technically you can see this on the info menu when right clicking on the map.  The only thing to be careful of is if the linkage is updated the timer will change to whatever was most recently done to update it.
http://imgur.com/h7Ydlpp

**Comment by Tupsi** [comment]
It is a nice workaround for now, thanks! Although a bit flunky, seeing that people touch stuff all the time, but better then nothing atm.

Still giving that table another row with a timestamp and show that on mouseover shouldnt be to hard to implement and it would give a solid answer to the question when it was set and not rely on chance that this was indeed the last edit

**Comment by dnolen** [comment]
Can it also be implemented based around the type of connection if the sig details are recorded to auto purge the hole from the map? 

Yes we may not know when the hole spawned but if the timer to purge it is set to Max 24 hours that will ensure the old sigs are purged from the DB to save space and clean up systems once the connection dies.

**Comment by exodus4d** [comment]
#### I added a new "EOL timer" to the map
The timestamp for "set to EOL" on connections, is now stored in `system_signature` table.
There is a new "show EOL timer" icon available to show that information on a map 

![map_eol](https://cloud.githubusercontent.com/assets/9299033/17272238/531c6308-5691-11e6-910d-4885f914f648.png)

**Comment by rmcginnis** [comment]
This will be awesome showing the EOL Timers..

**Comment by exodus4d** [comment]
It´s already implemented and waiting for the next release (probably this weekend)
