### ISSUE TITLE
Pull environment config values from environment variables

### ISSUE THREAD

**Issue by Regner** [exodus4d/pathfinder#175]
The 12 factor app gives some good reasons for this: http://12factor.net/config

Having the config values in environment variables means only having to maintain one list of config values and not having to switch between different configs. It also makes putting the application into a Docker container a lot easier, which is what I am hoping to do. :)

**Comment by exodus4d** [comment]
Absolutely agree with you! 
I´ll implement this as the new "default" in one of the next minor releases. If system vars are not set/found we use the environment.ini as fallback for those who are on a "shared hoster" or simply can´t set environment vars.
We need to add this check in here: https://github.com/exodus4d/pathfinder/blob/develop/app/main/controller/controller.php#L762

**Comment by exodus4d** [comment]
> **IMPORTANT:** If you have a running installation, nothing has to be changed! This is just an alternative setup feature for your environment configuration

##### When I´m done with my testing, I´ll push the following changes to `develop` branch:

- added a panel to `/setup` route that shows the current environment configuration
  - the first row shows, were those configuration came from:
    - `Config: environment.ini` **or**
    - `PHP: environment variables`
 - environment conf vars are checked against a "white list"
 - missing vars will have a red `[missing]` label
 - sensitive values like *secret keys, passwords,...* are obscured
- *Pathfinder* will automatically check for existing PHP environment variables
 - if environment variables were **not** found -> *envinment.ini* is loaded and parsed for that variables (as before)

##### Who should use this?
- Anyone who uses `git pull` and does not want the "environment settings" (DB credentials,..) to be overwritten any time
- Anyone who want to keep the "environment settings" independent from this installation

***

##### Environment panel
Environment variables from `Config: environment.ini` (fallback)
![setup_environment](https://cloud.githubusercontent.com/assets/9299033/15630284/6d916082-2534-11e6-84c0-0b0de2dc0fc3.png)

Environment variables from `PHP environment variables` (priority)
![setup_environment1](https://cloud.githubusercontent.com/assets/9299033/15630285/7498ee5e-2534-11e6-9e12-7a48e79b76f1.png)

***

> **Hint:** All environment variables are prefixed with `PF-ENV-`.

##### Set PHP environment variable
###### Nginx (FastCGI)
PHP environment variables  have to be passed as `fastcgi_param` to *PHP*: You should add a new `*.config` file to your *PHP* `location`section and create [develop-pathfinder.conf](https://gist.github.com/exodus4d/2b42057bb1b87990c0a17f704d22805f).


```
location ~ \.php$ {
    try_files             $uri =404;
    include              nginx.fastcgi.conf;
    fastcgi_pass      php_farm;
    include              /var/www/environment/develop-pathfinder.conf;
}
``` 

- restart/reload Nginx

###### Apache (mod_php)
You can pass all environment variables by adding them to your `.htaccess`.
This is **not** tested yet, but it *should* work :)


```
    SetEnv     PF-ENV-URL         http://www.pathfinder-w.space
    SetEnv     PF-ENV-DEBUG        3
```

- restart apache

***

**Comment by Tupsi** [comment]
this breaks the cronjobs using the prefered method A mentioned in the wiki documenation (as the cli php does not have access to the nginx env variables and falls back to what is in evironment.ini).

**Comment by exodus4d** [comment]
"_TCP socket_" config and `CACHE` backend can be set by _PHP environment vars_

Updated: [develop-pathfinder.conf](https://gist.github.com/exodus4d/2b42057bb1b87990c0a17f704d22805f) 
^^ Config example for [_Redis_](https://redis.io/) cache backend.

**Comment by exodus4d** [comment]
More information about new (optional) WebSocket setup: #420
