### ISSUE TITLE
[Feature Request] Filter scope wormhole systems only

### ISSUE THREAD

**Issue by Chrocied70** [exodus4d/pathfinder#176]
A new option to hide known space systems from people using star-gate would be nice to clean up the map.

**Comment by Ricaz** [comment]
I think this should be determined by map scope, or possibly a second setting. 

Our group is planning to switch to Pathfinder, but this feature (or lack thereof) alone is keeping us from using it. 
It's simply too much work to have everyone turn off tracking every time we roam nullsec.

**Comment by exodus4d** [comment]
Update to `v.1.1.0` and switch the map scope. Stargates are no longer tracked if you don´t want to. Read #132 for more information about that new feature. This will not "hide" stargate systems, but stargate systems will not be added to a map, if you don´t want to.

**Comment by exodus4d** [comment]
There will be a complete new "filter logic" implemented in the next release.
Please read this issue #641 for more information.

Please comment that issue if you have any further questions.
