### ISSUE TITLE
Constant emergency shutdown because of 500(Live dev)

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#177]
Every 5-10 minutes the live dev pathfinder comes back with a

```
Emergency shutdown
error 500:
exec(): Unable to fork [php -v2&gt;&amp;1]
```
The url which it fails on is: https://www.dev.pathfinder-w.space/api/map/updateData

Everyone in our corp is getting it, and it is becoming for frequent, last night we only had it every hour

**Comment by exodus4d** [comment]
Thanks, sorry for that! Should be fixed (for now). (same problem as #156)

I´m currently testing an improved *PHP-FPM* configuration. Unfortunately this requires some server load or at least a great number of active clients, to figure out how much RAM is required for a specific number of active *PHP* FastCGI processes.
But I think I´m on a good way with this...

What happened: To many (inactive) FPM processes reserve to much RAM
