### ISSUE TITLE
missing statics for some Shattered Systems

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#180]
I noticed that some Shattered (or maybe even all of them?) are still missing there statics. Date sites I found so far with information about them:

http://wiki.eveuniversity.org/Project_Reassembly/List_of_Shattered_Systems
http://collapsedbehind.blogspot.de/2014/08/c4-wormholespace-dual-statics.html
https://eveeye.com

we should try to get a more complete list of statics for these systems. Anyone who has more/additional info feel free to share.

**Comment by Ligraph** [comment]
Tripwire appears to have the statics, it's open source at https://bitbucket.org/daimian/tripwire, and I'm attaching the statics JSON (in a zip).
[statics.zip](https://github.com/exodus4d/pathfinder/files/335601/statics.zip)

**Comment by exodus4d** [comment]
Awesome! Thanks

**Comment by Ligraph** [comment]
If you need other stats, Tripwire stores them in the tools subfolder, and comine.json has them all.  Was a great help for me when I was making a tracker.  Also, I'm fairly sure that wormholes.json contains the shattered statics.

**Comment by exodus4d** [comment]
I just checked the *JSON* data. I found some problems:
- The data dump does not have **all** shattered wormholes (e.g. `J000304`)
 - I found **101** on *eveuniversity* page (linked above)
 - I found **75** in the *JSON* data

Should be add at least the information for thos **75** holes? What you think?

**Comment by Ligraph** [comment]
It would be nice to have that info.  Its interesting that the json is missing statics, I've never seen them not show up.  Do you know how many are missing?  Thinking it could be just the c13 and/or drifter holes.

**Comment by exodus4d** [comment]
I just compared the J-numbers that start with **J0xxxx**. I couldn´t find e.g. `J000304` in that *JSON* but this system exists in game. Or are there *shattered* systems with other J-number syntax?
It looks like **26** systems were missing.

I´m currently writing an importer for that *JSON* which compares the statics I already have with those. And add missing once automatically. So we should get the best out of both sources ;)

**Comment by exodus4d** [comment]
##### Static systems for *shattered* wormholes were added now.

*Shattered* data was added to `pathfinder.sql`. There is now a new way to setup/update all static data from `pathfinder.sql`. I added `*.csv* dumps for those tables to the repo (èxports/csv). 
Read https://github.com/exodus4d/pathfinder/issues/125#issuecomment-233143388 for more information.

I´m pretty sure the *Tripwire* `*.json` file from above is not 100% completed yet. E.g:
- **J000304** is not included.
- **J011376** has 2 statics [C247, X877] according to that *JSON* file. But [ellatha.com](http://www.ellatha.com/eve/WormholeSystemview.asp?key=011376) reports [U210, X877]
