### ISSUE TITLE
Adding new system manually/Routes not working

### ISSUE THREAD

**Issue by CokkocZateki** [exodus4d/pathfinder#181]
Hi
I was trying to add a system manually, however the system doesnt seem to allow me to add it.

Same with routes not loading.

http://postimg.org/image/lggsx25m3/

anyone know how to resolve these issues

**Comment by exodus4d** [comment]
You sure the system is not already somewhere on the map? Maybe it was renamed on the map and you can´t just compair names...

**Comment by CokkocZateki** [comment]
ahhh found it. was stacked with another tab. any ideas on the route to trade hubs

**Comment by exodus4d** [comment]
Do you mean, set waypoints to trade hubs? There is already a feature request open: #178

I guess we can close this now ;)
