### ISSUE TITLE
[Feature] Notes should be consistent and survive deletion of the system

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#184]
we need a place to put intel about the system which would survive the deletion of the system. So when you came back to that system a day, a week or a month later, that info is still there. Ideally there is a new place besides the current notes where to put this, so the current notes could stay like it is, but the new intel tab/panel would be persistent. As there is a basic "who can see what map" system in place, that intel tab has to honor this setting naturally.

**Comment by exodus4d** [comment]
Agree! This should be cool :) But it requires some larger refactoring work :( But it is definitely something I´ll think about in the future :)

**Comment by Calavoow** [comment]
We would also very much like a way to persistently store intel. I like that the notes section is freeform since it allows for more easy data entry and most data in Siggy Intel is unnecessary anyway (pos tower type?).

**Comment by Bingmano** [comment]
> We would also very much like a way to persistently store intel. I like that the notes section is freeform since it allows for more easy data entry and most data in Siggy Intel is unnecessary anyway (pos tower type?).

I agree with this, perhaps if development work is going to be done in this space, we could get some enhancements regarding information at a glace.  Systems that had been connected or have been on the map in the past would have a color, or even if a system has intel typed in notes it would have a color.

**Comment by exodus4d** [comment]
@Bingmano @Calavoow @Tupsi This will probably become the next feature :)  I´m currently thinking about what information should be persistent, and what additional UI elements are needed. I´ll try to add POS/Citadel intel information as well. 
Do you have any suggestions how it "should" look like? Are you fine with just the single description field to add all that information, or do you need some extra fields/dialogs for other information?

Please let me know what you expect and/or would like to have. Ill check what will be possible in time.... ;)

**Comment by exodus4d** [comment]
### Changelist
#### Systems:
- [ ] Systems will **no longer** be deleted from DB when they are removed from a map.
 - [ ] Set systemData to `active = 0`.
- [ ] **Check** for existing `active = 0` systemData when a system gets readded.
 - [ ] If exists -> set systemData back to default: `active = 1`.
- [ ] **Keep** systemData untouched for column:
 - [ ] `alias`  (e.g. "*[CUSTOM_NAME]*")
 - [ ] `status`  (e.g. "hostile")
 - [ ] `description`
- [ ] **Reset** systemData for column:
 - [ ] `locked`
 - [ ] `rallyUpdated`
 - [ ] `rallyPoke`

#### Signatures:
- [ ] **Add** new cronjob to delete "outdated" signatures on **inactive** (not mapped) systems
 - [ ] cronjob function: `deleteMapData()`
 - [ ] cronjob frequency: `30 minutes`
 - [ ] delete signatures: `last update > 3days`

***
#### Technical information:
- This will massively **increase** the number of inactive `systems` and `signatures`! We should keep an eye on system performance ;)

**Comment by exodus4d** [comment]
### Signature example:

1. Add new system to a map
2. Add some signatures (_"AAA", ""BBB"_, ...) to it
3. Delete system from map
4. Re-Add system to map -> _"AAA", ""BBB"_ should be still there
5. **next day** Add a third signature to that system (_"CCC"_)
6. Delete system again.
7. **2 days later** Re-Add system ->  _"AAA", ""BBB"_ will be **deleted** automatically. _"CCC"_ should be **still there** (the new signature expire time [default: 3days]) cleared the outdated signatures, but new signatures are not touched...

This should help while _"rage rolling"_ or when jumping into a recently removed system...

***

- We have to see if the expire time (3 days) is fine. -> can be changed in `pathfinder.ini`.
- Maybe we should consider to include "active" (visible on a map) systems for that cronjob as well.
