### ISSUE TITLE
SSO returns "invalid_request" (callback URI doesn't match)

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#186]
My installation is [here](https://www.dcsl.dk) (temporary domain).

I'm pretty sure everything is set up properly (`/setup` has no issues).

When I try to login with SSO, CCP's server returns this:
```
{"error":"invalid_request","error_description":"The callback URI doesn't match the value stored for this client"}
```
I set the callback URI as on the wiki, so I don't really know where to go from here.

The callback URL is set to: `https://www.dcsl.dk/sso/callbackAuthorization`

**Comment by Tupsi** [comment]
have you setup a dev account with ccp and entered the website as application? Just putting that URL in the .ini is not enough.

**Comment by Tupsi** [comment]
hmm, could it be possible that you mistyped at ccp and forgot the S in https?
Because when I try to login at your site I see this url in the error page:

https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Fdcsl.dk%2F%2Fsso%2FcallbackAuthorization&client_id=85ecf21caa8047239afa6a92ec4661d7&scope=characterLocationRead%20characterNavigationWrite&state=c3b8114893297f435b68642e

**Comment by Tupsi** [comment]
I also faintly remember having problems at ccp at first as well. Try creating a new (2nd) app with different key and secret and try that.

**Comment by Ricaz** [comment]
Tried making a 2nd application, but I still get the same error.

This is what it looks like: [screenshot](http://i.imgur.com/49PO8Pa.jpg)

**Comment by Tupsi** [comment]
works now for me one your site

**Comment by Ricaz** [comment]
Just tried on mobile, and now it does send me to the login page, but after the login I get the same error when I'm sent back. 

Will try later from home.

**Comment by Ricaz** [comment]
I still get the same error across multiple browsers.

Apparently some people don't, but it doesn't work in-game either way.

**Comment by exodus4d** [comment]
@Ricaz This is pretty easy to fix ;) When I click on your SSO button. The Redirection URL (in my browser) looks like this:

```
https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fwww.dcsl.dk%2F%2Fsso%2FcallbackAuthorization&client_id=9918956c8aa748169af017ae5df31d4d&scope=characterLocationRead%20characterNavigationWrite&state=a5d251c927d77805d2d5f3eb
```
Look for the `&redirect_uri=` parameter and its value:  `https%3A%2F%2Fwww.dcsl.dk%2F%2Fsso%2FcallbackAuthorization`. **URL decode** this string, e.g. by using [this](http://meyerweb.com/eric/tools/dencoder/) tool, will show you:
`https://www.dcsl.dk//sso/callbackAuthorization`.

'You see the *double slash* ?

##### Solution

- Edit your `environment.ini` and remove the `/` at the end or your *URL = https://www.dcsl.dk/*.

**Comment by Ricaz** [comment]
The URL doesn't have the double slash for me.
I removed the trailing slash in `environment.ini`, but it didn't fix anything.

**Comment by exodus4d** [comment]
Sure it does, I now get redirected to CCPs SSO form. Looks good now ;)
e.g. clear browser cache ;9

**Comment by Ricaz** [comment]
I removed the trailing slash from the SSO application, now it works.

Thank you :)
