### ISSUE TITLE
[Feature request] Option not to automatically create k-space -> k-space connection

### ISSUE THREAD

**Issue by pyonium** [exodus4d/pathfinder#188]
A lot of users jump into k-space from the chain to go to a tradehub. However, having to disable tracking in k-space can be quite a hassle, considering multiple jumps through k-space aren't too common in your chain. Therefore, I propose an option being added to disable automatically created links between k-space systems to easen k-space travel.

Maybe as a personal setting where the owner can set a default for all users in that map?

**Comment by exodus4d** [comment]
https://github.com/exodus4d/pathfinder/issues/132#issuecomment-223827643 Already in progress... ;)
