### ISSUE TITLE
Request to add K-Space Routes to Trading Hubs

### ISSUE THREAD

**Issue by cadetmcgregor** [exodus4d/pathfinder#189]
Would love to see K-Space systems NOT on the map in the Route planner to allow us to see how many jumps thru low class systems would need to be made. eg. 5 jumps thru null/ lowsec prior to highsec visible similar to the way it is now or in game with colored boxes. It would also b e awesome to allow this to use the wormholes on the map to allow for faster jump times. EG. WH Sys 1 -> 2 K-Space -> Wh 2 -> WH 3 -> K - Space -> Trading Hub.

This may be a bit of an expanded request however would definitely be used by every member using pathfinder on a daily basis.

**Comment by Tupsi** [comment]
I am having trouble connecting your subject to the rest of the text. Maybe you should rephrase the subject line.
Regarding the 2nd part of your request, that is imo already working. Every system with every connection on the map gets used when calculating the route.

**Comment by exodus4d** [comment]
Yeah trade hubs on the map, does not make sense if they are not manually mapped to it.
With the last release, there is already a new route search function implemented, that adds**any** system (e.g. wormholes,...) to it for route search: https://github.com/exodus4d/pathfinder/issues/131#issuecomment-214016064

With the next release k-space systems will not be added to the map automatically. There is a new "map scope" feature already implemented and in testing: https://github.com/exodus4d/pathfinder/issues/132

**Comment by exodus4d** [comment]
Forgot to close this one. `v1.1.0`is already live with the extended route search. Check #132 for more information.
