### ISSUE TITLE
IGB headers not properly parsed when using IIS

### ISSUE THREAD

**Issue by IvandaNothabeer** [exodus4d/pathfinder#19]
The php implementation of apache_request_headers in windows based versions of php alters the case of the returned IGB header information. This in turn means that the IGB header information is not parsed correctly.

Under XAMP, the header data returned is "EVE_TRUSTED"
Under Windows the Header data is "Eve-Trusted"

File : app\main\controller\controller.php
Line: 115 thru 130

Need to review case sensitivity and underscore/dash characters when parsing this data. See http://php.net/manual/en/function.apache-request-headers.php  for other options.

**Comment by exodus4d** [comment]
Thanks for reporting! Ill check.

**Comment by IvandaNothabeer** [comment]
Try ....

    static function getIGBHeaderData(){
        $data = (object) [];
        $data->trusted = false;
        $data->values = [];
        $headerData = apache_request_headers();

        foreach($headerData as $key => $value){
            $key = strtolower($key);
            $key = str_replace('eve_', 'eve-', $key);

            if (strpos($key, 'eve-') === 0) {
                $key = str_replace('eve-', '', $key);                
                if (
                    $key === 'trusted' &&
                    $value === 'Yes'
                ) {
                    $data->trusted = true;
                }

                $data->values[$key] = $value;
            }
        }

        return $data;
    }

**Comment by exodus4d** [comment]
Thx for reporting I'll check and fix this in v0.0.10

Ivanda Nothabeer <notifications@github.com> schrieb am Di., 15. Sep. 2015
01:51:

**Comment by mglinski** [comment]
Using apache_request_headers() will fail on some setups. It's better to use $_SERVER as any extra headers are passed in there by default on apache, and any FCGI setup will expose its added variables there too.

**Comment by exodus4d** [comment]
Issue should be fixed in v0.0.10.

For some reason, there are no custom CCP Header data in $_SERVER (local xampp @ Win). I guess it has something to do with:

- http://stackoverflow.com/questions/15382407/not-all-headers-available-in-server-php
- http://stackoverflow.com/questions/7141566/server-headers-are-missing-in-php-but-present-in-python

I can´t find any clean solution for the problem, just ugly `mod_rewrite` rules and implementations that mix up `$_SERVER` and `apache_request_headers()`. For now we stick to `apache_request_headers()`

**Comment by mglinski** [comment]
Just do detection when trying to read the headers and if none match, fall back to apache_request_headers().

On NGINX I inject the headers into $_SERVER via fcgi_variables, so this will work correctly on nginx regardless.
