### ISSUE TITLE
[Feature Request] Add submit button to sig reader

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#190]
Not sure how it's supposed to work, but 'enter' just makes new lines.

**Comment by Ricaz** [comment]
Apparently it just didn't show up for some reason. No idea why.
It's there now.

**Comment by Ricaz** [comment]
I need to sometimes scroll up for the buttons to appear.

**Comment by exodus4d** [comment]
Which Browser? iGB?

**Comment by Ricaz** [comment]
Yes

**Comment by Ricaz** [comment]
Different issue, quick question:
Are there wormhole types missing or is it just for me?
[screenshot](http://i.imgur.com/H2u5Cwa.jpg)

**Comment by exodus4d** [comment]
The types list for shattered holes is not 100% completed or even fully
known. But there is a Update for sind of the aleady confirmed types coming
soon

Martin Alstrup <notifications@github.com> schrieb am So., 12. Juni 2016,
19:27:

**Comment by Ricaz** [comment]
Well, this hole specifically is a C5 static (N062) and not on the list.

**Comment by Tupsi** [comment]
I explicitly made an issue for that to get the missing statics done. This should not be discussed here under a different subject. No one will find this ever again otherwise...
