### ISSUE TITLE
[Feature Request] Connection Labels for Sig ID

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#191]
Something that would be helpful would be the ability to add the signature ID to the map itself as an overlay.  The label wouldn't show unless you enter a value (unlike in eve w-space where if there was no value it was ???).  It would make bookmarks more effective along with containing less information.

Crude example:
http://i.imgur.com/96Lr1cN.png

Example of eve w-space
https://interstellarprivateer.files.wordpress.com/2013/02/wspace-map-storyhead.jpg

**Comment by Ligraph** [comment]
Having wormhole type would be nice as well.

**Comment by garemoko** [comment]
From what I can see sigs aren't linked to connections at all. I had a play around with it this morning but need to do a bunch more work. My interest is having the sig's created time automatically feed the connection's expected time remaining.

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic: #290
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*

**Comment by exodus4d** [comment]
I reopen this one, because "connection **labels**" were not implemented in #290

**Comment by exodus4d** [comment]
Labels were added in #290
