### ISSUE TITLE
Crest Issue

### ISSUE THREAD

**Issue by CokkocZateki** [exodus4d/pathfinder#192]
Hi
Ive installed the latest dev version onto my server. However i get the error Invalid "ENVIRONMENT.[ENVIRONMENT].CCP_CREST_URL" url. Controller\\Ccp\\Sso::getCrestEndpoint when i try to login using SS0

**Comment by CokkocZateki** [comment]
still got this issue. :(

**Comment by exodus4d** [comment]
@CokkocZateki could you please link a screenshot from your "configuration" panel on /setup ?

**Comment by CokkocZateki** [comment]
@exodus4d sure

https://postimg.org/image/dk8utoekn/

**Comment by CokkocZateki** [comment]
um okay for some reason it works now. i havent changed any settings lol.
case close i suppose
