### ISSUE TITLE
Error after upgrading to 1.1

### ISSUE THREAD

**Issue by daschalki** [exodus4d/pathfinder#194]
http://pastebin.com/tWw5ii12

showing up in the logs when
- passing through wormholes
- switching maps
- adding systems (http://pastebin.com/kFrYDu4g)

not certain if configuration issue.

**Comment by exodus4d** [comment]
You cleared the /tmp/cache folder afterwards? and re-run the "setup-tables" button under the /setup route, to properly add the new "map scope" options? 
Which PHP version?

**Comment by daschalki** [comment]
Did not clear /tmp/cache right after upgrading but cleared right now.
Also re-run the setup-tables.

Running PHP Version => 5.6.20-0+deb8u1

Nothing changed after clearing/re-run setup-tables

**Comment by exodus4d** [comment]
Thanks for reporting.
It is a PHP 5.6 Error,.... should be fixed with the next release.

**Comment by daschalki** [comment]
alright, thanks - is there a workaround for now?

**Comment by exodus4d** [comment]
Just replace the single PHP file with the file from the commit above.

daschalki <notifications@github.com> schrieb am Mi., 15. Juni 2016, 20:43:

**Comment by daschalki** [comment]
awesome, ty
