### ISSUE TITLE
JS and CSS not found when using Localhost

### ISSUE THREAD

**Issue by IvandaNothabeer** [exodus4d/pathfinder#195]
Using Apache on Windows 7 development environment. The environment.ini is set as follows ...
```

[ENVIRONMENT.DEVELOP]
; path to index.php (Default: leave blank == "auto-detect")
; -> e.g. set /pathfinder if your URL looks like https://www.[YOUR_DOMAIN]/pathfinder (subfolder)
BASE                        =   /pathfinder
; deployment URL (e.g. http://localhost)
URL                         =   http://localhost
```

The js and css files are not found by index.php. Pathfinder appears to be looking in the root /www directory instead of the /www/pathfinder/ directory for the js and www/public/css instead of www/pathfinder/public/css

Modifying the following lines in www/pathfinder/index.html appears to resolve the issue but I'm unsure if this is the correct fix or if I'm doing something really dumb ...

```
Line 55:     <link rel="stylesheet" type="text/css" media="screen" href="public/css/pathfinder.css?{{ @PATHFINDER.VERSION }}">

Line 64: <script data-main="js/app" src="js/lib/require.js" ></script>
```

Note: remove leading '/' from 'js' and 'public'

**Comment by IvandaNothabeer** [comment]
seems to be the same issue as #87

**Comment by exodus4d** [comment]
Thanks for reporting.
Should be fixed with the next release. Unfortunately I don´t have a **Apache** or subDir installation available for proper testing.  
Please report any problems.

**important:** You have to change `BASE` from `/pathfinder` to `pathfinder/` when the fix is online
