### ISSUE TITLE
Pasting Scan Result into Signature Reader

### ISSUE THREAD

**Issue by manimax3** [exodus4d/pathfinder#196]
When I paste my Scan result into the Signature Reader it overwrites all of the existing signatures. It would be nice if there is an option to just override the signatures when more information is known (eg Unknown Sig -> Wormhole)  or add new ones which arent known yet.

**Comment by Tupsi** [comment]
this is marked as fixed currently as it was reported already earlier in #81. Are you sure that you are using the latest 1.1?

**Comment by atkinsj** [comment]
I still have the same behavior in 1.1. It keeps reappearing and being said
its fixed but it's been broken ever since #81 for me.

**Comment by manimax3** [comment]
Yes, Im using the newest available version

**Comment by exodus4d** [comment]
This should be fixed in #207
