### ISSUE TITLE
maps out of sync

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#197]
after the latest ccp fuckup (read new CREST version) you have to manually reload your browser in order to see your new location after a jump. As a reload fixes the problem there might be just some tweaking you have todo with your code in order to get it right.

Steps to reproduce:
1) login into game and browser with same char (you see him in the system)
2) jump a wh (character does NOT move on the map)
3) hit browser reload (character shows up in the new system)

also new jumps dont generate the wh link from old system to new system. you have to manually add that.

**Comment by exodus4d** [comment]
@Tupsi Thanks! Does this happen on IGB **and** OGB?

**Comment by Tupsi** [comment]
uhh, why do we even care after the devblog from yesterday? :-) Honestly I dont know as I talked all my people into using ogb already.

**Comment by atkinsj** [comment]
I can confirm that this behaviour happens in the OGB via CREST but **not in the IGB.** A reload does not always fix the problem either: I had a user show in one system, hit reload, and it showed him in a slightly more up to date system but still not the most recent one.

I have a lot of users complaining about this.

**Comment by Tupsi** [comment]
this should be fixed with todays patch at DT. At least my users report that it is working again and that setting waypoints once again work.
