### ISSUE TITLE
Is this a real shutting down error or just your 500 page?

### ISSUE THREAD

**Issue by IslayTzash** [exodus4d/pathfinder#198]
I'm trying to access {goofy alliance url} after logging in, but I keep getting this popup.

If it's trying to indicate the server is shutting down, it probably shouldn't say "Only variables should be passed by refererence" an maybe you could trap this error and make a more custom message.   If it's really a generic 500 error page, it probably shouldn't say shutdown so much.

Also, why am I getting this error when I login.

FYI: The error goes away if I quickly toggle the green map tracking on/off in the top right.   Same behavior in desktop chrome and in game browser.

![capture](https://cloud.githubusercontent.com/assets/18371221/16178067/dc6386e6-360c-11e6-8dd0-eb59d42221db.PNG)

**Comment by CokkocZateki** [comment]
i get the same error

**Comment by exodus4d** [comment]
I´m pretty sure this is already fixed in #194. This is  problem with PHP 5.6. Switch to PHP7 or replace the single file with the one I have pushed.

**Comment by IslayTzash** [comment]
I see it on http://pathfinder.online-eve.com/map - isn't that you @exodus4d ?

**Comment by CokkocZateki** [comment]
no @exodus4d site is https://www.pathfinder-w.space?

**Comment by CokkocZateki** [comment]
no @exodus4d site is at https://www.pathfinder-w.space ? where did u get that from?

**Comment by exodus4d** [comment]
Confirmed! http://pathfinder.online-eve.com/map is **NOT** mine! You should check the URL twice, otherwise you will grant *CREST* access to someone else. 
If you don´t know who´s page that is, check your account management settings and remove unknown pages.

**Comment by exodus4d** [comment]
@IslayTzash can we close this?

**Comment by IslayTzash** [comment]
Still wondering why it says "Emergency shutdown" instead of OOPS?

**Comment by IvandaNothabeer** [comment]
I agree, its a misleading description of an "Internal Server Error". Its not clear to a casual user what an "Emergency Shutdown" is and its easily confused with a shutdown of the Eve game server

**Comment by exodus4d** [comment]
I changed the `HTTP: 500` status to `HTTP: 403` (unauthorized) and changed the dialog text.
There were also a few authentication tweeks included in cdd1846.

You will now see this error when the *login timer* (default: 240min) expires:
![logout_dialog](https://cloud.githubusercontent.com/assets/9299033/16742247/350d3d7c-47a7-11e6-80a3-bfa4c9822f5c.png)

**Comment by CokkocZateki** [comment]
Couldn't the text be a little more informative. Il get bombarded with user
not found when all they have to do is relog. My guys are not the brightest
light bulb out there so perhaps add relog to continue or something...

**Comment by exodus4d** [comment]
- Hitting the "reload" button redirect you straight away back to the login form. Your Cookies are not deleted so you can click on your character to log back in.

- If you don´t like the limt. Feel free to increase that value to e.g. `99999` `pathfinder.ini`

**Comment by IslayTzash** [comment]
I'm ok with the new screen.  I'm unsubscribing from this issue.
