### ISSUE TITLE
Configuration files should not be tracked

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#203]
I think it would be nice to remove the config files from git. Rename them to `config.example.ini` instead, and have people make their own config files from those.

It just makes it easier to keep using `git pull` without having to fix config files every time (or use a similarly unhandy solution).

**Comment by exodus4d** [comment]
You can pass environment variables by adding system-environment vars:
check this: https://github.com/exodus4d/pathfinder/issues/175#issuecomment-222334819

So you don´t have to care about the `environment.ini` any longer. I use this setup for multiple installations and testing instances of PF.

There is just one Issue with this. Cronjobs are triggerd by CLI (async). To make cronjobs working with this setup you have to set them up as "real" OS-system vars. But this is just something for advanced users :)
