### ISSUE TITLE
Feature Request: instant blacklist

### ISSUE THREAD

**Issue by id0** [exodus4d/pathfinder#204]
from what i read so far pathfinder mostly looks at the crop a pilot is in, if a black sheep need's to be removed it can take up to 24h or longer to a crop to take care of this matter aka. pod the pilot if needed so he gets removed from corp for good.
id realy like to see my crop using pathfinder asap - but not being able to revoke a individuals access (with out restarting the server) is a no go for us

**Comment by IvandaNothabeer** [comment]
See #205 for details on how to implement an external authorization scheme for a private pathfinder installation.

**Comment by WildStrawberryEVE** [comment]
External auth is a bit too complicated for me. Some simple blacklist by adding banned characterID to database or even a file would be great.
Less levels of authentication for user is better.
Some more complex ACLs (whitelisting preferred over blacklisting) (possibly using database) would be great.

**Comment by WildStrawberryEVE** [comment]
Ok.. I'm not a coder, i never coded in PHP in my life but...

```
--- /home/wildstrawberry/PF_Blacklist/pathfinder-1.1.5.orig/app/main/model/charactermodel.php   2016-09-24 16:32:11.000000000 +0200
+++ charactermodel.php  2016-10-01 01:05:14.152267537 +0200
@@ -297,6 +297,23 @@
         $f3 = self::getF3();

         $whitelistCorporations = $whitelistAlliance = [];
+
+/* Blacklist check - by character's "name" BLACKLIST = "name1","name2"*/
+       $instantBlacklist = [];
+
+       if( !empty($f3->get('PATHFINDER.LOGIN.BLACKLIST')) ){
+            $instantBlacklist = array_map('trim',(array) $f3->get('PATHFINDER.LOGIN.BLACKLIST') );
+        }
+       if(
+               !empty($instantBlacklist) &&
+               in_array($this->get('name', true), $instantBlacklist)
+       ){
+               $isAuthorized = false;
+               return $isAuthorized;
+       }
+/**/
+
+
         if( !empty($f3->get('PATHFINDER.LOGIN.CORPORATION')) ){
             $whitelistCorporations = array_map('trim',(array) $f3->get('PATHFINDER.LOGIN.CORPORATION') );
         }
```

```
--- /home/wildstrawberry/PF_Blacklist/pathfinder-1.1.5.orig/app/pathfinder.ini  2016-09-24 16:32:11.000000000 +0200
+++ ../../pathfinder.ini        2016-10-01 01:03:36.195560441 +0200
@@ -28,7 +28,9 @@

 ; restrict login to specific corporations/alliances by id (e.g. 1000166,1000080)
 CORPORATION                 =
 ALLIANCE                    =
+BLACKLIST                   = "Bad Guy 1","Bad guy 2"
+

 ; View ============================================================================================
 [PATHFINDER.VIEW]
```

Please tell me if it's catastrophic ;)

**Comment by exodus4d** [comment]
A blacklist can be managed on the new admin interface: #494

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #494
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
