### ISSUE TITLE
[Enhancement] Signature updating

### ISSUE THREAD

**Issue by krjohnn** [exodus4d/pathfinder#207]
Currently when you scan down a system, Signature module only keeps track of Signature Type but does not update Signature Description ( Site name, etc. ) when you scan it down further down and paste it into the Signature list.

On top of that, when you leave the system and want to check for new/disappeared sigs, there's no way to do it other than going through manually and when adding ( copy pasting ) the entire list again, it overwrites existing Signature Type back to Unknown

Would it be possible to implement 3 things
* Update existing signatures if the type is known but there is not description - to update the description for Combat/Relic/Data sites
* Do not update the signature if it exists in the list and the pasted type is Unknown - to avoid wrongfully updating already added/scanned/classified signatures
* Add signature if it's missing from the map signature list + show what's missing - to see new signatures and see which one has disappeared ( offer to delete the missing one/ones )

**Comment by exodus4d** [comment]
Thanks for reporting! This i definitely something I´ll add in one of the next releases.

**Comment by exodus4d** [comment]
@krjohnn do you have your *EVE*-client set to **Englisch**?

> Update existing signatures if the type is known but there is not description - to update the description for Combat/Relic/Data sites

I didn´t get your point :( Could you please give me an example of what you mean?

> Do not update the signature if it exists in the list and the pasted type is Unknown - to avoid wrongfully updating already added/scanned/classified signatures

I have fixed this in bfcf7fc. Signature `groupId` and `typeId` are no longer overwritten if they already exist. Should also fix #81 and #196

> Add signature if it's missing from the map signature list + show what's missing - to see new signatures and see which one has disappeared ( offer to delete the missing one/ones )

"Expired" (old) signatures can now be auto-deleted. I have added a new *checkbox* to the reader dialog. Check this issue: #95

**Comment by krjohnn** [comment]
Yes, it's English.

1. Sure. Following scenarion:

You enter a system, you see a signature. Cosmic Signature
You start scanning it down and now you know it's a Relic Site, so you copy and paste it to the Signature List, it updates fine
You keep scanning and now you know it's a Ruined Serpentis Monument Site, and you want to update it accordingly in the Signature List, but when you copy paste the result, it doesn't change the description. 

If I want to add the exact site name ( without typing it in manually ) I have to delete the site and add it again, then it will - Relic - Ruined Serpentis Monument Site.

Problem is that, it does not update the Description to the site if it become available ( for Data/Relic/Combat ), I suppose Wormholes are a different matter altogether.

2. That is odd, I am using 1.1.0 on https://www.pathfinder-w.space/map and it still updates existing sites to unknown if it I copy paste it again after leaving the system and coming back in. Anything to do with that browser I use ?

**Comment by exodus4d** [comment]
Thanks! The changes are not live yet. The Code is currently on the `develop` branch and is tagged for the upcoming release `v1.1.1`. This will be done in a few days.
