### ISSUE TITLE
Error 500: Internal Server Error / Creating default object from empty value

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#209]
![image](https://cloud.githubusercontent.com/assets/16602120/16359753/bcd4dbec-3b0f-11e6-9ffb-03f2bf82cdbb.png)

The error message above appears when using the pathfinder-w.space deployment in a consistent manner if the map is left open and untouched.  Could there be a timeout issue?  There is another post about this, but the error is different.

**Comment by exodus4d** [comment]
Thanks. I got the same error: [Stacktrace](http://pastebin.com/egRrX0Jc)
Should be fixed in the next release.
