### ISSUE TITLE
Re-installed pathfinder, can no longer navigate to /setup, /cron, or SSO

### ISSUE THREAD

**Issue by Geabo** [exodus4d/pathfinder#210]
I was forced to re-installed pathfinder on my server because of other issues. I kept the same apache .conf files, but I can no longer navigate to /setup,  /cron, or anything SSO related. I think it has something to do with the .htaccess file. I will post mine below (the www rewrite functions are commented out because I don't like that function) This all worked before the new install, and currently I can navigate to the login page.

```
# HTTP version
# Information: https://github.com/exodus4d/pathfinder/wiki/Apache

# Enable rewrite engine and route requests to framework ===========================================
RewriteEngine On

# Rewrite NONE www. to force www. =================================================================
# RewriteCond %{HTTP_HOST} !^www\.
# skip "localhost" (dev environment)...
RewriteCond %{HTTP_HOST} !=localhost
# skip IP calls (dev environment) e.g. 127.0.0.1
RewriteCond %{HTTP_HOST} !^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$
# rewrite everything else to "http://" and "www."
RewriteRule .* http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Some servers require you to specify the `RewriteBase` directive
# In such cases, it should be the path (relative to the document root)
# containing this .htaccess file:
# RewriteBase /app/
RewriteBase /pathfinder/

# Protect system files ============================================================================
RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteRule ^(lib|tmp)\/|\.(ini|php)$ - [R=404]

# Rewrite "everything" to index.php (dispatcher) ==================================================
RewriteCond %{REQUEST_FILENAME} !-l
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php [L,QSA]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

# PHP global Vars (can be set in php.ini as well,...) =============================================
php_value max_input_vars 5000
php_value suhosin.get.max_vars 5000
php_value suhosin.post.max_vars 5000
php_value suhosin.request.max_vars 5000

# Activate PHP error log ==========================================================================
php_flag log_errors on
php_value error_log "/www/htdocs/w0128162/www.pathfinder-dev.exodus4d.de/logs/php_errors.log"

# Cache Header ====================================================================================
# You should not change anything in here!
# New versioned files come with a unique path (e.g. ../js/v1.0.0/..) to force client cache busting.
<ifmodule mod_expires.c>
    # fonts
    <Filesmatch "\.(eot|woff2|woff|ttf|ttf|svg)$">
        ExpiresActive on
        ExpiresDefault "access plus 1 month"
        Header append Cache-Control "public"
    </Filesmatch>

    # images/vector graphics
    <Filesmatch "\.(jpg|jpeg|png|gif|swf|ico|svg)$">
        ExpiresActive on
        ExpiresDefault "access plus 1 year"
        Header append Cache-Control "public"
        FileETag None
        Header unset ETag
    </Filesmatch>

    # css
    <Filesmatch "\.(css)$">
        ExpiresActive on
        ExpiresDefault "access plus 1 month"
    </Filesmatch>

    ## js/source maps
    <Filesmatch "\.(js|map)$">
        ExpiresActive on
        ExpiresDefault "access plus 1 year"
        Header append Cache-Control "public"
        FileETag None
        Header unset ETag
    </Filesmatch>

    # html templates
    <Filesmatch "\.(htm|html)$">
        ExpiresActive on
        ExpiresDefault "access plus 1 week"
    </Filesmatch>
</ifmodule>
```

Whenever I navigate to /setup, /cron/ or try to click on the SSO link (which I did setup), I get the following page.
http://prntscr.com/bl664c

It makes me think the error has to be in apache somewhere, but the .conf file didn't change at all, only the .htaccess file.

**Comment by Geabo** [comment]
Might it also be a permissions issue?

**Comment by exodus4d** [comment]
Can you find anything in your php error.log or Apache access log files?

**Comment by Geabo** [comment]
From pathfinder_error.log in /var/logs/apache2/

[Sun Jun 26 00:35:37.945513 2016] [:error] [pid 1368] [client 207.173.42.232:61870] [app/lib/base.php:1518] Base->error(404)
[Sun Jun 26 00:35:37.945522 2016] [:error] [pid 1368] [client 207.173.42.232:61870] [index.php:19] Base->run()
[Sun Jun 26 00:38:06.890872 2016] [:error] [pid 1476] [client 207.173.42.232:61986] HTTP 404 (GET /var/www/pathfinder/public/js/v1.0.0RC2/app/setup.js), referer: http://pathfinder.mydomain.com/var/www/pathfinder/setup
[Sun Jun 26 00:38:06.891027 2016] [:error] [pid 1476] [client 207.173.42.232:61986] [app/lib/base.php:1518] Base->error(404), referer: http://pathfinder.mydomain.com/var/www/pathfinder/setup
[Sun Jun 26 00:38:06.891041 2016] [:error] [pid 1476] [client 207.173.42.232:61986] [index.php:19] Base->run(), referer: http://pathfinder.mydomain.com/var/www/pathfinder/setup

**Comment by Geabo** [comment]
Any insight into these errors?

**Comment by Tupsi** [comment]
check the pathfinder/public/js directory if you have that v1.0.0RC2. Most likely you updated the install and still have the old VERSION variable set in pathfinder.ini. It has to much the directory. So currently depending on what version you downloaded that variable should either say v1.1.0 or v1.1.1. Easiest way to find out what should be there is to just hunt down the directory and use that name in the variable.

**Comment by Geabo** [comment]
the directory and pathfinder.ini **both** say 1.1.0. Where would the /v1.0.0RC2/ in the above error file path be coming from? Please keep in mind, I was forced to delete my pathfinder directory and start over due to other issues at the beginning of this install. Are there files in other directories that could still be the old version?

**Comment by exodus4d** [comment]
Sorry about that *pre release* candidates are no longer supported. There were to many DB changes. You have to grap the latest release and rebuild your database.
