### ISSUE TITLE
comment in environment.ini develop branch is wrong

### ISSUE THREAD

**Issue by garemoko** [exodus4d/pathfinder#212]
https://github.com/exodus4d/pathfinder/blob/develop/app/environment.ini#L11

In fact, the base needs to be `/pathfinder` instead of `pathfinder/`

Note: I'm still trying to get pathfinder working on localhost so i may come back and edit this!

**Comment by garemoko** [comment]
having made that change, I'm now getting the html apparently working but the css and js resources are looking in the wrong place

**Comment by garemoko** [comment]
In fact with 'pathfinder/' the css/js doesn't work either because it then looks at 'http://www.localhost:8888/pathfinder/pathfinder/public/js/v1.1.1/lib/require.js'

**Comment by exodus4d** [comment]
Have you checked this fix for the next release? https://github.com/exodus4d/pathfinder/issues/195 (its currently on develop branch).

If you have a local Nginx running. The best way to configure it lokal, is to leave `BASE` empty, set a random `URL` (like `http://pathfinder.local`) in your environments.ini, and then add a new entry to your `etc/hosts`( like `127.0.0.1 pathfinder.local`).

**Comment by garemoko** [comment]
@exodus4d I'm using the develop branch and MAMP (apache on mac). Looking at Master, the links to css and js are much simpler and I imagine don't have the same issue. 

Looking at the index template on develop, I wonder if (for example)
`{{ @BASE }}`

should be

`{{ @BASE }}/` and the environment file should tell you to use "/pathfinder"? 

That appears to work for me. Lemme make a PR...

**Comment by garemoko** [comment]
https://github.com/exodus4d/pathfinder/pull/213

**Comment by garemoko** [comment]
By the way, the version of Apache that comes with MAMP is 2.2.29, rather than the required 2.5, so I'm running an unsupported version there.

**Comment by exodus4d** [comment]
Issue was fixed a while ago
