### ISSUE TITLE
The sign up link does nothing

### ISSUE THREAD

**Issue by garemoko** [exodus4d/pathfinder#214]
This applies both to the version on https://www.pathfinder-w.space/ and on my local machine (forked from development). Clicking the sign up link does nothing. No errors in console, no network activity, nothing.

**Comment by exodus4d** [comment]
Can not confirm. works fine for me. Clear your /tmp/cache folder and browser cache please. multiple hundred users online currently. Anything in your log files?
Please join *Slack* for questions like this.

**Comment by garemoko** [comment]
![image](https://cloud.githubusercontent.com/assets/1363163/16363120/731c71c8-3bb8-11e6-9d2f-2169768acb0e.png)

Just to be clear, I'm talking about that button, not the EVE SSO. Tested in Firefox too, which I set up to clear everything whenever I open it - same problem. 

What's the slack channel please?

**Comment by Bingmano** [comment]
ah confirmed, that doesn't work for me either.

**Comment by exodus4d** [comment]
I removed those links from the panels. They are relicts from the Beta version.
