### ISSUE TITLE
Server error 500 when using SSO from http://localhost:8888/pathfinder/

### ISSUE THREAD

**Issue by garemoko** [exodus4d/pathfinder#216]
Apologies for raising this here rather than Slack - I've not been able to find details of the Slack channel yet. 

I'm trying to get SSO working so I can log in on my local install. I've got as far as redirecting to EVE SSO, selecting a character and clicking "authorize". 

On the first attempt, I get redirected to the main page but am not logged on. Nothing is saved in the DB.  

On the second attempt, my alliance and corp get created in relevant tables, but no users are created. I get a server error 500:

> Message: PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:50:00) AS `date` FROM `alliance` WHERE `id`=99003244' at line 1

On the third attempt, I get logged in fine. 

I'm using MySQL 5.6.25. 

I suspect the problem is with trying to fetch data from the database immediately after storing it in charactermodel.php. I'm pursuing that line of investigation.

**Comment by garemoko** [comment]
This seems to be caused by an adhoc field called date getting included when the alliance table is reloaded after inserting. 

[This fix](https://github.com/garemoko/pathfinder/blob/garemoko-2/app/lib/db/sql/mapper.php#L428) works but I'm concerned that I don't really understand what adhox is and may be breaking something else.

**Comment by exodus4d** [comment]
This is very very strange -_- . I have never heard about that bug :(
The code you mention is *thired-party* framework code. Not written by me. I guess there is not very much I can do about that.
