### ISSUE TITLE
[Feature] Undo button

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#218]
Because I just deleted the wrong wormhole.  It would be amazing to have, both for the map, and for sigs.  So if I paste sigs in the wrong system, I can just undo it.

If this is something that would take time, an edit log help.  Also so you can see if someone is messing with the map.

**Comment by InfiniZ** [comment]
Seconding this feature request.  Had a few corp users request an undo, due to pasting sigs in the wrong system and overwriting previous ones.

**Comment by dnolen** [comment]
This is needed. Multiple pilots working on multiple connections can at times lead to incorrect data. 

Please look at implementation of this for future releases. My sanity thanks you for your consideration/work on this.

**Comment by exodus4d** [comment]
#### Signature table history [beta]
There is now a "_semi persistent_" history for signature tables available.  Features:
- Each change in the table creates a new history record with **all** signatures on it.
  - Add/Delete or Update a signatures creates a record of all signatures
- Historic signature data is stored in **Cache** for **2h**
  - If Cache gets cleared, historic data is also cleared
- Up to **10** history record can be stored for a table
  - It is not just an "undo" action, you can choose between the last 10 stats of the table
- The "character name" who did the change, is recorded as well
- The total number of signatures + timestamp of a record is visible in the UI
- There are icons for "add, delete, update" action that triggered the new history record added to UI
- If someone _undos_ (load old table state) a table, this can be seen as well in the UI


![sig_history](https://user-images.githubusercontent.com/9299033/54841017-9a776280-4cce-11e9-9198-a24fc1a12ec2.gif)
