### ISSUE TITLE
[Minor Feature/Enhancement]  Sig and wormhole expire after time

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#219]
So that wormhole connections would expire after the max lifetime (36h?).  Wormhole sigs as well, and any others that spawn.   Just something to make managing the map a little easier.

**Comment by Bingmano** [comment]
+1 for this, my corp is full of lazy people :(

**Comment by cmasiah** [comment]
+1 Exodus, we would benefit from this addition as well. Having WH sigs disappear after X amount of time and also DELETED from the map view would be great. I've logged into Pathfinder numerous times now and seen 3+ day old WHs still on the map. My corp is full of lazies.

**Comment by dudelard** [comment]
+1 need this feature, wormhole expiration specially

**Comment by dnolen** [comment]
This is a feature that I loved in tripwire and it would be awesome to see it enabled in pathfinder. 

Also side now. Can you change the EOL timer from a starting value of 00:00:00 to a count down from 4 hours? Just makes it more prevalent to the time remaining rather then the time the has been marked EOL.  Just my opinion though.

**Comment by exodus4d** [comment]
#### This issue currently in development:
I implement this in **two** iterations over the next releases.

##### 1. Iteration (Connections):
- Add new map settings option "**Delete expired connections?**" and make it configurable per map (default: **enabled**)
- Auto delete **_EOL_** (wh) connections where `eolUpdated` column older **4h 15min** (cronjob)
- Auto delete (wh) connections where `updated` column older **36h** (cronjob)

![test](https://cloud.githubusercontent.com/assets/9299033/19623080/fd0635da-98bb-11e6-9a40-28cf265ad40f.png)

##### 2. Iteration (Signatures):
- Auto delete signatures where `updated` column older **36h** (cronjob)

****

#### Hint
- When connections get deleted automatically, there might be floating systems without connections.

**Comment by exodus4d** [comment]
### New Improvement
#### There is now a new option (default: active) for auto-delete wormholes with a *create* timestamp older than *2days*. 

- The default of 2days can be adjusted in `pathfinder.ini`, key `EXPIRE_CONNECTIONS_WH`
- A new * cronjob* for cleanup runs hourly
- Connections with other scopes (*stargate*, *jumpbridge*) are not affected by this

![haw58co](https://cloud.githubusercontent.com/assets/9299033/26004898/a02c9d20-3737-11e7-99f4-a1e6ec917508.png)
