### ISSUE TITLE
Internal Server Error after moving systems on Map

### ISSUE THREAD

**Issue by IvandaNothabeer** [exodus4d/pathfinder#22]
After moving a system on  a map, I get an error 500: internal system error. An "Emergency Shutdown" splashscreen appears and the account is logged off.

The account can no longer log in after this error occurs. Seems to be an error with drawing the map after systems are moved. 

To resolve this error I need to delete the "system" , "map" and  "user_map" records from the database.

Unfortunately my php debugger doesn't catch any exception so Im not sure where to start looking for the bug.

**Comment by exodus4d** [comment]
Sorry Im not able to give any support for external installations for now. The DB dump published from "mglinski" in this wiki is *not*  final! 

Thinks to try:
- Is your cache engine working correct? (delete cache folder if file cachine is active)
- Set "debug" level to "3", this should enable advanced error logging.
- Check your php error file for more information.

I need more detailed information.

**Comment by IvandaNothabeer** [comment]
Well ...  See issue #11 :)

**Comment by IvandaNothabeer** [comment]
So here's the problem ...

I'd really like to thank you for putting together what is a truly great looking program. Something that I would love to be a part of bringing to wider Eve online community. Unfortunately, despite many hours of testing and debugging code I  can no longer continue to do this  because you have decided not to release a critical component of your "open source" code - ie. the database. Which is a foundation of your application.

Apparently, I'm not the only person to feel this way. MGlinsky has spent hours reverse engineering your code to provide us with the essential, but missing, database schema that lies behind your months of sterling efforts.

Frankly, while I think you have a potentially brilliant tool here, I'm simply not prepared to try to help any longer if you continue to hobble us this way. Without the database schemes, your code is utterly useless. It might as well not be open source. Spending hours debugging hijacked database schemas when I'm actually volunteering  to test your code is a complete waste of my time.

**Comment by exodus4d** [comment]
Thanks for your feedback! You are right i was wrong. #11 has been marked for the next milestone "v 0.0.10 BETA" 3 days before your  comment. Which is not far off (some days).

Additional information for your installtion is already available in the `develop` branch:
https://github.com/exodus4d/pathfinder/blob/develop/README.md
