### ISSUE TITLE
[Security Enhancement]  An option to not show where you are on map.

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#220]
An option where the map will still track your location, but not share it with everyone viewing the map.

**Comment by Bingmano** [comment]
If you want to just see the map, you can turn off tracking, or you can set the map to track a toon that is not in the chain.  Maybe if you could elaborate some on why this is important to you?  Personally i can't think of a scenario of where this could be useful, but i'm now curious :)

**Comment by Ligraph** [comment]
Even if you turn tracking off, it still shows where you are on the map, assuming you are in a mapped system. 
Lets say you had a spy in alliance.  They would be able to see where everyone who was using pathfinder was as long as they were in a mapped system.

**Comment by Bingmano** [comment]
Ah i see your point now, that makes sense.  Perhaps the identity tracking could be controlled at the map level instead of having people remember to turn it off under blackout conditions.  Another thought could be, now that CREST is fully implemented, control who can actually see locations on the map based on role?

**Comment by Ligraph** [comment]
That would be nice too.  Or even better, use a access list on whoever created the map (assuming that read access lists gets added)

**Comment by exodus4d** [comment]
Good feature! If you could solve this client-side it would be very easy to implement (data send to clients but not rendered). But we need this on server-side which makes it a bit more costlier ;)

**Comment by exodus4d** [comment]
There is now a **new** tab under "_Account settings_" -> "_Character_" Where character specific settings will be added. 
I added a new option "**_Auto update current location_**" (default: **enabled**).  This works as a global switch for the current character if the _CREST_/character/location endpoint is used to update the current location, or not.
Deactivating this, will immediately delete your current DB location entry and disable any further _CREST_ updates.

> **Important:** Do not mix this up with the "**_map tracking_**" toggle in the navigation bar! 
The new option is mandatory for  the "map tracking" toggle to work. The "map tracking" toggle just affects auto-adding new connections to a map, when a jump was detected **and** the the new connection matches the "map scope".

![account_settings_character_location_tracking](https://cloud.githubusercontent.com/assets/9299033/19831832/7c03462c-9e14-11e6-910b-bd2f04680e3a.png)
