### ISSUE TITLE
[Enhancement] Show classes for shatered wormholes

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#221]
Right now all that is shown in SH, it would be nice to see the class, too.  Also, statics to and from shattered wormholes aren't working (I think this is known?).

**Comment by Bingmano** [comment]
I have been connected to a C1 that is shattered that shows up as a C1.  Could this possibly just be certain holes are labeled as SH?

**Comment by Ligraph** [comment]
No idea, but all the shattered ones I see show up as SH.  Did statics work for you?

**Comment by exodus4d** [comment]
There is already an issue for this #180
