### ISSUE TITLE
[Feature Request] Make system status and description persistent 

### ISSUE THREAD

**Issue by Waigie** [exodus4d/pathfinder#223]
It would be really helpful, if the system status and the systems description would be persistent.

We like to set the system status for occupied/hostile systems and add the corp/group name as description. But those data is lost once the system is deleted from the map. So the moment we add that system again to the same map, we have to re-input the data.

**Comment by Tupsi** [comment]
I already requested this, see #184

**Comment by Waigie** [comment]
Okay missed that, sry

Duplicate of #184
