### ISSUE TITLE
Error 403 while adding/removing items

### ISSUE THREAD

**Issue by RichterSR** [exodus4d/pathfinder#226]
Hi,

I have setup a private instance of pathfinder today on my server (Ubuntu 14.04, Apache 2.4.20, PHP5.6, MySQL 5.6 on a remote server).

Now everything is working exept the following:

Everytime I try to add a system manually to the map I receive an error (403; forbidden). 
Also when I try to delete a Map or insert signatures.

Unter /setup everthings looks fine.

i hope someone can help me with this.

**Comment by exodus4d** [comment]
- Which PF version are you running?
- Anything in your Apache error log files?

**Comment by exodus4d** [comment]
I didn´t got any feedback :( Ill close. Feel free to reopen with more detailed information.
