### ISSUE TITLE
[Enhancement] Allow people to add corporations to alliance maps

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#227]
On alliance maps, let us add corps and/or people to the map.  Could do the same with corp maps (let us add people).  For example, we have a alt corp in a different alliance, and it would be nice to get the map there as well.

**Comment by garemoko** [comment]
Oh, just read your last sentence. This is for associates.  I'm working on wh expiry right now, but can maybe look at this next.

**Comment by garemoko** [comment]
Any reason why we can't just add the whole associates alliance?

**Comment by exodus4d** [comment]
Yeah this is a dublicat #222
