### ISSUE TITLE
Dying and moving to your home station maps as a WH

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#230]
When you die, pathfinder adds a wormhole from where you die to your home station.

**Comment by exodus4d** [comment]
Yeah that´s right, but there is no way to figure out whether someone was podded or if this was an intended pod jump (e.g. from a wormhole to HS).
Unfortunately we can´t fix this... :(

**Comment by garemoko** [comment]
@Ligraph don't die!
