### ISSUE TITLE
Map layout syncing still not functioning

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#231]
I am still having big issues where if one person rearranges the layout of the systems of the map the changes are not visible to other users until they manually refresh the page.

This leads to multiple people rearranging the same map and changes being lost or overwritten. This is happening on the 1.1.1 dev branch current as of now.

**Comment by exodus4d** [comment]
Is this fixed now for you? haven´t seen this issue in the latest 1.1.6 version
