### ISSUE TITLE
[Feature] Clone jump is registered as WH jump

### ISSUE THREAD

**Issue by Grookshank** [exodus4d/pathfinder#235]
When using a jump clone PF added a connection from the system I jumped from to the system I jumped to.

**Comment by garemoko** [comment]
Pathfinder works by noticing when you change system and checking if there's a stargate between those two systems. Eve's API does not tell us how you got from one system to another so there is no way to avoid this problem. Just manually delete any whs created by jump cloning or dying. 

The only thing I could think we could do is to not track jumps when you are in a pod. People are unlikely to be scanning in pods.

**Comment by exodus4d** [comment]
That´s correct.

**Comment by exodus4d** [comment]
That´s corect!

There are some other options but none of them is 100% save:
- From CREST we also get the current docked station. So you could check if *station* **and** *system* changed between two CREST calls. This just fails in case you jump a stargate with a POD, warp to station and dock in less than 10s (this is the CREST update interval). I don´t know if someone could manage this :)

**Comment by Regner** [comment]
FYI: The CREST cache time for a characters location was lowered to 5 seconds. So you could be going faster if you wanted. :)

**Comment by exodus4d** [comment]
Cache time for character location *CREST* calls was reduced from 10s -> 5s in https://github.com/exodus4d/pathfinder/commit/7d9e184e0f3c9fb301357cd21e3588f9caf77238

**Comment by exodus4d** [comment]
I thing we should close this Issue, There is no solution for this at the moment.
I decided not to implement any functionality that **should** work in **most** use cases. It would make it opaque to users.

If someone has a proper solution for that, feel free to comment this issue. We can always reopen it ;)
