### ISSUE TITLE
[Feature Request] Add an option to show the region for systems on a map

### ISSUE THREAD

**Issue by Grookshank** [exodus4d/pathfinder#236]
This would be very useful to have in Thera and for connections going out of it, but maybe also for other WHs.

**Comment by garemoko** [comment]
+1

**Comment by exodus4d** [comment]
Good Idea, The implementation  is not a problem that information is already available in javascript. But where should we show that information? I don´t want to mess up the map with millions of overlays :) Maybe we could add a new filter for that information.

Until then you could use the "map information" dialog and filter/sort for regions if you are looking for an exit in region XYZ:

![filter_region](https://cloud.githubusercontent.com/assets/9299033/16715462/9aaffbbe-46e0-11e6-9c7f-5c1a13bc4fb6.png)

**Comment by atkinsj** [comment]
We do this already -- we've added it to the system icon in the map itself
so it sits below the system name and security. It makes each system a
little larger but people are very interested in having this information
upfront.

I'll attach a screenshot when I'm back at a PC.

**Comment by Grookshank** [comment]
What atkinsj did is what I had in mind.

**Comment by exodus4d** [comment]
I´m currently working on a new **label-function**. 
There will be a new **tag-tool** in the upper right which will show you more system information on *mouseover*. We start with "region name" but it will be extended with more information in future.

I like the tooltip approach more than a persistent solution. Map does not get messed up:
![map_regions](https://cloud.githubusercontent.com/assets/9299033/16896897/e00d0dee-4ba1-11e6-991b-26cd67b0363f.png)
