### ISSUE TITLE
Missing statics from Thera

### ISSUE THREAD

**Issue by Grookshank** [exodus4d/pathfinder#240]
As written in https://forums.eveonline.com/default.aspx?g=posts&m=6556052#post6556052:

Please add the following statics as Thera exits:

Thera to NS - E587
Thera to LS - V898
Thera to HS - Q063

**Comment by exodus4d** [comment]
#### Statics for *Thera* wormhole will be added with the next release

> **Important:** 
- If you have a private installation for *Pathfinder*, you have to (re)import the static `/export/sql/pathfinder.sql` file in order get the new wormhole types!
- Clear `/tmp/cache/` folder afterwards

**New statics:**
![thera_statics](https://cloud.githubusercontent.com/assets/9299033/16886518/26de4206-4ad5-11e6-9864-a6eec98fa0b9.png)

**New "database index" panel on `/setup` route:**
![setup_index](https://cloud.githubusercontent.com/assets/9299033/16886528/34bfec62-4ad5-11e6-8659-bd117f0b6f4d.png)
