### ISSUE TITLE
"cytaclysmic" typo

### ISSUE THREAD

**Issue by Gi133** [exodus4d/pathfinder#241]
Instead of "Cataclysmic", pathfinder has that wormhole effect down as "cytaclysmic".

**Comment by dnolen** [comment]
is there an alter statement we can run in private instances to correct this or an sql that can be deployed to make said change?

**Comment by exodus4d** [comment]
No, you have to re-build the js source files with *Gulp* (described in the wiki) in order to get the fix. or simply wait for the next release ´v1.1.2`.
