### ISSUE TITLE
[Feature] Thera EVE-Scout data added to map tab

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#243]
Suggestion: 
When adding thera (new tab for thera only connections or current map) create a pull request from the eve scout mapping data to populate sigs with in pathfinder.

**Comment by exodus4d** [comment]
Is there a public API for pulling those information? Could you please post a link in here. Thanks

**Comment by dnolen** [comment]
I do not have a public API available. you may want to reach to the folks that run eve scout if they can provide you one. Other mappers have their map included so there has to be something available. 

https://www.eve-scout.com/thera/

**Comment by Grookshank** [comment]
Please don't make this mandatory for Thera maps, since Eve-scout tends to be outdated and has mistakes in mapping.

**Comment by dnolen** [comment]
Having some form of routing info for quick access would be a nice to have if group use it to hope from one side of new eden to the other. 

If data is being referenced from EVE-scouts data it should hopefully be relatively upto day with new entries but I'm not sure how often the purge connections when they die.

**Comment by Grookshank** [comment]
> If data is being referenced from EVE-scouts data it should hopefully be relatively upto date with new entries but I'm not sure how often the purge connections when they die. 

It is not up to date. I live in Thera. Having evescout info on Thera maps mandatory would be very bad.

**Comment by dnolen** [comment]
Upto date or no, this needs to included in the mapping tool. We have a need to be able to see the exits for routing purposes. 

Most of the other mapping tools already include some form of link to the thera exit data so it would make sense to tie it in here seeing as a few mappers won't work out of game with the browser it fully removed.

**Comment by dnolen** [comment]
Just a thought in regards to this. Would it be beneficial to talk to evescout team to find out how to get an API into their updated map info to populate an additional tab if desired for Thera?

**Comment by maurerit** [comment]
Was just goofing around and searching about and ran across this: https://eve-scout.com/api/wormholes

**Comment by exodus4d** [comment]
I close this issue because of duplicate. See #829
I plan to add a _PF_ map for "Thera" connections with the above issue, as well for _Pathfinder_ release `v1.5.6`.
