### ISSUE TITLE
Importing new pathfinder.sql fails with error

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#248]
`ERROR 1054 (42S22) at line 124: Unknown column 'systemId' in 'field list'`

This is the error received when attempting to import the new pathfinder.sql on the develop branch. I attempted to refresh the db using the /setup route but this fails with an error 500:

`[Sat Jul 16 15:26:31.591612 2016] [:error] [pid 8817] [client 127.0.0.1:61267] PDOStatement: Table 'pathfinder.constellation_wormhole' doesn't exist`

**Comment by Tupsi** [comment]
yep, reading this first could have saved me some time. :-) git pulling the newest stuff leads straight to the mentioned 500 error. Sounds like the classic egg/chicken problem. We need to get into /setup to create the new table, but can not enter setup because the table is not there, nice one ;-)

**Comment by Tupsi** [comment]
he mentioned in #125 that we have to drop/recreate these tables (wormhole, constellation_wormhole, system_wormhole), but I do not find something explaining how they should look like. In any case, this should not refuse us entry to /setup as this is where one should be able to (re)create them in the first place, right?

**Comment by exodus4d** [comment]
@Tupsi thats 100% correct :) The table structure has changed, therefore you have to re-create those tables. But you should be able to enter /setup for this. Do you get any errors on the /setup page?

**Comment by Tupsi** [comment]
as I already said, I get the same error as @atkinsj, saying 500 table doesnt exist.
nginx log files show:
`2016/07/17 06:49:04 [error] 8198#8198: *1145 FastCGI sent in stderr: "PHP message: PDOStatement: Table 'mydb.constellation_wormhole' doesn't exist
PHP message: [app/lib/base.php:2032] Base->error(500,'PDOStatement: Table 'evepathfinderdev.constellation_wormhole' doesn't exist')
PHP message: [app/lib/db/sql.php:339] DB\SQL->exec(array('SHOW columns FROM `mydb`.`constellation_wormhole`;'),array(array()),86400)
PHP message: [app/lib/db/sql/mapper.php:629] DB\SQL->schema('constellation_wormhole',NULL,86400)
PHP message: [app/lib/db/cortex.php:138] DB\SQL\Mapper->__construct(DBSQL::__set_state(array()),'constellation_wormhole',NULL,86400)
PHP message: [app/lib/db/cortex.php:124] DB\Cortex->initMapper()
PHP message: [app/main/model/basicmodel.php:77] DB\Cortex->__construct('DB_PF',NULL,NULL,86400)
PHP message: [app/main/model/basicmodel.php:610] Model\BasicModel->__construct(NULL,NULL,NULL,86400)
PHP message: [app/main/model/systemmodel.php:434] Model\BasicModel::getNew('\Model\ConstellationWormholeModel')
PHP message: [app/main/model/systemmodel.php:239] Model\SystemModel->getStaticWormholeData()
PHP message: [app/main/model/mapmodel.php:310] Model\SystemModel->getData()
PHP message: [app/main/model/mapmodel.php:198] Model\MapModel->getSystemData()
PHP message: [app/main/controller/api/map.php:645] Model\MapModel->getData()
PHP message: [app/main/controller/api/map.php:619] Controller\Api\Map::getFormattedMapData(array(ModelMapModel::__set_state(array())))
PHP message: [app/lib/base.php:1672] Controller\Api\Map->updateData(Base::__set_state(array('hive'=>array('HEADERS'=>array('Cookie'=>'pathfinder_session=9afsjrpxxxxpkqg3qt3','Content-Length'=>'0','Referer'=>'https://xxx/map','X-Requested-With'=>'XMLHttpRequest','Accept-Encoding'=>'gzip, deflate, br','Accept-Language'=>'en-US,en;q=0.5','Accept'=>'application/json, text/javascript, */*; q=0.01','User-Agent'=>'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0','Host'=>'host'),'AGENT
`

**Comment by exodus4d** [comment]
This should now work. If you still have problems:
- **delete** the "static" DB-tables
 - `wormhole`
 - `system_wormhole`
 - `constellation_wormhole`
- **clear** cache folder
- **re-create** them on `/setup` page:
