### ISSUE TITLE
Unable to import database in Mysql

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#25]
Hello,

I am unable to import the .sql in Mysql, also, I also had to change the php upload_max_filesize (only becxause I'm using phpMyAdmin I think) value to more than 2M (by default), maybe you should note it in the installation documentation, could be useful.

![](http://sakarias.eu/u/20150923000138.png)

**Comment by IvandaNothabeer** [comment]
Issue is supposed to be resolved in MySQL 5.6.5

Note that this means the Requirements listed for Pathfinder MySQL version are incorrect.

**Comment by Sakarias-Longhorn** [comment]
Well i'm using "sudo tasksel install lamp-server" to install my lamp stack. I'll update the mysql db and report.

**Comment by Sakarias-Longhorn** [comment]
Oh..It seems I can't install mysql 5.6.. I uninstalled the old mysql from my server and installed the new mysql-server-5.6 but when I login on PhpMyAdmin, it says my version is still 5.5.44. Any idea ?

**Comment by IvandaNothabeer** [comment]
http://stackoverflow.com/questions/6576989/two-mysql-timestamp-columns-in-one-table

**Comment by Sakarias-Longhorn** [comment]
![](http://sakarias.eu/u/20150923031410.png)
![](http://sakarias.eu/u/20150923031505.png)

Looks like it's importing without any error now =) Thanks.

**Comment by IvandaNothabeer** [comment]
Yeah, well my Hosting service only provides MySQL 5.5.23

R.I.P.

**Comment by exodus4d** [comment]
Thanks for reporting. I added the `upload_max_filesize ` to the wiki. Ill check the MySQL version and update the "Requirement" section if needed.
