### ISSUE TITLE
Debug logging not working

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#252]
Hello,
my Pathfinder private install suddenly stopped working. Can´t login in, no error is shown , after entering credentials I got CCP Authorize dialog, after authorizing in comes back to login page. To debug this I changed in environment.ini DEBUG variable to 3, but nothing changed in logging behavior. 

Thanks

**Comment by dkrotil** [comment]
Looks like some improvements will be in 1.1.2 , is there any ETA for that version ?

**Comment by exodus4d** [comment]
Hi, thanks for reporting. `v1.1.2` will be released this week. I was on vacation the last two weeks.

Have you checked your Nginx error logs and fpm-php error logs, too?

**Comment by dkrotil** [comment]
Hello, there aren´t any errors in Nginx / PHP FPM after unsuccessful login to Pathfinder.

**Comment by exodus4d** [comment]
Interesting... It´s hard to help without any additional information :(

### Some suggestions:

* If the redirect from CCPs SSO back to Pathfinder succeeded, you should end up in [sso.php#L161](https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/ccp/sso.php#L161). This can be used for debugging e.g.:
```
var_dump('test');
die();
```
> Don´t forget the `die()` otherwise you will get redirected back to the landing page (as you described) abover... at the end of this function!

* You should check if you land in any of the `else{...}` (error) cases
* If you **don´t** get any debug output in here. Your redirect URL fails, check the URL in your browser (e.g. link in here, maybe I can help you) and compaire with the URL on the developer page.
* Check if there is a log file `logs/crest.log` for errors.
* Check the owner permissions for `logs/` for read/write rights
* Any "errors/warnings" on the `/setup` page?
* If you recently updated *PF* clear `/tmp/cache` folder and check owner permissions

**Comment by dkrotil** [comment]
Hello, 
I put that your code on line 278 in sso.php .
output is :

string(4) "test"

- In **crest.log** is only error, when I tested wrong password, nothing else.
- logs folder has proper permissions , there are many log files, but nothing when I try to login 
- /setup page is green, no warnings at all
- URL looks OK /sso/callbackAuthorization?code=

**Comment by dkrotil** [comment]
Have updated Pathfinder to 1.1.2, but problem is still there, can´t login to Pathfinder, Debug is set to 3, but only Cron logs are current, crest.log , login.log and error.log have entries more then week old. even I tried to login couple minutes ago.

**Comment by dkrotil** [comment]
I looked on all log files again and found this :

PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session_id' at row 1 in /srv/www/htdocs/app/lib/db/sql.php:202

**Comment by dkrotil** [comment]
Debug looging is working, will close this and create new issue with sesssion_id problem.
