### ISSUE TITLE
[Bug] Signature Adder confined to Map area only

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#255]
We are seeing issues with the signature add tool in the interface. 

Currently it appears that the tool to add sigs into the map is not breaking out of the map area if required and there are issues with scrolling with in the interface when the addition tool is opened.

**Comment by dnolen** [comment]
See example below 

http://i.imgur.com/cX2JG67.png

**Comment by exodus4d** [comment]
Are those screenshots from the IGB?
