### ISSUE TITLE
[bug] Russian client "signature reading" button

### ISSUE THREAD

**Issue by Leg501** [exodus4d/pathfinder#256]
On the Russian client when adding signatures through "signature reading" button.
addition does not take place (not even filling the id)

BJV-285	Источники сигналов			0%	42,40 а.е.
ZXU-948	Источники сигналов	Червоточина	Нестабильная червоточина	100,0%	8,05 а.е.

**Comment by exodus4d** [comment]
Thanks for report :)
*Pathfinder* only supports the English client and English signature names!
But we should at least add signatures in other Clients.  I added `Источники сигналов` to the allowed strings for signatures. 

But i need your help:
In the Englisch client there are **two** strings for signatures: 
- "Cosmic Anomaly"
- "Cosmic Signature"

What does `Источники сигналов` mean? - Is it the first or the second string? Could you please copy&paste me the **exact** Russian word for the **other** string? - I´ll add this as well

#### With the upcoming release, you should see at least the sig-name:
![signature](http://i.imgur.com/zElvQNs.png)

But please, do not expect more support like "type", "group" detection for signatures....

**Comment by ComBin** [comment]
Hello! Thanks for you answer.

Here is another example:

> FSX-821 Космическая аномалия ОПАСНО: район повышенной опасности Frontier Barracks 100,00% 3,12 а.е.
> WPU-280 Космическая аномалия РУДА: район добычи руды Common Perimeter Deposit 100,00% 12,64 а.е.
> OKV-584 Космическая аномалия ОПАСНО: район повышенной опасности Integrated Terminus 100,00% 12,99 а.е.
> KTL-056 Источники сигналов   0% 5,25 а.е.
> SCW-730 Источники сигналов   0% 2,80 а.е.
> XQE-870 Источники сигналов   0% 6,23 а.е.
> SKZ-930 Источники сигналов   0% 5,31 а.е.
> XVR-422 Источники сигналов   0% 10,32 а.е.
> CHG-000 Источники сигналов   0% 3,24 а.е.

In this case:
- "Космическая аномалия" mean "Cosmic Anomaly";
- "Источники сигналов" this is "Cosmic Signature".

**Comment by rsrg** [comment]
Please add support for determination of group of fields for russian client.

"Cosmic Signature" - "Источники сигналов"
"Cosmic Anomaly" - "Космическая аномалия"

"Wormhole" - "Червоточина"
"Relic Site" - "АРТЕФАКТЫ: район поиска артефактов"
"Gas Site" - "ГАЗ: район добычи газа"
"Ore Site" - "РУДА: район добычи руды"
"Data Site" - "ДАННЫЕ: район сбора данных"
"Combat Site" - "ОПАСНО: район повышенной опасности"

If you have any questions, do let me know.
