### ISSUE TITLE
Disabled HTTPS

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#26]
Hello again,

I receive a **ERR_CONNECTION_REFUSED** when I try to access pathfinder (Probably because I don't have mod_ssl enabled, and I don't want to enable it, plus I don't have a certificate to use with it)

Is there any way to disable HTTPS in pathfinder ? (I even tried commenting out some rewrite rules but it keeps redirecting me to HTTPS, you probably hardcoded it :/ )

Thanks.

**Comment by exodus4d** [comment]
Please check .htaccess https://github.com/exodus4d/pathfinder/blob/master/.htaccess L.10-16. It is not "hardcoded" :). I expect anyone who is installing a copy of *Pathfinder* to edit this file, to get it to work in his environment.  
Using SSL is recommended. Ill add a hint in the wiki. Thanks for reporting.

**Comment by Sakarias-Longhorn** [comment]
As I said, I tried commenting the lines but it keeps redirecting me to HTTPS. I even tried REMOVING the .htaccess file and I got redirected to https again...

**Comment by Zumochi** [comment]
Did you try removing history or in incognito? It's very possible your browser remembers that it redirects to https.



—

**Comment by Sakarias-Longhorn** [comment]
I cleared my browser's cache, now I just get a ERR_NAME_NOT_RESOLVED, So I created an A RECORD pointing to www (I think that's the cause, correct me If I'm wrong), I'm waiting for the record to be created now, and i'll report after.

**Comment by exodus4d** [comment]
Do not remove them. They are necessary, otherwise the Framework can´t redirect URLs back to the index.php. The index.php works as a dispatcher for any Ajax URL that is called.
 This is how it works: http://fatfreeframework.com/routing-engine#sample-apache-configuration

There is no "HTTPS (on/off) switch in the config. But yeah changes to the .htaccess need a complete history clean in your browser. And even than i have sometimes problems to get new changes to work. I´ll do a fresh installation (without SSL) this weekend and check it.

**Comment by Sakarias-Longhorn** [comment]
Ok, I'll try to get it to work on my end for now,
Also~ In the installation instructions, at the cron tab part, what cron do I need to add exactly ? (I'm not very familiar with cron jobs, and it says to trigger /cron but.. I don't see that folder in the installation folder.)

**Comment by Sakarias-Longhorn** [comment]
**EDIT** Looks like my virtualhost file is the problem...
When I access **pathfinder.polaris-industries.com**
**.htaccess** redirects me to **www.pathfinder.polaris-industries.com**
and I get **ERR_NAME_NOT_RESOLVED**

*000-default.conf*
![](http://sakarias.eu/u/20150923132418.png)

*DNS Zones*
![](http://sakarias.eu/u/20150923132527.png)

**Comment by Sakarias-Longhorn** [comment]
Ok so, definitely a cache issue, it's working now... well, I can get to the page but it says 500 Internal Error. (white page)

**Comment by exodus4d** [comment]
`/cron` cron is no folder or any physically script that should be triggered by a Cronjob. It is just a virtual URL, known to Pathfinder (like all the other Ajax URLs in this project). You just have to trigger that URL by a cronjob. If you are on a shared hoster and there is no option to configure Cronjobs (check the Admin interface,...) you will probably switch to a 3rd party Cronjob hoster (e.g. https://www.setcronjob.com/) and configure that path as a Cronjob.

The Script that will be executed behind /cron will then decide which other Cronjob should be executed. For example, some Script should run each hour. That means, that the executed Script (/Cron) will poke an other Script every 60th time. You don´t have to worry about this tasks, they are configures in the cron.ini don´t touch them if you dont know what you are doing.

More Information about the Cron-Extension I use:
https://github.com/xfra35/f3-cron

**Comment by Sakarias-Longhorn** [comment]
Ok thanks, I'm reading that, so if I understand correctly I need to : 
Create a cron.php somewhere in my /www containing
> exec('wget -qO- /dev/null [YOUR INSTALLATION]/cron &> /dev/null', $out, $result);
> echo "start:";
> echo "Returncode: " .$result ."<br>";
> echo "Ausgabe des Scripts: " ."<br>";
> echo "<pre>"; print_r($out);

and add a cron job like so
> * * * * * php-cli -f /var/www/cron.php

Is it correct ? If yes, should I run the script every minute/hours/days ?

Thanks a lot.

**Comment by exodus4d** [comment]
No all you have to do is to "simulate" "someone" that calls the URL http://www.[Your Project]/cron every minute. You cant do that with PHP. e.g. an endless loop wont work (time out problem). 
So no one wants to call that URL manually :) So you need an other way to trigger that URL. That is usually done by a Cronjob Configuration. There are many ways to do that. A easy way will probably a 3rd party hoster just for that cronjob (see post above).

**Comment by Sakarias-Longhorn** [comment]
I added that one
* * * * * wget -O - http://www.pathfinder.polaris-industries.com/cron/cron.phpx /dev/null 2>&1

cron.phpx is empty btw, is it good enough ?

**Comment by Sakarias-Longhorn** [comment]
Everything is working, so when we look at the error.log we can see
> Table 'galatea.mapsolarsystems' doesn't exist
So, I just went to phpmyadmin and checked the tables... they were named for example : 
> invType
> mapSolarSystems
(Notice the capital letters), that's why it wasn't working, but I used the table you provided so.. did I do something wrong when I imported the tables ?

Glad it's working now ! Good job and thanks for your patience.

**Comment by Sakarias-Longhorn** [comment]
Tables are still broken in 0.0.11 (needs to be renamed to lowercase, I added a note in the wiki)

**Comment by kimian** [comment]
For many users without cron job knowledge, using third party cron job service is a good choice.
There is another easy-to-use cron job service that may help: https://www.easycron.com.
