### ISSUE TITLE
[Bug/question] Map timeout

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#263]
Issue: 
Members are reporting map time out in and out of game. The map does not show a change to info or a status change from online to offline in the upper left corner.  

This can occur with in minutes to hours. 

Behaviors of this range from:
a) Not show current corp member locations 
b) Not allowing destination info to be set via the crest API with out reloading the map page

**Comment by dkrotil** [comment]
Current browsers have function to suspend inactive tabs, maybe this is causing your trouble. Try to open only one tab for Pathfinder, don´t minimize it.

**Comment by exodus4d** [comment]
Is this issue still relevant? if yes, please give us a screenshot from your "network" tab (browser dev tools)
