### ISSUE TITLE
[Feature Request] Improve keyboard use within the signature adder

### ISSUE THREAD

**Issue by krjohnn** [exodus4d/pathfinder#266]
Could it be possible to have some improvements in signature adder window?
1. When manually entering the Description, Enter should enter the signature instead of inserting a new line and Shift+Enter would insert a new line instead.
2. Would it be possible have customer WH Type entries ? Often times when scanning Shattered wormholes, I can't find WH Type in the dropdown list, it's just different from what's available in the list. Would it be possible to have a Custom type that you enter by yourself if it's not in the list ?

**Comment by exodus4d** [comment]
### :star2: Feature request accepted
Great feature request! I really like your idea.
Please, keep in mind that new features need some time to be implemented. New requests are always prioritized by their *cost/benefit* for all users.

#### :information_source: Feel free to ask for the current *route map* in our dev-chat: [#Slack](https://pathfinder-eve-online.slack.com)

***
*Auto-generated response*

**Comment by exodus4d** [comment]
- Arrow keys (`up`, `down`, `left`, `right`) can now be used to navigate inside the signature table
-  `return` key can be used to "open" in-place editor for current focused cell
-  `return` key can be used to "save" in-place editor
    - Inside "description" textarea,  `return` adds new _line break_. `ctrl` + `return` can be used to save that field.

![keyboard_arrow_keys](https://user-images.githubusercontent.com/9299033/44955347-17b5c400-aeb2-11e8-827e-a89dca228c19.gif)
