### ISSUE TITLE
[Enhancement] Logs for everything!

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#271]
Logs for adding and deleting systems, connections, sigs, etc.  So I can see who messed up the map and needs a tutorial.

**Comment by dnolen** [comment]
YES!

**Comment by Tupsi** [comment]
This could be the foundation for some nice statistics as well (like siggy has it). Showing who did the most sig adding/editing, open wormholes.

**Comment by dkrotil** [comment]
Auditing can be very performance hungry, I have local installation on my own server, don´t have problem with memory or CPU, but someone who has VPS ... . 
But don´t saying, that I don´t it. It would be nice. 

There are information already, only thing is not to delete it after deleting system and expiring after 3 days which is currently the case. This is the easy part, much more work will be with UI to get these information back.

**Comment by WildStrawberryEVE** [comment]
If you don't have time to make UI for this, even text logs to files would do. Anything to help CSI:WH.
If there is possibility to add an option to redirect such activity data to text files - please think about it.
Even hundreds megabytes per day is better than having no clue.
