### ISSUE TITLE
Build 1.1.2 - Can´t setup system tables

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#272]
Hi,
I populated system_neighbour table with data - OK, 5214 rows
I tried populate wormhole table with data and getting error " Status: 'Internal Server Error'                        Message: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'massTotal' at row 1"

MySQL 5.6 DB , only one warning in setup page , but even I set lower_case_table_names = 2 in my.cnf and restarted DB still I see warning about lower case table names = 0

David

**Comment by exodus4d** [comment]
Oh my fault :unamused: , sorry! I changed the column type from `varchar(128)` to `int(11)` which can not handle integers larger than `2147483647`. How to fix manually:

1. **Replace** your files with the files from this commit
2. Go to  `/setup` page (you should now see **3** warnings.
3. Auto-fix them by clicking "Fix columns/keys" button
4. Try to import your data again
4. Clear Cache dir

**Comment by dkrotil** [comment]
Hi, 
thanks for fix, it helped.

**Comment by dkrotil** [comment]
And comment to lower_case_table_names settings. On my Linux system I´m getting this message in MySQL log :
[Warning] lower_case_table_names was set to 2, even though your the file system '/var/lib/mysql/' is case sensitive.  Now setting lower_case_table_names to 0 to avoid future problems.

**Comment by exodus4d** [comment]
set to 0 is absolute OK for Unix systems (which is the default).
The default on Windows is 1 (that is a problems which the static SDE SQL import) -> Table names become lowercase.
Set to 2 works on both (win + unix). Therefore I set it to 2.
