### ISSUE TITLE
Data too long for column 'session_id' 

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#273]
I don´t know if this issue is after update to 1.1.2 , or was there before, but in nginx error log file I found this :

2016/07/30 00:24:24 [error] 26299#26299: *646 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session_id' at row 1 in /srv/www/htdocs/app/lib/db/sql.php:202
Stack trace:
#0 /srv/www/htdocs/app/lib/db/sql.php(202): PDOStatement->execute()
#1 /srv/www/htdocs/app/lib/db/sql/mapper.php(418): DB\SQL->exec(Array, Array)
#2 /srv/www/htdocs/app/lib/db/cursor.php(242): DB\SQL\Mapper->insert()
#3 /srv/www/htdocs/app/lib/db/sql/session.php(94): DB\Cursor->save()
#4 [internal function]: DB\SQL\Session->write('49n55saan9n48b6...', '')
#5 /srv/www/htdocs/app/lib/base.php(1910): session_commit()
#6 [internal function]: Base->unload('/srv/www/htdocs')
#7 {main}
thrown in /srv/www/htdocs/app/lib/db/sql.php on line 202" while reading upstream, client: 17.87.40.7, server: pathfinder.unknown.cz, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "pathfinder.unknown.cz", referrer: "https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fpathfinder.uknown.cz%2Fsso%2FcallbackAuthorization&client_id=6c1a30d6cd79463281491f7153a9b5dd&scope=characterLocationRead%20characterNavigationWrite&state=e38c78c4d16d4298588abffc"

**Comment by exodus4d** [comment]
Thanks for the report. The code that causes that issue is *third party* *PHP* framework code. 
Nothing I can do about that for now.
I reported this. We have to see what they can do :unamused:

**Comment by dkrotil** [comment]
Can be this cause of the failed logins to Pathfinder ?

**Comment by exodus4d** [comment]
Very likely! You could try to change the column from `VARCHAR(40)` to `VARCHAR(255)` manually **OR**: 1. change https://github.com/bcosca/fatfree/blob/master/lib/db/sql/session.php#L183 to ``VARCHAR(255)`.
2. clear cache
3. reload login page (this should auto-create the `session` table with the new type.

**Comment by dkrotil** [comment]
Changing table column session_id in MySQL from VARCHAR(40) to VARCHAR(255) and the same on line 183 in session.php helped proceed to next stage . Now I´m getting this error : 

Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '20:08:00) AS `date` FROM `alliance` WHERE `id`=1002884793' at line 1

I have setup alliance checking in pathfinder.ini .

**Comment by dkrotil** [comment]
After deleting alliance ID from pathfinder.ini , I was able to login to Pathfinder.

**Comment by exodus4d** [comment]
Ok interesting. 
I fixed a bug where SSO login error messages were not shown on login form if something fails. 
Can you now see the alliance in `alliance` table? - If you can, see the entry, anyone should be able to login from your Ally when you re-renter the ID in pathfinder.ini. - Strange behaviour.

**Comment by dkrotil** [comment]
I think the problem with login problems , when the alliance was set in pathfinder,ini was only till first character logged in, because now I set the ID of our alliance in patfinder.ini and I can login without any problem.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
