### ISSUE TITLE
[Minor bug] Locale FR problem

### ISSUE THREAD

**Issue by Nyxtorm** [exodus4d/pathfinder#275]
Hello,

Great app, thank you !

I noticed that there is a small problem for browsers in french.
Example : If Chrome is set to "français (France)", there is a display bug on the security status if they are not equal to 1. Here is a picture to illustrate the problem : http://i.imgur.com/71HtTQl.png

If I set "Français (France)" in last position on Chrome, the bug is fixed : http://i.imgur.com/bpq1274.png

There is the same problem with Firefox if it is set to "Français" or "Français/France".

Sorry for my bad English, I'm French.

Nyxtorm

**Comment by exodus4d** [comment]
Thanks for reporting this is the same bug as #277. It will be fixed with the upcoming release.
