### ISSUE TITLE
HTTP error 404 - fonts missing

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#278]
Hi,
even font files are on file system , I´m getting there errors :

`FastCGI sent in stderr: "PHP message: HTTP 404 (GET /public/fonts/oxygen-bold-webfont.eot)%20format(%22embedded-opentype%22),%20url(../fonts/oxygen-bold-webfont.woff2)%20format(%22woff2%22),%20url(../fonts/oxygen-bold-webfont.woff)%20format(%22woff%22),%20url(../fonts/oxygen-bold-webfont.ttf)%20format(%22truetype%22)" while reading response header from upstream, client: 46.39.184.159, server: pathfinder.bandofmagnus.cz, request: "GET /public/fonts/oxygen-bold-webfont.eot)%20format(%22embedded-opentype%22),%20url(../fonts/oxygen-bold-webfont.woff2)%20format(%22woff2%22),%20url(../fonts/oxygen-bold-webfont.woff)%20format(%22woff%22),%20url(../fonts/oxygen-bold-webfont.ttf)%20format(%22truetype%22 HTTP/1.1",`

**Comment by dkrotil** [comment]
Maybe this will help http://readableweb.com/mo-bulletproofer-font-face-css-syntax/ .

**Comment by exodus4d** [comment]
If you use Nginx, please check your rules for font loading. E.g. add/edit it. Here is the `location` block i use:

```
location ~* \.(?:ttf|ttc|otf|eot|woff|woff2)$ {
    add_header "Access-Control-Allow-Origin" "*";

    # Also, set cache rules for webfonts.
    #
    # See http://wiki.nginx.org/HttpCoreModule#location
    # And https://github.com/h5bp/server-configs/issues/85
    # And https://github.com/h5bp/server-configs/issues/86
    expires 1M;
    access_log off;
    add_header Cache-Control "public";
}

```

**Comment by dkrotil** [comment]
@exodus4d I´m using h5bp config files as you recommended in Wiki and there is this rule.

**Comment by dkrotil** [comment]
Will close this, because I have seen this only few times.
