### ISSUE TITLE
[Feature Request] Activity Monitor - Top Users, Most WHs mapped/updated

### ISSUE THREAD

**Issue by cmasiah** [exodus4d/pathfinder#280]
My corp has incentives and rewards for the users who scan the most, update the most WHs and map the best/longest chains. In order to move over completely to Pathfinder, we need a way to track who is adding the most WHs to the map and updating the sigs.
Can this be added soon?

**Comment by rmcginnis** [comment]
This would be a great feature too!    I remember siggy at least tracked and added the eve character name who added the sigs..  But, this would be even better!

**Comment by nrcsantos** [comment]
This would be great indeed. :)

**Comment by Nitesedge** [comment]
+1

**Comment by dnolen** [comment]
+1 for this. I love the reporting functionality of Siggy (I think this is in Tripwire as well). 

Definitely a boost gto have corp members try to get tops on the list for the month/week

**Comment by exodus4d** [comment]
### New Statistics module:
I implemented a new "*statistics module*" that records  some map actions from users. The module is very similar to the one from [*Siggy*-stats](http://wiki.siggy.borkedlabs.com/usage/other-features/#stats). 

**System**,  **Connection**,  **Signature** actions:
- *create*
- *update*
- *delete*

Activity is tracked per **calendar week** and can be filtered by **periods**
- *weekly*
- *monthly*
- *yearly*

Activity is tracked by *mapType* (*private*, *corporation*, *alliance*) and can be filtered by it.

> **Important:** "corporation/alliance" filter will show you **all** activity from a character in your corp/ally. This *includes* activity on their *private* maps,... ( a new filter option is on the way for that problem)

"**_monthly_**" , and "**_yearly_**" filter show activity charts for all actions in its period. ( each *value* represents a *calendar week*) [e.g. "*yearly*" ≙ **53** *calendar weeks*, "*monthly*" ≙ **4** *calendar weeks*]

#### Statistics dialog
![statistics_dialog](https://cloud.githubusercontent.com/assets/9299033/19450964/c39338fc-94ab-11e6-967f-0f035d2028d4.png)

#### Cronjob
A new cronjob (weekly) was implemented that deletes activity logs that are older than **one year** (53 weeks).

#### Configuration/Setup

Activity logging can be dis-/enabled in `pathfinder.ini`, look for `ACTIVITY_LOGGING`. It can be configured for "private","corporation","alliance" maps individually. 

By default **alliance** maps are **disabled**.

***
### Whats next?

There are some features I want to add in later releases:
- Add "**map filter**" to filter activity just for a single map (not all corporation/alliance maps,...)
