### ISSUE TITLE
Error 500 - after this error user is logged out

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#282]
2016/08/08 21:08:03 [error] 12232#12232: _306202 FastCGI sent in stderr: "PHP message: Creating default object from empty value
PHP message: [app/lib/base.php:2032] Base->error(500,'Creating default object from empty value')
PHP message: [app/main/controller/api/map.php:727] Base->{closure}(2,'Creating default object from empty value','/srv/www/htdocs/app/main/controller/api/map.php',727,array('f3'=>Base::__set_state(array('hive'=>array('HEADERS'=>array('Cookie'=>'cookie=1; char_4101c4e4516de4cccc9c1b29fc90290c=7d3c7152adf68f1fd08306f1%3A6fad586ec55e240fbaa2da6e48a6a330; pathfinder_session=dkki2917gf8v1bb4aaqe08a72evodqvedhfdlns5s77u5895sh51; char_a4da6cab87c30c405f5b06804ecd5748=ddbe851d8659a52e78f451e2%3Adb5a4633cf832f5318a2f652814edaf7','Content-Length'=>'2525','Referer'=>'https://pathfinder.bandofmagnus.cz/map','X-Requested-With'=>'XMLHttpRequest','Content-Type'=>'application/x-www-form-urlencoded; charset=UTF-8','Accept-Encoding'=>'gzip, deflate','Accept-Language'=>'cs,en-US;q=0.7,en;q=0.3','Accept'=>'application/json, text/javascript, */_; q=0.01','User-Agent'=>'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0','Host'=>'pathfinder.bandofmagnus.cz'),'AGENT'=>'Mozilla/5.0 (Windows NT 10.0; WOW64; ...
PHP message: [app/lib/base.php:1672] Controller\Api\Map->updateUserData(Base::__set_state(array('hive'=>array('HEADERS'=>array('Cookie'=>'cookie=1; char_4101c4e4516de4cccc9c1b29fc90290c=7d3c7152adf68f1fd08306f1%3A6fad586ec55e240fbaa2da6e48a6a330; pathfinder_session=dkki2917gf8v1bb4aaqe08a72evodqvedhfdlns5s77u5895sh51; char_a4da6cab87c30c405f5b06804ecd5748=ddbe851d8659a52e78f451e2%3Adb5a4633cf832f5318a2f652814edaf7','Content-Length'=>'2525','Referer'=>'https://pathfinder.bandofmagnus.cz/map','X-Requested-With'=>'XMLHttpRequest','Content-Type'=>'application/x-www-form-urlencoded; charset=UTF-8','Accept-Encoding'=>'gzip, deflate','Accept-Language'=>'cs,en-US;q=0.7,en;q=0.3','Accept'=>'application/json, text/javascript, _/_; q=0.01','User-Agent'=>'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0

**Comment by exodus4d** [comment]
Interesting... no idea why this happens :( I have to investigate some time in this, i think.

**Comment by exodus4d** [comment]
Have you come across  this Issue recently on a up2date version? I´m pretty sure the code existed in mid 2016 is completely re-written in the meantime.
