### ISSUE TITLE
nginx.service - failed to read PID from file /run/nginx.pid - Invalid Augument

### ISSUE THREAD

**Issue by rmcginnis** [exodus4d/pathfinder#283]
I've checked the nginx.conf file and it's pointing to the correct place.  Pathfinder is running on my server, but when i check status I get this: 

Aug 08 14:23:20 pathfinder.eveminions.com systemd[1]: Starting A high performance web server and a reverse proxy server...
Aug 08 14:23:20 pathfinder.eveminions.com systemd[1]: nginx.service: Failed to read PID from file /run/nginx.pid: Invalid argument
Aug 08 14:23:20 pathfinder.eveminions.com systemd[1]: Started A high performance web server and a reverse proxy server.

**Comment by rmcginnis** [comment]
Running ubuntu server 16.04 on digital ocean / running nginx version 1.10.0

**Comment by dkrotil** [comment]
We solved it, @exodus4d you can close it.

**Comment by MeLeRyZ** [comment]
Actually no. Where is the solution to solve this problem?

**Comment by nimitbhargava** [comment]
@MeLeRyZ This worked for me.

That warning with the nginx.pid file is a know bug (at least for Ubutnu if not for other distros as well). More details here:
https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864

Workaround (on a ssh console, as root, use the commands bellow):
 
    mkdir /etc/systemd/system/nginx.service.d
    printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" > /etc/systemd/system/nginx.service.d/override.conf
    systemctl daemon-reload
    systemctl restart nginx 

Then check if you still see that nginx.pid error and also if nginx is actually running and if you can connect to port 80 on your server.

I would also check if this actually exists and the permissions on it:

    /run/uwsgi/mysite3.sock

If nginx is running and uWSGI is running as well then I guess it's a configuration problem

I understand you want to use Django so I would recommend to review your actual configuration and compare it with the one from here:

http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html

I hope it helps!


Source - https://stackoverflow.com/a/42084804/6230772
