### ISSUE TITLE
Multiple errors in FF browser - nothing in any log even debug set on 3

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#285]
This error 
`DataTables warning: table id=DataTables_Table_20 - Requested unknown parameter 'status' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4`

shows as dialog in browser, I´m getting it multiple times , after clicking on OK, Pathfinder shows 10 ( or any other number ) signatures added.

**Comment by exodus4d** [comment]
Hi, unfortunately I can´t reproduce this in FF :( Can you add some more details, please?

1. Do you get this error **anytime** you select a system first, or even when signatures get updated (**every** 5sec)?
2. ...or just on systems with signatures stored?
3. Have you resized your browser window? (the `status` column is not visible on smaller windows)
4. Have you cleared browser cache? Don´t know if this could solve it, but *DataTables* caches table-column information on the client.
5. What´s your browser language, English?

**Comment by dkrotil** [comment]
I haven´t got this message again, will ask corpmates.

**Comment by dkrotil** [comment]
Hello, corpmate reported this error `DataTables warning: table id=DataTables_Table_11 - Requested unknown parameter 'created' for row 0, column 5. For more information about this error, please see http://datatables.net/tn/4`

it was when he inserted this signature 
`IOY-100 Cosmic Signature Gas Site Bountiful Frontier Reservoir 100,0% 126,25 AU
WKY-630 Cosmic Signature Wormhole Unstable Wormhole 100,0% 123,69 AU
KWL-500 Cosmic Signature Gas Site Vast Frontier Reservoir 100,0% 182,70 AU
RAP-128 Cosmic Signature Gas Site Ordinary Perimeter Reservoir 100,0% 1,43 AU
KIM-986 Cosmic Signature Gas Site Barren Perimeter Reservoir 100,0% 124,10 AU
NMV-660 Cosmic Signature Gas Site Sizeable Perimeter Reservoir 100,0% 2,67 AU
XSG-279 Cosmic Signature Gas Site Ordinary Perimeter Reservoir 100,0% 127,09 AU
PAQ-791 Cosmic Signature Gas Site Barren Perimeter Reservoir 100,0% 100 km
SHK-000 Cosmic Signature Gas Site Sizeable Perimeter Reservoir 100,0% 121,95 AU
MDJ-420 Cosmic Signature Data Site Unsecured Frontier Enclave Relay 100,0% 128,71 AU
SYX-914 Cosmic Signature Data Site 35,6% 2,88 AU
FXT-590 Cosmic Signature 0,0% 121,13 AU
CRA-720 Cosmic Signature Data Site 0,0% 1,43 AU
EDK-270 Cosmic Signature 0,0% 3,06 AU`

same error again , when he inserted another set of signatures in another wh system.

**Comment by exodus4d** [comment]
@dkrotil I tried to reproduce this :( no success.

I upgraded the dataTables plugin several times in the meantime. Have you ever seen this bug again?

**Comment by dkrotil** [comment]
@exodus4d no one reported it again, I think it´s solved now.
