### ISSUE TITLE
Feature - Automatically set connection EOL when timers reaches x time

### ISSUE THREAD

**Issue by rmcginnis** [exodus4d/pathfinder#286]
I think this would be a nice feature to automatically set a connection and toggle the EOL when a timers reaches X time.

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic: #219
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
