### ISSUE TITLE
[Feature] The ability to specify the map as an anchor to /map

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#287]
It would be great if we could have the ability to specify an anchor in the URL that, when clicked, opens Pathfinder on a specific map. This means you could share maps by linking them to other users, useful when you have many maps available.

For example:

`https://pathfinder.dev/map#mymap`

would open Pathfinder on the 'mymap' tab.

**Comment by rmcginnis** [comment]
:+1:

**Comment by exodus4d** [comment]
This is already implemented. There is even a "copy to clipboard" icon for deeplinks into a specific system on map
