### ISSUE TITLE
[Feature]  Ignore Crest errors at the down time or anytime ?

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#288]
Hi,
can be ignored "Not accepting connections"  , when you enable Debug logging ? These aren´t errors and when you have some kind of monitoring ( in my case Amplify ) you will get false alerts .

PHP message: [app/main/lib/web.php:156] Base->error(503,'HTTP 503: 'Not accepting connections' | url: GET 'http
s://crest-tq.eveonline.com/characters/96382478/location/' | body: stdClass Object
PHP message: (
PHP message:     [message] => Not accepting connections
PHP message:     [key] => NotAcceptingConnection
PHP message:     [exceptionType] => ServiceUnavailableError
PHP message: )
PHP message: ')

**Comment by rmcginnis** [comment]
:+1:    Plus one this please.

**Comment by exodus4d** [comment]
*CREST* "location" endpoint errors will no longer trigger a HTTP 5xx on failure.
But they still get logged in *Pathfinder* error logs: `/logs/error.log`
