### ISSUE TITLE
Error.log > HTTP 404

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#29]
Hello,
When I open my apache error.log I can see entries like that.

http://hastebin.com/eyejulumuv.coffee

(You can notice there is something weird like *Base->error(404), referer: http://www.pathfinder.polaris-industries.com/var/www/html/pathfinder/*)

Is it a normal behavior or I misconfigured something ? What could cause that.

Usefull Informations : 
> BASE = /var/www/html/pathfinder
> URL =  http://www.pathfinder.polaris-industries.com
> Virtualhost = http://sakarias.eu/u/20150923201849.png

**Comment by exodus4d** [comment]
Yeah you are right. I could reproduce that error by refreshing the `/map` URL (after logged in). This is a problem with the IGB only. I haven´t figgured out how to fix it. In some cases the IGB is pretty bad :(

So this is not a big problem here i guess.
