### ISSUE TITLE
Rally and poke problem on private installation

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#293]
![image](https://cloud.githubusercontent.com/assets/10422726/17708557/dff51480-63e5-11e6-8e4b-ab03d46f681c.png)

When I try to set rally and poke there is logout with this error. 
I have problem with setting up TLS communication , would be nice to have some logging with SMTP/ Email errors, would be nice to lower SMTP_SCHEME at non TLS level and it looks like it ignore RALLY_SET, sending email to exodus4d@gmail.com?

**Comment by dkrotil** [comment]
PHP message: [app/lib/base.php:1672] Controller\Api\Map->updateData(Base::__set_state(array('hive'=>array('H
2016/08/16 19:14:45 [error] 2746#2746: *67911 FastCGI sent in stderr: "PHP message: stream_socket_enable_crypto(): this stream does not support SSL/crypto
PHP message: [app/lib/base.php:2032] Base->error(500,'stream_socket_enable_crypto(): this stream does not support SSL/crypto')
PHP message: [app/lib/smtp.php:183] stream_socket_enable_crypto(NULL,true,9)
PHP message: [app/main/controller/mailcontroller.php:55] SMTP->send('Map:               Map 
PHP message: System:            J171136
PHP message: Region:            E-R00026
PHP message: Security:  C5
PHP message: Character: Tonny
PHP message: Time:              5:14 pm; August 16, 2016')
PHP message: [app/main/model/systemmodel.php:511] controller\MailController->sendRallyPoint('exodus4d@gmail.com','Map:          Map 
PHP message: System:            J171136
PHP message: Region:            E-R00026
PHP message: Security:  C5
PHP message: Character: Tonny
PHP message: Time:              5:14 pm; August 16, 2016')
PHP message: [app/main/model/systemmodel.php:337] Model\SystemModel->sendRallyPointMail(1471367684)
PHP message: [app/lib/db/cortex.php:1395] DB\Cortex->emit('set_rallyUpdated','1')
PHP message: [app/main/model/basicmodel.php:151] DB\Cortex->set('rallyUpdated','1')
PHP message: [app/lib/magic.php:73] Model\BasicModel->set('rallyUpdated','1')
PHP message: [app/lib/magic.php:117] Magic->offsetset('rallyUpdated','1')
PHP message: [app/main/model/systemmodel.php:181] Magic->__set('rallyUpdated','1')
PHP message: [app/main/controller/api/map.php:578] Model\SystemModel->setData(array('id'=>'648','systemId'=>'31002114','name'=>'J171136','alias'=>'y J171136','effect'=>'','type'=>array('id'=>'1'),'security'=>'C5','trueSec'=>'-1','region'=>array('id'=>'11000026','name'=>'E-R00026'),'constellation'=>array('id'=>'21000263','name'=>'E-C00263'),'status'=>array('id'=>'1'),'locked'=>'0','rallyUpdated'=>'1','rallyPoke'=>'1','currentUser'=>'false','statics'=>array(array('name'=>'V753','security'=>'C6','massTotal'=>array('value'=>'3000000000','format'=>'3.000.000.000 Kg'),'massIndividual'=>array('value'=>'13500

**Comment by exodus4d** [comment]
HAHA FUCK! By bad.... I forget to replace my hard-coded Email address.... with the one from the config file.... lol

**Comment by exodus4d** [comment]
You need to replace the single PHP file from the last commit.... That should solve the problem
