### ISSUE TITLE
[Feature Request] Rally point and poke adding some description text

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#295]
Would be nice to have possibility to add some short message in the body of email ( in our case Slack ) message.
On the bottom, like :

**Message:   Capitals in the static** 
Map:        Mordor
System:        J212612
Region:        F-R00030
Security:    C6
Character:    Johnson
Time:        10:48 pm; August 16, 2016

**Comment by dkrotil** [comment]
I talked to my corpmates and this is must have addition, because currently there is no intel inside this poke, maybe if it helps strip Region and replace it with Message.

**Comment by rmcginnis** [comment]
this would be nice, i'd like to see this added but also can we get issue 297 tagged to get fixed @exodus4d

**Comment by dkrotil** [comment]
@rmcginnis you got your fix, now I want my feature  :o)

**Comment by dkrotil** [comment]
I´m curious if others are happy with information which are added to poke, my corpmates asking for description text because if they getting Slack notify , they don´t know if the poke is important or not.

**Comment by dkrotil** [comment]
@exodus4d can you look on the feature now ? Descriptive text and _@everyone_ tag, that on **Slack** everybody on channel getting notify from **Slack** app on mobile phone.
