### ISSUE TITLE
HTML tags on mouseover

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#296]
![image](https://cloud.githubusercontent.com/assets/10422726/17751122/ec7a09aa-64c5-11e6-8882-729f77246a34.png)

Someone reported it some time ago, I think . This showed after deletion of interconnected WH.

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #262
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
