### ISSUE TITLE
setting rally point - getting email/notification shows old/wrong character

### ISSUE THREAD

**Issue by rmcginnis** [exodus4d/pathfinder#297]
After setting up rally point email and zap integration with slack.  When a user clicks on set rally point it shows incorrect character name.

**Comment by dkrotil** [comment]
Looks like in saves character name on first poke and doesn´t update it on consecutive pokes.

**Comment by rmcginnis** [comment]
Here's a screen shot on a few pokes for you @exodus4d 
<img width="663" alt="capture" src="https://cloud.githubusercontent.com/assets/2511721/17759812/63162900-64c0-11e6-9338-4208b84c6c7d.PNG">

**Comment by dkrotil** [comment]
This looks for me less important as #295

**Comment by exodus4d** [comment]
This should now be fixed. 
I have also added some configuration information to the dialog:

![rally_point_dialog](https://cloud.githubusercontent.com/assets/9299033/18030335/3c42bb6e-6cb2-11e6-88ca-195d27259594.png)
