### ISSUE TITLE
[New Feature] Increase map (vertically) to include bigger maps

### ISSUE THREAD

**Issue by nrcsantos** [exodus4d/pathfinder#298]
Very useful if we use this with multi-regions JB network maps. If we could expand the map not only to the 'right' of the screen but also 'bottom'... it would be PERFECT.

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic: #234
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
