### ISSUE TITLE
When multiple systems are selected, "Delete System" should delete all systems

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#299]
I know that if you click the background the option is "delete system**s**" and that will happily delete all the systems you have selected, however if you click a system (while many systems are selected) then the context menu option only deletes one of them. This is unintuitive to me and many users mistake this behaviour and assume you cannot delete multiple systems at all.

When multiple systems are selected the only context menu option should be to delete all selected systems regardless of what is clicked.

**Comment by exodus4d** [comment]
The following changes have been made:
  1. renamed "**delete system**" system contextmenu entry to "**delete system(s)**"
  2. remove **all** *selected systems* **and** *current* system after confirmation
    1. E.g. *systemA* and *systemB* were selected, open context menu on *systemC*, choose "delete systems(s)" -> will delete all **3** systems
  3. added *system name* to confirm dialog, if just a single system was marked for *delete*
  4. fixed a bug where **locked** systems could be deleted, when they were already selected before someone else locked it.
