### ISSUE TITLE
Missing DB population?

### ISSUE THREAD

**Issue by kilgarth** [exodus4d/pathfinder#3]
I am attempting to get a working instance of this setup, however I cannot find any sql file or any function that creates the needed tables. 

[Sun Aug 30 01:40:22 2015] PDOStatement: Table 'pathfinder.user' doesn't exist
[Sun Aug 30 01:40:22 2015] [app/lib/base.php:2015] Base->error(500,'PDOStatement: Table 'pathfinder.user' doesn't exist')

**Comment by exodus4d** [comment]
I will include all required SQL dumps once the beta phase is over and the tool works stable with a large number of active accounts. This is a pre-beta version and at this point there are still significant DB-changes. With the first final release (v1.0.0) I will provide all required files you need for your own installation. Do not expect this before end of 2015.

**Comment by rcreasey** [comment]
So, this is a pre-beta with no schema?

See you in 2016.

**Comment by mglinski** [comment]
See #6

**Comment by exodus4d** [comment]
As mentioned in the README https://github.com/exodus4d/pathfinder/blob/master/README.md all required Dump files will be delivered once the beta is done. This is just for  security reasons. No one can guarantee that the current beta is running stable. As @mglinski points out, there are plans to build the required tables automatically with settingUp() all Models.

**Comment by mglinski** [comment]
@kilgarth if you want the DB dump my install is working on lmk, though I don't think this is ready for primetime yet. Talk to porkbutte to get my jabber name and ill send you a db export.
