### ISSUE TITLE
[Feature Request] Tag bubbled

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#301]
It would be nice to have same tag as "save mass" for bubbled WH exit.

**Comment by Tupsi** [comment]
That would need a side distinction as well, as you want to know which side is bubbled.

**Comment by dkrotil** [comment]
Yeah, maybe some arrow sign.

**Comment by Bingmano** [comment]
I like this, however adding it into the description portion of a system might suffice?  A visual is indeed a good idea, perhaps an animation that flows in a certain direction to indicate a bubble is active outgoing or incoming?

**Comment by exodus4d** [comment]
### New "*bubbled*"-tag for connection endpoints:
There is a new *context menu* (`right click`) added to each of the **two**  connection endpoints (e.g. wormhole, stargate,..) . 
_Bubbles_ can be placed on "**target**" endpoint, "**destination**" endpoint or on **both** endpoints of a connection. Context menu options:

- Add  "*bubbled*"-tag renders a visual warp bubble around the selected endpoint.

The "route finder" dialog got a new filter option that excludes connections from search, that are tagged with bubbles.

### Preview:

![map_bubble2](https://user-images.githubusercontent.com/9299033/56855058-acd56380-6940-11e9-804b-73900a601893.gif)
