### ISSUE TITLE
Connections drawn incorrectly since v1.1.4 release

### ISSUE THREAD

**Issue by tavik83** [exodus4d/pathfinder#307]
![pathfinder_bug](https://cloud.githubusercontent.com/assets/5068810/18228060/1f43a5fc-7200-11e6-8522-0e209f58fb6e.png)

System connections are drawn off to the side instead of between the systems since the v1.1.4 release.  Tested on IE 11, Chrome 52.0.2743.116m (64-bit), and Edge.  See the sanitized screenshot above.

**Comment by padibona** [comment]
I concur.

Recently add Content Security Policy headers?

Tons of errors shown in web Dev console in chrome.

[www.pathfinder-w.space-1472947119408.log.txt](https://github.com/exodus4d/pathfinder/files/453692/www.pathfinder-w.space-1472947119408.log.txt)

**Comment by padibona** [comment]
I was able to fix the issue by adding a browser extension to Chrome that turns off CSP. 

https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden  

Hope that helps.

**Comment by dkrotil** [comment]
I think there should be a system wide fix.

**Comment by padibona** [comment]
I believe it has been fixed already. You would need to clear your browser caches and cookies, etc. to clear the old setup.
