### ISSUE TITLE
Spelling/ Grammer on Front page.

### ISSUE THREAD

**Issue by cadetmcgregor** [exodus4d/pathfinder#308]
Hey,

Wanted to point out that the front page elements have several spelling and grammar issues including "Avoid risk and grap your chancse" and "Enjoy playing EVE fly safe".

I figured it would be a quick fix and since it was pointed out by one my users while I was introducing it to the corp and fixing it will help to reinforce Pathfinder as a real and authentic mapping program :)

Sorry for the spelling hits, I know you have a lot more important things to work on. :)

Thanks.

**Comment by dkrotil** [comment]
No problem, can you post string replacements here ? It will help exodus4d fix the issue(s) quickly.  

Thanks

**Comment by cadetmcgregor** [comment]
I wasn't able to find that string in the code base, then realized that as
the words are not intractable I believe it is a static image. However I'm
having trouble figuring out which one it is as it is not treated as an
image by chrome.

Thanks.

**Comment by dkrotil** [comment]
Sure, with strings I mean , write what is wrong and should be there like 
"Avoid risk and grap your chancse" -> "Avoid risk and **grab** your **chance**"
Exodus4d  is from Germany, I´m from Czech Republic, English is not our native  language.

**Comment by cadetmcgregor** [comment]
Alright, all the love to all of my euro friends. :) I will proofread the
full page later today, there is a lot of material and I would prefer to
provide an accurate set of corrections that only has to be applied once.

**Comment by exodus4d** [comment]
@cadetmcgregor Are you still planning to help with this Issue? - If not I´ll close it because I can´t solve this issue without help from a native English speaker.

**Comment by cadetmcgregor** [comment]
Sorry,  this totally slipped my mind. Will take a look at it later today.

**Comment by shanahanjrs** [comment]
Hey @exodus4d possible to re-open this issue? I can provide some spelling/grammar fixes here if so.

_Speed up scanning, update sigs and connections_
Should be:
**Speed up scanning and updating sigs and connections**

_Avoid risk and grap your chancse_ 
Should be:
**Avoid risk and grab your chance**

_Quick access to aggregated meta data and charts_
Should be:
**Quick access to aggregated metadata and charts**

_Increase your skills and fun by focusing relevant tasks_
Should be:
**Increase your skills and fun by focusing on relevant tasks**

_Enjoy playing EVE fly save_
Should be:
**Enjoy playing EVE, fly safe**

**Comment by hilocz** [comment]
Don´t think you get any response, this project is  abandoned for some time.
