### ISSUE TITLE
[BUG] Names of Pilots in system are cut off in Chrome

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#309]
See screen below, the user's name is cut off even after hovering over the object.

![image](https://cloud.githubusercontent.com/assets/16602120/18232340/bd15dfc0-729b-11e6-81b8-49b85b5cb79d.png)

![image](https://cloud.githubusercontent.com/assets/16602120/18232343/c4559938-729b-11e6-957d-1c3ed7dcf966.png)

**Comment by Bingmano** [comment]
confirmed this behavior occurs in Chrome 53 and Edge

**Comment by exodus4d** [comment]
Confirmed. Will fix this for the next release.

**Comment by exodus4d** [comment]
@Bingmano I can´t reproduce this with `Chrome  53.0.2785.89` on `v1.1.4`.  Can you confirm this? 
Maybe Google fixed this in a minor version today?

![test](https://cloud.githubusercontent.com/assets/9299033/18254665/3808b220-73a0-11e6-9514-52ed0a83cebb.png)

**Comment by Bingmano** [comment]
Will check when I return home.

**Comment by atkinsj** [comment]
Not to hijack but in your screenshot it shows you as being in the system
twice; my pilots are reporting the same. Is this a bug?

**Comment by exodus4d** [comment]
@atkinsj No I manipulated the DOM to "fake/simulate" multiple Pilots in a system.

If they were reported twice in the same system, it would be a bug. But I have never seen this.

**Comment by atkinsj** [comment]
Thanks, I'll try and narrow it down and file a bug report.

**Comment by Bingmano** [comment]
`Version 53.0.2785.89 `m still showing cut off

![image](https://cloud.githubusercontent.com/assets/16602120/18255862/1068ce40-737c-11e6-8e94-ca7fb1d67542.png)

**Comment by rmcginnis** [comment]
I'm seeing the same issue as well 
<img width="403" alt="2016-09-07_12-42-51" src="https://cloud.githubusercontent.com/assets/2511721/18322565/ed935678-74f8-11e6-88bc-40de0182b88b.png">

**Comment by Bellerian** [comment]
Question on this, are the ship names also suppose to display? Possibly as a hover over?  Or is this a feature still in flight?

**Comment by exodus4d** [comment]
@Bellerian They were supported a while ago in the IGB. Unfortunately CCP haven´t added them to the CREST API counterpart.... So we have to wait for them to be re-added. If CCP would add Ship information to the "Location" endpoint, it is just a a few lines of code to re-add them.

**Comment by dkrotil** [comment]
@Bellerian I have created forum post https://forums.eveonline.com/default.aspx?g=posts&t=490255&find=unread , add your opinion there. Keep this thread alive, maybe will CCP listen.

**Comment by Bellerian** [comment]
Thanks dkrotil!  I Plan on getting the Corp mates to keep this alive!

**Comment by dnolen** [comment]
Reproduced on 1.1.4 with Chrome 53.0.2785.101. 

Can you please make the pilot name text something other then Grey? White perhaps?

**Comment by dnolen** [comment]
Reproducible on 1.1.5. Pilot names are being cut off in system bubble.

**Comment by exodus4d** [comment]
Not 100% sure if this fixes the problem. I did some CSS tweaks. Please let me know if something is still buggy.
