### ISSUE TITLE
[BUG] Description field does not become editable

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#310]
Cannot update or add descriptions after 1.1.4 release, keeps showing loading icon.

![image](https://cloud.githubusercontent.com/assets/16602120/18233360/5e570abe-72b3-11e6-9a93-b372b6c3f4cc.png)

**Comment by dkrotil** [comment]
Looks like this is problem related to your installation, we don´t have such problem. Alias and description are editable.

**Comment by Bingmano** [comment]
This behavior was on the pathfinder-w.space environment

On Sep 5, 2016 2:07 AM, "dkrotil" <notifications@github.com> wrote:

Looks like this is problem related to your installation, we don´t have such
problem. Alias and description are editable.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/exodus4d/pathfinder/issues/310#issuecomment-244665353>,
or mute the thread

**Comment by dkrotil** [comment]
Ok, than on Exodus4d installation :o)

**Comment by exodus4d** [comment]
Yeah can confirm this. I have seen it some times this weekend.

**Comment by exodus4d** [comment]
**This bug existed for a long time... :( I was unable to reproduce this in the past. But now I could finally fix it!**

It was a timing problem with some *Javascript* event handlers.
