### ISSUE TITLE
[Bug] Users are logged out even they were active

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#312]
Looks like we getting logouts after 4 hours after login, but seconds after user is active on the map. User activity on the map should be prolong the logout interval to maximum time or I´m mistaken ?

**Comment by exodus4d** [comment]
@dkrotil It´s a feature not a bug :) Feel free to increase the 4h timer to what ever you want:

https://github.com/exodus4d/pathfinder/blob/master/app/pathfinder.ini#L81

**Comment by dkrotil** [comment]
OK, but this isn´t normal application behavior. Normally there is security feature, inactivity timer. In your case is only how maximal can be user be logged in before he will be automatically disconnected, even he is currently active. I see this for the first time.
