### ISSUE TITLE
[Feature] Logging in multiple pilots in a tabbed browser changes the active pilot on all tabs

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#314]
Issue reported so far on Chrome [latest release]

When attempting to tracking more then one pilot via multiple account logins in pathfinder is changing the active logged in pilot from the original logged in pilot to the last logged in pilot in the active pilot drop down menu in the upper left menu. 

I have created logins for all of my active pilots with in my instance and this issue occurs regardless of login order .

**Comment by dkrotil** [comment]
That´s not a bug, Login information is held in cookie, tabs sharing authentication information, you need open new browser window to be able login mutliple times

**Comment by exodus4d** [comment]
This is **not** a bug, that´s correct. 
I changed the topic to "Feature" request.

@dkrotil That is not 100% true. The login information is held in the *PHP Session*. The cookies just store the information of all characters who had access before (to show the nice char-images on login form)

**Comment by dkrotil** [comment]
If this is possible to have multiple character in separate tabs, that would be awesome, this is number one request in our alliance.

**Comment by cadetmcgregor** [comment]
Absolutely the same , as  I have 5 separate pilots pilots that have called me out today alone

**Comment by exodus4d** [comment]
I´m on it ;) Currently figuring out what is the best way to implement that.
I made a post to the *PHP* framework devs to check if there is already something available:
https://groups.google.com/forum/#!topic/f3-framework/9QpmsTgNtVE

Otherwise I´ll probably implement something like "multi-session" management by myself 😃

**Comment by exodus4d** [comment]
#### New improvements:
- [ ] Implement **multi character support**
 - [ ] Each user can have up **3-5** (not sure what should be the default limit, yet) active characters in a session
 - [ ] Each browser tab holds a character session. (3 active characters -> 3 open browser tabs)
 - [ ] Adding/Removing a character by using the **character select** in the **map view**, will update all active browser tabs with that new characters.
 - [ ] The "logout" button will logout **all** active characters at once (SESSION -> clear)
 - [ ] The same character can be active on multiple browser tabs at once (if someone even uses that)
- [ ] Make *location tracking* working on **all** active characters
- [ ] Test everything :)

**Comment by exodus4d** [comment]
I reworked the **character switch** popover and added some more options:
- "open in new tab"
- "switch character" -> same tab

![character switch](https://cloud.githubusercontent.com/assets/9299033/18683610/3a4c3f66-7f71-11e6-9023-307103dd02c8.png)
