### ISSUE TITLE
[Feature] Allow filtering on EOL connections in the route planner

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#315]
In the route planner you can exclude stage 1 and stage 2 holes but not EOL holes. Being able to exclude EOL holes would be very useful.

**Comment by exodus4d** [comment]
#### New filter option for "*End of Live*" was added:

![routefinder_eol_filter](https://cloud.githubusercontent.com/assets/9299033/18611032/c7d5a73c-7d2d-11e6-9e4f-21486d92c64c.png)
