### ISSUE TITLE
[Feature] Return whether or not a system is a wormhole connection in the routes data

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#316]
The routesData return is currently just a list of systems, if we could mark which one of those was a wormhole then we could easily point out that jump so scouts could double check it was still there etc.

**Comment by exodus4d** [comment]
Wormholes have now a new icon in *route finder* module (circle with dot):

![test](https://cloud.githubusercontent.com/assets/9299033/19603745/87ae14d8-97b2-11e6-9f4a-4cf323dd231c.png)
