### ISSUE TITLE
Pilot names are cutoff/ don't show fully when not hovering or hovering over system

### ISSUE THREAD

**Issue by rmcginnis** [exodus4d/pathfinder#318]
Browser - Google chrome

After upgrading to ver 1.1.4
pilot names online and in-game under the system they are in don't show fully and are cut off a bit 

<img width="403" alt="2016-09-07_12-42-51" src="https://cloud.githubusercontent.com/assets/2511721/18322512/ab11f2d2-74f8-11e6-9f8c-b20593806f0b.png">

**Comment by rmcginnis** [comment]
after entering this - I saw this was already entered by https://github.com/exodus4d/pathfinder/issues/309  but i'm seeing this issue as well

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
