### ISSUE TITLE
[Bug] Routes showing wrong number of jumps

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#321]
In Routes there are +1 number of jumps, because you are counting system in which is the exit. For example Kor-Azor Prime shows 2 jumps to Amarr, but is only one.

**Comment by exodus4d** [comment]
@dkrotil Sorry, I can´t reproduce this. This bug should be fixed a while ago. `v1.1.4` looks fine:

![test](https://cloud.githubusercontent.com/assets/9299033/18610284/450ba7f8-7d18-11e6-879f-0e0413ce3701.png)

**Comment by dkrotil** [comment]
I can´t reproduce it too. You can close it.
