### ISSUE TITLE
[Bug] Missing WH options in signature reader

### ISSUE THREAD

**Issue by InfiniZ** [exodus4d/pathfinder#322]
![capture](https://cloud.githubusercontent.com/assets/5418804/18415665/2a7e4b48-77af-11e6-8521-9cb6248b1345.PNG)

![capture2](https://cloud.githubusercontent.com/assets/5418804/18415671/570154da-77af-11e6-9dfb-15880b8f4ca0.PNG)

As seen in the screenshots, I'm unable to select D382 from the WH drop-down list.  This is not the 1st time this has happened.  Several corp mates have reported this to me as well, but I've not been able to get any good screenshots or the systems/WH ID's to test myself until now.

**Comment by InfiniZ** [comment]
And now I see this is just a repeat of Ticket #276

**Comment by exodus4d** [comment]
@InfiniZ Thanks for your report! 
This should be fixed in #276 now and is ready for the next release.

I close this one because its a duplicate

**Comment by Tupsi** [comment]
you only fixed this for C2 systems, but the problems still exists in other shattered systems. They are missing all types of wandering and seems to randomly have them all. Just had a guy here complain about being unable to add a U210 to a C4 SHATTERED. Screenshot shows for J011376 for instance, that you can not add any wandering at all. Maybe you should just give up on finding a pattern to these SHs and add them all. :-)
![pasted_image_at_2016_09_28_15_19](https://cloud.githubusercontent.com/assets/3730499/18946368/dbf70c06-862e-11e6-8ed6-568253f38c53.png)
