### ISSUE TITLE
[FEATURE] Securing map functions via specific member accounts (ACL function)

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#325]
As a request/requirement we need some form of functional lock ability for certain mapping data (tabs, static systems, settings) 

At present it appears any and all users can just delete systems and map tabs at will (as well as disable/enable certain functions) 

My proposal is to have some form of ACL (access control list) for the higher level functions of the mapper. Corp mates (and anyone granted access) can add and remove wandering sigs, move connections, etc... However for things mentioned above that a vital to mapping should be inaccessible.

**Comment by exodus4d** [comment]
I added some kind of admin interface with role management in v1.3.3 
https://github.com/exodus4d/pathfinder/issues/164#issuecomment-366307442
