### ISSUE TITLE
[Bug] Error 403 - Access Denied: User not found after session left idle in chrome

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#327]
Issue: 
Leaving pathfinder open for a period of time (Hour+) generates errors (trying to determine if this related to client being logged out of game). 

Issue occurs on all client instances open in Chrome (3 characters) 

http://i.imgur.com/O5CCKN5.png

Causes full client login session from character selection screen.

**Comment by dkrotil** [comment]
Besides of the strange error, this is feature of PF, look for variable 
LOGGED                      =   240
in pathfinder.ini . 
You were logged out.

**Comment by exodus4d** [comment]
As @dkrotil mentioned It´s a feature not a Bug.  
This is just a basic "idle protection".
Duplicate: https://github.com/exodus4d/pathfinder/issues/312
Reade more: https://github.com/exodus4d/pathfinder/issues/198#issuecomment-231826043

**Comment by dnolen** [comment]
Issue is occurring immediately upon logging into a new browser session. 
Changed time out value to try and create a longer time out however the 403 - User not found error is still triggering with multiple tabs opened with 3 different characters.
