### ISSUE TITLE
Green arrows not disapearing on an idle tab

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#33]
Hello,
If you keep a map open in a tab you're not looking at, the green arrows stays  even when you leave the system..
![](http://i.imgur.com/lwV0Yef.png)

**Comment by exodus4d** [comment]
I really did my best to reproduce this but i was unable to do :( Can you please provide some more details?

- Was this on IGB or OGB or both?
- Do you mean with "tab" the map tabs in pathfinder or the browser tabs?
- Where all the systems  still on the map before you switched to an other tab and then came back to the tab and the tooltips were broken? Or were all systems added in the background while watching an other webpage?

**Comment by PaulMurdock** [comment]
Hello,

What I did to achieve this was:
I had Pathfinder open in the IGB, but minimized
I had Pathfinder open in the OGB but not in the tab i was looking at.
After doing a few jumps I opened the pathfinder tab again in the OGB and the arrows were stuck there till I refreshed the page.

**Comment by exodus4d** [comment]
No chance to reproduce sorry :( 
There is a good chance, that this has already been fixed with 1bfcabe

Otherwise, please reopen
