### ISSUE TITLE
Inactive Users still remain on map

### ISSUE THREAD

**Issue by Necrotex** [exodus4d/pathfinder#330]
Some of our Members are still shown to be in a System when they're actually logged off in eve. My personal take on this is that when you log off and close pathfinder before the next update cycle the user never gets updated again and thus remains as a zombie on the map.

Possible solutions could be a cronjob removing inactive sessions from the system and cleaning up the map.

**Comment by exodus4d** [comment]
Hi, there is already a cronjob for this task (running each 10 minutes):
https://github.com/exodus4d/pathfinder/blob/master/app/cron.ini#L27

If you have set up your cronjob right (check the wiki), inactive characters should be cleared automatically. Have you checked your cronjob config?

**Comment by Necrotex** [comment]
Yes, the cronjob is running. I'll take a look at the cron.ini later today. Thanks.

**Comment by Necrotex** [comment]
Got it to work yesterday. Cron did't had the permissions to run the index.php. Thanks for your help.
