### ISSUE TITLE
[Error] Logged out error 0: For security reasons, you were logged out...

### ISSUE THREAD

**Issue by dingdongdiddlerydoo** [exodus4d/pathfinder#333]
![image](https://cloud.githubusercontent.com/assets/22627618/19096731/836bdfd4-8a53-11e6-8e44-6d4095543c17.png)

My corp mates and I keep getting this error randomly after using pathfinder for about 30 min to 2 hours. Only some of us are being affected though. What are these security reasons, and how come this keeps happening?

Processor: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 CPUs), ~3.2GHz
Memory: 8 GB DDR4 SDRAM x 2 Dual-Channel
GPU: MSI GTX 980 (MS-V317)
DirectX Version: DirectX 12
Operating System: Windows 10 Pro 64-bit (10.0, Build 14393) (14393.rs1_release.160915-0644) 
Browser: Chrome Version 53.0.2785.143 m

**Comment by dkrotil** [comment]
Hi, there is feature in Pathfinder , which will automatically logout every user after 4 hours, you can change this parameter. If this happens randomly, then maybe exodus has some ideas , why this is happening.

**Comment by dingdongdiddlerydoo** [comment]
> dkrotil commented 6 hours ago
Hi, there is feature in Pathfinder , which will automatically logout every user after 4 hours, you can change this parameter. If this happens randomly, then maybe exodus has some ideas , why this is happening.

How do you disable this "feature" I cant seem to find it in the settings.

**Comment by exodus4d** [comment]
https://github.com/exodus4d/pathfinder/blob/master/app/pathfinder.ini#L81

240 (default) will log out any user after 240min(4h) Change it it what ever you want.

**Comment by dingdongdiddlerydoo** [comment]
Im guessing the only way for me to edit the .ini file is if im hosting pathfinder on my own. Which means web users are stuck with the 4 hour log off timer?

**Comment by exodus4d** [comment]
@dingdongdiddlerydoo exact. This is just for performance reasons. Inactive users still require a lot network/CPU traffic to keep there maps up2date. There are several hundred active users on my installation, and I can´t handle to much traffic without upgrading my VPS even further (which costs even more €/month). -> Install your own copy of Pathfinder and configure everything to your needs)

So "inactive" users get logged out after 4h.
