### ISSUE TITLE
[Feature] Show time since a connection was created

### ISSUE THREAD

**Issue by Necrotex** [exodus4d/pathfinder#334]
Would be great to have a timer from when the connection was created when I mouse over the connection (like the EOL one).

**Comment by exodus4d** [comment]
Why don´t you use the map overview panel for that? There should be a created timestamp for that information. You can remove connections within this panel as well.

**Comment by Necrotex** [comment]
It would be more user friendly if I could just mouse over the connection to see when it was created (so I can estimate the the lifetime of the connection). Having to click on the system and then looking for the signature belonging to the connection is cumbersome and a nightmare if you want to check a whole chain.

**Comment by dkrotil** [comment]
Map overview is better I think, timestamp doesn´t tell you anything about the connection, because time of the jump through is not related to any system connection property.

**Comment by exodus4d** [comment]
Showing the "*connection created*" timestamp would not be a problem. (the timestamp is already available on the client).
But I don´t want to mess up the map with to much information. Therefore I moved some of those information ("*EOL timestamps*", "*system region labels*") to those tooltips.

**This Issue brings me to an idea that looks more promising to me:**
Anytime a pilot jumps through a wormhole, a new timer will be reset on that connection. So we could highlight connections based on "last jump time", maybe some kind of "gradient" from green to orange, to highlight connections that have been used recently....  
In addition we could add a new "context menu" entry **verify connection" to reset that timer manually (e.g. You set next to a active wormhole but don´t want to jump through)

What you think about this?

**Comment by Necrotex** [comment]
So kind of a heat map for recently used connections. I like it, but it solves not problem I originally had :) 

The problem with the tool tips is that everything gets displayed simultaneously which clutters the map. Would be much better if it only pops up for a single connection when I hover over it for a certain amount of time (like 2 seconds).  Maybe even make the tooltip bigger and include more info (time created, last used, eol timer etc).

**Comment by exodus4d** [comment]
I´m working on a new overlay for wormholes:
- WH signature information, is shown next to the "endpoints" (e.g. K162, N110,....) (requires signatures linked to a connection)
- Small (green) "Arrow" indicates the direction of a wormhole
- WHs get a new overlay with timers.
   - time elapsed since "creation"
   - time elapsed since "last update"

Not sure about the colors/icons...

![connection_labels](https://cloud.githubusercontent.com/assets/9299033/22863474/17383f92-f141-11e6-9bf7-cfad7bf8cad4.png)
