### ISSUE TITLE
Error durring setup

### ISSUE THREAD

**Issue by Hightech1011** [exodus4d/pathfinder#335]
I am getting a blank screen when trying to run setup for the first time. Apache log shows the following:

PHP Fatal error:  Arrays are not allowed in class constants in /var/www/pathfinder/app/main/db/sql/mysql/tablemodifier.php on line 184

Also got the following error when going to the main landing page:

PHP Parse error:  syntax error, unexpected '*', expecting ',' or ';' in /var/www/pathfinder/app/main/controller/ccp/sso.php on line 31

**Comment by dkrotil** [comment]
Looks like problem with PHP part. Join Slack group, we will try to help you there.

**Comment by exodus4d** [comment]
This is no Bug.... I`m 100% your PHP Version is outdated:

This is the Code: https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/ccp/sso.php#L31

Same problem reported here: http://stackoverflow.com/questions/10969342/parse-error-syntax-error-unexpected-expecting-or

Solution: Upgrade your PHP Version to 7.x
***

Update for PHP >= 5.6

PHP 5.6 brought limited support for expressions:

> In PHP 5.6 and later, the same rules apply as const expressions: some limited expressions are possible, provided they can be evaluated at compile time.
