### ISSUE TITLE
[Bug] Class tag info displaying in tool tip on mouse over

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#339]
Issue: 
Users are reporting when mousing over they are seeing class info still being shown as a tool tip. 

Example: 
http://i.imgur.com/wKsipW0.png

Version: 1.1.5

**Comment by exodus4d** [comment]
Hi,

Safari is not a supported browser. Check the FAQ: https://www.pathfinder-w.space . So it´s not a bug :) - And to be honest, Safari will not get any support in the near future. No time for this :(

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic: #262
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
