### ISSUE TITLE
[Bug] Pathfinder maps not loading in Safari

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#342]
Issue: 
Corp members are reporting that when attempting to access mapping data on a mac using safari the map data is unavailable. Tabs for maps will load and users are able to successfully login but map data does not display. 

Reproducible on multiple machines:  Not only on my private installation, but on pathfinder-w.space as well. 

![image](https://cloud.githubusercontent.com/assets/20019999/19229158/6724b5ea-8e99-11e6-8477-279796b4f5e3.png)

**Comment by exodus4d** [comment]
Hi,

Safari is not a supported browser. Check the FAQ: https://www.pathfinder-w.space . So it´s not a bug :) - And to be honest, Safari will not get any support in the near future. No time for this :(
