### ISSUE TITLE
[Feature] Resizeable map/info areas (customizable window placement)? 

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#343]
Request:

Created the ability to scale the window size for the map (and other areas?) of the pathfinder window. This could be a per client rather then a global setting. 

Also potential functionality could include the ability to relocate the items around the interface for customization.

**Comment by exodus4d** [comment]
Nice feature but this is very time consuming to be implemented... So to be honest do not expect this to be done. There are so many more important features :( Resizable Windows would probably work but not re-arrangable/relocation of items .....
