### ISSUE TITLE
Ship info invisible

### ISSUE THREAD

**Issue by dudelard** [exodus4d/pathfinder#345]
First thing, Thank you a lot for this tool and for all the work you have done.

According to" public/img/landing/map_3.jpg", i would like to show current ships in systems info.

I tried to set newShipId to "1" in js\app\page.js. But nothing shown on map.
I tried to modify opacity to "1" and visibility to "visible" to sass/layout/_main.scss. 
Compass built the new public/css/pathfinder.css successfully. But nothing shown on map.

Did i missed something ? Do i need more crest authorisation ?
Thank you for your help and sry for my bad english

**Comment by exodus4d** [comment]
The ShipID is not yet active and available over CREST. They were available over the IGB HTTP Headers. but CCP haven´t added them to the /location endpoint yet. This is still on testing and not yet available. Ill add this information as soon as CCP released the final endpoint.... SO for now, you have no change to get the ShipID.

Official Post: https://forums.eveonline.com/default.aspx?g=posts&m=6667919#post6667919

**Comment by dudelard** [comment]
Oh okay :)
Hope it will be available soon.
Thank you very much
