### ISSUE TITLE
[Feature] Signatures Window - Undo function

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#346]
Request: 
Enable a way in the signatures info box to undo changes in the event of an inadvertent copy/paste into the wrong wormhole field or in the case of an accidental deletion.

**Comment by dkrotil** [comment]
I think this is duplicate request, someone asked for Undo a time ago, but this is often requested feature in our corp too.

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic: #218
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
