### ISSUE TITLE
[Feature] Updates to EOL timer/Toggle function

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#347]
Request: 
1) Enable toggle on EOL timer to be persitantly displayed per client so timers are displayed actively on the mapper. Perhaps a two stage setting can be enabled (mouse over to show timer as a temp overlay) and click to enable permanent display until the hole is dead.

**Comment by exodus4d** [comment]
The problem with permanent overlays is, that they will overlap other stuff on the map. Even now "frigat"/"reserver mass" labels are not visible with active *EOL* labels:

![test](https://cloud.githubusercontent.com/assets/9299033/19439700/61943862-947f-11e6-9e82-69b3f9c41b64.png)

**Comment by exodus4d** [comment]
Sorry, this will not be implemented. With the new signature-overlays it becomes very "overloaded" with that many permanent overlays. I think "hover" an icon, is not that difficult to make them visible for a moment.
