### ISSUE TITLE
[Bug] Infrequent Core Deposit (Ore), Bountiful Frontier Reservoir (Gas) not added properly in signature reader

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#348]
![a09319cbf05528a2a43896554775e323](https://cloud.githubusercontent.com/assets/20519150/19417273/41286200-93a9-11e6-961a-d7171bede607.png)

When adding signatures, there are two which are not listed in "type" field:
Infrequent Core Deposit
Bountiful Frontier Reservoir

You also cannot add them manually because they don't exist on the list. When being added with a signature reader, their name is automaticaly put in the description. 
Unfortunately that leaves "type" field as "unknown" with no real alternative. It breaks the order when sorting by type.

**Comment by exodus4d** [comment]
Thanks for reporting. Could you please give me J-number or at least the "C" number of the systems? I need to know where to add the 2 signature names. Thanks.

**Comment by exodus4d** [comment]
OK it looks like it was a C4 right?

**Comment by WildStrawberryEVE** [comment]
Yes, it was a C4 for sure. I don't remember it's J.
