### ISSUE TITLE
[Feature request] Filters for signature reader

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#349]
Would be nice to have a functionality to filter signatures like in probe scanner in Eve.
Different people have different preferences when it comes to what to add to the signature reader.
When somebody in shattered system adds 60 anomalies and 50 scanned signatures... Simple filter by type would be helpful - to filter out 100% anomalies or even more complex - to leave for example only wormholes.
Preferably - setting saved per user so one does not have to click it every time.

**Comment by exodus4d** [comment]
### New features:
- The "*search*" field can be used to filter the "*signature table*" by **group** column (e.g. combat, gas,...):
![test2](https://cloud.githubusercontent.com/assets/9299033/19449543/49d8e8e0-94a6-11e6-9a6c-4423de778a84.png)
- New filter icon was added to **group** column. This will show a *select* field with all group names in table:
![test](https://cloud.githubusercontent.com/assets/9299033/19449617/8f82f16a-94a6-11e6-9ed3-b3c28b916102.png)
