### ISSUE TITLE
Setup page second database cannot be created

### ISSUE THREAD

**Issue by zozo6015** [exodus4d/pathfinder#350]
Hello,

I am trying to install pathfinder into my server running nginx and I have successfully created the first database and added the data into it the second database is showing as connected but the buttons are not active so that I could insert data in it.

Please help me with this issue.

Regards,
Peter

**Comment by exodus4d** [comment]
Read point 3. https://github.com/exodus4d/pathfinder/wiki/Database

This must be done manually.
