### ISSUE TITLE
[Feature] Option to disable map downloading

### ISSUE THREAD

**Issue by vivace-io** [exodus4d/pathfinder#352]
We would like to be able to disable the ability for users to download maps for purposes of security. While it wouldn't be a perfect solution, it would make it more difficult for malicious sharing of map data.

Currently I just kinda hacked it out of the code, disabling the web route and so on. Don't get me wrong, the ability to download map data is really awesome, and you should by no means remove it from the project. It just presents certain risks.

An option to disable globally from one of the config files would be nice, however disabling map-by-map would be ideal.

Cheers!

Viv

**Comment by exodus4d** [comment]
This feature was implemented a while ago, forgot to close this issue.
Corporation `managers` (read from ESI) and `admins` (read from local *.ini file) can access the `/admin` page and disable `map import` and `map export` for default user group (`member`):

#### Admin page:
![hgrxuho](https://user-images.githubusercontent.com/9299033/48968863-ca9b4700-eff5-11e8-8d32-1d553851b279.png)

#### Disabled map export button:
![61lrysw](https://user-images.githubusercontent.com/9299033/48968879-e9014280-eff5-11e8-93b1-c1d5b93df943.png)
