### ISSUE TITLE
[Feature] Auto highlight all text when opening system names in map field

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#353]
Request: 
Enable automatic select all if possible on text entry fields for the on map signatures. 

Purpose: 
Saves a few clicks to speed up the process of entering unique sig id names if used.

**Comment by exodus4d** [comment]
Sorry, did´t get your point. :( any example?

**Comment by dnolen** [comment]
What I mean is this: 
When you double click on a signature to update the naming info by default the cursor starts at the first character. What I am asking is if the behaviour so that the entire text in the text entry field is highlighted so we can just quickly copy paste info or just overwrite the entire field without having to hit CTRL+a. 

http://i.imgur.com/MzOJtSo.png

Was an ask from my CEO

**Comment by exodus4d** [comment]
Ok, what do you think about this approach:

We could add a new context-menu option "**_copy information_**" (to clipboard). This would copy a string with more system information to clipboard. e.g. "**J110043 (WH)  (occupied)**" or something like this?

![test](https://cloud.githubusercontent.com/assets/9299033/19604553/0c28aa86-97b6-11e6-905f-0d8688313687.png)

**Comment by dnolen** [comment]
I like that option. Good for quick exports. 

We don't use the jcodes in the signature names, so one reason we want to have the text entry field behaviour changed is to just make the adding sig names quicker.

**Comment by exodus4d** [comment]
sure, we could add the alias name as well in front to it: "**My alias - J110043 (WH)  (occupied)**"

**Comment by dnolen** [comment]
Sure.. 

Only real change i wanted to convey at this time is the text box presentation on double clicking a signature. 

Steps as per current
1) Enter new system and wormhole populates itself on map
2) double click the sig id to add the tag we want to have as the label 
3) Have to select all in the text box for overwrite 
4) change label 

How my CEOs request would work 
1) Populate sig
2) double click to enter text edit mode 
3) Enter label with out having to select all before changing text
