### ISSUE TITLE
[Bug] On Debian, with PHP 5.6.26

### ISSUE THREAD

**Issue by andevellicus** [exodus4d/pathfinder#354]
When starting in Debian, I get the error
apc_store() expects parameter 3 to be long, string given

In lib/base.php line 2261, changing: 

`return apc_store($ndx,$data, $ttl);`

to
`return apc_store($ndx,$data, (int)$ttl);`

fixed this problem.

**Comment by exodus4d** [comment]
You should disable APC PHP plugin if you don´t use it. It is recommended not to use APC because I can´t provide any testing for it.

**Comment by andevellicus** [comment]
Ok. 

Debian doesn't support PHP 7x yet I don't think, and that's what I use for my server.
