### ISSUE TITLE
[Bug] Pilots podded makes connection to kspace as a wormhole connect

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#355]
Issue: 
When pilots are podded the system forces a new wormhole link to the HS system where the pilot respawned. 

Version: 1.1.6

**Comment by exodus4d** [comment]
Dublicate: #235, #259, #230

Read this (there is currently no solution for this): https://github.com/exodus4d/pathfinder/issues/235#issuecomment-236392042
