### ISSUE TITLE
Mapper does not update.

### ISSUE THREAD

**Issue by MDDG** [exodus4d/pathfinder#356]
Corp uses Pathfinder. No issues for anyone, except me: Mapper does not update. I can add and delete systems manually, but it wont show me the chains entered by our members. Whatever they edit, i can not see it. I see two statics and a chain of 3 wormholes, and that has been the same for me since corp started using the mapper.

Ive tried various browsers, with no luck. Deleted account and create a new one, with same result.

**Comment by exodus4d** [comment]
I´m on it thanks! Duplicate: #357

**Comment by MDDG** [comment]
http://prntscr.com/cxj5oq

Thats what i been getting, without any change. Can the problem be on my end
somehow? My ingame name is MD74.

Thanks!

**Comment by atkinsj** [comment]
Are you sure you're not using the -w.space pathfinder while your corp uses
an internally hosted one?
