### ISSUE TITLE
[Bug] Map changes are being reverted - Map/Signatures windows

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#357]
Information: 

Users are reporting issues when  making updates to the map and signature addition files 
When moving/update sigs in the map area the changes will immediately revert when the change is completed. This includes moving signatures, adding text to the info box. 
This is also occurring with in the signature windows with statics wormholes being updated and the changes not applying or are being reverted. 

Version 1.1.6

**Comment by dagoaty** [comment]
I have also seen this under version 1.1.5. I assumed it was because of updates to the map by other people but I have seen it on a private map only I was using.

**Comment by exodus4d** [comment]
Thanks I´m on it!
