### ISSUE TITLE
[Change Request] Move the position of the cookie accept window

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#359]
Request: 
Please change the display method for the cookie acceptance button from the bottom right of the screen to a different position that is more obvious. 

Multiple users are reporting they get stuck in a loop not realizing they have to accept the cookie notifications due to the color scheme being so similar to the theme of the login portal

**Comment by dnolen** [comment]
Hey there. Just as a thought to this request. Can you make the acknowledgement of the caching so form of floating prompt before even being able to hit the signin option for SSO?

**Comment by Regner** [comment]
Hopefully soon that whole cookie non-sense goes away: http://www.bbc.com/news/business-38583001

**Comment by exodus4d** [comment]
If cookies are not accepted, users get a new tooltip:

![xy03kga](https://cloud.githubusercontent.com/assets/9299033/25568398/5ad35fc2-2e02-11e7-9771-2e422765c07d.png)
