### ISSUE TITLE
Enhancement: WH Alias in more places.

### ISSUE THREAD

**Issue by Kimeni** [exodus4d/pathfinder#362]
Non critical, but for real convenience, in both the Map Information window, where systems are listed, if whatever Alias has been assigned could be included either as another column, or before/after the J-Sig, it would make identifying systems in the list more efficient.

Additionally, if you have given a WH an alias, when you delete the WH, the deletion confirmation box only asks you to confirm the J-Sig, adding the Alias to the dialog box would make verifying what you're about to delete more comforting.

**Comment by dnolen** [comment]
Great idea. Usually we manually enter in the connection details into the info field in the signature list 
Current system - Leads to (example: c1a-c2c)

If you could populate the details as current system label - connected system label  I think that would be valuable to keep the info upto date.

**Comment by exodus4d** [comment]
![test](https://cloud.githubusercontent.com/assets/9299033/19660614/d03f1186-9a30-11e6-94db-68e656f15806.png)
![test2](https://cloud.githubusercontent.com/assets/9299033/19660616/d184b820-9a30-11e6-91d7-3f2e4c75658f.png)

**Comment by dnolen** [comment]
Is it possible to make a two way functional change? so say we remove a sig off the mapping area it will also remove the associated sig from the signatures list?

**Comment by exodus4d** [comment]
Not yet. There have to be made some major changes to the DB-Schema and how connections are connected with signatures. There is already an issue for that feature.

**Comment by Kimeni** [comment]
This looks fantastic - you're a hero.

**Comment by dnolen** [comment]
Awesome man, Thanks
