### ISSUE TITLE
Enhancement: Scroll Bar for System Notes field

### ISSUE THREAD

**Issue by Kimeni** [exodus4d/pathfinder#363]
Our corp uses the system notes to record intel, unfortunately that occasionally takes up quite a bit of space, and it currently gets cut off, a scroll bar would be needed to see all the notes.

**Comment by exodus4d** [comment]
#### I made some improvements to system _description_ field:
- The height of the _description text_ container depends on the saved description text
 - No scrollbars required to see the complete description
- The `<textarea>` has a dynamic with -> larger screens will benefit from this change
 - `<textarea>` can be resized (vertical)
- Added a "_character counter_" while edit dialog is active
 - Max char count is **512**. (database column limit)
 - Added `maxlength="512"` HTML attribute to `<textarea>`

***
#### New edit mode (dynamic width):
![system_description_edit](https://cloud.githubusercontent.com/assets/9299033/19817427/d11ce6d2-9d4b-11e6-9e11-93d13300ec49.png)

#### Description text (multiple line breaks,...)
![system_description_longer](https://cloud.githubusercontent.com/assets/9299033/19817613/8e3bf80c-9d4c-11e6-9ca3-62fc5d135f42.png)

**Comment by Kimeni** [comment]
Awesome, great solution. Scrolls bars are terrible.
