### ISSUE TITLE
Enhancement: Pasting signatures only where you are.

### ISSUE THREAD

**Issue by Kimeni** [exodus4d/pathfinder#366]
If possible, only allowing signatures to be pasted into the system you are currently in, or, perhaps creating a confirmation popup if you try pasting to a hole you are not in.

**Comment by exodus4d** [comment]
Do you mean with "pasting" the "signature reader dialog"? - Or the lazy way: You can simply press `CTRL` + `v`. If a system was selected the signatures will get updated automatically.

To prevent update signatures in other systems is very important. So a confirmation dialog, and/or a visual warning should work as well, what do you think?

**Comment by Kimeni** [comment]
Yep, either a confirmation or warning - either way as long as it gives you a chance to cancel your action. 

I wouldn't want to completely remove the ability to paste to other systems, occasionally, you leave a system, remember you didn't paste the sigs, but still have them saved to your clipboard.

**Comment by exodus4d** [comment]
#### I made the following changes:
- A new _confirmation_ dialog for *signature update* was added:
 - Update signatures by pressing `ctrl` + `v` on a selected system, which is **not** the current system of a character, will show a confirmation dialog.

![update_signatures_confirm](https://cloud.githubusercontent.com/assets/9299033/19833316/fb2e481a-9e3d-11e6-876c-d0fbfcc52850.png)
