### ISSUE TITLE
[Feature Request] An API to pull map/connection data.

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#372]
It would be nice to be able to get connection and system data from an api.  Maybe require an access token for a character, then be able to access any maps that character has access to.

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic: See #274.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
