### ISSUE TITLE
Overwolf browser support?

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#374]
I'm not sure how relevant is it to #329 , #319 but is it possible to make Pathfinder work on Overwolf's browser? 
So far it's blank after login. Making it work would help a lot to substitute missing IGB.

CEF 3.2357.1289.gc27da0e
Chromium    43.0.2357.130
OS  Windows
WebKit  537.36
JavaScript  4.3.61.30
Flash   22.0.0.209
User Agent  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 OverwolfClient/0.98.211.0
Command Line    "C:\Program Files (x86)\Overwolf\OverwolfLauncher.exe" -overwolfsilent -silent --browser-subprocess-path="C:\Program Files (x86)\Overwolf\0.98.211.0\OverwolfBrowser.exe" --no-sandbox --lang=en-GB --log-file="C:\Users\WildStrawberry\AppData\Local\Overwolf\Log\OverwolfCEF_10952.log" --log-severity=error --remote-debugging-port=54284 --uncaught-exception-stack-size=20 --enable-begin-frame-scheduling --off-screen-rendering-enabled --off-screen-frame-rate=60 --enable-media-stream --locales-dir-path="C:\Program Files (x86)\Overwolf\0.98.211.0\Locales" --enable-npapi --ppapi-flash-path="C:\Program Files (x86)\Overwolf\0.98.211.0\PepperFlash\pepflashplayer32.dll" --ppapi-flash-version=22.0.0.209 --process-per-site --user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 OverwolfClient/0.98.211.0"
Module Path C:\Program Files (x86)\Overwolf\0.98.211.0\libcef.DLL
Cache Path  C:\Users\WildStrawberry\AppData\Local\Overwolf\BrowserCache

**Comment by exodus4d** [comment]
The `Chromium 43.0.2357.130` was released somewhere in June 2015. 
There where some new features added in the meantime which are required (e.g. client site storage) for Pathfinder.

Making _Pathfinder_ backwards compatible with older render engines would take a **lot** time. I can´t afford this :(

But there are some very nice Chrome extensions out there that do the same trick (undock a single tab, keep the window in front, hide browser controls, make browser frame semi transparent,....) If you are interested in this, I could write a short tutorial, or make short _YouTube_ video.

**Comment by WildStrawberryEVE** [comment]
When I noticed the version I had similar concerns.
It would be nice if you could find some time to make such tutorial.
Alt-tabbing is very inconvenient. If there is a way to avoid it, please share.

**Comment by WildStrawberryEVE** [comment]
Overwolf updated it's browser to:
Chromium	55.0.2883.59
Now pathfinder runs on it.
