### ISSUE TITLE
[Feature] Create character blacklist for immediate security concerns

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#377]
Request: 
Enable a user blacklist in the event of users being removed from corp and pending role removal/corporate removal time out. 

As map is editable by any and all users vital information for chain maps can be offloaded and completely removed with out restoration options. 

Use Case: 
A pilot is being removed from corp and to secure map data for corp users we need a way to immediately cut off that pilot from being able to login to the map. Current corp removal takes 24 hours to purge once roles are revoked, this will impact nothing to the ability to login and break the map data if someone is malicious 

Aside from blacklisting an IP in my firewall I don't know how else to cut someone off from the map data in the current release.

**Comment by dnolen** [comment]
This ties into previous requests for admin level controls for map data/user account. 

Please consider creating an ACL as per previously requested and grant admins some ability to delete user accounts from the host from the instance once the pilots has had their permissions revoked

**Comment by WildStrawberryEVE** [comment]
I would love to see some ACLs implemented into Pathfinder.
My preferred approach would be - based only on SSO authentication.
I would really like to avoid forcing users to make separate pathfinder accounts, to store their passwords and make them link them with CREST accounts.
Simpler to use = better. All the users should care is to open the web page and all that admin should care is to make sure only eligible users would succeed.  

I know that such approach has it's limits (you never know who would log in when you allow the whole alliance).
Simplest ACLs could be in fact blacklists - like "Alliance" excluding "Char1", "Char2"... etc.
or Whitelists with character names added one by one by admin.

Some kind of admin control over logging off blacklisted accounts would be appreciated. The question is - should "map admin" be able to do that or rather "Pathfinder admin" should deal with that via some /admin type page with access to the list of active sessions?

**Comment by dnolen** [comment]
@WildStrawberryEVE  I think the last question would be best centered around a group of pathfinder admin users. 

I'd like to see the pathfinder admins have functional control like setting specific locks on static entries, restricting permissions to functions (enabling grid, magnetizing, etc) on a per map (or server level) basis.

**Comment by exodus4d** [comment]
The problem is, that you can´t figure out who is a "manager" (in game). So I can´t identify potential Admins for corp/ally.
And I don´t want to manually add/remove them.

We could think about some kind of "voting" system. E.g. If 3 characters (same corporation) vote for a character, he will be banned for 24h for corp/ally maps. But yeah this is not perfect and could be abused abused. E.g. if someone has 3 chars in a corporation and crates 3 Pathfinder-Accounts for them.
We could make it transparent for banned characters and show them the names who voted?


btw. This is a duplicate Issue. Ill close this one: see: #204
