### ISSUE TITLE
Enhancement: Subject and Body for Notification System

### ISSUE THREAD

**Issue by Kimeni** [exodus4d/pathfinder#379]
"Pinging" or sending "Alerts" for offline or otherwise afk players in your corporation is a standard way of living for Eve. To get the most out of that, those messages need to have enough information that the ones receiving them can determine whether or not the situation is applicable to them.

Pretty much the final main feature my corporation is missing is the ability to stratify and add specifics to our alerts in Pathfinder.

Here is an example of what we'd love to see.

![notification example](https://cloud.githubusercontent.com/assets/23005528/20023579/d6bda460-a295-11e6-8c74-9b9f8ebb2a87.jpg)

**Comment by exodus4d** [comment]
### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic. See #295
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
