### ISSUE TITLE
[BUG] Max Stable Mass is wrong in some statics

### ISSUE THREAD

**Issue by RomanKornev** [exodus4d/pathfinder#380]
Max Stable Mass is capped at 32 bit signed integer:
![3bkg_mass_bug](https://cloud.githubusercontent.com/assets/5807561/20031244/5075716c-a385-11e6-92e3-00b77eea8180.png)
Real mass is 3 000 000 000 kg

**Comment by exodus4d** [comment]
This has been fixed some month ago. Coumn type is now `varcher(128): 
https://github.com/exodus4d/pathfinder/blob/master/app/main/model/wormholemodel.php#L34

have you checked your installation?
