### ISSUE TITLE
[Feature] Tracking mass and character's current ship

### ISSUE THREAD

**Issue by vivace-io** [exodus4d/pathfinder#382]
The new EIS API supports pulling a character's current ship (yay). 

By the looks of it, this is can work alongside the other SSO scopes. Exact mass won't be possible because we can't pull down the fit, but it's a start.

[Link to endpoint.](https://esi.tech.ccp.is/latest/#!/Live/get_characters_character_id_ship)

**Comment by vivace-io** [comment]
Looking more closely, it _should_ be possible to match the ship's unique ID to the XML API. Caching might present a problem with the assets list having a 2 hour cache, but it's better than nothing.

**Comment by ZarosTenjin** [comment]
doing anything with the xml api is kinda bad. it will get phased out with the current plan being 18 months from now. looking at long term use i wouldnt rely on APIs with counted days you can also make educated guesses about the mass of a ship given you know the hull and maybe assume one plate on an armor ship. not the exact science but good enough to not accidentally collapse a hole from non reduction

**Comment by vivace-io** [comment]
Sure, it might get phased out (CCP FoxFour said there was no plans at the
time before she left the company, so it may have changed).

But at present there is no other way to work this, so we have to make do.
And an exact calculation is better than an educated guess.

**Comment by ZarosTenjin** [comment]
be sure that it'll get phased out pretty quickly if feature parity is archieved in the 18 months the dev blog eluded to in the subsection "What about XML API and CREST?"

I'm not questioning that exact calculation is better but i'm questioning if it is worth the effort and dev time to dedicate to a feature requiring an API thats on a death timer

**Comment by Regner** [comment]
I heard talks about getting the assets endpoints in ESI. So maybe talk with the CCPers in the ESI channel and ask for an ETA on that.

**Comment by vivace-io** [comment]
Got an ETA of Soon(TM) so who knows. Ultimately, 18 months IS a decent chunk of time for it to be around and reliable. Though the time commitment is always up for debate.

**Comment by dkrotil** [comment]
Duplicate #313, guys , pls before you open any issue, try to look on current issues. Thanks.

**Comment by vivace-io** [comment]
Thought it closed, so I didn't check. My bad I guess.
