### ISSUE TITLE
[Feature Request] Merge All Invite Types

### ISSUE THREAD

**Issue by NatuIi** [exodus4d/pathfinder#383]
Currently when adding entities on the access list to a map you are only allowed to invite within the specific setting.  For example, corp maps can only invite other corps, alliances only other alliances, and private only other individual characters.

When scanning, often times we want a map available to corp but at the same time the ability to invite our neutral probing characters.  

Would it be possible to remove the restriction on map invites so that you could chose to invite a corporation, alliance, and individuals all to the same map instead of having it being restricted to only one group?

**Comment by InfiniZ** [comment]
This is currently an active Feature Request per #222 .

Please make sure to search before opening new tickets.

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
