### ISSUE TITLE
[Enhancement] Route finder module

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#386]
The route-finder module is very CPU intensive (recursive search across thousands of systems,...). We need to tweak it a bit.

I´m aware of the fact, that some changes will user experience in a negative manner. But there are technical limitations that require some adjustments.

#### Changes:
- All routes get a new "**status**" column:
  - **green** route found
  - **orange** route not searched
  - **red** route not found
- When a system was selected, only the first **2** saved default routes will be calculated. ( reduced from 4 to 2).
- If there are more than 2 default systems saved, they will be shown as "not search" (orange). Route search for those systems has to be triggered manually.
- The max limit for routes in the table (default routes + custom routes) is now limited by **6**.
- All route limits can now be adjusted in `pathfinder.ini` on selfe hosted installations

#### New route status row:
![routefinder_status](https://cloud.githubusercontent.com/assets/9299033/20456712/1cf118b2-ae7c-11e6-8860-5886ce31ac74.png)

**Comment by WildStrawberryEVE** [comment]
Please also think about adding one more option - "Prefer safer".
It's very confusing when route finder finds 10j route to Jita out of which half is through low-sec just because pure hi-sec route is 11j long.
