### ISSUE TITLE
Ship Activity

### ISSUE THREAD

**Issue by sNakiex** [exodus4d/pathfinder#389]
It seems that ship activity isn't working.

There is a ESI endpoint available https://esi.tech.ccp.is/latest/#!/Live/get_characters_character_id_ship
It requires the scope esi-location.read_ship_type.v1

**Comment by InfiniZ** [comment]
I don't believe ESI has been implemented yet with Pathfinder.

**Comment by sNakiex** [comment]
As far as i know ESI and CREST use the same authentication system, the only difference between ESI and CREST is the url and scopes, Pathfinder will need to use only ESI eventually as it will replace both crest and XML system.

**Comment by exodus4d** [comment]
I´ll implement ESI in Q1 2017. I didn´t had the time to look into it. But it should not take to long for implementation. Pathfinder has just 2 XML dependendencies (Alliance Infos, and system jump/die history for the last 24h, which is not implemented in CREST now). All the rest is CREST only.

**Comment by exodus4d** [comment]
Sorry, forget to close this issue. ESI ship tracking was already implemented in the last version (`v1.2.2). More ESI features (like `online` endpoint) and improvements  will come with the next release (1-2 weeks)
