### ISSUE TITLE
[Feature request] Tooltips for commonly used sig properties

### ISSUE THREAD

**Issue by joonashak** [exodus4d/pathfinder#390]
I'm ripping this completely off of Siggy. I find that the tooltips that open up upon hovering on a signature's type in a system's signature list is a quick and useful way to access most frequently used information. The most important would be wormhole masses and lifetimes. Also other things like gas amount, rats, etc. would probably be useful for many people.

Thanks for a great piece of software!

**Comment by exodus4d** [comment]
#### New tooltips
- Added tooltip with wormhole information next to the _select_ field(cell)
- Added colors to the _select_ field (e.g. C2 is 'blue', C3 is 'orange',..)

![signature_wh_type_tooltip](https://user-images.githubusercontent.com/9299033/43971072-0e385b5c-9cd0-11e8-9f12-ddb57de6c0b8.gif)

These other new features coming in `v1.4.1` might also interest you:
- Keybord navigation in signature table: #652 , #266

**Comment by LuxNitor** [comment]
Would hard coding the seven K163 option tags with [@accesskey](https://www.w3schools.com/tags/att_global_accesskey.asp) be an option?
