### ISSUE TITLE
Wrong security status of system in the Route Finder.

### ISSUE THREAD

**Issue by XenoChick** [exodus4d/pathfinder#391]
Security status of system Aunenen is 0.4.
In the route finder it appears as 0.5 though.
![image](https://cloud.githubusercontent.com/assets/22633222/20593034/0c5e6320-b231-11e6-8ad0-02cf05dd9f3c.png)

**Comment by exodus4d** [comment]
This is already fixed in `v1.2.0´. Thanks for the report!
