### ISSUE TITLE
Corporation/Ally Map administrator [Feature request]

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#392]
There were few discussions about admins, blacklists, access lists, external authentications etc.
There was some information and ideas exchanged but finally no conclusions.

I would like to have some ground on which in the future some other options could be build.

1. Accounts in pathfinder.
	Short registration form - Username,e-mail,password.

2. Corporation/Ally maps should require being logged in order to be created.
	Logged in person would be able to create (and delete) corporation or alliance map.
	For regular use of the map - CREST/ESI/WhateverCCP_invents authentication exactly like it is working now
	
Way I see it - a button like "Admin Login" should be available on top bar. 
When clicked it should let a person log in (or create account) with separate credentials (using pathfinder database for that) and allow to perform critical actions to the maps assigned to such user. Like delete now.

In the future it could allow to add admin features like:
- creating ACLs (blacklists, whitelists etc)
- viewing detailed, time stamped logs of activity (like every action - jumping through/adding/deleting/modification of: connections, signatures, comments, aliases, etc.),
- arbitrary setting some presets for the map (or even separate systems on it - like locking), not to be modified by regular users.

**Comment by exodus4d** [comment]
Thanks for your ideas. I created a new issue (#494) with all new functions coming in the next release. Feel free to comment it, if i missed something from this issue.
I close this one because of duplicate.
