### ISSUE TITLE
[Feature Request] Indicator/Toggle to identify if a wormhole/connection is bubbled

### ISSUE THREAD

**Issue by eboaen** [exodus4d/pathfinder#394]
Request to add an option to indicate if a wormhole connection is bubbled (by an Interdictor or anchorable Warp Disruption bubble).

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #301
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
