### ISSUE TITLE
[Bug] "Lazy" pasting of signatures stops working after first paste

### ISSUE THREAD

**Issue by MorpheusXAUT** [exodus4d/pathfinder#397]
My current scanning process is as follows:

1. Jump into new system, make sure it connected properly on pathfinder and select new system to show details
2. Launch probes and copy all signatures ingame
3. Click back _somewhere_ in the pathfinder browser window and paste all signatures by simply pressing CTRL+V
4. Go back to ingame scanning, scan down one sig after another
5. After each sig, I copy the updated sig again and paste it into pathfinder again to update the list
6. Ignore the sig ingame and continue with 4-6 until the whole system is scanned down

I have recently noticed that pathfinder doesn't properly update the signatures anymore, many times only allowing one single "lazy" paste before not reacting to CTRL+V anymore. I have also noticed that clicking the system in the map again (thus having it reload the the system details) OR clicking into the "system comment box" (next to name, security, static) and outside of it seems to reset this behavior, thus allowing me to paste once again.

I have the suspicion this might be related to what @krjohnn reported in #207 - specifically in [this comment](https://github.com/exodus4d/pathfinder/issues/207#issuecomment-228570116).

A friend of mine and me first noticed this behavior with your hosted instance of pathfinder (sigs would fail to be pasted or take forever sometimes), so we've decided to host our own instance (running v1.1.7 at 7e11bf15e9f20053d9c2477bd96d93663155e1ee, installed on Friday according to your wiki) since we figured it might just be the hosted one being overloaded. Unfortunately, the issue persisted, but was a bit easier to narrow down. Most of the times, I can only do a single paste before having to "reset" it as described above.

The server's running Ubuntu 16.04.1 LTS with latest nginx and php available and a MySQL database. All requests are proxied through Cloudflare, although that should pose no issue.
Both our EVE clients are in English.
pathfinder is running in Chrome Version 56.0.2924.3 dev (64-bit) on my PC.

Should you need any other information or access to systems to try and reproduce the issue. I'm available to talk in German as well if preferred.

**Comment by MorpheusXAUT** [comment]
I have also noticed that clicking inside the map-"window" at the very top allows me to repeatedly copy/paste signatures without using the signature reader. Clicking anywhere outside the map-"window" allows a single paste, but still nothing afterwards as described above.

**Comment by exodus4d** [comment]
@MorpheusXAUT I can´t reproduce this in `v1.2.0` :( even copy&paste multiple signature updates (whiteout using the sig reader dialog) workes for me, you you confirm?

**Comment by Slivo-fr** [comment]
Happens on my end after few copy paste, v1.2 self hosted.
Work around proposed in the issue resolve it

**Comment by Slivo-fr** [comment]
I can reproduce this bug on each system I scan, I'm available if you need help bugtracking it

**Comment by exodus4d** [comment]
Thanks for all your help :) It took quit a while to hunt this down.... :(
It was a Javascript "[event bubbling](https://javascript.info/tutorial/bubbling-and-capturing)" problem which an external jQuery plugin i use.

**Comment by Slivo-fr** [comment]
Glad we helped!
