### ISSUE TITLE
Is there a way to test the app without a valid CREST developer API Key?

### ISSUE THREAD

**Issue by IronArthur** [exodus4d/pathfinder#399]
Hi,

BTW, Fantastic app 

I´m trying to tinker with the code for educational purposes. Specially for graphs and auths to external apis

I´ve installed the develop branch of the code but i´ve encountered a problem to try to start testing it. i can´t login because my Eve account is Alpha and i´ve only added time codes with plexes so no Developer API.

Is there anything i can´t do? maybe load some TEST/Static data just for development?

**Comment by exodus4d** [comment]
Hi, unfortunetelly not :( - I´m not sure but it might be possible to crate a developer key for your Installaton, even with an "Alpha-Character".

The problem is, that _Pathfinder_ heavily depends on CCPs SSO login system.

**Comment by IronArthur** [comment]
Thanks anyway. 

In the Eve URL you posted on the CREST section of the wiki, it says that you need to have paid at least once a month of the game for validation purposes. No plexes. 

At least i have a lot of code to look in the setup route and I really like your login/cookie handling.

**Comment by IvandaNothabeer** [comment]
You don't have to actually pay, you just have to identify yourself with a credit card at least once to CCP. This can be a zero cost transaction. See this blog for details ...

https://community.eveonline.com/news/dev-blogs/introducing-the-free-ccp-developer-license-and-the-crest-api-beta-test-period/

**Comment by IronArthur** [comment]
Maybe at that time (2012), it was true, but right now there is no option to validate a card with a "zero cost transaction". 

"You can add a valid form of payment to your account by visiting EVE Account Management and purchasing a PLEX or paying for a subscription in order to satisfy this requirement."
