### ISSUE TITLE
Wrong statics assigned to J013070

### ISSUE THREAD

**Issue by MorpheusXAUT** [exodus4d/pathfinder#400]
J013070 (_systemId 31002517_) has two statics set (_wormholeId 6_ and _21_, _id 139_ and _140_ in the _system_wormhole_ table).
The system was apparently converted to a shattered wormhole and thus does not have any known statics according to this [list of shattered wormholes](http://wiki.eveuniversity.org/Project_Reassembly/List_of_Shattered_Systems). Unfortunately, most other sites providing info about WH statics also seem to be listing the old information, however the system in question definitely had an epicenter and did NOT have a HS or NS connection at the time I scanned it.

Does pathfinder have a separate classification/indication for shattered wormholes (e.g. an extra field or piece of information to be displayed)? If so, the system should also be added to that list.

**Comment by exodus4d** [comment]
Please read my comment: https://github.com/exodus4d/pathfinder/issues/413#issuecomment-279167691
Thanks for your report, when I get more precise/valid data about shatered holes. I´ll add them

There are some suggestions for a "Report system":

> A "Report system" system for statics is probably the best way to grap that data over time automated. But it requires some work. I would make it "anonymous", users can´t see how often and what is reported so far. any report would require at least 2-3 "verifications" by someone else, or some character from an other alliance. And a "spam" protection, e.g. each char can report max X statics,
  - After some time/month I could auto-import those reports and use/show them.
  - this also requires a "report abuse" function where characters can complain about those imported statics. If X characters complain about a static, I could remove it again.

> But this will come with some "problemes".  Corporations would probably "report abuse" for statics in their home systems (in case of a shattered hole) to keep their home system "obscure" for others....


### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
