### ISSUE TITLE
Users not logged out

### ISSUE THREAD

**Issue by Einste1n** [exodus4d/pathfinder#401]
Hi,

thanks for this great Tool. But we have one Problem. Many users are not logged out even though they are offline.

**Comment by dasnomad** [comment]
We are using pathfinder too, and have the same problem. Also occuring are random disconnects to the mapper. Sometimes you stay connected the whole time, without doing much, sometimes you are logged off
while jumping o another system..

**Comment by exodus4d** [comment]
@Einste1n check your Cronjob. Users get "deleted" from the `activity_log` table after some munutes of inactivity. If they are still online (just AFK) they get a new table entry a few ms later on.

**Comment by dnolen** [comment]
I'm seeing the same on 1.2.0. 
Cron is installed with the proper project path but I'm seeing complaints of offline pilots remaining on map

**Comment by xDreamCoding** [comment]
Can't you send something to the server in window.onclose event?

FYI: I haven't looked at the source just chiming in.

**Comment by Slivo-fr** [comment]
I'm experiencing this issue on fresh v1.2.0. 
Some logged out pilots are still displayed on the map over night.

**Comment by DLB82** [comment]
With the cron configuration enabled, this problem is resolved for me.
https://github.com/exodus4d/pathfinder/wiki/Cronjob

Have you activated it?

**Comment by Slivo-fr** [comment]
Forgot about this issue. 
Running the cron as root solved it for me

**Comment by exodus4d** [comment]
Thanks for your contribution! This issue should be fixed with #495
