### ISSUE TITLE
Delete missing sigs option when not using sig reader

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#402]
For when people just copy-paste sigs onto the window.  Maybe a small popup near the sig window?

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue #445
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
