### ISSUE TITLE
Wrong WH class for J013123

### ISSUE THREAD

**Issue by evilcroco** [exodus4d/pathfinder#403]
Shattered WH system J013123 has set class 2 in pathfinder but actually it is class 3. This result to various problems with signature handling.

**Comment by exodus4d** [comment]
Please read my comment: https://github.com/exodus4d/pathfinder/issues/413#issuecomment-279167691
Thanks for your report, when I get more precise/valid data about shatered holes. I´ll add them

### :grey_exclamation: Dublicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
