### ISSUE TITLE
Error when using postgres database

### ISSUE THREAD

**Issue by EvilGrinUK** [exodus4d/pathfinder#404]
Ubuntu 16.04 EC2 nano instance.
Nginx 1.10.0
PHP 7.0.8
Postgres 9.5.5

Attempting to use a Postgres db backend doesn't work as /app/main/db/database.php refers to MySQL specific option 'MYSQL_ATTR_COMPRESS' when trying to connect to the database.

2016/12/02 15:13:36 [error] 23697#23697: *290 FastCGI sent in stderr: "PHP message: Undefined class constant 'MYSQL_ATTR_COMPRESS'
PHP message: PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_COMPRESS' in /var/www/html/app/main/db/database.php:113
Stack trace:
#0 /var/www/html/app/main/db/database.php(49): DB\Database->connect('pgsql:host=loca...', 'pathfinder', 'pathfinder', '*******')
#1 /var/www/html/app/main/db/database.php(18): DB\Database->setDB('PF')
#2 [internal function]: DB\Database->__construct('PF')
#3 /var/www/html/app/lib/base.php(35): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/html/app/main/controller/controller.php(78): Prefab::instance('PF')
#5 /var/www/html/app/lib/base.php(1669): Controller\Controller->beforeroute(Object(Base), Array)
#6 /var/www/html/app/lib/base.php(1179): Base->call(Array, Array, Array)
#7 /var/www/html/app/lib/base.php(2026): Base->error(500, 'Undefined class...', '')
#8 [internal function]: Base->{closure}(Object(Error))
#9 {main}
  thrown in /var/www/html/app/main/db/database.php on line 113" while reading response header from upstream, client: 194.168.*.*, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "test"

**Comment by exodus4d** [comment]
Sorry for the late response. Unfortunately I had to drop postgres support a few releases ago :(

I adjusted https://github.com/exodus4d/pathfinder/wiki/Requirements

**Comment by vivace-io** [comment]
Is there interest in supporting Postgres? Personally, I'm toying with the idea of migrating our alliance stuff over to CochroachDB (you should check it out... it's cool) for various reasons/fun, which uses the Postgres protocol.

If it's something that the maintainer or others want, I may give it a shot in bringing it up to speed?
