### ISSUE TITLE
sso callbacks and /setup

### ISSUE THREAD

**Issue by h4sk1** [exodus4d/pathfinder#405]
Hello Lads,
im unable to use /setup nor will the sso callback part work.
Is it related to mod rewrite or mod headers?

Regards

**Comment by paulipa** [comment]
im having the same problem myself with IIS7 enviroment. Receiving 404

**Comment by h4sk1** [comment]
So / setup failure got fixed by reenabling mods :D 
Still got problems with the sso login --> getting 500

**Comment by dnolen** [comment]
You'd probably get more timely response on the pathfinder slack guys. I had the same issue but ended up being some missing dependences in my linux config.

**Comment by Regner** [comment]
@h4sk1 where/when in the flow are you getting the 500? From pathfinder or on the SSO end from CCP?

**Comment by h4sk1** [comment]
Im getting the error right when i hit the login button.

**Comment by FusionPwN** [comment]
this happened to me aswell... if I remember correctly this is due to the URL in environment.ini.
If it is URL = http://pathfinder.local (something like this, I don't remember exactly how it was) change the URL to yours

**Comment by h4sk1** [comment]
Problems are fixed, some more questions:

How do I enable an alliance map?
and
How do I add other Corps to my maps?

**Comment by exodus4d** [comment]
- If you are logged in with a char in an alliance, you should be able to create those maps as well.
- You need someone from the corp you want to "invite" in your installation as well. This guy needs to enable the "allow share" option for its Corp. Then you should be able to find this corp in dropDown as well. And you can add this corp. -> More information about that is in the manual.
