### ISSUE TITLE
Failed to create session for proxied IPv6 clients

### ISSUE THREAD

**Issue by MorpheusXAUT** [exodus4d/pathfinder#407]
I've just had a user report being unable to log into my self-hosted pathfinder instance while others and myself were experiencing no issues. The PHP error log thankfully pointed me in the right direction quite fast:

```
2016/12/09 15:43:41 [error] 27418#27418: *28375 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1 in /var/www/pathfinder/app/lib/db/sql.php:202
Stack trace:
#0 /var/www/pathfinder/app/lib/db/sql.php(202): PDOStatement->execute()
#1 /var/www/pathfinder/app/lib/db/sql/mapper.php(418): DB\SQL->exec(Array, Array)
#2 /var/www/pathfinder/app/lib/db/cursor.php(242): DB\SQL\Mapper->insert()
#3 /var/www/pathfinder/app/lib/db/sql/session.php(94): DB\Cursor->save()
#4 [internal function]: DB\SQL\Session->write('k04agv589ijaoms...', '')
#5 /var/www/pathfinder/app/lib/base.php(1910): session_commit()
#6 [internal function]: Base->unload('/var/www/pathfi...')
#7 {main}
  thrown in /var/www/pathfinder/app/lib/db/sql.php on line 202" while reading upstream, client: CLIENT_IPV6_ADDRESS, server: , request: "GET / HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "PATHFINDER_MY_HOST", referrer: "https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=PATHFINDER_REDIRECT_URI"
```

Taking a look into the session table of pathfinder's database, I realised all IPs were stored as "pairs" (e.g. "123.123.123.123, 123.123.123.123". I assume this is caused by the way my instance is set up/proxied.

My current setup is: `Cloudflare --> nginx proxy--> nginx/php pathfinder instance`
The nginx proxyis only accepting connections from Cloudflare's network and acts as a public front for all internal services, apps and websites run by me. All other instances are not reachable to the public and only accept connections over the private network from the proxy.

Due to the double proxying as well as Cloudflare, the request ends up with the "X-Forwarded-For" header of "123.123.123.123, 123.123.123.123" when it reaches the pathfinder instance. I assume pathfinder/the framework you're using stores the whole "X-Forwarded-For" header, thus saving the same IP address multiple times. This works fine for IPv4 addresses (since the maximum for that is 32/40 chars with the "double proxy"), but the column is too short for IPv6 adresses.

I have circumvented this issue by increasing the max column length form 45 to 255, now allowing all users to log in just fine. The max. length of this column was already increased from 40 to 45 in 65108d22058b8ad260deb6ea236cc15fbd826529 referencing #273.
I'm honestly not sure what the best way to prevent this problem would be - either increasing the limit again or somehow changing the way pathfinder stores the client's IP address...

**Comment by exodus4d** [comment]
@MorpheusXAUT  Thanks for your report. This is a Framework bug, I opened this Issue a few month ago (https://github.com/bcosca/fatfree/issues/950) and it was already fixed. But as you said, the column is still not big enough.

I´ll open a new Issue for it and reference this Issue.

**Comment by MorpheusXAUT** [comment]
Yeah, I figured as much. Thought I'd let you know anyways so it's documented here 😄 Pretty easy "intermediate" fix for other people running into similar issues until it gets fixed upstream.

**Comment by MorpheusXAUT** [comment]
Looks like this was fixed in the upstream master of fatfree 😄 
I assume we'll have to wait until they release a new version until this change makes it into pathfinder?

**Comment by exodus4d** [comment]
Yeah I want to keep 3rd party libs untouched.

**Comment by MorpheusXAUT** [comment]
Yeah, fair enough!
Glad to see it fixed upstream though, the temporary workaround by extending column length works fine until a new release of the framework.

**Comment by DanielMack** [comment]
just a tiny question out of curiosity : you are actually using a cluster / several nginx instances with pathfinder and **load-balance** for them [like so](http://nginx.org/en/docs/http/load_balancing.html)?? How did you fix the database concurrency issues?

**Comment by MorpheusXAUT** [comment]
@DanielMack sorry for the late reply.

My current setup consists of multiple small, independent VPS, each running their own (single) service and each isolated from the public. On top of that, I run one public-facing machine that proxies requests to the appropriate backend services (based on hostname, etc).

By doing so, I run 1 "public" nginx instance that receives all traffic and proxies it to the second nginx instance running on my "dedicated" pathfinder VPS. On top of that, I've set up Cloudflare to pipe all my traffic through their service, thus technically adding a third nginx "layer".

**Comment by DanielMack** [comment]
Um ... thats not what "loadbalancing" means. You do not loadbalance anything, you are running multiple instances and thats about it. Please do not re-define technical terms, thats really confusing and kind of ... pretentious, to be honest

**Comment by MorpheusXAUT** [comment]
@DanielMack You're correct, it's not loadbalancing, at least not in my current setup. Bad wording from my side, removed it from the first post, although it did not change much regarding the actual problem I was experiencing. While my public-facing nginx does in fact loadbalance for other applications, it does not for pathfinder 😄 

I did tinker with running multiple instances of pathfinder in a loadbalanced setup, however the fact that I left the larger corp is was running the services for drastically reduced the load on my self-hosted instances, thus making a distributed setup obsolete.
