### ISSUE TITLE
Routes module still not working after importing all data

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#409]
Not sure if I've done anything wrong.
I imported the pathfinder.sql and SDE, then imported everything on `/setup`, but it still doesn't show the routes. Can anyone help?

Screenshots of the relevant `/setup` section:

![ss-20161212-13 14 33](https://cloud.githubusercontent.com/assets/1160186/21099215/3b09e664-c06d-11e6-961f-34db7889c2e0.jpg)

**Comment by exodus4d** [comment]
Have you imported the static Data? 

http://i.imgur.com/NtgszbK.png

**Comment by Ricaz** [comment]
@exodus4d Yes, I put it in the screenshot as well.

**Comment by Kill4Free** [comment]
I had the same issue today.
Clearing "files cache" solved this issue.

Tell me if it worked for you too.

**Comment by exodus4d** [comment]
Ill close this issue. No response from author.
