### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#41]
Some people from my corporation get that error when they are trying to login, I can still login, some other people can still login.
![](http://i.imgur.com/BJC3JkI.jpg)

It was working fine yesterday, nothing changed on the server.

**Comment by exodus4d** [comment]
Thx, can you provide a screenshot with the "login" Ajax request please?

- click "network" tab,
- click the login request named "login"
- select the "preview" tab of that request

If there was a DB error, this should be visible on this panel.

![login](https://cloud.githubusercontent.com/assets/9299033/10268895/c5a1a09e-6ac6-11e5-8395-afef7ab40feb.png)

**Comment by Sakarias-Longhorn** [comment]
![](http://i.imgur.com/7oIxoAG.jpg)

**Comment by exodus4d** [comment]
Thanks for this. The problem ist die unique column index `userId_3` in table `user_character`

```
  UNIQUE KEY `userId_3` (`userId`,`characterId`),`
```

This doesn´t work for users who have multiple API Keys stored, and a single Character can be accessed by multiple valid API Keys. I have already fixed this, but there are some lines of code that have to be changed as well. After testing, the code will be pushed into `develop` branch for the upcoming release.
