### ISSUE TITLE
[Feature request] Add WH effect tooltip for *some* frigate/shattered holes.

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#413]
Regular WH with some effect looks like that:
https://gyazo.com/caf2af3bd4040462d9f395ae28d1b80c
With tooltip showing effect on "?"

Small Shattered wormholes (names starting with J000), which have Wolf-Rayet C6 effect, don't have "?" sign and tooltip.
https://gyazo.com/e04e7cce7ed49e6f379d5e63ec03fbfc

**Comment by exodus4d** [comment]
The information is missing because I don´t have it for all shattered holes :( - If you have a list/sheet for that information I could add it of course.

**Comment by MorpheusXAUT** [comment]
There's a list of shattered wormholes on [eve-uni's wiki](http://wiki.eveuniversity.org/Project_Reassembly/List_of_Shattered_Systems), although it's not complete either. The wiki also links to [this Google spreadsheet](https://docs.google.com/spreadsheets/d/1wbMdouiafkE-yT7Du0eKF0aoeF9gjNQco4ms74VX1dw/htmlview?pli=1) with apparently similar data.

Maybe creating a separate table/list of shattered wormholes, their statics and effects would be good in pathfinder (since that information does not appear to be available in other data exports or likewise). That would also help solving problems mentioned in #400 and #403.

I'd be glad to help set something up for data collection and contribute info as I encounter shattered holes myself.

**Comment by WildStrawberryEVE** [comment]
Jack Hayson - former member of Atztech Inc. was trying to map these new wormholes.
Around 2 years ago he made this google doc based on player reports.

[https://docs.google.com/spreadsheets/d/1wbMdouiafkE-yT7Du0eKF0aoeF9gjNQco4ms74VX1dw/htmlview?pli=1](https://docs.google.com/spreadsheets/d/1wbMdouiafkE-yT7Du0eKF0aoeF9gjNQco4ms74VX1dw/htmlview?pli=1)

Possible statics would require further verification but I think effect data is quite usable.

All shattered holes in C1-C5 range (and names starting with J0 or J00) have correspoding class' effect.
They are shattered holes so they have ice,debris field and also Anomalies,Datas and Relics from other classes.

All "C13" holes (SH in Pathfinder, names starting with J000) are frigate holes with C6 Wolf-Ryet effect.

**Comment by exodus4d** [comment]
@WildStrawberryEVE I just did a quick look at the Spreadsheet. I tried to find any "logic" that could help with importing data, or verify what is correct.

As you can see in #403, **J013123** is a **C2** in Pathfinder, which correspond  with the Spreadsheet you linked. But it is supposed to be a **C3** .....

For me it is not a problem to import all that data, but I prefer valid data over outdated data.

**Comment by WildStrawberryEVE** [comment]
I would say - import everything unless you're sure it's incorrect.
CCP probably changed few systems during major updates and that probably caused some inconsistency.
If you have no data served everywhere than people would simply accept it.
If you have data that is mostly correct, people would file issues with correct data just like now they are doing it with missing sites.
Anyway decision is yours.

Another approach is to build some UI for automatic reporting of incorrect data. Some 'report system' button. That could work even for systems without data. Jack Hayson made that google doc manually - from ingame emails. You can make it automated enough to gather data without having to dig through emails.

Also - there are few things which are a sure thing like shattered WHs C13 starting with J000 and having wolf-rayet C6 effect or "normal" shattered systems having sites from other classes.

**Comment by exodus4d** [comment]
Since `v1.4.0` _Pathfinder_ has a complete new/reworked `eve_universe` DB that holds all static System data. System statics and Shattered systems are also updated. Data from http://anoik.is/systems is now used for systems where statics data was missing before. 
I Think we can close this.
