### ISSUE TITLE
[Feature request] Option to make the route finder return multiple possibilities

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#416]
It would be nice if either findRoute could be modified to take an optional argument or a UI feature added so that the route finder could return multiple options rather than just the shortest path: i.e., return the shortest and second shortest and third shortest.

**Comment by exodus4d** [comment]
The route calculation algorithm is very CPU intensive. Any new performed search slows down the Webserver. It is not planned to add more alternative possibilities in the near future.

But 1.2.0 will get a new "saver route" option (shield icon). That can be toggled on any route, to avoid, WH/LS/0.0 systems:

![route](https://cloud.githubusercontent.com/assets/9299033/21582005/acd2cf1e-d048-11e6-9aa2-8c570adb87f5.png)
