### ISSUE TITLE
[Feature request] Routes data should indicate jumps that are wormholes even if they do not go through a j-space system

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#417]
In #316 we added the ability to mark a system as a wormhole in the routes panel except this only shows if they are a j-space system. If a system is a NS->NS or LS->LS hole (or other k-space hole), it is not immediately obvious in the routes data that they are not neighbouring systems.

The routes data should show if two systems are not neighbours (and thus connected by a jb or wh).

**Comment by exodus4d** [comment]
I added a new button that toggles connection information between jumps.
![tx8jjfg](https://user-images.githubusercontent.com/9299033/37869713-17abca00-2fbd-11e8-8649-c054df6dcee9.png)

If it´s a "custom connection" (no stargate) connections can be clicked at to show more information.
![route_connections](https://user-images.githubusercontent.com/9299033/37869714-1c13c444-2fbd-11e8-926f-9bef5bb18aff.gif)
