### ISSUE TITLE
Issues first login/subsequent. Error 500 

### ISSUE THREAD

**Issue by jaythespacehound** [exodus4d/pathfinder#421]
Hi all,
Trying to get this set up. Got to the setup screen and set databases etc seems ok.
When logging in through the EVE api it returns:

```
Error - 500

Oooops, Something went wrong! You have experienced a technical error. We apologize.

Status: 'Internal Server Error'
Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '13:48:00) AS `date` FROM `alliance` WHERE `id`=99003214' at line 1
```

nginx log at the same time:
several of:
```
2017/01/06 10:35:52 [error] 14155#0: *142 FastCGI sent in stderr: "PHP message: HTTP 404 (GET /sso/favicon/favicon-96x96.png)
PHP message: [app/lib/base.php:1532] Base->error(404)
PHP message: [index.php:14] Base->run()" while reading response header from upstream, client: xxx.xxx.x.xxx, server: pathfinder.xxxxxx.com, request: "GET /sso/favicon/favicon-96x96.png HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "pathfinder.xxxxxx.com", referrer: "https://pathfinder.xxxxxxx.com/sso/callbackAuthorization?code=vtzC1y-fxxxxxxxxxxxxxxxxxxxx1xxxxxxxxxxxxxxxxxxxxxx&state=xxxxxxxxxxxx5904cfa"
```

Attempting to log in anew got me an immediate popup:
```
Application Error:
Logged out
error 500: Internal server error
```
Nothing in the nginx log, nothing in the pathfinder error.log (debug set to 3)

pressing 'restart' shows my character.
clicking him shows the same error:500 as above. Again no errors associated. 
Looking in the console just gives me:
```
Failed to load  https://pathfinder.xxxx.com/api/map/init resource: the server responded with a status of 500 (Internal Server Error)
```

any help appreciated

edit:
nginx 1.9.9
fpm-fcgi
php 7.0.8-0

seems related to #216 but only the first bit. Major problem is second bit.

**Comment by jaythespacehound** [comment]
Ok restarting the browser and clearing the cache appears to have fixed this...

**Comment by exodus4d** [comment]
Hi @jaythespacehound , sorry for the late response :( to busy.

Yeah, I got the same error a few times in the past. But as you said, it is very hard to reproduce. It just happend when the first character logs into _Pathfinder_ on a fresh/empty DB.  I´m not 100% sure, but I think I could eliminate the bug somehow :)

I tested it 3-4 times today (drop DB, register new character that is in an alliance) but was unable to get the error. I´ll close this Issue, If you see it again, feel free to re-open. A backtrace would be awesome!
