### ISSUE TITLE
[Feature request] Connecting WH signatures to routes

### ISSUE THREAD

**Issue by oskari** [exodus4d/pathfinder#423]
Currently there's no connection between wormhole signatures in system to the actual routes/connections that the system has. For example if we have 3 C4 wormholes there's no telling which signature is a connection to which system in map.

**Comment by MorpheusXAUT** [comment]
Something like this was started in #228 but never finished due to the author stopping to play EVE...

I would very much like to see that feature as well though, would be a huge QoL improvement!

**Comment by exodus4d** [comment]
This will be implemented with the next release v1.2.1. I close this as duplicate #290
