### ISSUE TITLE
SSL Privacy Error

### ISSUE THREAD

**Issue by mirlotus** [exodus4d/pathfinder#425]
"This server could not prove that it is www.pathfinder-w.space; its security certificate is from dev.pathfinder-w.space. This may be caused by a misconfiguration or an attacker intercepting your connection.

You cannot proceed because the website operator has requested heightened security for this domain."

**Comment by vivace-io** [comment]
Just a matter of a deployment mis-configuration for TLS communications, not an actual software error. :)

**Comment by kdfreeheart** [comment]
Seems like a flub on the last deployment, and not an actual error with the code. 

dev.pathfinder-w.space is the test bed for development features and links to Sisi.

Was this deployed unintentionally?

**Comment by exodus4d** [comment]
I made some changes to the Nginx config 2 days ago. I can´t see any problems with the Cert:

https://www.sslshopper.com/ssl-checker.html#hostname=www.pathfinder-w.space

**Comment by exodus4d** [comment]
It looks like the problem was fixed.
