### ISSUE TITLE
My private map dissapeared after few days withou loging in

### ISSUE THREAD

**Issue by Thaom** [exodus4d/pathfinder#427]
I logged in today and found out that my private map has dissapeared. I still got my alliance maps but i crafted my map of null space and now its gone :(

**Comment by dkrotil** [comment]
Few days ? There is lifetime for private maps in pathfinder.ini -> 

[PATHFINDER.MAP.PRIVATE]
LIFETIME                    =   14

**Comment by exodus4d** [comment]
Yeah, private maps get deleted after the timer expired. I´ll increase the timer with the next release. The timer gets a reset if something has changed on the map.

- private maps will e set to `active = 0` after X days without any changes on the map.
- private maps get deleted after about 30days of inactivity. 

So if you realy want your map back and 30days haven´t passed. You can send me Mail with your charname and I can manually re-activate it.

The current lifetime (in days) can be checked on the login page:
![bildschirmfoto 2017-01-30 um 09 38 19](https://cloud.githubusercontent.com/assets/9299033/22416615/f3e15716-e6cf-11e6-9978-3a30e4236a4f.png)
gin page as well:

**Comment by Thaom** [comment]
ty very much for info:)
