### ISSUE TITLE
Errors after install

### ISSUE THREAD

**Issue by ecortinas** [exodus4d/pathfinder#428]
I am getting these errors when trying to access the page after install. Error 500.

[Tue Jan 31 16:58:44.717812 2017] [:error] [pid 5028] [client] PHP Warning:  file_put_contents(tmp/cache/e9qwqh0btibw.3c7hoawcwa804.sql): failed to open stream: Permission denied in /var/www/pathfinder/app/lib/base.php on line 1834
[Tue Jan 31 16:58:44.731631 2017] [:error] [pid 5028] [client] PHP Warning:  file_put_contents(tmp/34hvqvgcm9esg.n8dy5gthftgj.php): failed to open stream: Permission denied in /var/www/pathfinder/app/lib/base.php on line 1834
[Tue Jan 31 16:58:44.734161 2017] [:error] [pid 5028] [client] PHP Warning:  require(tmp/34hvqvgcm9esg.n8dy5gthftgj.php): failed to open stream: No such file or directory in /var/www/pathfinder/app/lib/base.php on line 2504
[Tue Jan 31 16:58:44.734205 2017] [:error] [pid 5028] [client] PHP Fatal error:  require(): Failed opening required 'tmp/34hvqvgcm9esg.n8dy5gthftgj.php' (include_path='.:/usr/share/php') in /var/www/pathfinder/app/lib/base.php on line 2504

**Comment by exodus4d** [comment]
check the rights for your /tmp/cache/ dir..... your WebServer User does not have the rights to access them...

**Comment by ecortinas** [comment]
So changing the right let me access it. My setup page though has no styling. It's plain html.
