### ISSUE TITLE
Safe route - ability to ignore "starting" wormholes.

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#433]
It would be nice to have the possibility to ignore wormholes at the beginning of the path when calculating safe route. I mean - not delete them from view but from security status calculation.

For example:
Let's say I'm in 115026, looking for Dodixie.
It's ok with 'unsafe' path
https://gyazo.com/75b16ebcd70d0389eb60f57420540e52

there is no route with 'safe' path
https://gyazo.com/a4300f6dc3b07b8628a0b349e1611573

because first 2 jumps are through WH systems
https://gyazo.com/69d7d1f2ee9e40f56b92daf58c97c4a4

Making such change would save clicking. With multiple LS/HS exits one needs to click every exit system to check the safe route for it instead of 'home' system and look for a shortest hisec route after leaving WH chain.

Also - it would be nice to make the safe/unsafe choice permanent. Now it defaults to unsafe every time I change selected system on map.

**Comment by Slivo-fr** [comment]
Agree with all of this

**Comment by OmniarchIO** [comment]
another way is to count systems tagged friendly or empty as 'safe' (or even have a new tag like 'secured'?) in the route calculation.

**Comment by exodus4d** [comment]
_Pathfinder_ uses the new ESI endpoint for route search as the new "default" #590 . WHs are no excluded from the search, when using for "secure"
