### ISSUE TITLE
PayPal donations - FYI

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#435]
I wasn't sure where else to post this but just an FYI with your new PayPal donation button, I think this may be in breach of the license agreement for developer applications.

> Developer may not charge any fee in exchange for a Player's access to or use of the Application, or otherwise monetize or generate any revenue from the Application. 

https://developers.eveonline.com/resource/license-agreement

EDIT: Actually, there's a condition, but worth double checking (though I'm sure you have!):

> (b) Developer may solicit voluntary donations of money from Players (i.e., U.S. dollars, British Pounds Sterling, etc.) solely to offset Developer's costs of maintaining and supporting an Application, provided that use of the Application is not in any way restricted or conditioned on providing such a donation;

**Comment by Regner** [comment]
The license agreement basically says you cannot charge for access to an application or to unlock more access to the application. So long as he hasn't started doing that Pathfinder is in the clear.

**Comment by exodus4d** [comment]
@Regner Thanks for clarification :)

I added the button to the "Licence information" dialog. There are no changes for the users. They don´t have to "accept/pay" anything. 
Donations are not "tracked" by characters and completely voluntarily.

Commits: eff90d3118393d94d016dd0221775aff7581ce19 7cf8b2eb56e6f244b2f6be21339e75282f34a97b

![pz3iaia](https://cloud.githubusercontent.com/assets/9299033/22626469/49efaecc-ebae-11e6-9000-4942a06bf181.png)

**Comment by Regner** [comment]
Yea, you're in the clear. :)
