### ISSUE TITLE
Mark all signatures as updated after using signature reader

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#436]
This is purely a request/idea.

It would be nice to be able to tell when someone last checked the signatures of a system. We usually just copy the signature list from in-game and paste it in the reader in Pathfinder.

I realize the 'updated' column for signatures is used for actual updates, but maybe adding a third column or mouse-over on that could be a solution?

**Comment by MorpheusXAUT** [comment]
👍 Maybe a small popup - appearing when you mouse over the `updated` value of a sig - displaying an additional `last seen` value would be a nice addition. That information would definitely be nice to have, but I wouldn't replace the current `updated` value every time it gets pasted again.
