### ISSUE TITLE
Add option to show a log of changes after using signature reader

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#437]
This could make it a lot easier to manage in-game bookmarks, especially in big systems (and Thera).

**Comment by exodus4d** [comment]
What kind of log you are thinking of? Just a simple history, or a visual "diff" of current signatures and the history?

**Comment by Ricaz** [comment]
@exodus4d A simple list of the systems that were added and deleted would be sufficient I guess.

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #816
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
