### ISSUE TITLE
Routes window has incorrect routes

### ISSUE THREAD

**Issue by ArtificialQualia** [exodus4d/pathfinder#440]
I noticed today some odd routes when trying to find a good hi sec trading hub.  For instance, Pathfinder seems to think Uzistoon is connected to both Jita and Rens.  Here is a copy and paste of both these routes (sorry for the messy html, just copy+pasted from browser):

Route to Jita:
`<td><i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J132106 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J145322 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J123546 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J155340 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J144621 [-1.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="1V-LI2 [-0.4] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="Q-K2T7 [-0.5] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="XV-MWG [-0.4] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="SG-75T [-0.3] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="N3-JBX [-0.1] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="9PX2-F [-0.1] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="ARG-3R [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="VOL-MI [-0.1] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="8G-MQV [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="CL-85V [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="K-QWHE [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="RMOC-W [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="HEMIN [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="UTOPIA [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="DORIL [-0.0] "></i> <i class="fa fa-square pf-system-security-0-3" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="SENDAYA [0.3] "></i> <i class="fa fa-square pf-system-security-0-4" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="ONSOOH [0.4] "></i> <i class="fa fa-square pf-system-security-0-5" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="CHIDAH [0.5] "></i> <i class="fa fa-square pf-system-security-0-5" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="SHENELA [0.5] "></i> <i class="fa fa-square pf-system-security-0-4" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="DOOZ [0.4] "></i> <i class="fa fa-square pf-system-security-0-4" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="UZISTOON [0.4] "></i> <i class="fa fa-square pf-system-security-0-9" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="JITA [0.9] "></i></td>`

Route to Rens:
`<td><i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J132106 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J145322 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J123546 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J155340 [-1.0] "></i> <i class="fa fa-dot-circle-o pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="J144621 [-1.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="1V-LI2 [-0.4] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="Q-K2T7 [-0.5] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="XV-MWG [-0.4] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="SG-75T [-0.3] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="N3-JBX [-0.1] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="9PX2-F [-0.1] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="ARG-3R [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="VOL-MI [-0.1] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="8G-MQV [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="CL-85V [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="K-QWHE [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="RMOC-W [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="HEMIN [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="UTOPIA [-0.0] "></i> <i class="fa fa-square pf-system-security-0-0" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="DORIL [-0.0] "></i> <i class="fa fa-square pf-system-security-0-3" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="SENDAYA [0.3] "></i> <i class="fa fa-square pf-system-security-0-4" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="ONSOOH [0.4] "></i> <i class="fa fa-square pf-system-security-0-5" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="CHIDAH [0.5] "></i> <i class="fa fa-square pf-system-security-0-5" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="SHENELA [0.5] "></i> <i class="fa fa-square pf-system-security-0-4" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="DOOZ [0.4] "></i> <i class="fa fa-square pf-system-security-0-4" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="UZISTOON [0.4] "></i> <i class="fa fa-square pf-system-security-0-9" data-toggle="tooltip" data-placement="bottom" data-container="body" title="" data-original-title="RENS [0.9] "></i></td>`

Let me know if you need any additional information, thanks!

**Comment by MorpheusXAUT** [comment]
Just for easier readability, here's a "cleaned" list of systems listed by the route-planner (parsed from the HTML provided above, not actually produced by my own pathfinder instance):

Route to Jita:
```
J132106
J145322
J123546
J155340
J144621
1V-LI2
Q-K2T7
XV-MWG
SG-75T
N3-JBX
9PX2-F
ARG-3R
VOL-MI
8G-MQV
CL-85V
K-QWHE
RMOC-W
HEMIN
UTOPIA
DORIL
SENDAYA
ONSOOH
CHIDAH
SHENELA
DOOZ
UZISTOON
JITA
```

Route to Rens:
```
J132106
J145322
J123546
J155340
J144621
1V-LI2
Q-K2T7
XV-MWG
SG-75T
N3-JBX
9PX2-F
ARG-3R
VOL-MI
8G-MQV
CL-85V
K-QWHE
RMOC-W
HEMIN
UTOPIA
DORIL
SENDAYA
ONSOOH
CHIDAH
SHENELA
DOOZ
UZISTOON
RENS
```

I'll try to reproduce this issue with my local instance as well.

**Comment by MorpheusXAUT** [comment]
My local pathfinder instance produces the correct path between `1V-LI2` and `Jita`, however the one between `1V-LI2` and `Rens` is slightly different, although of the same length as the result produced by e.g. dotlan or other route planning tools.

I thus assume both paths produced by my pathfinder instance should be correct. I've begun digging into the route generation of pathfinder and the tables used by it a bit... @ArtificialQualia Could it be you're using an older/outdated EVE SDE table for your `CCP` database?

As a test, could you run this query against the **pathfinder** database:
```SQL
SELECT * FROM system_neighbour WHERE systemName LIKE 'Uzistoon';
```
The expected result would be a row with a `jumpNodes` value of `Dooz:Bayuka:Sari`. I guess your table will probably return something else, probably including `Jita` and `Rens`.

As a second test, could you run this query against the **CCP** database:
```SQL
SELECT
  systems.solarSystemName
FROM
  mapSolarSystemJumps jumps INNER JOIN
  mapSolarSystems systems ON
  systems.solarSystemID = jumps.toSolarSystemID
WHERE
  jumps.fromSolarSystemID = 30000040;
```
The expected result would be three rows with values `Dooz`, `Bayuka`, `Sari`. Note that `30000040` is the `solarSystemID` of `Uzistoon` as retrieved from the `mapSolarSystems` table via:
```SQL
SELECT systems.solarSystemID FROM mapSolarSystems systems WHERE systems.solarSystemName LIKE 'Uzistoon';
```

My assumption would be that your pathfinder and/or CCP database queries will return a different result, thus leading to pathfinder's confusion in route generation. If the results are indeed different, you could try re-importing the latest EVE SDE (e.g. provided by Steve Ronuken [here](https://www.fuzzwork.co.uk/dump/mysql-latest.tar.bz2)) and then re-running the system neighbour generation in pathfinder's setup page. That should hopefully fix the issue.

Should the result be indeed the same as above, there's something actually wrong in pathfinder's code 😄

**Comment by ArtificialQualia** [comment]
I should have specificed - I'm not using a private server for pathfinder.  I'm using the public one on www.pathfinder-w.space, so I'd hope the databases are up to date!

**Comment by ArtificialQualia** [comment]
Oh, also another issue I noticed today with the route finder.  It thinks Neziel is a .5 (hisec) system, but it is actually a .4 (lowsec) system in-game.  Maybe that is somehow related to the databases being out of date?

If you'd like me to open a separate bug report for that specific bug let me know.

**Comment by MorpheusXAUT** [comment]
> I should have specificed - I'm not using a private server for pathfinder. I'm using the public one on www.pathfinder-w.space, so I'd hope the databases are up to date!

Oh. Sorry, shouldn't have assumed you were running a self-hosted instance. Guess @exodus4d has to go check that then 😄

**Comment by MorpheusXAUT** [comment]
@ArtificialQualia are you still seeing this behaviour on the [public pathfinder instance](https://www.pathfinder-w.space)? I just tried manually adding the system to my map there and having it calculate results, which yielded a valid route...

Does it still act up if you re-add the system to your map and check again?

**Comment by ArtificialQualia** [comment]
I just tried it with 1V-LI2 and UZISTOON and both seemed to have valid paths.  Not sure why it would be different now, I know we didn't have any weird connections with Uzistoon on our map (it wasn't on our map at all at the time) so not sure what would cause that.

**Comment by exodus4d** [comment]
@MorpheusXAUT Thanks for the research!

@ArtificialQualia  Is it possible that you did a manual search? - By using the dialog?
If you have added multiple maps to it, it might be possible that there was any other connection in one of those maps that changed/shortened the route. The "refresh" icon _remembers_ your setting when you click it.  (at least until you changed your current active system).

The algorithm it selfe is called "[Dijkstra](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) algorithm". I made some changes to it to work with _Pathfinder´s_ data. It is not the same algorithm _CCP_ used thats for sure, but it is basicalls doing the same. If there are multiple possible routes with the same length, the result might vary.

My implementation: https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/api/route.php#L322

I guess we can close this one.
