### ISSUE TITLE
Safe route search only functioning from highsec

### ISSUE THREAD

**Issue by moe-alabel** [exodus4d/pathfinder#447]
Safe route search should work from any security system

**Comment by exodus4d** [comment]
For now "safe route" means `TrueSec` > 0.5 = HighSec.
If you are asking for a "saver" route, or "best" route in case of `TrueSec`, We need multiple route searches for a single search, and then compare them and find out the best option. This is very CPU intensive. I cant provide something like this with a VPS (mid scale). 

Sorry for close.
