### ISSUE TITLE
[FEATURE] Manual mass tracking and calculator

### ISSUE THREAD

**Issue by nezroy** [exodus4d/pathfinder#449]
It would be nice to have the ability to manually enter a jump log for a connection for mass tracking purposes. A simple manual log of jumps, each with a mass value and a flag if that jump made the hole reduce or crit. It should be straight forward to use this data to compare against the signature type and account for a minimum safe/maximum potential remaining mass based on the +/- 10% deviance.

I know that automatic mass tracking is a ways off without ESI support/proper ship-type info (as per #313), but for small/solo corps that can trust each other to manually enter the jump log it would be very handy for tracking low/hisec exits being used for market purposes or when trying to collapse or crit a hole.

I think a manual log would be waaaay easier than the auto-tracking of mass. Auto-tracking of mass is going to require a complete implementation of dogma to calculate ship fits + pilot skills to get accurate #'s. Otherwise it's just estimates, and estimates won't be useful if they can't be manually edited as needed, and manually editing of a jump log brings us full circle back to just starting with a completely manual jump tracker as suggested here :)

**Comment by dkrotil** [comment]
This will be huge tast for couple month ? I think it will be better , when you wait for ESI. I think everyone, which is living in WH wants mass tracking, but not like that.

**Comment by nezroy** [comment]
It's not just for a few months though. If I can't manually edit the mass for a jump, even with automatic tracking, then tracking won't be useful. Even with full ESI you won't know if an AB/MWD/HIC bubble was active during the jump. Being able to 1) manually enter a jump and 2) manually add/edit the mass for a given jump, even when full automatic tracking is a thing, is critical. Without those two manual abilities, jump tracking is not reliable. 

As a result, I believe waiting for ESI and ship info with a goal of starting with automatic tracking is the wrong way to go about this. A manual log should be the first step. That can be immediately enhanced with automatically adding jump entries to the log, which is easy to do with the existing location endpoints, though these entries will still require manual mass entry.

Finally, when ESI endpoints for ship stuff are avail, it would be enhanced again by auto-adding mass to the log entry, when that info is available. But if the entire system is depending on the ship type and mass calcs first, I believe it's starting at the wrong end.

**Comment by exodus4d** [comment]
This will definitely be implemented in one of the next releases! 
The switch to ESI is already implemented and  tagged for the next release.

This is a duplicate issue... #313
