### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by jintarokee** [exodus4d/pathfinder#450]
Installed at https://mysite.com/pathfinder/
In `environment.ini`
```
BASE                        =   /pathfinder
URL                         =   https://mysite.com
```
In `.htaccess`
`RewriteBase /pathfinder/`

But:
setup link `https://mysite.com/setup` instead of `https://mysite.com/pathfinder/setup`
Sign Up link `https://mysite.com/sso/requestAuthorization` instead of `https://mysite.com/pathfinder/sso/requestAuthorization`

if i'am manualy go to `https://mysite.com/pathfinder/setup`
i see blank page and error in apache log
`PHP Parse error:  syntax error, unexpected '(' in /var/www/pathfinder/app/main/lib/socket.php on line 47`

47 string at socket.php   ` protected $ttl = ( self::DEFAULT_TTL_MAX / self::DEFAULT_RETRY_MAX );`

**Comment by MorpheusXAUT** [comment]
Have you enabled `AllowOverride All` in your Apache settings, as mentioned in [this comment](https://github.com/exodus4d/pathfinder/issues/149#issuecomment-219225299)?

**Comment by glyyf** [comment]
I'm also having this issue, but with a fairly default setup. Hosted on local server, 
Base is blank (default)
URL = http://(local-ip)

SSO works, The landing page works, but if I try to access http://(local-ip)/setup, I get a 500 error and in the error log it lists:
`PHP Parse error:  syntax error, unexpected '(' in /var/www/html/app/main/lib/socket.php on line 47`

Using PHP version 7.1.3, mysql version 14.14, on a Debian based system. 

Thanks ahead for the help.

**Comment by exodus4d** [comment]
@glyyf The problem you have relates to this like:

`protected $ttl = (self::DEFAULT_TTL_MAX / self::DEFAULT_RETRY_MAX);`

Assigning Class member variables works in PHP 7.1 but not in older PHP versions (I think < 7.0). 
You have 7.1.3, I have no problems with 7.1.2 and can not image this has changed :(

Please re-check your PHP version on /setup page.

**Comment by glyyf** [comment]
@exodus4d 

Yup, that was it, it was using PHP 5 for some reason. 

For anybody working with the same issue, I am working of a debian based system, so I ran

`sudo a2dismod php5.0`
`sudo a2enmod php7.1`
and then restarted the server with `sudo service apache2 restart`

and it looks like we're good to go. 

Thanks for your help!
