### ISSUE TITLE
Error 500 - session_start(): Failed to read session data

### ISSUE THREAD

**Issue by Ricaz** [exodus4d/pathfinder#455]
A few days after I updated to 1.2.0 (did a fresh reinstall), Pathfinder just stopped working. Since then I've tried fixing it by
 - a re-clone,
 - reinstalling databases,
 - switching to Nginx from Apache,
 - installing Redis,
 - installing ZeroMQ and setting up websockets

When I visit `/` it flashes an error that fades out instantly. It reads:
`PHP Warning:  session_start(): Failed to read session data: user (path: )`.

This is obviously just a warning.

I didn't have the WebSocket stuff installed (ZeroMQ) or configured when it broke down, but I do now.

`nginx` access log:
```
"GET / HTTP/1.1" 500
"POST /api/user/getEveServerStatus HTTP/1.1" 200
```

`nginx` error log:
```
2017/03/08 22:25:48 [error] 507#507: *118 FastCGI sent in stderr: "PHP message: session_start(): Failed to read session data: user (path: )
PHP message: [app/lib/base.php:2152] Base->error()
PHP message: [app/lib/base.php:2831] session_start()
PHP message: [app/main/controller/controller.php:106] Preview->render()
PHP message: [app/main/controller/appcontroller.php:20] Controller\Controller->afterroute()
PHP message: [app/lib/base.php:1782] Controller\AppController->afterroute()
PHP message: [app/lib/base.php:1599] Base->call()
PHP message: [index.php:14] Base->run()
PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: ) in /srv/http/pathfinder/app/lib/base.php on line 2831
PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: ) in /srv/http/pathfinder/app/lib/base.php on line 2831" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxx.xx, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "xxx.xx"
```

The error is probably not related to this, but the WebSocket doesn't seem to connect.
Everything in `/setup` is green except for this in the WebSocket section:
![WebSocket](http://i.imgur.com/D8s03Kt.jpg)

 I can manually connect to the server with a CLI tool called `wscat` (in `npm`) at `ws://host.com:8020/ws/map/update` (and any other URL) as long as I specify the port. Without it just returns `404`.

I mention this because `/setup` tries to connect to `ws://host.com/ws/map/update` without specifying the port, and gets a `500` in return:
`"GET /ws/map/update HTTP/1.1" 500`

Environment:
![Environment](http://i.imgur.com/PRwjGKn.jpg)

I don't know what it could be. Please help.

**Comment by dkrotil** [comment]
Disable web sockets and you will be fine.

**Comment by exodus4d** [comment]
@Ricaz  Check your php.ini config for Session handling:

```
session.save_handler = files
session.save_path = "i:/wt-nmp/tmp"
```

This is just an ** example** of my local path, Check if your path exists and PHP has the rights to read/save data to it.
This has nothing to do with "WebSocket" stuff, just a fail configuration of your PHP environment.
