### ISSUE TITLE
database update issue during api-key registration

### ISSUE THREAD

**Issue by shunsine** [exodus4d/pathfinder#46]
After getting a beta-key by mail and starting the registration process the system presents a dialog asking for the API-keys. I created a new key and copied the info into the dialog. 
When clicking "next" the attached message comes up. 

(To be precise, first i clicked "add" and then "next", realized that now the dialog contained 2 fields, one being empty, and removed the empty field again. In any case the error stays the same.)

![image](https://cloud.githubusercontent.com/assets/15065240/10411737/be5a3ba4-6f6f-11e5-8126-433140e84889.png)

**Comment by shunsine** [comment]
Not sure if this is related. 
I received emails with the login-credentials and tried logging in. In that case i get an "internal  server error". But this might just be a sideeffect of the registration going south.

**Comment by exodus4d** [comment]
I'm fairly certain that this will be fixed with #46 (`v.0.0.13`) is coming this week.
