### ISSUE TITLE
[Feature Request] Option to exempt frigate wormholes in route finder

### ISSUE THREAD

**Issue by luct** [exodus4d/pathfinder#460]
In addition to the mass options within the route finder, is it possible to add an option to remove frigate wormholes from the resulting route?

**Comment by exodus4d** [comment]
Nice feature. I is implemented and will be shipped with the next release:
Default for route search is: "**Include** frigate holes"

#### New Dialog:

![mgncvem](https://cloud.githubusercontent.com/assets/9299033/24967370/235f9738-1faa-11e7-96c0-679aff3fa398.png)
