### ISSUE TITLE
[Feature Request] Add a button to refresh system details after location update

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#463]
Hi,

Amazing app ! Bravo :)
A simple idea : Add a button to activate/deactive an auto-refresh of the system details with current location when you change of system.

It's easier than click on the current location for refresh system details manually always. :)

**Comment by bancatech** [comment]
I highly support this, also would be nice to be able to disable the loads of things, for example disable some modules, that I don't really want updated, since I am only interested in the sigs.

Great work btw.

**Comment by exodus4d** [comment]
When you are in a system that is currently mapped. You should be able to click at the system name (top navigation) to select your current system and/or refresh the data. What would be the benefit of an additional button?

![slsxctk](https://cloud.githubusercontent.com/assets/9299033/25564792/e99e0cf4-2dba-11e7-889c-222a4cd948c1.png)

**Comment by bancatech** [comment]
Sorry for the confusion, I meant an option to auto-follow such changesa as you move, so everytime you change system you don't need to manually refresh it :)

**Comment by DLB82** [comment]
Right. That is what I want say in my initial message. It's I think an improve really amazing to simplify my probing.

**Comment by DLB82** [comment]
1.5.0 Feature. Thanks a lot.
