### ISSUE TITLE
Sign up is not registered

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#465]
Hi,

With Chrome, I must sign up when I close my browser and open it again, or , if I click on Menu > Home.
I have'nt this problem with firefox.

Other guys of my corp have the same issue.

Have you got an idea why?

**Comment by IrateRedKite** [comment]
Make sure you've accepted the cookies on the front page when you sign up, otherwise logins can't persist. 
If you're self-hosting you should also make sure you've changed the log-out timer from it's 4h default to 24h in the config file.

**Comment by DLB82** [comment]
I check on 2 PC with 2 chrome with same parameters.
One register : cookie, pathfinder_session and char_xxx (that contains sign up information)
Th other has just "cookie" and "pathfinder_session" cookies.

I remove all plugins. I check that the browser accept cookies. This is just the "char_xx" cookie that is not created.

I don't understand why. I continue to investigate if other guy has the same problem (log in when you go on pathfinder).

**Comment by DLB82** [comment]
I have the same problem on firefox since I login & remove cookie 
I installed 1.2.0 first the last month. This month, I upgraded pathfinder to 1.2.1 with clear cache files.

**Comment by DLB82** [comment]
I find my error !
I forget to accept cookie in the first page with a click on "That's fine!".

Thanks. Issue closed.
