### ISSUE TITLE
Missing wandering WHs in a C4 shattered WH. (e.g. J010247)

### ISSUE THREAD

**Issue by Slivo-fr** [exodus4d/pathfinder#466]
![image](https://cloud.githubusercontent.com/assets/10325988/24271538/cdf6225c-1019-11e7-841a-da91e1670644.png)

**Comment by Slivo-fr** [comment]
Same issue with wandering WH in J004470

**Comment by exodus4d** [comment]
Are you on Pathfinder `v1.2.1` ? On my installation I have the missing `N766` option as well as some other "possible" static holes. it is not proofed if all of them are "real" statics or not, so I can´t remove them :(

If you have the latest Pathfinder installation, try to re-import the wormhole tables from the `/setup` page. This should add the new added static information for about 60 other systems too, which were added in this release:

![jgeeisu](https://cloud.githubusercontent.com/assets/9299033/24968574/ee27f75a-1fad-11e7-9f27-e28344af14fb.png)

**Comment by Slivo-fr** [comment]
I am on 1.2.1.
However the main issue isn't statics, it's the missing wandering WH choices when you update signatures

**Comment by exodus4d** [comment]
I investigated some time in research. You are right, C4s don´t have wandering WHs in _Pathfinder_. 

I checked the code, and found this comment.
I´m pretty sure there was a reason for my comment regarding C4 holes: [signature_type.js#L230](https://github.com/exodus4d/pathfinder/blob/master/js/app/config/signature_type.js#L230)

I did some more investigation and found this:
> C4 wandering wormholes, do they exist? Never seen one

Source: [https://forums.eveonline.com]( https://forums.eveonline.com/default.aspx?g=posts&m=3176899#post3176899)

And this: 
> No wandering wormholes depart from class 4 (needs confirmation).

Source: [https://www.fuzzwork.co.uk/evelopedia](https://www.fuzzwork.co.uk/evelopedia/index.php/List_of_All_W-Space_Systems#Class_4_Wormhole_Systems_.5BRegions_16-23.5D_.28Total:_505_Systems.29)

#### I assume, that this information is either outdated, or does not count for "shattered" wormholes.

****

The question, what can I do for now? - I think the best approach a **in-game screenshot from a fully scanned C4 shattered WH**. Then we can decide, what types of wandering holes, can exist there, and add them one by one.

Ill set the issue to `on hold` status, until someone has a screenshot for us.

**Comment by Slivo-fr** [comment]
You may be right for classics C4s, but we are talking about shattered ones.
I can confirm I found multiple wandering WHs in multiples Shattered

**Comment by exodus4d** [comment]
Yeah I have no doubt about it. But the important information is: 
**Which kind of wandering whs can spawn in a shattered C4?** (H121, C125) 

I don´t want to add all available types to a shattered C4. Each type (C1, C2, C3,...) has their related set of wandering holes that could spawn. Thats why I asked for some more information (e.g. screenshot). If we have that data, it is very easy to add more options to the DB :)

**Comment by Slivo-fr** [comment]
If I remember right, it was c4 wandering, not sure anyway. 
Is it really an issue to add each type until we find out? 
Better too much than missing, isn't it?

**Comment by exodus4d** [comment]
Thanks, I just tested it with **J010247**. I get the 2 statics X822 and N766. It looks like this was fixed in the meantime :) (Pathfinder `v1.4.0`)

**Comment by Slivo-fr** [comment]
Well the issue was about wandering WH in shattered, not statics !

**Comment by exodus4d** [comment]
Sry my fault. "wandering" WHs have been updated as well in `v1.4.0`

`J010247` has the two wandering WHs:
-  N766>c2
- X877>c4
- U210>ls 

-> (see. http://anoik.is/systems/J010247)

If you still miss a type please let me know

**Comment by Slivo-fr** [comment]
Sounds good for this system. I'll watch for errors over time !
Thanks
