### ISSUE TITLE
500 error when deleting account

### ISSUE THREAD

**Issue by jajmo** [exodus4d/pathfinder#468]
Attempting to delete an account without SSL or a mail server configured leaves the following stack trace:

```2017/03/29 21:47:20 [error] 31847#31847: *4 FastCGI sent in stderr: "PHP message: HTTP 500 (POST /api/user/deleteAccount)
PHP message: [app/lib/smtp.php:201] Base->error()
PHP message: [app/main/controller/mailcontroller.php:40] SMTP->send()
PHP message: [app/main/controller/api/user.php:348] controller\MailController->sendDeleteAccount()
PHP message: [index.php:14] Base->run()" while reading response header from upstream, client: xx.xx.xx.xx, server: xx.xx.xx.xx, request: "POST /api/user/deleteAccount HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "xx.xx.xx.xx", referrer: "http://xx.xx.xx.xx/map"

**Comment by jajmo** [comment]
Update: Wrapping these 4 lines https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/mailcontroller.php#L37 in an `if()` that checked all of the config local variables worked. So by default, set `$status` to true, and then the `if()` will check if a mail server is configured. If it isn't, don't send the mail.

I can send a PR if you want.

**Comment by exodus4d** [comment]
@jajmo Thanks for checking it out. Please send a PR to `develop` branch for it. Thanks!
