### ISSUE TITLE
Character/Corporation search requests never are sent.

### ISSUE THREAD

**Issue by Judahmeek** [exodus4d/pathfinder#469]
![image](https://cloud.githubusercontent.com/assets/8206741/24630334/ed210b2c-1881-11e7-83a6-405e0a0e2a48.png)

**Comment by Judahmeek** [comment]
But then I'm not sure whether that matters considering that the [request url](https://www.pathfinder-w.space/api/access/search/character/Raymond) 404'ed.

**Comment by Shegox** [comment]
Had the same problem, it is working as intenden, you have to activate under account -> share the map invite option for character/corp/alliance. See the extract from the manuel. I think this is the problem you have.
![grafik](https://cloud.githubusercontent.com/assets/16856448/24838430/fc3bd978-1d47-11e7-95a7-362f1cdfe063.png)

**Comment by exodus4d** [comment]
@Shegox Thanks for clarification! :)

It is just a security feature. This should prevent people to spam-map invites to hostile groups. This could be a problem on a public installation like mine.
