### ISSUE TITLE
Feature Request Map resize?

### ISSUE THREAD

**Issue by vaporflame** [exodus4d/pathfinder#472]
So my corp has need for more space on the map in height not in width is there a option to change this? or can i edit css code?, if so can i get some info on this?

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. "Layout" #470 
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
