### ISSUE TITLE
System hover tooltip

### ISSUE THREAD

**Issue by Slivo-fr** [exodus4d/pathfinder#476]
In some frequent cases, hovering a system opens a tooltip with HTML code, see bellow. More annoying, this tooltip sometime stay displayed no matter what.

![image](https://cloud.githubusercontent.com/assets/10325988/25085670/af22f33e-2363-11e7-8486-3f89351f11fa.png)

Self hosted on v1.2.1

**Comment by dkrotil** [comment]
This is duplicate https://github.com/exodus4d/pathfinder/issues/262

**Comment by Slivo-fr** [comment]
Indeed, my bad

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
