### ISSUE TITLE
/setup Error 500

### ISSUE THREAD

**Issue by candlespit** [exodus4d/pathfinder#480]
I have setup pathfinder on a local server running Nginx. I am able to see the login page but when I try to go to the setup page for the database it gives me the following:

Error-500
Status: 'Internal Server Error'
Message: No valid DB Connection given

The error.log message
SQLSTATE[HY000] [2002] No such file or directory

private info is redacted
The nginx_error.log message
1654#1654: *1 FastCGI sent in stderr: "PHP message: No valid DB Connection given.
PHP message: [app/lib/base.php:2159] Base->error()
PHP message: [app/main/model/basicmodel.php:104] DB\Cortex->__construct()
PHP message: [app/lib/db/cortex.php:227] Model\BasicModel->__construct()
PHP message: [app/main/controller/setup.php:199] Controller\Setup->checkDatabase()
PHP message: [app/lib/base.php:1779] Controller\Setup->init()
PHP message: [app/lib/base.php:1601] Base->call()
PHP message: [index.php:14] Base->run()" while reading response header from upstream, client: xx.xx.xx.xxx, server: www.xxx.xxx, request: "GET /setup HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "www.xxx.xxx", referrer: "https://www.xxx.xxx/"

Ive been problem solving this for hours with no luck. Any help would be appreciated and if this is the wrong place to post this please let me know.

**Comment by dkrotil** [comment]
I will look on DB side, if you localhost connection, try 127.0.0.1 in DB setting in https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini

**Comment by candlespit** [comment]
Thanks for the response. I don't have localhost connection sorry for being misleading. I connect through ssh. But I tried your suggestion anyways and no luck

**Comment by dkrotil** [comment]
I had never problems to connect to DB, than I would dig deeper into question is your connection string ( setup ) OK, is the database accessible ? If you making connection through SSH tunnel the DB port is still 3306 ?

**Comment by candlespit** [comment]
The port is 3306. I'm going to start over and set it up again and see where I went wrong. It is probably on my end since the DB is correct and others are not having the same issue.

**Comment by candlespit** [comment]
I got it to work it was mysql messing up. when I reinstalled it it fixed the problem
