### ISSUE TITLE
[Feature] New "Near By" overlay

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#481]
#### Features
- Overlay can be opened by click (slide left/right)
 - "open status" is stored **per map** in **LocalStorage - IndexDB**
- Default jump radius around your current location: **3 jumps** => could be made configurable in future...
- Shows total pilot count. All within **3 jumps** on the right side (green > 0, red == 0)
- Shows total pilots count. Your **current** system on the left
- Shows Your current System name (or alias if set) e.g. "Amarr" + TrueSec status (e.g. **H = HighSec**)

#### Rows:
1. col: Jump distance from your current system (+ tooltip on hover: System name e.g. "Jita")
2 col: Ship thumbnail (+ tooltip on hover: shows ship type e.g. "Amarr Shuttle")
3. col: Ship name
4. col: Pilote name
5. col: "Is docked" icon (+ tooltip on hover: shows stationname e.g. "Amarr VIII (Oris) - Emperor Family Academy")
6. col: "ID-card" icon => clickable, opens inGame info window

#### Table sorting:
- Default sort (jump distance, ASC)

****

#### Some screenshots with _dummy data_:

- (15 pilots) near by, Large overlay, + pagination (13 per page) 
![ku15bvz](https://cloud.githubusercontent.com/assets/9299033/25307108/a9f9f736-279b-11e7-9930-68f393bab6ea.png)

- (  2 pilots) near by, Small overlay (no pagination)
![06eebyu](https://cloud.githubusercontent.com/assets/9299033/25307115/bee2dbfe-279b-11e7-9189-970165ad286c.png)

- (  0 pilots) near by, Empty overlay
![iicxc0h](https://cloud.githubusercontent.com/assets/9299033/25307116/c7a0c9cc-279b-11e7-9d11-979d0c9ae930.png)

- (  0 pilots)  collapsed overlay
![mf0zrhm](https://cloud.githubusercontent.com/assets/9299033/25307119/d0f80760-279b-11e7-9446-f07265d19306.png)

**Comment by DanielMack** [comment]
im just gonna leave this here : https://www.grammarly.com/answers/questions/9500-nearby-vs-near-by/

**Comment by exodus4d** [comment]
@DanielMack Thanks should be fixed now
