### ISSUE TITLE
Map completely missing everything else working

### ISSUE THREAD

**Issue by IceZaroth** [exodus4d/pathfinder#482]
setup works now disabled to get full site working, pulling eve character from DEV API also working fine but when you choose a character all myself and others see is planets in background and no map.

sending images for items seen, setup in 2 images followed by screen after picking a character ...

![2017-04-23_01-26-59](https://cloud.githubusercontent.com/assets/27898202/25309383/07d771b2-27c4-11e7-916d-6bfb98cef576.png)

![chrome_2017-04-23_01-26-39](https://cloud.githubusercontent.com/assets/27898202/25309384/0f7cdd30-27c4-11e7-9923-acf3ca95243f.png)

![chrome_2017-04-23_01-26-20](https://cloud.githubusercontent.com/assets/27898202/25309385/1363802a-27c4-11e7-82d2-6e5a6650c5d0.png)

![chrome_2017-04-23_01-25-46](https://cloud.githubusercontent.com/assets/27898202/25309386/1baaba5a-27c4-11e7-84f8-9802b7b49845.png)

![chrome_2017-04-23_01-24-02](https://cloud.githubusercontent.com/assets/27898202/25309388/1f1340ae-27c4-11e7-9ff0-0a3d4d68aa6d.png)

Hoping to get this up and working after spending a few hours going over everything to get to this point.

**Comment by DanielMack** [comment]
your apache version is too low ... and your setup page even shows it. I dont know if this is the root cause of your problem but its worth a shot

**Comment by Ordo-Vhett** [comment]
you dont have a map loaded. the DB table shows an empty battery on /setup which means there is no row data in that table.

**Comment by Ordo-Vhett** [comment]
click the MAP icon in the top right. click configuration. click new map. set up as needed and click save

**Comment by exodus4d** [comment]
@IceZaroth Yould you solve this problem with @Ordo-Vhett´s tip?

if not, please link some details from the "*network*" tab from your browsers "developer tools".
Feel free to join us on Slack. We will try to help you:  pathfinder@exodus4d.de
