### ISSUE TITLE
1.2.1 Setup unable to run setup-tables with valid MySQL connection

### ISSUE THREAD

**Issue by zmiguel** [exodus4d/pathfinder#483]
Currently running on Nginx 1.10.0 with PHP version: 7.0.15-fpm, MySQL 5.7.17 and redis on ubuntu

![capture](https://cloud.githubusercontent.com/assets/4400540/25317293/fac6ad12-286d-11e7-8bed-660782f716d4.PNG)

When I try to do the tables setup the page refreshes and nothing is changed, after checking the database I see a "sessions" table with one entry

no idea why this is happening, it's able to read fine from the database and the mysql user has full access to the database

**Comment by DanielMack** [comment]
its kind of tricky to get pathfinder running on nginx - what do your logs show?

**Comment by zmiguel** [comment]
` - - [24/Apr/2017:14:02:11 +0000] "GET /setup?db=PF HTTP/2.0" 200 49897 "https://address/setup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.15 Safari/537.36"
 - - [24/Apr/2017:14:02:12 +0000] "GET /ws/map/update HTTP/1.1" 404 1334 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.15 Safari/537.36"`

that's the log when I hit setup-tables, to note that I'm getting a 404 error related to websockets, but that shouldn't be affecting the db connection

Also tried using the develop branch, got the same problem, seems to be nginx config related, after checking all the recommended configs there's nothing mentioned there that I have different.

**Comment by DanielMack** [comment]
im guessing we need the database log now

**Comment by zmiguel** [comment]
mysql logs: https://pastebin.com/C9TmBppV

for both when I refresh the setup page and for when I click on setup-tables.

the only thing that seems to work is the sessions table, everything else is missing, looking at the mysql activity when I try to setup-tables I get hit with ~700 queries/questions, but nothing happens. I might have the logging wrong on mysql... using general_log and error_log, the error log is empty...

**Comment by DanielMack** [comment]
you forgot the pathfinder logs

**Comment by zmiguel** [comment]
pathfinder/logs/error.log is empty :(

@DanielMack thanks for the help so far 👍

**Comment by Ordo-Vhett** [comment]
try manually installing the Schema that is located in the /export/sql/pathfinder.sql

**Comment by brianmadden** [comment]
I'm having the same issue. Everything is a green checkmark in the DB section, but when I click `setup tables` nothing happens. I receive no errors in any of my logs (I've checked nginx, php-fpm, and pathfinder logs). I've also tried to manually create some of the tables and then use the `fix columns/keys` button which also does not work.

I have tried these on both `master` and `develop` branches.

**Comment by dkrotil** [comment]
You need set DEBUG on 3.

**Comment by zmiguel** [comment]
Even with DEBUG set to 3 there are no logs on pathfinder logs directory

**Comment by brianmadden** [comment]
Yep, same thing here. I intentionally set some of the settings wrong to see if it would generate an error.log and it did. I then reverted the settings to the correct state and there is nothing new in the error log. I think this is just a silent failure.

Can we get a schema file to create all of the tables using the `mysql` command line utility by chance?

**Comment by Ordo-Vhett** [comment]
(Pathfinderinstallfolder)/export/sql/pathfinder.sql

**Comment by brianmadden** [comment]
That file doesn't have any of the CREATE statements from what I saw. I tried to use it to create the tables, etc on the command line and it barfed.

**Comment by exodus4d** [comment]
@zmiguel @brianmadden Here is a fresh (empty) DB dump I created on `/setup` page. I can´t see any issues on my side :( If you have any more detailed log/error data, please let me know.

**v1.2.2 SQL dump:** [pathfinder.zip](https://github.com/exodus4d/pathfinder/files/980942/pathfinder.zip)

> **Hint:** This is **not** the intended way, how to use *Pathfinder*! The UI elements on `/setup` are very handy for further updates. The "DB-Diff" features on that page will check your existing DB for changes and automatically update/add missing columns/indexes,.... The alternative is to re-build your DB from scratch with a new update...

**Comment by avree** [comment]
@exodus4d Any chance of a fresh DB dump being produced for latest version? I am having this same issue. Just tried on a fresh Ubuntu 16.04 install running PHP 7.0 and Nginx.

**Comment by WildStrawberryEVE** [comment]
If your ubuntu is mainly for the pathfinder I would suggest upgrading it to 17.04 - it has all libraries in at least minimal required versions for PF. Even if it's on VPS it should not be too complicated - just replace name of distribution somewhere in /etc/apt/sources.list (all occurences to "zesty").
