### ISSUE TITLE
Adding Corps to Map

### ISSUE THREAD

**Issue by Starconquer** [exodus4d/pathfinder#484]
I am unable to add other corps to the pathfinder map, it won't find any corp at all.

As far as I can see it seems that the issue is on the server side.

http://i.imgur.com/hLFI0LT.png

**Comment by dkrotil** [comment]
Look into manual, you need enable sharing from corporation , which you want add to the map. Login as character from other corporation , go to Menu -> Account -> Share -> Enable map invite for corporation map.

**Comment by exodus4d** [comment]
@dkrotil  Thanks for clarification! **FTFM** ;)
