### ISSUE TITLE
Active pilot since 1.2.2 upgrade

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#486]
Hi,

A question about a difference between the 1.2.1 and the 1.2.2 version.

I have updated PathFinder from 1.2.1 to 1.2.2. Everything seems good but now if I log out, I am always considereted as Active. Before, I was removed to the active pilote list.

Is it normal?

**Comment by dkrotil** [comment]
Looks like you aren´t alone, on Slack somebody else reported it too, can you check cron job processing ?

**Comment by DLB82** [comment]
Cron job seems good. Cron logs "deleteConnections" and "deleteLogData" (that remove character_log).
cf. "cron.log"

**Comment by DLB82** [comment]
That is strange. When I log in pathfinder wwithout the client opened, I am considereted as "active" so connected?

**Comment by DLB82** [comment]
Ok I think I understand. Now for pathfinder apps , you are "active" when you have pathfinder open or if you have an active client opened.

**Comment by DanielMack** [comment]
um ..... of course ... its not feasible for any software to poll external servers for every known dataset (characters), that would increase server load exponentially. Thats ... pretty much working how its supposed to be, i would be frightened if pathfinder actually spams the CCP servers like you apparently thought it should behave, that'd be **dangerous** and a really severy design flaw

**Comment by DLB82** [comment]
I think you don't understand me.

In 1.2.1, when you are logged in pathfinder and when you are disconnected in eve, you aren't considerate as active pilot.
In 1.2.2, when you are logged in pathfinder and when you are disconnected in eve, you are considerate as active pilot.

Is it normal?

**Comment by Slivo-fr** [comment]
This happens because ESI location API return the location even if the pilot is offline.
Pathfinder was previously basing his online display on CREST location API that returned nothing if pilot was offline.

ESI should make online/offline check possible, but it's not available yet.
Until this happens, a pilot logged on pathfinder will be displayed on the map

**Comment by DLB82** [comment]
Thanks for your answer. I can close this issue. :)

**Comment by exodus4d** [comment]
@Slivo-fr  Thanks for the clarification :) It is not a Bug, it is just a "lag of feature" in the ESI API. 
CCP is working on this.... Ill implement this asap.

Nevertheless, I implemented some minor improvements, check #489
