### ISSUE TITLE
[Feature Request] Selectable route options

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#491]
In the current release it appears that the predefined route options are defaulting to shortest route. 

Can you make it so that these items are use selectable between "safest", "shorter", "Less secure" paths for any items added to the routes options.

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #406
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
