### ISSUE TITLE
[BUG] Route options only populate top two entries

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#492]
Predefined routes are not populating all routes until a manual refresh of the routes options upon logging in. Only the top two added items automatically search their routes 

![image](https://cloud.githubusercontent.com/assets/20019999/26012816/cfdcadc6-3723-11e7-9f57-4f28040897a8.png)

Version 1.2.2 and below appear to have encountered this issue.

**Comment by exodus4d** [comment]
It´s not a bug, it´s a feature ;)

Increase this value: https://github.com/exodus4d/pathfinder/blob/master/app/pathfinder.ini#L89

**Comment by exodus4d** [comment]
You could also increase the `MAX_Default_COUNT` and `LIMIT` in this config section, if you want to.

**Comment by dnolen** [comment]
Not my server install. I will advise the admin. Thanks
