### ISSUE TITLE
SDE Database tables not recognized

### ISSUE THREAD

**Issue by inoxat** [exodus4d/pathfinder#493]
hi all,

i've installed a new instance of Pathfinder, everthing looks to be fine, logon works....

but the SDE database tables are not recognized, i've imported first the dump bundled with the pf-package then the new one from fuzzywork, case sensitive in the mysql server is set to 1 ... 

![grafik](https://cloud.githubusercontent.com/assets/23635154/26028520/757a1882-3822-11e7-9e6e-b5f095216104.png)

![grafik](https://cloud.githubusercontent.com/assets/23635154/26028557/6a65f6fe-3823-11e7-9260-2881ba44e997.png)

any ideas where to look?
thx

**Comment by WildStrawberryEVE** [comment]
I think it's the case of PF being case sensitive. You created tables with only lowercase and pathfinder is case sensitive. For example you have a table "invtypes" and it should be "invTypes".

**Comment by inoxat** [comment]
You are right, its inversely, case sensitive must be 0, Pathfinder is case sensitive

thx a lot

![grafik](https://cloud.githubusercontent.com/assets/23635154/26029002/2c9c8b96-382b-11e7-9347-67ddebf5ed02.png)
