### ISSUE TITLE
[Feature] New admin interface (iteration 1)

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#494]
> Note: This issue is _WIP_. More included features will be added as comment. This issue represents the *first* iteration of a new _admin interface_

**Motivation:** Server admins, Corporation admins should be able to manage their registered users (characters).

#### Changes:
- New URL `[YOUR_DOMAIN]/admin` route added. HTTP requests  to this route **or** subRoute (e.g. `[YOUR_DOMAIN]/admin/test` require admin access.
  1. A new "_SuperAdmin_" user will be added with master access to all admin functions
  2. Any EVE character who is authorized to login (e.g. matches corp/ally white list) with **corp admin rules** is able to use the new admin SSO login
     - You need to accept the admin _ESI_ scopes ( all default scopes plus `esi-corporations.read_corporation_membership.v1`)
     - You need at least one of these inGame roles: `director`, `personnel_manager` or `security_officer` 
- Corporation admins have access to admin functions for members of their corp
  - **Kick member** for `5min`, `1h` or `24h`
  - **Ban member** forever
  - **Revoce kick/ban** actions of a member

#### WIP UI:
![tbtadfo](https://cloud.githubusercontent.com/assets/9299033/26324202/1dc2f354-3f32-11e7-93b7-c2dad798e85c.png)

#### Additional information
- You can not **kick/ban** yourself
- When a character changed corporation/alliance or its owner (sold character). **kick/ban** actions will be reset.
- When a character is **kicked/banned** a new log is written `logs/admin.log`

**Comment by exodus4d** [comment]
### Role system
#### Roles
- "**_MEMBER_**" - default role for normal characters (no admin rights)
- "**_CORPORATION_**" - grant access on corp wide admin rights (e.g. kick/ban corp members)
- "**_SUPERADMIN_**" - grant access on server wide admin rights (e.g. kick/ban members from other corps)
#### Role configuration
1. **InGame roles:** Characters with one of these inGame roles grant "**_CORPORATION_**" role in _Pathfinder_ ( `director`, `personnel_manager` or `security_officer` )
2. **Static roles:** Server admins can configure multiple characters with admin roles in `pathfinder.ini` config file. 
    - "Static roles" overwrite "inGame" roles (if exists)

Example config:
```
[PATHFINDER.ADMIN]
CHARACTER.0.ID = 1946320202
CHARACTER.0.ROLE = SUPERADMIN
CHARACTER.1.ID = 1234567889
CHARACTER.1.ROLE = CORPORATION
```

**Comment by exodus4d** [comment]
Added some "status rbbons" to the login page:
- ADMIN - for corporation admins (SUPERADMIN is not shown, for security reasons)
- KICKED - for kicked characters (`kickedUntil` information is not shown)
- BANNED - for banned characters.

![bimlp6k](https://user-images.githubusercontent.com/9299033/27005348-5f1a11d0-4e1d-11e7-96cb-dd4d9ed11693.png)

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*

**Comment by discoandhaze** [comment]
I admin my corp's Pathfinder server and I'm not able to give my character superadmin. My default pathfinder.ini has [PATHFINDER.ROLES] instead of [PATHFINDER.ADMIN] which is shown here. I have tried both with no luck. Receive message "ACCESS DENIED: Insufficient in-game roles. "my user" requires at least one of these corp roles: director, personnel_manager, security_officer."

[PATHFINDER.ROLES]
CHARACTER.0.ID = 956#####
CHARACTER.0.ROLE = SUPERADMIN

**Comment by Caffe1neAdd1ct** [comment]
@discoandhaze double check the SUPERADMIN part against your version of pathfinder i'm guessing this was a change between initial implementation and on this issue from 2017 and the actual code.

https://github.com/exodus4d/pathfinder/blob/f443e8016f4a3f79c126b661b24b637101cb69dd/app/pathfinder.ini#L372

work fine for me :+1:
