### ISSUE TITLE
Fix for table names in CCP sql dump

### ISSUE THREAD

**Issue by raphendyr** [exodus4d/pathfinder#50]
Hi,

After fast testing, I think doing this in install process should fix the table names:

```sh
sed 's/\(\(TABLE\|EXISTS\) `\)\([^`]*\)\(`\)/\1\L\3\4/g' mysql56-vanguard-1.0-114986.sql > fixed.sql
```

ps. didn't test importing yet.

**Comment by exodus4d** [comment]
Thanks for your suggestion :) [wiki [install]](https://github.com/exodus4d/pathfinder/wiki/Installation) is updated.

**Comment by daleghent** [comment]
It's advisable to test the importing first. This fixes the creation part, but not the locking and data insertion parts of the SQL dump. The correct sed incantation is:

`sed 's/\(\(TABLE\|EXISTS\|\TABLES\|INSERT INTO\) `\)\([^`]*\)\(`\)/\1\L\3\4/g' mysql56-vanguard-1.0-114986.sql > fixed.sql`

On the whole, I really suggest using the original SDE table names to avoid these kinds of acrobatics. Many of us use a common SDE DB across several apps and having to make a special snowflake version just for this wastes both disk space and cache.

**Comment by raphendyr** [comment]
Thanks @daleghent . Should have noticed those my self. Wanted to mention about this first.

Personally I do agree with you about how this should really be fixed. Just wanted to first fix the "go change stuff from phpmysql" part.

**Comment by exodus4d** [comment]
Yeah thats right, I addet it to my TODO list.

**Comment by Zumochi** [comment]
Mind I ask, why was the decision made to change the SDE's table names instead of just using them as-is?

**Comment by exodus4d** [comment]
There was no "decision" made :) The first dump i got, already had the tables named in lowerCase. I have no clue why. So i have never thought about "renaming" the tables in the past. 
It will be fixed in the future.

**Comment by Zumochi** [comment]
Understood, sounds good! :smiley:

**Comment by exodus4d** [comment]
This will be fixed in `v0.0.15`

**Comment by exodus4d** [comment]
@Zumochi: I found the "problem". 
On my local XAMPP environmet (Windows), the default value for `lower_case_table_names` in my MySQL (`my.ini`) was **1**

>  On Unix, the default value of lower_case_table_names is 0. On Windows the default value is 1. On OS X, the default value is 2.
https://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html

I changed it to **0** and now i get the camelCase names :)

**Comment by Zumochi** [comment]
Aha! Interesting, I'm actively using XAMPP (although I prefer setting up my own WAMP stack) and I don't think I ever got that issue :)

**Comment by exodus4d** [comment]
Table names are changed to "default" names (camelCase) (`v0.0.15`)
