### ISSUE TITLE
Composer requirement too prohibitive

### ISSUE THREAD

**Issue by tstivers1990** [exodus4d/pathfinder#500]
Previously I was able to use Pathfinder on my shared web host. After Composer was added as a requirement, I'm unable to get past that part of the setup. I'm not able to get Composer on my shared hosting.

**Comment by tstivers1990** [comment]
I managed to get around this by installing wampserver on my system and adding the required php module, then installing composer on my desktop, running `composer install` and then uploading the files to the web host. This is still a fairly complex process that required I install a WAMP hosting setup on my desktop, install composer, and add a module to the WAMP setup. Perhaps there should be an easier way to do this that doesn't require setting up a WAMP server.

**Comment by vivace-io** [comment]
Composer is what Pathfinder is built on. Changing this would require an extensive re-write of everything.

I do understand your frustration, though. Depending on what you pay for your shared host and bandwidth, Google Cloud or AWS might be a good place to look. You can get dirt cheap VM's for like $5 on GCE with root level access, and only pay for outbound bandwidth, which is not much if it's just Pathfinder you're hosting.

Regardless, if you are dead set on your host, don't forget you need to set up a cron job for Pathfinder to work appropriately... if you can't do that on your host, you should should expose the endpoint behind Basic Auth or something (seriously, protect the route) and schedule a call to that route on your computer or something else.

Hope this helps.

**Comment by Ordo-Vhett** [comment]
I always build the composer and edit any code on my local computer prior to uploading to my VPS. this way i can fix any issues prior to public release.

**Comment by exodus4d** [comment]
As @vivace-io already said. _Composer_ is primary packet managing tool for _PHP_ this can not be changed.
