### ISSUE TITLE
Can't Create Map

### ISSUE THREAD

**Issue by tstivers1990** [exodus4d/pathfinder#501]
After wiping pathfinder and reinstalling from scratch, I'm unable to create a map after logging in. I'm just presented with the pathfinder window after logging in, with no map in the center. The popup to create a map doesn't appear. Clicking the configuration button that used to be used to create a map, in the right slideout menu, does nothing.

**Comment by tstivers1990** [comment]
After investigation, this bug was introduced in 1.2.3. Pathfinder is working fine with 1.2.2.

**Comment by Ordo-Vhett** [comment]
is there any corresponding errors in any of your logs when this happened. set debug to 3 if it is not already and let us know what (if any) errors generate

**Comment by tstivers1990** [comment]
Just look at commit  4950c13

**Comment by exodus4d** [comment]
@tstivers1990 Could you please open your Browsers Dev tools (Win. shortcut `F12`), and check the _Console_ and _Network_ tab for any errors. If there is anything looking wrong, please share the error screenshot. (If available, extend the Js backtrace information as well).
