### ISSUE TITLE
time out and several other issues and improvement ideas

### ISSUE THREAD

**Issue by Koa-Pinaho** [exodus4d/pathfinder#502]
Just wanted to let you know that I was logged out 3 times while adding systems to the Alliance map. 

Also often after linking 2 systems, the link doesn't show up, but then if I linked them again then 2 links will show up, so I have to delete one.

Some of the systems will randomly change position on the map.
If a user logged in jumps to a cyno does it create a link between those 2 systems? 

Also, is there a way to make the map taller? 

It would be nice to be able to shape the jump bridge links around other systems instead of cutting through in a straight line.

Overall a great site, but seems unstable and unable to handle busy maps, looks like I'll have to delete a bunch of stuff.

**Comment by Ordo-Vhett** [comment]
i have found that the logged out issue is usually from a failed pull from the ESI-API. check your ESI Logs. I usually get an access denied or server failed to respond/server refused connection error in my log when this happens

**Comment by Koa-Pinaho** [comment]
It's not happening as often now.

I logged into the map from a different PC and the map layout was a bit mangled, wondering why system move around on top of each other like that.

**Comment by Ordo-Vhett** [comment]
when this is happening a lot over a short time I have found that logging out and logging back in to refresh the sso token reduces the frequency of this error.

**Comment by Koa-Pinaho** [comment]
Found another issue, when I update the signature reader and tick **delete old** it doesn't remove the wormhole system from the map, and still have to be deleted manually

**Comment by exodus4d** [comment]
According to the "time out" I´m pretty sure this was fixed in the meanwhile. Please let me know if you still get that issue and when it happens.

The map resize feature was added in #553

The **delete old** option in the sig reader just removed signatures but no wormholes/systems from the map.
