### ISSUE TITLE
Unable to share map since updating to 1.2.3

### ISSUE THREAD

**Issue by Elpho910** [exodus4d/pathfinder#503]
Trying to share a corporation map with a second corp, when you enter the corp name in the input box it just says "No Results Found" no matter what is entered.  This has only happened since the update to 1.2.3, it worked fine on 1.2.2.

**Comment by Tupsi** [comment]
I can confirm that not much corps show up, but some actually do. Checking my sql database I found out, that only the names from the corp table which have the shared attribute set to 1, although I have no clue what that setting is actually doing.

**Comment by Ordo-Vhett** [comment]
1 member of the corp must set share Corp maps to allow from the Corp you are attempting to add. You must also set this to allow. if you dont and no member of the corp  you are attempting to add has it set to allow the list will not populate

**Comment by Ordo-Vhett** [comment]
Menu(Top Left) -> Account -> Share -> Corp Maps - Enable

**Comment by Elpho910** [comment]
Awesome that fixed it, thanks heaps!

**Comment by maurerit** [comment]
This is actually in the documentation.  Click Map -> Manual and the scroll down to 'Sharing maps'.

**Comment by exodus4d** [comment]
Yeah this is some kind of "spam protection" on public servers. Corps/Allies have a "_MAX_COUNT_" for maps (`pathfinder.ini`). 
It could be annoying if a hostile group send "share invites". Ship locations will be shared as well...

**Comment by Ordo-Vhett** [comment]
maybe remove corp share option from all users and add it to the new admin page so only those with corp director roles can enable. to prevent Spy activity. as most people won't notice an additional map.
