### ISSUE TITLE
Region Information

### ISSUE THREAD

**Issue by moe-alabel** [exodus4d/pathfinder#504]
It would be helpful to have a visible list the show connected regions on the current map? For example, a prober is asked "Hey do you have a WH to Poitot?" With a quick glance at the list I can immediately know if I have anything remotely close to the requested destination. I am aware that there is a region overlay function, but if your map is as huge as mine, its almost unreadable

**Comment by Ordo-Vhett** [comment]
There already is a region overlay
![image](https://user-images.githubusercontent.com/28077119/27991170-a12ee66a-643c-11e7-83b0-37a929d397d8.png)

**Comment by midnightsteel** [comment]
@exodus4d Can we get this tagged as a feature request?

**Comment by exodus4d** [comment]
@moe-alabel Why do you don´t use the "_Map information_" dialog? There is a complete list with all systems on map. On larger maps you could filter for specific regions. (e.g. "dom" matches "Domain",... )

![tetglp5](https://user-images.githubusercontent.com/9299033/28249278-d79be9de-6a52-11e7-81c6-682b5d5ac5c7.png)

**Comment by moe-alabel** [comment]
It would be nice to not have this information so hidden. The current route is too hard to read

**Comment by exodus4d** [comment]
Sorry guys there are already 2 ways to achieve region information:
1. The overlay
2 The map information dialog + search

It is not planned to implement a 3rd option at this point.

**Comment by lord-carlos** [comment]
Currently working on this. My corp would like to have an easier access to this information. 
![image](https://user-images.githubusercontent.com/155855/49533041-4337b880-f8be-11e8-846b-86eb299c407d.png)
It shows regions for k-space systems.

The mouse overlay effect looks really cluttered. 

But exodus is right in that it should not be 3 places. 
My current idea would be to make the "Show regions" mouse over thingy a three state toggle.

Off, mouse over and on.

What are peoples opinion on this?
