### ISSUE TITLE
Offline characters are not always removed by crontab from the map.

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#507]
I noticed that few characters are quite often left on the map shown as online even though crontab job is running. Today at some point we had only one person online and 6 shown on the map:
[![Screenshot from Gyazo](https://gyazo.com/901e2b2d13326bea183f71a5998c74f8/raw)](https://gyazo.com/901e2b2d13326bea183f71a5998c74f8)

I deleted them manually as shown on the picture but also checked esi.error.client.log and there is a lot of stuff like this:
[https://pastebin.com/raw/bM1wYBJm](https://pastebin.com/raw/bM1wYBJm)
[https://pastebin.com/raw/f7qijGPX](https://pastebin.com/raw/f7qijGPX)

almost always online endpoint but sometimes ship too.

I'm getting also tons of these:
[https://pastebin.com/raw/RC1q2hAP](https://pastebin.com/raw/RC1q2hAP)

**Comment by Necrotex** [comment]
Yea, its pretty much the same for me. Same errors in the logs etc.

**Comment by aalfath** [comment]
this happens to me as well.
