### ISSUE TITLE
Current Location Not Tracking

### ISSUE THREAD

**Issue by Ordo-Vhett** [exodus4d/pathfinder#509]
Im Online logged in. But after Todays CCP Update Pathfinder is no longer tracking Pilot Current Location.
Its not even listing me in the Active Pilot Tab...

**Comment by Ordo-Vhett** [comment]
Nothing in Error Logs, I cleared Cache, Invalidated Authentication Data from Server, Cleared Local Cache and Cookies. Still nothing. Debug is set to 3

**Comment by exodus4d** [comment]
Hi @Ordo-Vhett ,

this sounds indeed a bit strange. Looks like your cronjob is not running as expected. Please check the following:
1. Check the content of `character_log` table. If you see chars online you should be able to see them in this table as well.
2. Check the `updated` column in this table. If your cronjob runs properly there should not be any rows with  `updated` older than **5min**.

let me know what you found.

**Comment by Ordo-Vhett** [comment]
operating on Windows platform. using taskscheduler to replace cronjob. corrected setup mistake. works fine now
