### ISSUE TITLE
Issue after SSO login.

### ISSUE THREAD

**Issue by meithtalann** [exodus4d/pathfinder#514]
When i login with SSO 
i got the transition page ( loading info or such )
and page change to a full gray screen notting appear. 

Tried to update chrome and notting change .

Any clue ?

**Comment by exodus4d** [comment]
@meithtalann Please link your Chrome version. I can´t see an issue with the latest `Version 60.0.3112.78`.

Could you please check the "Chrome dev. Tools" for errors.
Open the _console view_: `Ctrl + Shift + J`
