### ISSUE TITLE
Bugs on statistics identified in 1.2.4

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#517]
Hi,

v1.2.4 is really a good work. Thanks :)

**Bug 1** 
When you sort statistics **monthly** by the last column (sum), the sort is done as alpha-numeric and not numeric.
So, when you sort 4 lines with sum : 10, 8, 5 and 9, I can see : 10, 5, 8, 9 (sort - > +) AND not, 5, 8, 9, 10.
![bug1](https://user-images.githubusercontent.com/24720730/29115294-71c8e94c-7cf7-11e7-9037-0ef80b657567.JPG)

**Bug 2**
Table statistics yearly is not correctly displayed.
![bug2](https://user-images.githubusercontent.com/24720730/29115299-74957456-7cf7-11e7-8169-de0436207aa3.JPG)

**Comment by exodus4d** [comment]
Should be fixed with the latest version `1.3.0`
