### ISSUE TITLE
select with mouse is off when scrolling map

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#518]
hm, weird bug, when i scroll the map to the left it doesn't scroll my mouse frame of reference too, so when i make a box to select a bunch of systems at once but scroll over 2 inches, the box starts 2 inches over from where my mouse is.

**Comment by Slivo-fr** [comment]
Some of my users also reported this

**Comment by generalluser** [comment]
This also happens to me and my users. When you use the scroll bar at all, the drag and drop square is off to the left. This makes it hard to delete systems - you end up having to right click delete.

Hope this helps.
