### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by brian000** [exodus4d/pathfinder#520]
Would it be possible to get a Dockerfile that we could use to put Pathfinder in a Docker image?

**Comment by exodus4d** [comment]
@brian000 https://github.com/Nitesedge/pathfinder-dockerized
It´s not an official file and probably 1-2 releases outdated and needs some adjustments....

Feel free to request _Slack_ access to https://pathfinder-eve-online.slack.com (pathfinder@exodus4d.de) and ask for _@Nite_ he might help you with that.
