### ISSUE TITLE
No pilot location data

### ISSUE THREAD

**Issue by NovaNation** [exodus4d/pathfinder#521]
Since 18/07/17 pilots location is no longer functioning, has been checked on 4 computers, 3 different networks with multiple different browsers, every thing was functioning correct prior to the above date with it showing which wormhole the pilots were in and also adding the jump throughs onto the global map.

I have removed both my accounts and re-done the sso login but to no avail even tried adding admin permissions onto the scope via the admin login to see if that could get location data from the corp information but that didnt do any thing either.

Couldnt find any social media to contact creator via other than this and google + but meh to google +....

As I said above every thing was working fine the day before except 1 pilot didnt show up when he logged on then since then I dont even show up every thing shows as online, tracking is on but active =0 all the time and it doesnt recognise when i move into another wh or system or pull any of the sig data automatically (with the ceo scopes added).

Please advice what may be causing this, thanks in advance.

**Comment by dkrotil** [comment]
ESI is down ... duplicate to #519 close it pls .
