### ISSUE TITLE
Maps no longer tracking

### ISSUE THREAD

**Issue by patrickebates** [exodus4d/pathfinder#522]
Using the build hosted on the public site, about two weeks ago tracking stopped working on all maps for all of my characters, regardless of the Eve account.  Creating new maps doesn't seem to help.

Might be worth noting that during the Eve API outage about a week ago, the tracking appeared to be partially functional.  At the very least, it would acknowledge that a character was logged in and list their ship.

Let me know what additional information you may need, or if there is something I need to do on my end.

**Comment by dkrotil** [comment]
Duplicate to #519 , pls close it. Currently are problems with ESI, https://developers.eveonline.com/blog/article/2017-08-18-esi-outage-1 , universe/names endpoints are down .
