### ISSUE TITLE
Tracking still not working.

### ISSUE THREAD

**Issue by BaronNox** [exodus4d/pathfinder#524]
I stracking still not working? The dev blog says the endpoints are online again, but i cannot get the map to track my location.

**Comment by dkrotil** [comment]
Duplicate to #519  , pls close it. Currently are problems with ESI, https://developers.eveonline.com/blog/article/2017-08-18-esi-outage-1 , universe/names endpoints are down because of that tracking is not working.

**Comment by BaronNox** [comment]
Well second line of that blog says that all endpoints are online again.

**Comment by Slivo-fr** [comment]
I don't think this should be closed.

If it's indeed because names endpoint is down, I do think we shouldn't (if possible) depend on this endpoint to get location tracking working

**Comment by BaronNox** [comment]
I was wondering because other mappers don't seem to have the same issue. Could be due to CREST/XML-API tracking implementations.

**Comment by Slivo-fr** [comment]
I don't think there is any other tracking implementation in others APIs
You may want to rename the issue to something like 'names endpoint prevent tracking to work properly' if that's what you mean

**Comment by dkrotil** [comment]
Yes, this is possible, but I don´t think that opening several tickets for same issue is not good approach to solve it. I don´t think Exodus will implement it back .

**Comment by BaronNox** [comment]
Yeah I'll close this. No need to implement old APIs if they are gonne be shut down soon (May '18 iirc).
I was just wondering since a lot of people from the EvE-Scout channel told me their Pathfinder tracking worked and mine didn't.
Thanks for clarification that the endpoints are still down. Fly safe o7

**Comment by Slivo-fr** [comment]
I didn't meant to implement back old APIs, but reworking a bit the tracking to not depend on this names endpoint that doesn't seems to be required

**Comment by BaronNox** [comment]
afaik there's only one endpoint for getting the location of a player using ESI and if that endpoint is down there's no way (w/o implementing the old APIs) to get the player location.

**Comment by Slivo-fr** [comment]
Indeed, but this ESI location endpoint is now working 'perfectly'.
Pathfinder struggle tracking because of the universe/names endpoint still being down

**Comment by BaronNox** [comment]
Oh ok, didn't know that.

**Comment by exodus4d** [comment]
Yeah the Universe endpoint is down. But will be online in a few days. I quick fixed this and "disabled" the endpoint on my prod server.
