### ISSUE TITLE
[BUG?!?!] Database Setup Routing Issue

### ISSUE THREAD

**Issue by ddavaham** [exodus4d/pathfinder#527]
Is this a bug? I had to manually go in and the call to $this->hive['base'] in order for my Database Setup to redirect correctly. Please review for correctness.

https://github.com/exodus4d/pathfinder/blame/489e7d816876cb9db0422bc9f511a1750d5eded9/app/lib/base.php#L1381-L1382

I have recorded myself displaying this bug. The video is about 4m long and linked below.

https://www.youtube.com/watch?v=vo3mmiEgyiU (Uploaded minutes ago so Youtube is still doing their thing to the video)

On a side note, I did modify my .htaccess because this site is on subdomain but i do not believe that this is affecting anything.

Here is the .htaccess
https://gist.githubusercontent.com/ddouglas493/e6ff4aad1a35a0dc67911ab017c4fb8b/raw/00c7d6628505d5b4a93928c891dd3a59216084c3/.htaccess

**Comment by sn0opy** [comment]
What's the value of `URL` in your environment.ini? There's rather a configuration / rewriting issue than an actual issue with the underlying framework.

**Comment by exodus4d** [comment]
I closed this because of response. We need more information, error logs, php logs, access logs?
