### ISSUE TITLE
Internal Server Error when logging in 

### ISSUE THREAD

**Issue by Legacy** [exodus4d/pathfinder#529]
Hi just wanted to report an error, 

The admin has updated the mapping tool but its seems to be just me thats been affected. I've cleared the cache and cookies and still get this error, hopefully you'll know whats going on 

![screenshot 138](https://user-images.githubusercontent.com/2722063/30525385-a0e26b5c-9bfd-11e7-91a3-cc48e36c4f0a.png)

**Comment by dkrotil** [comment]
Had you admin done this ?

3. Clear cache data

Clear cached template files (tmp/)
Clear cached data (filecache: tmp/cache or Redis)
