### ISSUE TITLE
Map Settings: shared setting - character/corp search doesn't work properly

### ISSUE THREAD

**Issue by mykola-skrypets-lebara** [exodus4d/pathfinder#530]
In Select2 input, search kicks in only when 3 characters are typed which gives incorrect results in return, if you type more it returns empty JSON string.

**Comment by exodus4d** [comment]
Sorry, but I can not  reproduce this :(

![share_search](https://user-images.githubusercontent.com/9299033/37869980-6ffa0e1e-2fc3-11e8-8a2a-2734de43db05.gif)

**Comment by der-micky** [comment]
![image](https://user-images.githubusercontent.com/29451620/43756723-36306b84-9a16-11e8-9ad9-994c25a56192.png)
Same issue here. (Almost) fresh install and can't share our map.

**Comment by exodus4d** [comment]
Have you **enabled** the "share" feature for "Winning eve" corporation? - if you don´t have a character in this corp, ask someone else to do it -> "Left menu" -> "Account settings" -> "share" tab

**Comment by exodus4d** [comment]
### :x: Issue closed
This issue has been closed because it has been inactive for a while.

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*
