### ISSUE TITLE
Systems moves back when refreshing.

### ISSUE THREAD

**Issue by Jeppezon** [exodus4d/pathfinder#531]
I can move system to another spot but when refreshing the page they move back to where they was before.
Tried in google chrome, and in incognito and it still diden't work. I've tried locking the systems after I moved them it dosen't help. Pathfinder looks like shit right now because no one can move shit. We have like 4 or 5 systems stack on top of eachothers.
Edit: seems like the only person who can move a system is the person who adds it...

**Comment by exodus4d** [comment]
When someone moves systems around, the map update counter (bottom right of a map) starts to count from 3 to 0. If the counter hits 0, all new map changes get pushed to the server and visible to others. If you refresh before the counter hits 0 changes will not be stored and you will get the old positions.
