### ISSUE TITLE
Error 520: No Reason Phrase

### ISSUE THREAD

**Issue by TrinityErik** [exodus4d/pathfinder#532]
I keep getting this message:

![2017-09-23-101453_694x245_scrot](https://user-images.githubusercontent.com/20780338/30775427-511dfe16-a048-11e7-9c86-ad0952dd4b37.png)

This happens at random and keeps disconnecting users within a minute or two of inactivity.

Where should I be looking to resolve this?

**Comment by jajmo** [comment]
Check your server and pathfinder logs. There might be some insight in those files.
