### ISSUE TITLE
Click + Drag bug

### ISSUE THREAD

**Issue by ninjawolfy** [exodus4d/pathfinder#533]
Selection box created through click and drag is off set and the off set is directly prepositional to how far you have scrolled over on your map. So if you haven't moved the scroll bar to the right at all then your selection is in point, scrolling to the far right creates an huge offset dis-allowing you to select any systems.

**Comment by mrurb** [comment]
A screen shot of the problem
![skaermbillede 2017-10-05 04 38 49](https://user-images.githubusercontent.com/3414748/31208821-a675f22c-a987-11e7-98d1-adac400729d8.png)

**Comment by atkinsj** [comment]
This is not fixed in #544. The bug still happens on the head of dev right now.
