### ISSUE TITLE
unable to install zmq on godaddy cpanel

### ISSUE THREAD

**Issue by garemoko** [exodus4d/pathfinder#538]
I'm trying to install on a site on GoDaddy's shared hosting. 

When running composer I get the following error

```
Problem 1
    - The requested PHP extension ext-zmq 1.1.* is missing from your system. Install or enable PHP's zmq extension.
  Problem 2
    - Installation request for react/zmq 0.3.* -> satisfiable by react/zmq[v0.3.0].
    - react/zmq v0.3.0 requires ext-zmq * -> the requested PHP extension zmq is missing from your system.
```

Any advice on how to get this working on godaddy, or is there a way to run this without zmq?

**Comment by sn0opy** [comment]
Basically you have to do, what it says. The PHP extension zmq (zeromq) needs to be installed. Most distributions have a package called php-zmq.

**Comment by garemoko** [comment]
Thanks for letting me know. I also confirmed with godadday that they do not support zmq extension.
