### ISSUE TITLE
Error on step #1 of registering

### ISSUE THREAD

**Issue by Raykazi** [exodus4d/pathfinder#54]
Running this on 
Debian Wheezy 7.8, Nginx, Mysql 5.6
Tried to register and got a 500 error
checked the log and saw this
syntax error, unexpected '(array)' (array) (T_ARRAY_CAST) in /var/www/app/main/model/basicmodel.php on line 371
Fatal error: syntax error, unexpected '(array)' (array) (T_ARRAY_CAST)

**Comment by exodus4d** [comment]
Thanks for reporting. The following line does not work ` !empty( (array)$cacheData )`

Context:
```
if(
    $data_ttl > 0 &&
    !empty( (array)$cacheData )
){
    $cacheKey = $this->getCacheKey($dataCacheKeyPrefix);

    if( !is_null($cacheKey) ){
        self::getF3()->set($cacheKey, $cacheData, $data_ttl);
    }
}
````

Do you have a PHP Version <= 5.4.x ? If this is the case, there is a known PHP bug:

http://stackoverflow.com/a/9412313/4415736

Ill fix it!

**Comment by Raykazi** [comment]
I did, i applied the fix to the function and thought i would share it.

    public function updateCacheData($cacheData, $dataCacheKeyPrefix = '', $data_ttl = 300){

        // check if data should be cached
        // and cacheData is not empty
	$arr = (array)$cacheData;
        if(
            $data_ttl > 0 &&
            !empty($arr)
        ){
            $cacheKey = $this->getCacheKey($dataCacheKeyPrefix);

            if( !is_null($cacheKey) ){
                self::getF3()->set($cacheKey, $cacheData, $data_ttl);
            }
        }
    }
