### ISSUE TITLE
Unable to setup tables.

### ISSUE THREAD

**Issue by avree** [exodus4d/pathfinder#540]
When I click "setup tables" for the Pathfinder database, the page refreshes but no tables are created (verifiable my loading the mySQL database). 

With debugging set to 3, there is no related error in the log for mysql, nginx, or pathfinder.

I had previously created a  database with the same name ("pathfinder"), but for certain reasons I needed to delete it and remake it. Upon re-creation, with nothing changed, the app is unable to setup tables.

I suspected some sort of caching issue, but upon clearing /tmp/cache, the problem persisted. 

I have also attempted to change the name of the db to be targeted in environment.ini and the same problem occurs. 

/setup page shows both DBs (pathfinder and SDE db) connecting properly.

**Comment by avree** [comment]
Seems related to #483

**Comment by zmiguel** [comment]
Hi @avree I think I may have found why this happens, on a standard nginx install with php the try_files thing is modified to include the php file&args, that is usually done by simply putting replacing nginx's default with something like this: `try_files $uri $uri/ /index.php?$args;` however, this doesn't seem to work for everything. I then noticed that exodus4d uses a different try_files on his .conf file. so try and replace whatever you have on you try_files in nginx with `try_files $uri $uri/ /index.php?$query_string;`
