### ISSUE TITLE
Wrong statics for J012157

### ISSUE THREAD

**Issue by Ptitlaby** [exodus4d/pathfinder#541]
Listed statics : J244, N110

Correct statics imo : J244, Z060 (Nullsec, not listed in the dropdown menu)

![image](https://user-images.githubusercontent.com/5570178/31762843-ca5aa742-b4bc-11e7-9478-b870e90a4b99.png)

![image](https://user-images.githubusercontent.com/5570178/31762868-e34f19fe-b4bc-11e7-83fb-2d7dcf8cc1ff.png)

Here is everything I scanned down. Only 3 wormholes so far, including a K162 which is leading to a C4 having a C1 static  : this system

![image](https://user-images.githubusercontent.com/5570178/31762907-01bb73a6-b4bd-11e7-8cf2-d1064f9f6ab7.png)

**Comment by exodus4d** [comment]
Thanks for your reporting! Unfortunately I can´t reproduce this on my official installation `v.1.3.0`
Is this a self hosted installation? 

![test](https://user-images.githubusercontent.com/9299033/33808526-4be76a58-dde8-11e7-9706-d5c05840a4f9.png)

**Comment by Ptitlaby** [comment]
Yup, self hosted, may be not the lastest version

2017-12-10 20:26 GMT+01:00 Mark Friedrich <notifications@github.com>:
