### ISSUE TITLE
[Feature Request] Allow discord webhooks aswell as slack

### ISSUE THREAD

**Issue by Busterguy** [exodus4d/pathfinder#547]
With discord being used just as much if not more than slack can you please allow webhooks to discord as well as slack because at the moment it's rejecting the input.
https://i.gyazo.com/5b538c94679e565e35ac2d584f0b41e1.png

Discord already has the ability to accept the slack format by just putting /slack on the end of a discord webhook.
https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

**Comment by srmo** [comment]
I like that idea. What would that enable? How does the interaction with discord look like?

**Comment by Busterguy** [comment]
It would be the same as slack. You can read more at https://discordapp.com/developers/docs/resources/webhook
Just that at the moment if I try to put another webhook in other than slack. it rejects the input.

**Comment by srmo** [comment]
My question was more like, what should the hook do? Do you want to post manually typed messages from pf to discord? What should happen when? Just adding an integration doesn't make much sense without a use case. That's what I'm missing.
I know Slack hooks for things like build or repository integrations, where the hook is used to push notifications about new commits or build results.

**Comment by srmo** [comment]
PS: If I'm just missing that there's already a slack integration for PF and this is to port it to discord, my apologies :)

**Comment by srmo** [comment]
EDIT: deleted my old comments as I just figured that I was totally wrong, i.e. didn't know about the existing slack integration

**Comment by srmo** [comment]
@Busterguy you could experiment by changing the pattern for the URL here:
https://github.com/exodus4d/pathfinder/blob/357e7b887c9884e966b67b62d7c2030f304a8e5d/public/templates/dialog/map.html#L126

The regex prevents you from trying out the discord URLs

**Comment by Busterguy** [comment]
Thanks. I’m not hosting my own at the moment.
But if I do later down the line il definitely try that.
This was mainly a suggestion for the master branch or whatever you call it.

**Comment by exodus4d** [comment]
Thanks for your suggestion. Ill think about that.
In the meantime you can use _Slack_ as a "proxy" .... just use the existing _Slack_ WebHook integration in a "Ghost" Slack channel (e.g. "private" or no users), just the Slack bot to pipe notifications from Pathfinder into Slack. 
Then add an other Slack Integration (I´m sure there is a Discord Integration arround) and proxy all messages from that channel to your Discord.

A bit hakky but it should work ;)

**Comment by aalfath** [comment]
I managed to make Pathfinder work with Discord's webhook using the link provided by @Busterguy 

It involved just 2 small hacks, particularly in the frontend validation mentioned by @srmo and a change the `slackWebHookURL` field in the in `map` table in the DB. Somehow that field was set to store a maximum of 128 characters of string, but apparently the added /slack webhook URL requires 129 chars in total.

However, I'd say that it works really well...

**Comment by DLB82** [comment]
I am interested by an operating procedure to connect a PathFinder hosted by myself & a discord as service.

**Comment by dkrotil** [comment]
Anything new here ? It should be very easy to modify current Slack integration to be able use it for Discord. Now I need to hack into PF, because there are checks, which disallows to safe Discords webhook URL.

**Comment by exodus4d** [comment]
### New feature: _Discord_ integration
#### Here are some WIP screens:

**Discord map settings:**
![rdg0ch4](https://user-images.githubusercontent.com/9299033/34127556-e76e3f0a-e43d-11e7-9d42-8aeec17929ff.png)


**Set rally point dialog:**
![i7jqv65](https://user-images.githubusercontent.com/9299033/34127561-eb50ae78-e43d-11e7-8ac9-8b206408f62e.png)


**Discord:**
![ird5sck](https://user-images.githubusercontent.com/9299033/34127565-eda63d78-e43d-11e7-937d-e7cba428d8ef.png)
