### ISSUE TITLE
The requested URL /setup was not found on this server.

### ISSUE THREAD

**Issue by BlackTigers** [exodus4d/pathfinder#548]
o/,

I just tried to install pathfinder on my root server. To state this out first stuff was cancer as I forgot I hadn't updated PHP to 7 yet but whatever, thats done now, I'm coming to the landing page, the little yellow box sais me setup mode activated so I click on the Setup link and get redirected to /setup (which doesn't work obviously). I have found that the same goes for SSO login. My .htaccess is the standard HTTP one, OS is Debian 8.9 Jessie, PHP Version is 7.0.25 and I'm running Apache 2.4.10 right now. If you need any further information I can give them to you.

Thx in advance

**Comment by exodus4d** [comment]
o/, Looks like #543 is related to your problem.  This is probably a misconfiguration  on your side..
Unfortunately I´m not an _Apache_ expert and all my installations are on _Nginx_ . Feel free to join our _Slack_ chat and ask for someone with an _Apache_ installation: https://github.com/exodus4d/pathfinder/blob/master/README.md
