### ISSUE TITLE
Antivirus triggered by "JSCoinminer Download 6"

### ISSUE THREAD

**Issue by Techiastronamo** [exodus4d/pathfinder#551]
The site occasionally triggers my Norton Anti-virus software, stating that ellatha.com is trying to download "JSCoinminer Download 6". I have not accessed Ellatha at all, only having Pathfinder open. Does pathfinder connect to Ellatha at all, or is this a much deeper problem unrelated to Pathfinder?

**Comment by TrinityErik** [comment]
I'm having users report the same thing on my private instance of Pathfinder.

**Comment by exodus4d** [comment]
Hi, very strange. According to this https://www.symantec.com/security_response/attacksignatures/detail.jsp?asid=30356

**Comment by Techiastronamo** [comment]
I'm using the site, so I haven't installed anything from Pathfinder. Every time I go onto Ellatha for womhole classification based upon wormhole name, it blocks this very download, though I don't have it open while I use pathfinder because pathfinder does this for me.

**Comment by ssgtmccrae** [comment]
https://www.symantec.com/security_response/attacksignatures/detail.jsp?asid=30356

In this case it may be either loaded into one of ellatha's ads or the pages itself (although my digging through elattha's loaded JS sources didn't show anything for coinminer. I would advice using a script blocker (Such as Adblock or NoScript) and reporting to the Ellatha admins if this continues. Can you let us know if it happens on the actual pathfinder site at all?

**Comment by Techiastronamo** [comment]
I'll try out your suggestion as well as contacting the Ellatha admins so they are aware of this issue. It did definitely happen on Pathfinder when Ellatha was not open, but also happened when Ellatha was opened so I assume that if it is fixed on Ellatha it will be fixed on Pathfinder. Since this is a non-pathfinder problem (or rather unfixable by Pathfinder), I will close this issue.
