### ISSUE TITLE
[Feature Request] Adjustable Map Height

### ISSUE THREAD

**Issue by FireFeathers** [exodus4d/pathfinder#553]
I've received a request by the corp to see if I can make the map window taller.  It currently operates with 520px in height usable space.  It's easy to go in and update the CSS to give everyone an extra 200px for a total of 720px in height, but when we drag nodes below the previous 520 limit, they snap back to the previous max.  It's obviously some method within the Javascript, but as it's minimized and much harder to read than the other front end code, so I'm wondering if anyone can give me hints of where to look to set the new max there.

Thank you for any help you can provide!

**Comment by FireFeathers** [comment]
Still investigating and have found these segments that I believe pertain to the operation I'm looking for.
 setPosition: function(e, n) {
                    let i = !1;
                    n.left >= 0 && n.left <= 2300 && (i = !0, e.style.left = n.left + "px"), n.top >= 0 && n.top <= 498 && (i = !0, e.style.top = n.top + "px"), !0 === i && t(e).markAsChanged()
                },
Directly editing the 498 to a higher value doesn't fix the issue, but 498 is the top value adjusted on auto-correcting.
That also contains a constrain method:
constrain: function(t, n) {
                    return function(a, o, s) {
                        return i.hasClass(e.config.mapGridClass) ? {
                            left: t * Math.floor((o[0] + s.left) / t) - o[0],
                            top: n * Math.floor((o[1] + s.top) / n) - o[1]
                        } : s
                    }
Values are obfuscated, but somewhere in this logic is the key to expanding usable space.

**Comment by exodus4d** [comment]
This is now implemented and will be shipped with the next release:

![resize2](https://user-images.githubusercontent.com/9299033/34956595-249b1ce8-fa2a-11e7-94d6-7224fc29e2be.gif)
