### ISSUE TITLE
[Feature Request] Rework route display

### ISSUE THREAD

**Issue by moe-alabel** [exodus4d/pathfinder#555]
Though pretty to look at, the route display is not very usable, or human readable. I cannot easily determine if I have to jump a gate or a worm hole. We need something like https://camo.githubusercontent.com/621bf23fc9006c93ea09d5b3acbdae68d635aa24/687474703a2f2f692e696d6775722e636f6d2f364775543659592e706e67

**Comment by exodus4d** [comment]
I added more information to the routes panel, see #417 (will be shipped with the next release)
