### ISSUE TITLE
Error in controller.php

### ISSUE THREAD

**Issue by Raykazi** [exodus4d/pathfinder#56]
PHP Fatal error:  Can't use method return value in write context in /var/www/app/main/controller/controller.php on line 285
I did some research and it says that it only occurs in PHP 5.5 and lower but i got this while on 5.6.14.

Anyways made the correction.

	$errorCode = $f3->get('ERROR.code');
        if(!empty($errorCode)){
            $f3->status($f3->get('ERROR.code'));
        }

**Comment by exodus4d** [comment]
Thanks for reporting :) Should be fixed in `v0.0.15`.
