### ISSUE TITLE
SSO redirects to homepage but never logs in

### ISSUE THREAD

**Issue by rlayne** [exodus4d/pathfinder#566]
Unlike a similar issue from last year, in my case SSO redirects back to my host successfully in the sense that SSO is correctly configured, but on redirect back to my host, the homepage is exactly as it is prior to trying to log in.  This goes for logging in as admin too.  

In my case, I host on port 8031 in the root directory and have disabled part of the .htaccess to prevent it rewriting 'www'.  Self signed cert is working OK.  PHP version is 7.0 (it did NOT like 7.2 :P) I get lots of errors in the log too but unclear if related:

```
Wed, 20 Dec 2017 16:15:06 +0000 [x.x.x.x] Class "Monolog\Logger" not found. -> Check installed Composer pa...
Wed, 20 Dec 2017 16:15:06 +0000 [x.x.x.x] Class "Exodus4D\ESI\ESI" not found. -> Check installed Composer pa...
```

**Comment by exodus4d** [comment]
You need to run `composer install` on your project root dir, to install those dependencies. See https://github.com/exodus4d/pathfinder/wiki/Installation#4-install-dependencies

**Comment by rlayne** [comment]
@exodus4d cheers - your comment made me look again at composer since I had run it already.  In my case, it installed everything but error'd prior to generating the autoload files.  Fixing a few file perms solved the issue.  Merry xmas!

**Comment by fackir** [comment]
Class "Exodus4D\ESI\ESI" not found. -> Check installed Composer packages
`composer show -i --all`
  cache/adapter-common              1.1.0            
  cache/hierarchical-cache          1.0.0             .
  cache/tag-interop                 1.0.0              
  cache/void-adapter                1.0.0             
  caseyamcl/guzzle_retry_middleware v2.2               
  doctrine/lexer                    v1.0.1            
  egulias/email-validator           2.1.7             
  evenement/evenement               v2.1.0            
  exodus4d/pathfinder_esi           dev-master 
  guzzlehttp/guzzle                 6.3.3              
  guzzlehttp/promises               v1.3.1            
  guzzlehttp/psr7                   1.5.2              
  league/html-to-markdown           4.8.1              
  monolog/monolog                   1.24.0            
  psr/cache                         1.0.1              
  psr/http-message                  1.0.1             
  psr/log                           1.1.0              
  psr/simple-cache                  1.0.1              
  ralouphie/getallheaders           2.0.5              
  react/event-loop                  v0.4.3            
  react/zmq                         v0.3.0            
  swiftmailer/swiftmailer           v6.1.3             
  websoftwares/monolog-zmq-handler  0.2.2 

`root@test:/var/www/pathfinder# composer install`

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

Class "Exodus4D\ESI\ESI" not found. -> Check installed Composer packages

Help!!!!!!!!!!

**Comment by exodus4d** [comment]
please try this:

**Comment by exodus4d** [comment]
Please try this:
1. Clear old `vendor` dir created by previous _Composer_ installations in `/var/www/pathfinder/vendor`:
`/var/www/pathfinder# rm -rf vendor`
2. Reinstall _Composer_ dependencies and make sure to use `composer.json` and **not** the included `composer-dev.json`
`/var/www/pathfinder# set COMPOSER=composer.json && composer install`

**Comment by exodus4d** [comment]
@rlayne Some of the filenames changed from lowercase to uppercase, please make sure it is not a problem with _case sensitive_ file names.
