### ISSUE TITLE
[Feature Request] Ability to see people using PF without being logged in

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#567]
we can currently only see people on the activity window who are logged in and playing eve, but not who else is looking at maps through the browser.
Please list these people as well (somewhere).

**Comment by exodus4d** [comment]
>Important: New feature is only available for installations running beside a *WebSocket* (https://github.com/exodus4d/pathfinder_websocket). For technical reasons the "current active" state of a client (browser window) is just available inside the WebSocket server in real time.

I added some kind of a "traffic light system" that shows all active pilots:
- **first** counter: Pilots active on map
- **second** counter: Pilots active in a system that is **not** mapped
- **third** counter: Pilots **offline** inGame but **online** with a browser.

![7bjh8ap](https://user-images.githubusercontent.com/9299033/38439073-a535755a-39dc-11e8-8f0f-85f360016fbd.png)

The "_activity dialog_" now also shows the additional pilots, even if they are not on a mapped system **or** offline inGame but online with browser. If they are not online inGame there are some "unknown" columns:

![yobx7hi](https://user-images.githubusercontent.com/9299033/38439170-ee4ad37a-39dc-11e8-9202-53c3c94a591d.png)
