### ISSUE TITLE
[Feature Request] Autoselect New System

### ISSUE THREAD

**Issue by jajmo** [exodus4d/pathfinder#569]
It would be nice if Pathfinder automatically selected the system I jumped into. I understand that this has been discussed in the past, and it could possibly be annoying having the info panel reload on each jump, but it would be nice if this was a toggleable option.

When exploring, it's much nicer if the system automatically selected itself instead of me having to click it.

**Comment by jajmo** [comment]
Are there any plans to implement this @exodus4d ?

**Comment by exodus4d** [comment]
@jajmo Thanks for pushing up this Issue, I forgot about it :(
I´ll try to implement a "WIP" checkbox where users can active this option. But I have to say, that it will be just a "test" to see how much this will increase the server load.  I fear that most of the users don´n have _Pathfinder_ open all the time and reloading system information in the background is not relevant to all of them. 
If I see any issues with too many server requests that slow down the app, we have to think about other solutions, e.g. limit this feature to w-space jumps only....

**Comment by jajmo** [comment]
I don't mean all the time. I mean have it auto select the new system when they have it open, and when they have the checkbox selected.

**Comment by exodus4d** [comment]
### Implemented: "Autoselect current location" option [beta]
- New _checkbox_ added to "Account settings" dialog. This feature can be _enabled_ for current user character (default: disabled). "Auto select current location":

![r7wfbja](https://user-images.githubusercontent.com/9299033/50027092-5ac41f00-ffeb-11e8-897b-2cf63d78f47a.png)

- There is a _global_ on/off feature toggle added for this in `pathfinder.ini`, _overwrites_ character specific values.
  ```
  [PATHFINDER.CHARACTER]
  AUTO_LOCATION_SELECT        =   1
  ```

#### How it works:
- If feature enabled in `pathfinder.ini` **and** in "Account settings" dialog, mapped systems become **auto selected/loaded**  on system change/jump.
- "Autoselect location" is prevented if...
  - ... any modal open
  - ... system "description" editor is active
  - ... any form element (e.g. input, select,...) is active/focus in one of the current open system panels (e.g. in "signature table", system alias input,...)
