### ISSUE TITLE
Import/Export of maps

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#57]
With the growing number of external installations of Pathfinder, i would like to add an *Import/Export* feature for maps.

Features:
- Maps can be exported and downloaded.
 - Map data is downloaded as a `*.json` file (map, system, connection data)
 - Signatue data will not be exported
 - The user can set the name for the JSON file
- Maps can be imported
 - The user can select a JSON file for map import
 - The user can choose a map name and a map scope (private, corporation, ally) for the new map

With this feature, we can build up a "map library" like "Dotlan" with pre-saved k-space maps that can be imported

![export](https://cloud.githubusercontent.com/assets/9299033/10890456/4aba73d6-8198-11e5-931d-e2a43585ac66.png)
 for PvP-roams or PvE-Ops.

**Comment by Zumochi** [comment]
Great! Eve w-space added it not that long ago and I find it very useful.

**Comment by exodus4d** [comment]
Feature done :)

#### Map export
- Any map can be exported/downloaded as a *.json file
- The default filename for this file `[mapName][data].json`
- The name can be changed before exporting

#### Map import
- The `mapType` can be set before import (a "private" map export can imported as "corporation" or "alliancy" maps as well, ...)
-  Map files can be choosen for upload
- Alternatively the user can drag&drop valid files right into the "dropZone" area

#### Hint
- Feature just workes in out of game browser of course :) (dialog tab is "gray" in IGB)
- Feature requires some HTML5 APIs ( `FileReader`, `Drag&Drop`)
- No "save" button on this tab, dialog stays open after in/export action is finished. So you can drag&drop multiple files after each other...

#### Future plans
- Add some k-Space region maps to this project
- Add a "Select" with this maps to the "import" section. So users dont have to create this "fix" maps.


![export](https://cloud.githubusercontent.com/assets/9299033/11046118/c9d002a6-872b-11e5-971e-cbf551473c43.png)

**Comment by exodus4d** [comment]
Video: https://www.youtube.com/watch?v=PVyX_Xzt2Bg
