### ISSUE TITLE
[Enhancement] Prevent system overlapping

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#570]
**Problem:** When a new system is added to a map, either by `richt click` a system and choose `add system` **or** `richt click` the map and choose `add system`. The new system could get placed on top of other systems and overlap.

**Solution:**  I implemented a 2D collision detection that scans the surrounding area for empty space where the new system fits in. 
This demonstrates how it works:

![overlapping](https://user-images.githubusercontent.com/9299033/34313979-cc8f674c-e76f-11e7-83e4-f1d80646bb4d.gif)

**Comment by mrurb** [comment]
Is it possible to get this added as a global setting on a map, but only on system being added and not moved?
