### ISSUE TITLE
ERROR 502: Bad Gateway

### ISSUE THREAD

**Issue by levialex** [exodus4d/pathfinder#575]
Howdy folks!

I'm looking for some help with an issue that I currently have with Pathfinder.

Every time I try to log in with my account, I get the following error: http://prntscr.com/hx6n0c

If I just press "Restart", the page reloads, I log in again, and I get the very same error again, and again and again, no matter how many times I try this.

Is there any way to fix this issue?

Thank you!

**Comment by dkrotil** [comment]
We need more information about your setup, Nginx ? Reverse proxy setup ? Etc.

**Comment by exodus4d** [comment]
@levialex is this an issue with a self hosted version of _Pathfinder_ or with the official installation?
if it is on the official https://www.pathfinder-w.space server could you please give us the following information? - 
- Name of the character?
- Anything special about that character? Have you recently bought that character?
- Browser name?

Thanks.

**Comment by levialex** [comment]
I'm encountering this issue on a self hosted version. It is most likely held by Goonfleet and the version v1.3.1GSF1.
There's nothing special in regards to this character. I've been using it for almost 6 years now.
I'm trying to run it through the latest and fully updated version of Firefox.

**Comment by dkrotil** [comment]
@levialex we can´t help you, because we don´t have access to that self hosted Pathfinder to find out, what´s the problem is. Ask admin of that PF to look on your problem. He can contact us for sure.

**Comment by exodus4d** [comment]
@levialex , as @dkrotil already said. We can´t provide support for self hosted installations without having deeper knowledge about the setup/server.
- If there is something buggy and reproducible on the public installation please let us know. 
- If you can get more information about the server setup regarding your issue please let us know.
