### ISSUE TITLE
Screen Issues (IE based)

### ISSUE THREAD

**Issue by Ryisaa** [exodus4d/pathfinder#576]
Good Evening,

Have had this issue for a while now. Old issues usually fixed itself with the new patch. Every time I log on, screen is just jumbled, and when I make changes no one else seems to see them.

![image](https://user-images.githubusercontent.com/35585000/35130838-c92bc0f6-fc77-11e7-8564-90f2730e7a66.png)

I'm going to guess its IE based, but is there an easy fix?

Cheers
Ryisaa

**Comment by w9jds** [comment]
This isn't IE based, this is Edge, which is completely different code based and renders more like chrome than anything else.

**Comment by exodus4d** [comment]
Don´t use IE or Edge. They are not supported and will not get any support in future. 
-> Check the FAQ section on the _login_ page
Take Chrome or Firefox.
