### ISSUE TITLE
Codebase incompatible with nginx

### ISSUE THREAD

**Issue by andrewmunro** [exodus4d/pathfinder#58]
The issue can be found at https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/controller.php#L178

The use of `apache_get_headers` is not available when running php-fpm under nginx (obviously). To get around this, I added the following code:

```
// apache_request_headers replicement for nginx
if (!function_exists('apache_request_headers')) { 
        function apache_request_headers() { 
            foreach($_SERVER as $key=>$value) { 
                if (substr($key,0,5)=="HTTP_") { 
                    $key=str_replace(" ","-",ucwords(strtolower(str_replace("_"," ",substr($key,5))))); 
                    $out[$key]=$value; 
                }else{
                    $out[$key]=$value; 
		}
            } 
            return $out; 
        } 
}
```

I'm sure there may be a better solution, but this got me up and running quickly.

**Comment by Zumochi** [comment]
apache_fpm? Do you mean php-fpm or?

It seems like a good idea to try and make the application webserver independent :)

**Comment by andrewmunro** [comment]
Yes, sorry I did mean php-fpm.

**Comment by exodus4d** [comment]
Thanks, your fallback unfortunatelly is not working for me (Apache). I can access all Header Data by `$_SERVER` but i didn´t receive and EVE specific headers, even if the page is *trusted*.
I have absolute no idea why.... :(

Therefore, your fix will be executed in case that `apache_request_headers()` does not exist.

**Comment by andrewmunro** [comment]
@exodus4d Yeah I never tested on apache, my bad :(

It probably explains why all the code snippets wrap it in `if (!function_exists('getallheaders'))`.
