### ISSUE TITLE
[feature request] dump connections into local file

### ISSUE THREAD

**Issue by Solid-State-Society** [exodus4d/pathfinder#580]
I was searching through the code to find a way to extract connection data to save it locally and plot routes with it using other information, as well as

using it as a source to auto generate bookmark names

but I could not find it.
Would it be possible to implement such?

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #274
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
