### ISSUE TITLE
[V1.3.2] HTTP 500 on Login

### ISSUE THREAD

**Issue by ddavaham** [exodus4d/pathfinder#581]
I know it is the middle of the morning (EST) and I need to get to bed but I just upgrade ESI from 1.3.0 => 1.3.2 & also did a clean install. When I log in with my main, I received following and I can't get around it

https://i.imgur.com/QuCvUVm.jpg

I checked the console and I see this

`VM679:1 GET https://map.deadsunsrising.rocks/api/map/init 500 ()`

I turned on Debug mode and this did not return any output. Same message as the linked image.

Like I said I need to go to bed, but could somebody please ping me with ideas so I can review them when I wake up in the morning

This is very similar to https://github.com/exodus4d/pathfinder/issues/421 but this was closed as not being reproducible. 

Thanks. If I don't have any feedback when I wake up ill create an issue on Github in the morning

> exodus4d [3:57 PM]
@ddavaham please check your php error.log and copy here what you get, please.

```
[Wed Feb 21 00:47:31.153466 2018] [:error] [pid 9998] [client 108.162.237.53:30491] Call to a member function getData() on boolean [/var/www/prod/pathfinder/app/main/controller/api/map.php:169], referer: https://map.deadsunsrising.rocks/map
[Wed Feb 21 00:47:31.153560 2018] [:error] [pid 9998] [client 108.162.237.53:30491] [index.php:23] Base->run(), referer: https://map.deadsunsrising.rocks/map
```

So yeah, I have no clue what is going on here. Let me know what to fix because we cannot even sign into the application. I will delete and do a clean install of v1.3.1 when I get home tonight if you think that will work but we were really excited about the Discord Integration

**Comment by ddavaham** [comment]
I did I clean install of v1.3.1 and received the same error message. I am trying 1.3.0 right now

**Comment by ddavaham** [comment]
v1.3.0 is working now.

**Comment by dkrotil** [comment]
Looks like, there is something to old, when older version is working.

**Comment by ddavaham** [comment]
For anybody who comes along and sees this after upgrading. I was misunderstanding requirement of building the index data at the bottom of the `/setup` page due to the terminology used. Once I clicked on `build` followed by clicking on each of the `import` buttons, I was able to login and create a map and restore my production server to the latest version. 

https://i.imgur.com/S6AMWNf.png
