### ISSUE TITLE
Remember Map resize

### ISSUE THREAD

**Issue by moe-alabel** [exodus4d/pathfinder#585]
Please make it so that my selected map size is persistent across logins. I keep having to reseize the map on each login

**Comment by FireFeathers** [comment]
As an additional recommendation on this, make the map size able to be set by the map admin, so that all users see it in the same size by default.

**Comment by exodus4d** [comment]
Map size should be persistent. I mean the real "size" of the map is equal for all users, its just the "visible"  part of the map that is "resizable". 
But even this is persistent and stored per map and per character.  So your character and someone else who has map access can have different "visible" area stored for their characters for the *same* map.

If this is not working for you please give us some more information e.g. Browser version. Resize and size storage is a "client side feature".

**Comment by exodus4d** [comment]
#### Oh I missed something to comment in #553

I implemented a "_bleeding edge_" Javascript API called [ _ResizeObserver()_](https://wicg.github.io/ResizeObserver/#api)
- Chrome implemented that API in v64 (which is the current stable release). 
- Other browsers **do not support** that API *yet* but _Edge_ and _Firefox_ are currently implementing this on their browsers. see https://caniuse.com/#feat=resizeobserver

I´ll work on a _polyfill_ implementation for those browser that don´t support this API yet.

- You can check if your browser support that API [here](https://googlechrome.github.io/samples/resizeobserver/)
- You can find my implementation of that API [here](https://github.com/exodus4d/pathfinder/blob/master/js/app/map/map.js#L953)
- Google blog: "[_New in Chrome v64_](https://developers.google.com/web/updates/2018/01/nic64)"
