### ISSUE TITLE
Issues using app with MySQL

### ISSUE THREAD

**Issue by andrewmunro** [exodus4d/pathfinder#59]
I have been working on various scripts to get this project running in a docker container. You can find my progress at https://github.com/andrewmunro/pathfinder-docker. Eventually I was going to create a pull request to this repo if you feel it's relevant.

Anyway, upon running the project, I had various issues with the databases running in MySQL 5.7.9. Firstly, the eve database table names pulled from https://www.fuzzwork.co.uk/dump/mysql-latest.tar.bz2 are named differently, it seems that pathfinder uses the lowercase version to retrieve them:

- `invtypes (is actually `invTypes`)
- `mapconstellations` (is actually `mapConstellations`)
- `mapdenormalize` (is actually `mapDenormalize`)
- `maplocationwormholeclasses` (is actually `mapLocationWormholeClasses`)
- `mapregions` (is actually `mapRegions)
- `mapsolarsystems` (is actually `mapSolarSystems`)

I had to manually rename these tables to get the app working correctly :-1: 

Secondly, I had various errors by incorrect or undefined default values:

* In table `system`, columns `effect`, `security`, `constellation`, `region`, `name`, `description` and `alias`, are set to `NOT NULL` but no default values were set causing PHP errors.
  * Adding `DEFAULT ''` to the sql to generate these columns fixed this.
* In table `user`, column `lastLogin`, the default value is incorrect
  * Because the column type is `timestamp`, I had to change the value `0000-00-00 00:00:00` to `1970-01-01 00:00:00`

**Comment by Zumochi** [comment]
Yeah, I commented about this a few days ago. See #50.

**Comment by andrewmunro** [comment]
Right, Ill work on creating a fix for the SQL when I get home and create a pull request.

**Comment by exodus4d** [comment]
@andrewmunro thanks for reporting!

Table names will be fixed in `v0.0.15` I don´t need a pull request for this

I´ll check the default values as well. But if you want, you could add your fixed SQL dump in this issue, then I can compare your changes with my changes. So I don´t forget anything :)

**Comment by andrewmunro** [comment]
@exodus4d Will do! o/

**Comment by exodus4d** [comment]
Table names are now back to "normal" (camelCase) in `v.0.0.15`
