### ISSUE TITLE
Pathfinder slack

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#592]
In @exodus4d mentioned that 
> If you have update problems, feel free to ask in our dev-chat: [#Slack](https://pathfinder-eve-online.slack.com/)

But to create an account on that slack you need an, '@vivace.io' email.

Can i suggest that you either open it up to all emails or that we use [Tweetfleet](https://tweetfleet.slack.com/) and then create a channel in there for pathfinder. Since a lot of Eve online people are already on the tweetfleet slack it might make it easier.

**Comment by exodus4d** [comment]
@mrurb What do you mean with  '@vivace.io' email? You can mail me for an invite to our Slack pathfinder@exodus4d.de

The problem I have with a Tweetfleet channel is, that I don´t have control about who is joining. The Pathfinder slack is primary for admins/developers who have their own installation of Pathfinder hosted and/or need some help.
