### ISSUE TITLE
Feature request: Allow background image to be toggleable

### ISSUE THREAD

**Issue by bewbaloo** [exodus4d/pathfinder#598]
Just a tiny feature that would make the whole interface a bit more readable: an option to disable the
background picture (https://www.pathfinder-w.space/public/img/pf-bg.jpg).

The site's design has some colour-contrast issues (lots of light text on grey backdrops with translucent elements), but this image in-particular makes it really hard to see some things :\  It's easy to get around with a browser extension like Stylish, but a built-in option would be awesome.

**Comment by exodus4d** [comment]
Agree, with the new resizable map and content elements, some areas have contrast issue. I removed the BG  maybe I´ll look for a neutral image in future.
