### ISSUE TITLE
wishlist: new data entry form for citadels

### ISSUE THREAD

**Issue by Raltry** [exodus4d/pathfinder#601]
Lets be honest: scanning sigs and jumping holes is all fine - but in the end we all want to kill each other. So the information is vital, who is "the owner" of a WH system and what are his citadels. I would wish there is a possibility to add the owner corp/ally in a stylish way to pathfinder (perhaps even with an drop down list while your are typing - like zKB) 

And the same goes for the owner's citadels (dropdownlist with the types, some additional info - perhaps timer???). 
As there is typicaly only 1 corp/ally local in a wh it would be cool if that local/locals is/are shown highlighted (if already entered earlier)

**Comment by tralafiti** [comment]
We are missing a feature like this, too. We tend to use the system description textarea for this, but it would be great if you could one/many corps to a systems (search box as you described). With this formalized habitation info we could link directly to the z-kill of this corp, display there member-count, add a direct link to the in-game info-panel etc...

Maybe I will have a look at the corresponding code when I find time for it

**Comment by exodus4d** [comment]
@Raltry Thanks for your suggestion. There is already an Issue open for "Citadel tracking", see https://github.com/exodus4d/pathfinder/issues/246#issuecomment-385787638

This feature will come with the next release.
