### ISSUE TITLE
Less jumpy map systems with inline static info

### ISSUE THREAD

**Issue by tralafiti** [exodus4d/pathfinder#607]
Hey,

my wh-corp decided to ditch our old mapping system _J-Sig_ which we wrote years ago in favor of your great pathfinder as a solid modern framework for many more years of hunting in j-space :) 

After a few days we found the map to be a bit too busy for our taste with its animations, constantly moving systems when someone travels through and (sometimes buggy) active pilot tooltip. We feel that with a fixed system width and height in combination with a move of the active pilot list into a popover, we are able to "analyze" the map at a quick glance way easier.
In addition we wanted to provide our scouts and scanners with important information, so I added the statics to the map and added signature strength in their popover.
Since we like the grid snapping to keep everything tidy but are quite distracted by the grid-line-visuals we lowered there opacity a bit.

Preview:
![preview](https://user-images.githubusercontent.com/197687/38174891-8fee9f48-35d4-11e8-94a2-41b5db8b3296.PNG)

How do you feel about these changes? Any chance that you will pull them into the main line (with some modifications perhaps?) or are we "doomed" to keep using a fork? :)

**Comment by tralafiti** [comment]
It's all in the PR #604, but I didn't include a pre-build version to circumvent merge conflicts. 

If you want to check it out **right now** you would need to pull my branch and build it as described in https://github.com/exodus4d/pathfinder/wiki/Build-process

Or wait a few more days for a reply from @exodus4d :) I don't want to release a modified version without at least hearing from the creator of this awesome tool.

**Comment by WildStrawberryEVE** [comment]
I would suggest getting online on PF's slack for more attention :)
