### ISSUE TITLE
Impossible to log in

### ISSUE THREAD

**Issue by Sakamotochaton** [exodus4d/pathfinder#615]
Oï !
I was introduced to this website this morning and I must admit it looks as good as the design is beautiful.
There's a problem though, I managed to log in three of my characters this morning, but during the day they were disconnected, and now I can't even log in one. Is there someone able to help me please ?
Thanks in advance =)

**Comment by jajmo** [comment]
ESI has been having problems the last few days.

Perhaps it's related to that.

**Comment by exodus4d** [comment]
Yeah as @jajmo said, CCP had hard problems with ESI and DDOS attacks over the last 2 weeks, The last few days seems to be more stable. _Pathfinder_ heavily depends on stable _ESI_ API.

Do you still have login problems?
