### ISSUE TITLE
System count HTML bug

### ISSUE THREAD

**Issue by wickex** [exodus4d/pathfinder#617]
Hey,

Occasionally, we experience a small bug in Pathfinder. What happens is that the 'system count', the little annotation above the system that shows the number of pilots in that system, bugs out and displays raw HTML instead. Mousing over and then moving the mouse off of the system removes the annotation. I'm not sure what causes it and can't reliably reproduce it, but it always happens at some point if you leave Pathfinder open long enough.

I've attached a screenshot. Let me know if you need any other information.

![chrome_2018-04-25_20-47-16](https://user-images.githubusercontent.com/4346246/39266802-57d14fd4-48cb-11e8-97c2-d44b24a7dd5a.png)

**Comment by exodus4d** [comment]
I _hope_ this will be fixed with the next release, I made some changes to that and I can´t reproduce it on my current develop branch.
