### ISSUE TITLE
post login Error - 500

### ISSUE THREAD

**Issue by Ordo-Vhett** [exodus4d/pathfinder#626]
![error](https://user-images.githubusercontent.com/28077119/40028436-c8677d46-57ac-11e8-90ee-4937ea52271c.jpg)

New users (Those not already in DB) get this error upon logging in. before it was issuing a corporation whitelist error. so i temp disabled the whitelist. Now this is the error. I have dropped 'fk_character___roleid___role__id'  and added it back via Fix Column/Keys in /Setup.
'role' table has entries for ID's 1,2,and 3. so from what i understand from the error PF is trying to set an ID not in that table. I get nothing in the Logs even on debug 3. any help would be appreciated

**Comment by exodus4d** [comment]
I guess you upgraded from `1.3.2` please read the upgrade steps (you missed point **5.**)
https://github.com/exodus4d/pathfinder/releases/tag/v1.3.3
