### ISSUE TITLE
Websocket issue

### ISSUE THREAD

**Issue by snicker1968** [exodus4d/pathfinder#627]
I made a fresh Installation of Pathfinder.
When I want to log me in via SSO there is no map. I can only see the start page again.
Sorry for my questions, I am a beginner.

nginx_error.log:

22018/05/17 20:21:06 [error] 31538#31538: *3310 FastCGI sent in stderr: "PHP message: HTTP 404 (GET /ws/map/update)

Is this perhaps the same issue?
https://github.com/exodus4d/pathfinder/commit/948c9ca829c98d3987baaf3b2227ee8f3e88adf2

Also my websocket is not working. I got no error messages, when I installed it with composer.

Here my screenshot after starting the websocket:

![grafik](https://user-images.githubusercontent.com/39315447/40202897-c49aefc6-5a23-11e8-982a-061c6a3df458.png)

![unbenannt](https://user-images.githubusercontent.com/39315447/40202459-55b0b1be-5a22-11e8-9450-03b8948c8f16.png)

**Comment by snicker1968** [comment]
A little update. 
Now I can log me in.
Was a redirection failure in my vhost.conf

**Comment by snicker1968** [comment]
I need some additional Information about some errors, I dont't understand.

esi_error_client_log:
`Sat, 26 May 2018 07:13:43 +0000 [95.91.237.243] HTTP 404: 'Not Found' | url: GET 'https://esi.tech.ccp.is/v1/route/31002505/30001770/?datasource=tranquility' | body: stdClass Object
(
    [error] => No route found`

websocket error.log:

`PHP Notice:  Undefined offset: 1 in .../pathfinder_websocket/app/Main/MapUpdate.php on line 363`

Do I have to insert some CCP_ESI_SCOPES_ADMIN in environment.ini ?

**Comment by exodus4d** [comment]
NO you don´t need to fill  CCP_ESI_SCOPES_ADMIN .
It looks like your _Composer_ dependencies are not up2date. _Pathfinder_ complains about a missing _ESI_ API route. This route was added with one of the last releases. Delete your `/vendor` dir and run `composer install` again this should re install all dependencies
