### ISSUE TITLE
[Feature] UI improvement - less scrolling - more condensed signatures panel.

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#629]
Forwarding my fellow corporation member suggestion:

I would like to give into your attention the following UX/UI improvement.
Image below shows current UI (RED) and suggested (GREEN).

![image](https://user-images.githubusercontent.com/20519150/40258047-90ddd89c-5af0-11e8-8efb-b7681556c199.png)

Around 20% of vertical line is wasted. This force users to scroll down more often.
I hope you find it useful and easy to implement (via CSS?).

Regards,
Woby Kansene

**Comment by exodus4d** [comment]
Good point! I´ll move the buttons up.
Pagination dd and search field can´t be changed, they are auto generated by a 3rd party JS lib :(

**Comment by exodus4d** [comment]
#### Changes:
- Buttons are now split up in to **two** _groups_. 
  - **Module** related actions (e.g. "_show signature reader dialog_") moved to the top right of the signature module 
  - **Table** related actions (e.g. "_select all rows_") moved to the table toolbar
- **Table** related actions are now **inline** with the search `<input>` (no extra row)
- **Progress bar** moved to the modules head (no extra row)

#### Total height is reduced by **85px** (before/after):
![signature_module_height](https://user-images.githubusercontent.com/9299033/43657636-b1fb4bb6-9756-11e8-8be5-192b07b485fd.png)

#### Active "toggle" button for new signature:
![signature_module_add](https://user-images.githubusercontent.com/9299033/43657678-cbe32490-9756-11e8-9880-408e24ee1b00.png)

#### In action:
![signature_module_height2](https://user-images.githubusercontent.com/9299033/43657703-db0e0f48-9756-11e8-9db7-50715aa81f50.gif)
