### ISSUE TITLE
Unable to load index.php server 500 "PHP Fatal error:  Invalid class Controller\\Controller"

### ISSUE THREAD

**Issue by phneak** [exodus4d/pathfinder#63]
I'm trying to setup pathfinder on my debian box and have databases configured and apache2 all going, but I get an ambiguous error when attempting to load the index.php page in my apache logs:

`mkdir(): Permission denied
PHP Fatal error:  Invalid class Controller\\Controller in ~/pathfinder/pathfinder/app/lib/base.php on line 1598`

Any ideas?  I did not see a specific bug issue on the git tracker.

`# php -v
PHP 5.6.14-1+b1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies`

I have run a recent apt-get update / upgrade so everything should be current for Debian Sid

**Comment by phneak** [comment]
I updated permissions to 777 for entire pathfinder directory and accessed the site again.  I am getting a different error now (presumably because the call to mkdir() was fufilled)

` HTTP 404 (GET /)
PHP Fatal error:  Call to a member function exec() on null in /var/www/phneak.net/htdocs/pathfinder/pathfinder/app/main/db/database.php on line 55
Fatal error: Call to a member function exec() on null`

Any idears?

**Comment by exodus4d** [comment]
yeah, the DB connect was not successful. One of the two required DBs can not be accessed :)

**Comment by phneak** [comment]
Looks like I fixed the listining host issue on mysql

new errors are good?!
`HTTP 404 (GET /)
[pathfinder/pathfinder/app/lib/base.php:1518] Base->error(404)
[pathfinder/pathfinder/index.php:29] Base->run()`

I turned debugging up to 3

**Comment by Zumochi** [comment]
Also please don't use 777... That's painful and Super insecure.

**Comment by phneak** [comment]
I removed the files on disk and cloned repo again, but still had to give write permissions to tmp/ directory to get to most recent error.  It seems that the URL is not being recognized as "allowed" and does not render the rest of the page.

@Zumochi any Super ideas?

**Comment by Zumochi** [comment]
After cloning, did you chown the project as the web server user?

Just to confirm, you have a database for Pathfinder and a separate database for EVE's SDE?

Note my experience with apache2 is very limited, haven't actively used it for years.

Is the project in the root of the virtualhost? Did you change the configuration files to reflext host/port/path?

**Comment by phneak** [comment]
chown -R www-data:www-data pathfinder/ has been done

2 MySQL imports to 2 separate databses (parallax and pathfinder) and user has been granted full privileges to each

The project is in a subdirectory "pathfinder" of the virtual host and pathfinder.ini has been updated to point to the base directory and URL that should be used

**Comment by Quarky9** [comment]
Had similar issues due to the sub-directory ... give https://github.com/exodus4d/pathfinder/pull/87 a try.

**Comment by phneak** [comment]
Restarted with 1.0RC and could not replicate this issue
