### ISSUE TITLE
Abyssal space == Error 500

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#630]
When users enter Abyssal space, Pathfinder kicks them out with error 500.

2018/05/29 20:55:51 [error] 26292#26292: *2106269 FastCGI sent in stderr: "PHP message: SystemId "32000091"" does not exist in EVE!
PHP message: [app/main/model/mapmodel.php:485] Base->error()
PHP message: [app/main/controller/api/map.php:948] Model\MapModel->getNewSystem()
PHP message: [app/main/controller/api/map.php:850] Controller\Api\Map->updateMapData()
PHP message: [app/lib/base.php:1806] Controller\Api\Map->updateUserData()
PHP message: [app/lib/base.php:1627] Base->call()
PHP message: [index.php:23] Base->run()
PHP message: Call to a member function setActive() on null [/var/www/pathfinder_v1.3.4-t/app/main/model/mapmodel.php:489]
PHP message: [app/main/controller/api/map.php:948] Model\MapModel->getNewSystem(32000091)
PHP message: [app/main/controller/api/map.php:850] Controller\Api\Map->updateMapData(ModelCharacterModel::__set_state([]),ModelMapModel::__set_state([]))
PHP message: [app/lib/base.php:1806] Controller\Api\Map->updateUserData(Base::__set_state(['hive'=>['HEADERS'=>['Content-Length'=>'45','Content-Type'=>'application/x-www-form-urlencoded; charset=UTF-8','Cookie'=>'cookie=1; pathfinder_ses
sion=XXXXudobh4mn65ko9qinq2io; pathfinder_session=XXXXudobh4mn65ko9qinq2io; char_xxxxxf6bcb26de7c0e9b10f3c937aa2=xxxx4c99a6e49b87bdedfa0d4%3A0dd6dxxxxxb856ceb5dd9893f93a54963','Dnt'=>'1','X-Requested-With'=>'XMLHttpRequest','Pf-Charac
ter'=>'XXXX658940','Referer'=>'https://pf.ap0.space/map/XX%3X%3X','Accept-Encoding'=>'gzip, deflate, br','Accept-Language'=>'pl,en-US;q=0.7,en;q=0.3','Accept'=>'application/json, text/javascript, */*; q=0.01','User-Agent'=>'Mozilla/5.0 (
Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0','Host'=>'pf.ap0.space'],'LANGUAGE'=>'en-US,en','AGENT'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0','AJAX'=>true,'ALIAS'=>NULL,'ALIAS
ES'=>['setup'=>'/setup','login'=>'/','sso'=>'/sso/@action','map'=>'/map*...
PHP message: [app/main/controller/api/map.php:948] Model\MapModel->getNewSystem()
PHP message: [app/main/controller/api/map.php:850

**Comment by exodus4d** [comment]
Thanks for reporting! This will be fixed with #631
