### ISSUE TITLE
Upgrade 1.3.4 to 1.3.5 - Alter table foreignKey "structure" KO

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#637]
Hi,

When I upgrade from 1.3.4 to 1.3.5, this request is KO (Error 500 in setup).
> alter table corporation_structure add CONSTRAINT fk_corporation_structure___structureId___structure___Id FOREIGN KEY (structureId) REFERENCES structure(id) on DELETE CASCADE on UPDATE RESTRICT;

When I try to execute this query in MySQL, I have this return:
> #1215 - Cannot add foreign key constraint

I note : 
- structureId in corporation_structure is an integer(11)
- id in structure is a bigInteger(20)
- corporation_structure table is actually empty
- structure table contains data

I don't know if this error is normal.

Have you an idea to resolve this issue?

Thanks a lot.

![setup](https://user-images.githubusercontent.com/24720730/41354336-061c27e8-6f1f-11e8-9a58-6178b2fab0f7.jpg)

**Comment by exodus4d** [comment]
@DLB82 The interesting part is: Why is "id in structure a bigInteger(20)" ? There is no "special" implementation in the `structuremodel.php" which is responsible for the table schema of  "structure" table? Can you try to convert that id into integer(11) manually (then delete cache because table schema is cached) and then retry the "setup tables" button?

**Comment by DLB82** [comment]
Problem with lazy update from dscan now.
I think it's better to update structureId in corporation_structure as an bigint(20). I try this solution.

**Comment by DLB82** [comment]
> [Sat Jun 16 17:24:22.951531 2018] [:error] [pid 9538] [client 79.94.114.126:49466] SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value [/opt/pathfinder.v1.3.5/app/lib/db/sql.php:226], referer: ...

**Comment by DLB82** [comment]
Not a problem of type ^^

**Comment by DLB82** [comment]
> ALTER TABLE structure MODIFY id INT(11) NOT NULL AUTO_INCREMENT, ADD INDEX (id)

Before, remove constraint and after recreate foreign key.
Issue solved.
