### ISSUE TITLE
Tracking doesn't work when using WebSockets

### ISSUE THREAD

**Issue by jajmo** [exodus4d/pathfinder#642]
**Expected behavior**
Active users are tracked and their locations are displayed on the map when they have tracking enabled.

**Actual behavior**
When using WebSockets, the locations are tracked properly (confirmed in the database), but the locations are not displayed on the map. When using Ajax, this is not an issue.

**Notes**
There are no error messages or anything suspicious in the logfiles.

**Comment by wickex** [comment]
I've had the same issue since updating to 1.3.5 and have had to fall back to AJAX since. Composer dependencies are updated. Logfiles don't show anything strange either.

**Comment by exodus4d** [comment]
@jajmo @wickex Let´s see if I can help you guys
First of,  i can say that I spend some time with trying to reproduce your issues, without success. Check out my test cases at the end of this post. Maybe I missed a case.

1. Just to make sure we are talking about the same code base:
    1. You have a working instance of _Pathinder_ `1.3.5`
    2. Check your installed _Composer_ dependencies for the _Pathfinder_ (main) project. In project root run:
    `$ composer show` gives you the installed dependencies:
    ```
    doctrine/lexer                   v1.0.1
    egulias/email-validator          2.1.4
    evenement/evenement              v2.1.0
    exodus4d/pathfinder_esi          dev-master a9b7706 ESI API library for Pat...
    monolog/monolog                  1.23.0 
    psr/log                          1.0.2
    react/event-loop                 v0.4.3 
    react/zmq                        v0.3.0 
    swiftmailer/swiftmailer          v6.0.2
    websoftwares/monolog-zmq-handler 0.2.2 
    ```
    **a9b7706** is **important**! This is the current stable `pathfinder_esi` dependency [`v1.2.4`](https://github.com/exodus4d/pathfinder_esi/releases/tag/v1.2.4)
    3. Make sure you have the current stable release checked out of the [pathfinder_websocket](https://github.com/exodus4d/pathfinder_websocket) project which is: [**`v1.1.1`**](https://github.com/exodus4d/pathfinder_websocket/releases/tag/v1.1.1)
    3. Check your installed _Composer_ dependencies for the [pathfinder_websocket](https://github.com/exodus4d/pathfinder_websocket) project. In project root run:
        `$ composer show` gives you the installed dependencies:
    ```
    cboden/ratchet            v0.4.1
    evenement/evenement       v2.1.0
    guzzlehttp/psr7           1.4.2
    psr/http-message          1.0.1
    ratchet/rfc6455           v0.2.3
    react/cache               v0.4.2
    react/dns                 v0.4.13
    react/event-loop          v0.4.3
    react/promise             v2.5.1
    react/promise-timer       v1.2.1
    react/socket              v0.8.1
    react/stream              v0.7.7 
    react/zmq                 v0.3.0 
    symfony/http-foundation   v4.0.8
    symfony/polyfill-mbstring v1.7.0
    symfony/routing           v4.0.8
    ```
    > **Important:** If you upgraded the websocket project, you **need** to restart the WebSocket server in order to _use_ the updated PHP files! -> restart the `php cmd.php` file.

    > **Hint:**  I recommend to wrap that `php cmd.php` commant into a  service that takes over control and restarts the server in case of error/failure. It´s even nicer to start the process like `systemctl start websocket.pathfinder.service`, or something like this.

2. Start/restart the WebSocket server. 
3. Start your ChromeBrowser und log into Pathinfer
4. Check if connection Type is "Websocket"
5. You should also visit your `/setup` page and check if the WebSocket test connection is fine (green hint)

#### This is what I tested:
1. 2 different users (characters) on two different Browsers (Chrome and Firefox)....
    1. .... share the same **private** map
    2. .... share the same **corporation** map
2. Logged into EVE with one of the chars, and jumped between systems (I tested with "stargates" (k-space) connections).
3. Both characters have **enabled** location tracking (left menu -> "Account" -> "character")
4. Both chars have the _quick_ toggle button for tracking (slider at the top) active (green)

**Comment by jajmo** [comment]
It looks like the issue was resolved by updating pathfinder_websocket to the latest release.
