### ISSUE TITLE
setup page 403

### ISSUE THREAD

**Issue by chiefdan** [exodus4d/pathfinder#649]
I've completed all the configuration steps through SSO and ESI and I am trying to go to the setup page.

I am getting a 403 permissions error on the "mydomain.fqdn/setup" page. I get a log in prompt but I am not sure which user and password needs to be entered, I have tried several but none are working and I get 403 forbidden. 

Any thoughts?

Is this login supposed to come from the SSO or a user? SSO I am getting a SQL error that i thought was because I have not yet loaded the databases on the setup page.

**Comment by mrurb** [comment]
You don't need to login in order to get to the setup page. But can you give some more information? Are you running windows/linux and what kind of web server are you using, IIS, Nginx or apache?

But it sounds like you have managed to set password protection on the directory.

**Comment by chiefdan** [comment]
Its nginx on ubuntu. Not sure how i could have set that. Could it have to do with my www-data user's permissions?

**Comment by chiefdan** [comment]
Found there was an auth parameter in pathfinder.conf, i commented out and I'll try again.
