### ISSUE TITLE
Intel Tab - Delete Rows

### ISSUE THREAD

**Issue by pathfinder1234** [exodus4d/pathfinder#651]
o7

I was  looking at the manual, but couldnt find out how to delete the intel tab for certain system, delete an old structure that doesn't exist anymore etc. 

Is there any way i can delete the structures i have all ready added?

EDIT: My monitor is from the bronze age, i apologize after zooming out the page i saw the big red delete button.

Regards,

**Comment by pathfinder1234** [comment]
o7

The Intel Tab does not fit on a 21-23 inch monitor and the delete button for structures is hidden. 
You have to make the zoom level to 90% on google chrome in order to see it, but then it messes up the collumns in the intel tab and the resolution drops. Would be lovely if you can fix this.

Regards,

**Comment by exodus4d** [comment]
@pathfinder1234 NP :)

Just a small hint: Structure information is not _bound_ to a certain map (like signatures are). Structure data always  relates to the  Users Corporation. What does this mean:
1. If you create new "corporation" maps, and add a system to it that already has structures stored, you will see them on the new map, too.
2. If you delete a map that has systems with Structure data on it, and re-add a system on an other corporation map, you will see those structures again
3. If you share a corporation map with other corporations, you will see the structures of all corporations that have map access, but you *can not* edit/delete structures that are not owned by your corporation.
