### ISSUE TITLE
[Feature Request] Select "Incoming WH" sig type by numeric input

### ISSUE THREAD

**Issue by LuxNitor** [exodus4d/pathfinder#652]
It's very nice that when updating sigs after scanning then you can select a wormhole's "type" field, enter a letter, and if it is a static or possible wanderer it usually selects the correct sig type and closes the dialogue. Unfortunately this is not the case for incoming wormholes, as they all begin with the letter K.

Since all signatures start with letters, this leaves numbers available as a method of quickly selecting which K162 type the wormhole is. Assigning numbers to the types as they are already presented in the optgroup should be fine. i.e. 1=C1/2/3, 2=C4/5, 3=C6, 4=HS, etc.

**Comment by exodus4d** [comment]
Shortcuts would increase the complexity of that code to much :( I added a search field plus keyboard control to the signature table see #266 . So you can still quick-jump between options without mouse use.
Here is what it looks like now: https://github.com/exodus4d/pathfinder/issues/390#issuecomment-412144591

**Comment by LuxNitor** [comment]
Would hard coding the seven K163 option tags with [@accesskey](https://www.w3schools.com/tags/att_global_accesskey.asp) be an option?
