### ISSUE TITLE
Signature reader reader does not work in Russian localization

### ISSUE THREAD

**Issue by tezdal** [exodus4d/pathfinder#653]
if the client has a localization language Russian then the reader writes that the error of reading the signature.

how fix it?

**Comment by exodus4d** [comment]
Russian in "general" is not supported. But there are some essential keyWords translated that helps to map Russian Signature **types**e.g.

**Comment by tezdal** [comment]
I can scan in the English client tonight.
then switch the client language and scan again
that it would be easier for you to make a parser

**Comment by tezdal** [comment]
i change
init.js
```
         1: {
                name: '(combat site|kampfgebiet|site de combat|Боевой район)', //*
                label: 'Combat'
            },
            2: {
                name: '(relic site|reliktgebiet|site de reliques|Археологический район)', //*
                label: 'Relic'
            },
            3: {
                name: '(data site|datengebiet|site de données|Информационный район)',
                label: 'Data'
            },
            4: {
                name: '(gas site|gasgebiet|site de collecte de gaz|Газовый район)',
                label: 'Gas'
            },
            5: {
                name: '(wormhole|wurmloch|trou de ver|Червоточина)',
                label: 'Wormhole'
            },
            6: {
                name: '(ore site|mineraliengebiet|site de minerai|Астероидный район)',
                label: 'Ore'
            },
            7: {
                name: '(ghost|Призрачный)',
                label: 'Ghost'
            }


```
and system_signature.js
 ```
  let validSignatureNames = [                                                 // allowed signature type/names
        'Cosmic Anomaly',
        'Cosmic Signature',
        'Kosmische Anomalie',
        'Kosmische Signatur',
        'Anomalie cosmique',
        'Signature cosmique',
        'Космическая аномалия',                                                 // == "Cosmic Anomaly"
        'Скрытый сигнал'                                                    	// == "Cosmic Signature"
    ];

```
but it doesn't work

**Comment by exodus4d** [comment]
@tezdal It probably not works because the JS files are not used in the client as they are. There is a "frontend build" process that bundles/minifies all the JS files.  
But this is no problem I´ll add the labels you posted here and do the rest. :) Hopefully I can add the stuff before the next Pathfinder release gets out this weekend.

Thanks!

**Comment by tezdal** [comment]
but i use npm run gulp production and compile product.

These code fragments are still encountered in
public/v1.3.5/app/

**Comment by maiaz** [comment]
FYI 1.4.3 still not work w/ russian signatures :(

**Comment by exodus4d** [comment]
@tezdal Thanks for your translation!
I added your suggestions
