### ISSUE TITLE
Issue with Composer Install, ZMQ

### ISSUE THREAD

**Issue by Derjyn** [exodus4d/pathfinder#654]
Getting several issues (some fixed since starting issue):

At the patherfinder/setup url:

* Redis is installed, it is shown as missing.
* Composer is installed, it is shown as missing (hard to install Pathfinder, without Composer, isn't it?)
* Ruby 2.5.1 is installed, shown as missing
* Ruby Gems 2.7.7 installed, shown as missing
* Compass 1.0.3 (Polaris) installed, shown as missing

Also, there is no guidance on the SDE.  What do we do with the files we get from CCP?  It's stated that the database is required, but the format of the SDE is YAML, and there are a plethora of options for converting into other formats, and many avenues for error.  We have no clue how you went about working with the SDE, or at least I'm not able to find any documentation.

Thanks for any help, and keep up the good work!

**Comment by exodus4d** [comment]
🤔 interesting... _Pathfinder_ checks installed packages with the `exec()` function: https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/setup.php#L610

Please check this:
1. check `php.ini` for `disable_functions` section if `exec` is listed here.
2. check if the unix user used by your WebServer and/or e.g. _PHP-FPM_ process gets a result for the Shell commands (see setup.php linked above)

**Comment by exodus4d** [comment]
### :x: Issue closed
This issue has been closed because it has been inactive for a while.

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*
