### ISSUE TITLE
Don't find Corporation/Player/Aliance 

### ISSUE THREAD

**Issue by tezdal** [exodus4d/pathfinder#661]
I can not add a corporation or a player or an alliance in the map settings
System notifies me no result found, but it my twink corporation or my alt toon
[link](http://joxi.ru/KAx4MqlcMKJ0QA.jpg)

**Comment by exodus4d** [comment]
@tezdal RTFM ;) Corporations/Players/alliances need to *activate* map invites before others can see/find them. -> Spam protection
![kvrnyya](https://user-images.githubusercontent.com/9299033/43276837-6211ad94-9106-11e8-93fc-3e9d9dd5f66d.png)
