### ISSUE TITLE
Says Im Banned from Path Finder

### ISSUE THREAD

**Issue by Casteal2014** [exodus4d/pathfinder#663]
I only used Pathfinder a few times over 1 year and a half ago. How can I be banned?
In game Toon" Casteal Toledo" 
Well its with this Toon. Was able to log in with my Alt. 

Only used Path Finder for a week when I was with "Nihil Ad Abyssi" 8/2017.

Any reason why? Makes no sense?  My Accounts on SIGGY , and Tripwire work fine. 
Wont be able to Join new corp if I cant Use Pathfinder. So this is kinda pressing. 
Thank you

**Comment by exodus4d** [comment]
@Casteal2014

**Comment by exodus4d** [comment]
@Casteal2014 

``````

**Comment by exodus4d** [comment]
@Casteal2014 I checked the logs. 

You are banned since `Sun, 10 Sep 2017 19:48:15` by "**Henry DePour**". 

```
Sun, 10 Sep 2017 19:48:15 +0000 [xxx.xx.xxx.xxx] BAN "Casteal Toledo" from corporation "Nihil Ad Abyssi", by "Henry DePour"
```

Is "Nihil Ad Abyssi" still your characters corp? If yes please contact your corp, if no let me know thre is maybe a bug with the "un-ban" function, if a char switches corporation.
