### ISSUE TITLE
Updating pathfinder

### ISSUE THREAD

**Issue by D0N2k** [exodus4d/pathfinder#665]
Whats the best way to update pathfinder?

**Comment by Slivo-fr** [comment]
Check out releases : https://github.com/exodus4d/pathfinder/releases

**Comment by D0N2k** [comment]
Thanks I backup'd my inis and replaced the files. Now my pathfinder installation is still showing 1.3.4 and is missing its stylesheet. Any Idea

**Comment by D0N2k** [comment]
Had to change the version number within my pathfinder.ini

**Comment by mrurb** [comment]
I would suggest never to replace your settings files with the old ones, as you might miss new settings, you should fill out the new settings files each time.
