### ISSUE TITLE
Timeout time?

### ISSUE THREAD

**Issue by gnomegemini** [exodus4d/pathfinder#668]
Hey there,

is there any possibility to prolong the timeout which occurs when you are logged in pathfinder?

Thanks and kind regards,
Stefan

**Comment by exodus4d** [comment]
What timeouts to you get? On my installations it´s currently `480min` -> 6h . But this can be configured in the `pathfinder.ini` for any self hosted installation.

**Comment by Derjyn** [comment]
Among the other issues that I've chimed in on, I finally got things "running". However, even being a manager, and/or adding my character ID as a super user in pathfinder.ini... I am getting logged out in 3 seconds, and receiving a 500 error toast. I can log back in, but then a 3 second timer in the corner of the map counts down, and the auto logout kicks in again.

Default of 480 is set in pathfinder.ini

**Comment by Derjyn** [comment]
I'm not certain if these are relevant to the issue, but it seems to be in line with the timing of logging in, and getting booted:
```
2018/08/06 20:55:03 [error] 9700#9700: *1 FastCGI sent in stderr: "PHP message: file_put_contents(logs/login.log): failed to open stream: Permission denied
PHP message: [app/lib/log.php:44] Base->write()
PHP message: [app/main/controller/api/user.php:93] Log->write()
PHP message: [app/main/controller/ccp/sso.php:329] Controller\Api\User->loginByCharacter()
PHP message: [index.php:23] Base->run()" while reading response header from upstream, client: 24.21.217.227, server: ewyx.ml, request: "GET /sso/login?cookie=char_1768b8427a8440187f8df172b03ae64e&tabId=5yxzi HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "ewyx.ml", referrer: "https://ewyx.ml/"
2018/08/06 20:55:08 [error] 9700#9700: *1 FastCGI sent in stderr: "PHP message: Validation failed: "systemId" = "30000179" [/var/www/html/app/main/model/basicmodel.php:463]
PHP message: [app/main/model/systemmodel.php:242] Model\BasicModel->throwValidationException()
PHP message: [app/main/model/basicmodel.php:311] Model\SystemModel->validate_systemId()
PHP message: [app/main/model/basicmodel.php:184] Model\BasicModel->validateField()
PHP message: [app/lib/magic.php:73] Model\BasicModel->set()
PHP message: [app/lib/magic.php:117] Magic->offsetset()
PHP message: [app/main/model/mapmodel.php:480] Magic->__set()
PHP message: [app/main/controller/api/map.php:993] Model\MapModel->getNewSystem()
PHP message: [app/main/controller/api/map.php:893] Controller\Api\Map->updateMapData()
PHP message: [index.php:23] Base->run()" while reading response header from upstream, client: 24.21.217.227, server: ewyx.ml, request: "POST /api/map/updateUserData HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "ewyx.ml", referrer: "https://ewyx.ml/map/Mw%3D%3D"
```

**Comment by CalMatar** [comment]
I am not sure if I am having similar issues but with the main hosted system I will be using the system and suddenly get logged out with a "User Not Authorized" message and I end up having to log back in. There is a popup that says something about being logged out due to security reasons or something, I don't remember but it is aggravating when you are in the middle of modifying maps and you are logged out. I thought this had an inactivity timer on it not a flat timer.

**Comment by exodus4d** [comment]
@Derjyn setting permissions on all *.log files will not necessarily solve the issue, you need to check the permissions on the /log folder, too. I can´t see a bug here. This needs to be fixed on your server.

@gnomegemini @CalMatar Your bug description is something totally different, and sounds like the #718
