### ISSUE TITLE
404 On Login: SSO Issue

### ISSUE THREAD

**Issue by Derjyn** [exodus4d/pathfinder#669]
(Had to copy source code from browser, since... This block is not select-able, bad UX there)

`Status: "HTTP 404 (GET /sso/requestAuthorization/oauth/authorize?response_type=code&amp;redirect_uri=https%3A%2F%2Fpathfinder.grumpy.space%2Fsso%2FcallbackAuthorization&amp;client_id=623bac9abed14c1d95a1c6f05c16a187&amp;scope=esi-corporations.read_corporation_membership.v1%20esi-location.read_location.v1%20esi-location.read_online.v1%20esi-location.read_ship_type.v1%20esi-ui.open_window.v1%20esi-ui.write_waypoint.v1%20esi-universe.read_structures.v1&amp;state=b31bd97e701195003309774b)".`

I have quadruple checked environment.ini, and the application settings on the ESI/CCP side. Everything checks out. Everything else works, except... Logging in.

This looks correct, yes?
`CCP_SSO_URL =   https://pathfinder.grumpy.space/sso/requestAuthorization`

We have a subdomain set up, with "pathfinder" as the root. Thus `Base` value is left blank. If we throw `/pathfinder` in there, CSS/Javascript, etc. goes crazy. So I don't believe that is the issue.

VPS with Ubuntu 16.04, Nginx, and so on. All prerequisites met (even though setup is still reporting things as missing, such as Redis, even though it's there- might want to look into that as well). Any assistance would be appreciated. Alliance guys are getting pretty ticked off right now, heh.

**Comment by Flevity** [comment]
attach your environment.ini w/o ccp sso Secret/Client id and double check your Callback URL on developers.eveonline.com

**Comment by Derjyn** [comment]
Callback URL on application side (developers.eveonline.com) is:
`https://pathfinder.grumpy.space/sso/requestAuthorization`

[environment.txt](https://github.com/exodus4d/pathfinder/files/2258475/environment.txt)

**Comment by Flevity** [comment]
in evnv*.ini change ccp_sso_url to https://login.eveonline.com

**Comment by Derjyn** [comment]
Wow. I'm so glad that was a derpy mistake on my end, and not some major issue. Thanks for the assist!

**Comment by Flevity** [comment]
on developers.eveonline.com you shoud change it to https://pathfinder.grumpy.space/sso/callbackAuthorization

**Comment by Derjyn** [comment]
Okay, so it is set to that now. In the application settings at developers.eveonline.com it is:
`https://pathfinder.grumpy.space/sso/callbackAuthorization`
And in the environment.ini it is set to:
`https://login.eveonline.com/`
That results in the last error message I just posted a moment ago.

**Comment by Flevity** [comment]
I don't know it should work if you didn't forget to save it on developers.eveonline.com
maybe wrong url still on ccp cache or something

**Comment by Derjyn** [comment]
ESI scopes are spot on, and the error returned in the headers are referencing the grumpy.space URL, so I'm at a loss.  I also went into setup on the Pathfinder end, and cleared out authentication data/cookies, to no avail.  Got any more magic left?

**Comment by Flevity** [comment]
nope, I'm done =/ maybe exodus could help

**Comment by Derjyn** [comment]
Well, thanks for your assistance thus far. I appreciate it 😺

**Comment by exodus4d** [comment]
environment.ini
```
[ENVIRONMENT.DEVELOP]
... more stuff....

CCP_SSO_URL                 =   https://login.eveonline.com
CCP_SSO_CLIENT_ID           =   08a5cf3XXXXXXXXXXXXXXXXXX
CCP_SSO_SECRET_KEY          =   tTfJRRXXXXXXXXXXXXXXX

; CCP ESI API
CCP_ESI_URL                 =   https://esi.tech.ccp.is
CCP_ESI_DATASOURCE          =   tranquility
CCP_ESI_SCOPES              =   esi-location.read_online.v1,esi-location.read_location.v1,esi-location.read_ship_type.v1,esi-ui.write_waypoint.v1,esi-ui.open_window.v1,esi-universe.read_structures.v1,esi-corporations.read_corporation_membership.v1
CCP_ESI_SCOPES_ADMIN        =
```

`CCP_SSO_URL` should not be changed. 
On the CCP developer page you have to add your **callback url** (where CCP sends their **response** to). This is Your Webservers URL:
```
https://local.pathfinder/sso/callbackAuthorization
```
Yours should be `https://pathfinder.grumpy.space/sso/callbackAuthorization`. It looks good so far, when I enter this URL I get redirected to your login page -> OK

If you get this error from time to time (not always) it it for sure a problem on CCPs side.

**Comment by Derjyn** [comment]
Yeah, that bit works fine. It's once you've logged in, and go to accept, it errors out.

Here's the error message:
`{"error":"invalid_request","error_description":"The callback URI doesn't match the value stored for this client"}`

Here's the URL it's spitting out:
`https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fpathfinder.grumpy.space%2Fsso%2FcallbackAuthorization&client_id=623bac9abed14c1d95a1c6f05c16a187&scope=esi-corporations.read_corporation_membership.v1%20esi-location.read_location.v1%20esi-location.read_online.v1%20esi-location.read_ship_type.v1%20esi-ui.open_window.v1%20esi-ui.write_waypoint.v1%20esi-universe.read_structures.v1&state=3e8eefc28db9fa1b3d0e5ed1`

Our other apps have been working fine, that deal with SSO, such as SeAT and Tripwire. So it's not on CCP's end. I've been over and over various config files, and read a ton of the other issues and all the installation/usage wiki here. I thought it might be a cache issue, so cleared all that out. I'm all out of ideas, haha.

Thanks for the assistance.

**Comment by Derjyn** [comment]
Ugh... This thing is insanely difficult to set up. I've not had any issues with dozens of other tools... I just went through running a new install, on a different server and it seems everything works... Alas, you can't log in. This time it's spitting out a new error:
`Access denied - Failed to load characterData from ESI`

Also, I cannot set up the tables in /setup. When you go to "import" or "build", get an error:
`501: failed. Please retry. error Not Implemented`

Nothing is in any log, outside of a flood of the following error, repeated for several hundred lines:
`Class "Monolog\Logger" not found. -> Check installed Composer packages`
`Class "Exodus4D\ESI\ESI" not found. -> Check installed Composer packages`

**Comment by CalMatar** [comment]
Since I can not find anywhere else this might be I will ask on this thread. I am trying to log into the Admin section of Pathfinder using the main website and my SSO login. I have verified that I have the Corporation security_officer Role as per the warning but it will still not let me log in. I do not know what I should do at this point.

**Comment by CalMatar** [comment]
I am not using a self installed version, I am using the main Pathfinder website. I was given the personnel_director roles and everything is working now but there does seem to be an issue with the security_officer role permission on the website when you try to log in using SSO.

**Comment by Borst92** [comment]
I am having simmilar issues like the ones written here. I'd like to host pathfinder on a server and i'm having trouble with the esi login.

environment.ini
```
; CCP SSO (OAuth2) - visit: https://developers.eveonline.com/applications
CCP_SSO_URL                 =   https://login.eveonline.com
CCP_SSO_CLIENT_ID           =	4c70eb24eedc4b6696XXX....XXX
CCP_SSO_SECRET_KEY          =	Lvc9ZE3bqRd7JMzyg5lXkkOtXXXXXX...XX
CCP_SSO_DOWNTIME            =   11:00
```
I did set the Callback URL to 
`https://81.169.250.65/sso/callbackAuthorization`
in the eve-application, since i' adressing the server with the ip-address,

I'm receiving the error
`{"error":"invalid_request","error_description":"The callback URI doesn't match the value stored for this client"}`

the IP-Address has no typo. Can anyone give me a hint how to fix this?
Thanks!

**Comment by Code2200** [comment]
I am having the same issue as @Borst92. 

Environment.ini

`; CCP SSO
CCP_SSO_URL                 =   https://login.eveonline.com
CCP_SSO_CLIENT_ID           =   f73c32095b0f420783f7ba9...XXX
CCP_SSO_SECRET_KEY          =   78iHKUzMSmWiLPNf0H1O6AJihWG....XXX
CCP_SSO_DOWNTIME            =   11:00
`

Callback is set to:
hhtp://pathfinder.caprican-initiative.org/sso/callbackAuthorization

Which gives this error halfway through the login process:
`{"error":"invalid_request","error_description":"The callback URI doesn't match the value stored for this client"}`

Could also use some help with it.

**Comment by Code2200** [comment]
Fixed it! check the 'URL' in you environment.ini file does not have a '/' at the end. If it does, remove it started working right away. @Borst92

**Comment by exodus4d** [comment]
I think we can close this issue. Maybe I can add some `trim()` for `/` to the parsed URL value.
