### ISSUE TITLE
Missing WH type in Signatures dropdown list

### ISSUE THREAD

**Issue by Raisten** [exodus4d/pathfinder#670]
Pathfinder Version: 1.4.0

Wormhole type D382 is not listed in the Type drop down in the Signatures section
![wh_system](https://user-images.githubusercontent.com/39092381/43761669-1589f9f6-9a69-11e8-8458-6dd53b2eb126.jpg)
![signature_dropdown](https://user-images.githubusercontent.com/39092381/43761676-1a387cc0-9a69-11e8-870c-d2e874502b7a.jpg)

**Comment by exodus4d** [comment]
@Raisten Thanks for the report. 
That´s interesting. AFAIK is **D382** a static WH (not wandering). 
J142547 has 2 statics (O477 B274). 

So there are 2 options:
1. CCP changed the statics for this WH 
2. The data used by _Pathfinder_ is outdated (same for _Anoiks_ end ellatha)
3. This was a bug in the Eve Client

Do you have have a chance to re-scan that system so we could verify that **D382 ** is a true static of that system?

Source:
1. http://anoik.is/systems/J142547
2. http://www.ellatha.com/eve/WormholeSystemview.asp?key=142547

**Comment by WildStrawberryEVE** [comment]
Wandering WH may have the same type as static WH. So some hole may have D382 static and another wandering D382. I lived in C2 like 6 or 7 years ago but I remember it happened from time to time. Even if it changed, leaving such possibility for wandering WH in PF shouldn't hurt or be misleading IMHO.
