### ISSUE TITLE
Banned from Use?

### ISSUE THREAD

**Issue by OGBigMO** [exodus4d/pathfinder#673]
I attempted to log in to pathfinder since it has been some time since I used the tool (and lets face it, the group I am with is using it)

But I get a message stating that my character is banned? How do I get this fixed?

http://puu.sh/BgH09/892cefa2e8.png

**Comment by exodus4d** [comment]
If you give me your character name, I could give you more information from the logs who banned you.
Your character got probably banned by your (former) corporation. 
If you leave/switch that corporation you should be able to re-login using the _SSO Login_ button, then _Pathfinder_ should auto un-ban you.  If this does not work we have a bug.

A character name would help to figure out what happened and if it is a bug or intended behavior.
