### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by Allileh** [exodus4d/pathfinder#674]
www.pathfinder.exodus4d.de uses an invalid security certificate. 
The certificate does not come from a trusted source. The certificate expired on Saturday, August 18, 2018, 3:33:55 PM. The current time is August 23, 2018, 6:36 PM.

**Comment by exodus4d** [comment]
I know, www.pathfinder.exodus4d.de worked as a _redirect_ (HTTP 301) to https://www.pathfinder-w.space (which is the official project URL).  I moved the project to the new URL a few years ago never thought someone still uses the exodus4d URL so I have not installed a new SSL cert for the old URL. 
Please use  https://www.pathfinder-w.space and you should be fine
