### ISSUE TITLE
403 Access denied User not found

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#675]
People at my installation of PF get random (but consistent) forced log offs with their character. The software responds to them with a 403 Access denied User not found. While I do not understand the first part, the 2nd is def. total bs, as the users are all there, in the db, have access tokens, the whole shabang. Relogin in works for a while before they get thrown out with the same error eventually again.

![403](https://user-images.githubusercontent.com/3730499/44586254-5ad7af00-a7af-11e8-8f97-64000f9cd06b.png)

**Comment by Tupsi** [comment]
I am also seeing a lot of these errors in my nginx log:

`PHP message: [index.php:23] Base->run()
PHP message: array_unique() expects parameter 1 to be array, null given
PHP message: [app/lib/base.php:2219] Base->error()
PHP message: [vendor/exodus4d/pathfinder_esi/app/ESI.php:693] array_unique()
PHP message: [app/main/lib/ccpclient.php:81] call_user_func_array()
PHP message: [app/main/controller/api/route.php:585] lib\CcpClient->__call()
PHP message: [app/main/controller/api/route.php:421] Controller\Api\Route->searchRouteESI()
PHP message: [app/main/controller/api/map.php:1062] Controller\Api\Route->searchRoute()
PHP message: [app/main/controller/api/map.php:893] Controller\Api\Map->updateMapData()
PHP message: [app/lib/base.php:1834] Controller\Api\Map->updateUserData()
PHP message: [app/lib/base.php:1642] Base->call()
PHP message: [index.php:23] Base->run()" while reading response header from upstream, client: 000.000.000.000, server: pathfinder.xxx.net, request: "POST /api/map/updateUserData HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "pathfinder.xxx.net", referrer: "https://pathfinder.xxx.net/map/NDY5"
`
might be related, might be not.

**Comment by Tupsi** [comment]
I upgraded php from 7.0 to 7.2 and reinstalled pf 1.4.0 completely new from scratch. This seems to have made the situation better for now. Users have reported nothing so far, so I would close this.

**Comment by Sakata-MC** [comment]
This is back. Logs have nothing useful...
Sat, 20 Apr 2019 22:48:03 +0000 deleteLogData (1.798 s)
Sat, 20 Apr 2019 22:49:02 +0000 deleteLogData (1.200 s)
Sat, 20 Apr 2019 22:50:01 +0000 deleteEolConnections (0.012 s)

![image](https://user-images.githubusercontent.com/3158362/56463269-c570d700-639e-11e9-9692-1d1c1f66b1c4.png)
