### ISSUE TITLE
Ship Mass Calculation

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#676]
Is there a way for the system to actually calculate the ships true mass when it jumps through a WH or is it just using the base value for the hull with no fittings? 
The reason I ask is because when you are using the Ship Mass calculation tool to check on how much mass is on a hole so far as I can tell right now it does not calculate the mass of ships correctly. If you fit a Higgs Rig or a Prop Mod on a ship it changes the Mass of the ship thus when you jump through a WH with them on your ship the mass calculation is wrong and you can not count on it.

**Comment by exodus4d** [comment]
Unfortunately no. Mass calc is always a **rough estimation**  and give you the **minimum** mass reduction of a hole. Reasons:
1. Even if you grap the current fitting and do the **very complex** mass calculation for a ship, you will not get effects like "active MWD" which have a huge impact of the mass...
2. Even if you have a 100% correct mass calculation, there is always an _error factor_: _Pathfinder_ just records mass for active users, all other jumps are not recorded.
