### ISSUE TITLE
Website access issue

### ISSUE THREAD

**Issue by BeatByATaLi** [exodus4d/pathfinder#677]
Every time I use the url: https://www.pathfinder-w.space/ I am greeted with the first screenshot.
But when I used the url: https://pf.ap0.space/# I am greeted with the 2nd screenshot.
![image](https://user-images.githubusercontent.com/42752472/44684510-8b3a7a00-aa49-11e8-974a-476fab0762c3.png)

![image](https://user-images.githubusercontent.com/42752472/44684523-942b4b80-aa49-11e8-9a1b-3a3bd645c05f.png)

**Comment by WildStrawberryEVE** [comment]
The second link you linked (pf.ap0.space) is a private installation of Pathfinder, only for selected corporations/alliances. You won't get access there unless you are a member. Also it's not a subject to issue reports here since it's not an "official".

The official one - "www.pathfinder-w.space" - well, I can only say I see it the same way as you :)
You would probably have to wait for @exodus4d to sort this issue for you.

**Comment by exodus4d** [comment]
Interesting, I can´t see any problems on https://www.pathfinder-w.space (Chrome 68).
Regarding your screenshot:
- Pages itself loaded and CSS failed to load -> Could you check the Chrome Dev-Tools (F12) -> "Network" Tab for any errors and post a screenshot of it here?
- Have you checked your Chrome extensions (e.g. Add Blocker) if resources are blocked by any Chrome extension?

**Comment by WildStrawberryEVE** [comment]
I have uBlock Origin but it says it did not block anything. Disabling it changed nothing.

[![Screenshot from Gyazo](https://gyazo.com/64d90a6d86b701832bef4b50473191e1/raw)](https://gyazo.com/64d90a6d86b701832bef4b50473191e1)

**Comment by exodus4d** [comment]
@BeatByATaLi Do you have "_Bitdefender_" active on your Browser?  Someone else reported that problem and an active "Scan SSL" option caused the problem:

Possible problem: https://www.bitdefender.com/support/what-to-do-when-security-certificates-cannot-be-verified-installed-1090.html

![8b0c23b0d0e49a4a56a1d250ed6bc429](https://user-images.githubusercontent.com/9299033/45230013-c8afca80-b2c7-11e8-89c2-9435c767f2ab.png)
 
Deactivating that option is of course not a solution but it might help me to hunt that problem down.
