### ISSUE TITLE
Pathfinder initial web page not loading

### ISSUE THREAD

**Issue by SentientPulse** [exodus4d/pathfinder#681]
![pathfinder 1](https://user-images.githubusercontent.com/42942601/44995617-bbc76a00-af9b-11e8-81e4-f9b4750d5563.png)

I have this problem every time i try to load Pathfinder, any idea how to solve it?

I get the issue both in firefox and google/chrome?

**Comment by mrurb** [comment]
In chrome pres f12 to get the dev console open and then go to the tab Network, refresh pathfinder and take a printscreen of that.

Should look something like this:
![image](https://user-images.githubusercontent.com/3414748/45092015-71b5c400-b114-11e8-9913-911b221303f6.png)

**Comment by exodus4d** [comment]
@SentientPulse This issue is a dublicate of #677
Please read my comment and let me know if you have a similar issue:
https://github.com/exodus4d/pathfinder/issues/677#issuecomment-419486250
