### ISSUE TITLE
Map center

### ISSUE THREAD

**Issue by gdeld** [exodus4d/pathfinder#69]
The map is stretched in width, an horizontal scrolling bar on the bottom allow the centering of the map. When loaded the map is always off center

**Comment by exodus4d** [comment]
Yeah the map is always scrolled to the left. If you are looking for the systems you are currently in, just click the small "location" icon that should be visible on the top-right next to the "Map-Menu"-Navigation link.
This will select your current system and auto-scroll the map to the system you are in.

But yeah it does not make sense to show an "empty" view of the current map, if all the systems on the map are off-viewport. Ill think about a "auto-scroll" feature. This is not really but, its more a "missing feature" :)

**Comment by exodus4d** [comment]
##### Maps now "remember" the **scrollOffsetX** position :)

Each map now stores their current scroll position on the client. This is done by a **client side cache**. Called [IndexedDB](https://www.w3.org/TR/IndexedDB). This **API** was introduced on 2015 and is not supported by older browser!

- I added [**localForage**](https://mozilla.github.io/localForage/) (developed by [Mozilla Foundation](https://www.mozilla.org/en-US/foundation/) )
- I added a simply *store*/*read* (key/value) *API* for maps which can be used in future to store more information (e.g. "default map", "panel positions",...)
- Data is stored as a *JSON* object
- This *API* uses **[promises](https://www.w3.org/TR/2013/WD-dom-20131107/#promises)** as callback, which are **not** supported in the *IGB*!

###### This can be verified in your browsers dev tools:
![indexeddb](https://cloud.githubusercontent.com/assets/9299033/16499610/85d5b364-3f01-11e6-8705-a4bbec88e4e3.png)
