### ISSUE TITLE
Wormhole type list cannot be scrolled anymore

### ISSUE THREAD

**Issue by Slivo-fr** [exodus4d/pathfinder#692]
The previously scrollable list isn't anymore on v1.4.1. The whole page scroll instead of the drowdown list.

![image](https://user-images.githubusercontent.com/10325988/46134478-43bf2d80-c243-11e8-83ac-ccf5d5fe3925.png)

**Comment by mrurb** [comment]
I know it would be nice if you can use scroll wheel, but until it's fixed you can drag the scrollbar in the side.

**Comment by Slivo-fr** [comment]
Sure, that's a minor issue :)
