### ISSUE TITLE
Can't paste into signature reader

### ISSUE THREAD

**Issue by sikxshot** [exodus4d/pathfinder#694]
Hi on the public server, since the last update I can't paste into the signature reader. The dialog box opens but the "update signatures" button does nothing. I've created a new map but does not help.

**Comment by mrurb** [comment]
Duplicate of #691

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
