### ISSUE TITLE
[Feature Request] Colour coded EOL times in signature list

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#703]
Request: 
Add a visual indicator for EOL states to the signature list. Text colour change/counter value to indicate the remaining EOL time.

**Comment by exodus4d** [comment]
I added some "color codes" to the "leads to" system name of a chosen wormhole connection in the "signature" table:
- "fresh" wh → gray border
- "reduced" wh → gray border, orange background
- "critical" wh → gray border, red background
- EOL wh → pink border
- Frigate wh → dashed border

The "exclamation mark" that indicates a conflict (e.g. a connections is mapped to more than one target system) is not affected.

![tszrfh7](https://user-images.githubusercontent.com/9299033/48967532-4ab7b180-efe2-11e8-9df0-f199d201a0bc.png)
