### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by foxden79** [exodus4d/pathfinder#707]
When you try to build systems, an error 500 appears. 
<a href="http://pic.hostme.su/image/Y6"><img src="http://pic.hostme.su/images/2018/10/22/37110ce41332e7a99b2cf0c51e3c0c82.md.jpg" alt="37110ce41332e7a99b2cf0c51e3c0c82.jpg" border="0" /></a>
The following entry is in the logs:
2018/10/22 21:18:53 [error] 640#640: *46101 FastCGI sent in stderr: "PHP message: PHP Fatal error: 
 Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for colu
mn 'data' at row 1 in /var/www/eve/app/lib/db/sql.php:226
Stack trace:
#0 /var/www/eve/app/lib/db/sql.php(226): PDOStatement->execute()
#1 /var/www/eve/app/lib/db/sql/mapper.php(495): DB\SQL->exec(Array, Array)
#2 /var/www/eve/app/lib/db/cursor.php(245): DB\SQL\Mapper->update()
#3 /var/www/eve/app/lib/db/sql/session.php(95): DB\Cursor->save()
#4 [internal function]: DB\SQL\Session->write('opbh90gh9otmemo...', 'SETUP|a:1:{s:10...')
#5 /var/www/eve/app/lib/base.php(2091): session_commit()
#6 [internal function]: Base->unload('/var/www/eve')
#7 {main}
  thrown in /var/www/eve/app/lib/db/sql.php on line 226" while reading response header from upstream, client: 95.73.255.88, server: eve.openchat.ru, request: "POST /api/setup/buildIndex HTTP/1.1",
upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "eve.openchat.ru", referrer: "https://eve.openchat.ru/setup"

Because of this, nothing works :-( How to get rid of this error?

**Comment by justindh** [comment]
This might be related to #666 ? Worth giving a try

**Comment by foxden79** [comment]
> This might be related to #666 ? Worth giving a try

no. I tried.

**Comment by Gelikan** [comment]
Changing type of column 'data' in 'sessions' table from TEXT to LONGTEXT should help. Something like:
```sql
ALTER TABLE `sessions` CHANGE `data` `data` LONGTEXT 
```
 on MySQL 5.7.

**Comment by foxden79** [comment]
> Changing type of column 'data' in 'sessions' table from TEXT to LONGTEXT should help. Something like:
> 
> ```sql
> ALTER TABLE `sessions` CHANGE `data` `data` LONGTEXT;
> ```
> 
> on MySQL 5.7.

Thank. helped

**Comment by foxden79** [comment]
Corrected this error. It is necessary in the table "System" in the column "description" put the value "Not null"

**Comment by exodus4d** [comment]
@foxden79 Thanks for your report. I opened an Issue for this. This should be fixed in the _PHP_ framework _Pathfinder_ runs at.

**Comment by exodus4d** [comment]
I´m curious what large amount of Session data is stored. Could you please let us know and post the data in here (anonymised) here? I suspect is a collection of all 82xx systems in EVE.... Maybe I can improve and reduce data.
