### ISSUE TITLE
Character is banned?

### ISSUE THREAD

**Issue by ztyL6400** [exodus4d/pathfinder#708]
I'm trying to login to https://www.pathfinder-w.space/, but it says my character is banned. Is there something i can do to fix this?
The character in question is "Sexycabdriver 2nd"

**Comment by ztyL6400** [comment]
![image](https://user-images.githubusercontent.com/43452422/47916602-f91a7c00-dea6-11e8-9b83-fb469174a205.png)

**Comment by exodus4d** [comment]
@ztyL6400 This is what I can find in the logs:

```
BAN "Sexycabdriver 2nd" from corporation "Holy Hunters", by "Kiven Foster"
```

Please let me know if know if you you are still in the corporation where you are banned by.

**Comment by exodus4d** [comment]
If you have changed corporation ( I can check), you should be able to re-auth on Pathfinder by using the "SSO button" and you are no longer banned. If you are still in that corpoarion, contact your corp.

**Comment by exodus4d** [comment]
Your bann is from `Tue, 07 Aug 2018 02:58:42`

**Comment by ztyL6400** [comment]
Hi exodus.

Thanks for your reply.

Holy Hunters is an old corp and Kiven Foster was my CEO. I'm not in Holy Hunters anymore. I've joined another corp that had a pathfinder running on their own server. It was just recently when i joined the corp that i'm in now who are using the "public" server of pathfinder that i discovered that i'm banned..

I have tried to remove the sso from my eve account and i have tried the sso button numerous times, with no luck..

I can provide screenshots from ingame if it helps

**Comment by exodus4d** [comment]
@ztyL6400 I removed your ban and checked your current Corporation. You should be able to re-use the "SOO button" and retry login. (If it does not work wait up to 10min).

Ill check why auto-unban does not worked in your case, if your character switched corporation. And let you know what I can find.

**Comment by ztyL6400** [comment]
@exodus4d It works! Thank you very much.. No more pen and paper :)

And thanks for a awesome piece of software :)
