### ISSUE TITLE
[Feature] Custom/editable ship jump logs

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#709]
Jump logs should be editable. 
- You might want to change the ship mass of an existing jump log (e.g. lower mass for _HIC_ ships with active _bubble_). 
- You might want to add custom jump logs (e.g. if Pilot was not active on _Pathfinder_ and jump was not auto recorded)

**Comment by exodus4d** [comment]
![jjccyud](https://user-images.githubusercontent.com/9299033/49339508-26d41b80-f633-11e8-9fbe-38986108b505.png)

**Comment by CalMatar** [comment]
@exodus4d, I was just trying to use this feature and it will not let me do anything with the ship. I can change the mass and the character fine but can not save it as there is no ship data even though there is a ship in the initial log but when I go to edit it the ship is not there and it will not let me add or change it.

**Comment by exodus4d** [comment]
@CalMatar Thanks for reporting! - This is now fixed
