### ISSUE TITLE
Active pilots in system doesn't show up.

### ISSUE THREAD

**Issue by gdeld** [exodus4d/pathfinder#71]
I am not sure if it is a feature at all, but if there is a pilot in system the map shows a number and a arrow up. By clicking the arrow no information appears. It would be great to have name and ship flown popping up

**Comment by exodus4d** [comment]
The number is just an indicator of the current number of active pilots in that system. The arrow "up" (green) indicates a growing number of friendly pilots in that system. The arrow "down" (red) indicates a decreasing number of pilots.

This should help to "track" large number of pilots on a map. E.g. If everybody is jumping out of a system, you can see. Some for Systems with a growing number of pilots...

You should be able to see the names/Ships of any active pilot in a system by "hovering" the small gray arrow, right to a system name.

**Comment by gdeld** [comment]
Thanks for the follow up on all the issues. I so on imgur the snapshots and definitely I cannot see the pilot in system as it is shown on the snapshot. I'll leave a note here instead of opening a bug, unless you need more details about it.
