### ISSUE TITLE
Pathfinder Database creation warnings

### ISSUE THREAD

**Issue by nunnakii** [exodus4d/pathfinder#712]
So after running through setting up pathdiner a couple of times (mainly due to stupid mistakes because I suck at this kind of stuff) I excitedly arrived at the setup page. Everything was green except a couple things marked missing but they were under optional so I pressed forward. I made sure to configure the .ini files and hit setup tables for the Pathfinder database. After finishing it is showing 196 warnings. I hit the Fix columns option but the warnings are still here. The Eve-Online universe database setup without issue but I cannot for the life of me get the Pathfinder database to finish. If I click setup again it returns a Error - 500 with this http://yoururlhere/setup?action=bootstrapDB&db=PF#pf-setup-database. Any direction on how to solve this would be greatly appreciated.

**Comment by nunnakii** [comment]
Hey Justindh. I've been at this all day and it's late here but I will take a look into it in the morning and get back to you with the results.

**Comment by C64Gamer** [comment]
I'm having the same problem. My database setup ist not working. After the db script "http://YOURURL.com/setup?action=bootstrapDB&db=PF#pf-setup-database" was running a few seconds i get an error:

![screenshot_21](https://user-images.githubusercontent.com/13532609/47848521-dcab1080-ddce-11e8-8f0e-290de1e45122.png)

I'm running on MySQL 5.7.x with strict mode off on a CENTOS 7 system. I have tried MYSQL40 sql_mode but this was not helping. Any ideas? The db creation fails everytime i try to setup them.

**Comment by C64Gamer** [comment]
I have found the problem:

I have removed the parameter " **'default' => ''** " from the description column in the following files:

- model/universe/regionmodel.php
- model/universe/systemmodel.php
- model/universe/typemode.php
- model/rightmodel.php

The database setup is now running through.

**Comment by nunnakii** [comment]
Awesome. Now I guess the question of the day from the new kid on the block when it comes to this stuff is how the heck do I remove the parameter " 'default' => '' " from those lol. Sorry if this is completely obvious to everyone else but I don't normally take on setting up stuff like this.

**Comment by DLB82** [comment]
I have the same issue.
In apache logs, I have : 

> PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'data' at row 1 in /opt/pathfinder/app/lib/db/sql.php:226\nStack trace:\n#0 /opt/pathfinder/app/lib/db/sql.php(226): PDOStatement->execute()\n#1 /opt/pathfinder/app/lib/db/sql/mapper.php(495): DB\\SQL->exec(Array, Array)\n#2 /opt/pathfinder/app/lib/db/cursor.php(245): DB\\SQL\\Mapper->update()\n#3 /opt/pathfinder/app/lib/db/sql/session.php(95): DB\\Cursor->save()\n#4 [internal function]: DB\\SQL\\Session->write('k6t1cd22vs394u4...', 'SETUP|a:1:{s:10...')\n#5 /opt/pathfinder/app/lib/base.php(2091): session_commit()\n#6 [internal function]: Base->unload('/opt/pathfinder')\n#7 {main}\n  thrown in /opt/pathfinder/app/lib/db/sql.php on line 226, referer: https://pathfinder.guides-eve.online/setup

But, I don't see another logs.

**Comment by nunnakii** [comment]
Well, I've now tried #666 but no luck with that.

**Comment by DLB82** [comment]
It's an other issue. Not the same, I think @nunnakii .

**Comment by nunnakii** [comment]
at this point, I would be willing to pay someone a reasonable fee to just go in and set this up for me lol.

**Comment by C64Gamer** [comment]
@nunnakii How is your name in EVE ? I can contact you there. Maybe i'm able to help you.
Sorry for mixing up topcis.

**Comment by nunnakii** [comment]
@C64Gamer name in game is Nunnaki. And no worries on mixing topics.

**Comment by DLB82** [comment]
I get the request that I think generate my error: data too long...
[request.txt](https://github.com/exodus4d/pathfinder/files/2567686/request.txt)

Do you know why this request is generate and what can I do to finalize the installation?

**Comment by CokkocZateki** [comment]
> I have found the problem:
> 
> I have removed the parameter " **'default' => ''** " from the description column in the following files:
> 
> * model/universe/regionmodel.php
> * model/universe/systemmodel.php
> * model/universe/typemode.php
> * model/rightmodel.php
> 
> The database setup is now running through. Why ever you are not allow to set a default values for TEXT fields in mysql 5.7

This option didnt work for me. anyone have another solution...

**Comment by CokkocZateki** [comment]
so solution that worked for me

go into your pathfinder db

and then `ALTER TABLE `sessions` CHANGE `data` `data` LONGTEXT;`

refresh /setup page and build system index

**Comment by DLB82** [comment]
@CokkocZateki That's works for me. Thanks a lot. :)

**Comment by lebris-d** [comment]
I set default value in the database to NULL for the description and now, I can add systems.

> ALTER TABLE `system` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;

**Comment by exodus4d** [comment]
Thanks for your report! The `default` value for `system`.`description` column is a bug in the current release that is already fixed for the next one.

As as Workaround, this should help: https://github.com/exodus4d/pathfinder/issues/701#issuecomment-429390820

I close this one because it is a dublicate of #701
