### ISSUE TITLE
Error 500, Foreign key constraint on pathfinder.character during initial user registration

### ISSUE THREAD

**Issue by justindh** [exodus4d/pathfinder#713]
The first user to register since upgrading to 1.4.2 received the following error and fails to register, after signing in to eve, and being redirected to the '/sso/callbackAuthorization?code=stuff&state=stuff'. I've dug through the logs and have found nothing logged for the even at all

![image](https://user-images.githubusercontent.com/5378764/47872710-85a43c00-ddcc-11e8-9791-90cd27864f23.png)

**Comment by justindh** [comment]
`MariaDB [pathfinder]> alter table `character` alter roleId set default 1` fixed this issue for me. the default was 0, but there wasnt a role 0. Not sure how it got that way?

**Comment by exodus4d** [comment]
hm, that´s interesting 🤔 ...

`character`.`roleId` column alreads has a default of `1`: https://github.com/exodus4d/pathfinder/blob/master/app/main/model/charactermodel.php#L117
