### ISSUE TITLE
Warning: 1265 Data truncated for column 'description' at row 1

### ISSUE THREAD

**Issue by foxden79** [exodus4d/pathfinder#714]
Hi.
When you enter / setup, information about the error is displayed in the "system" table <a href="http://pic.hostme.su/image/lm"><img src="http://pic.hostme.su/images/2018/11/10/d68452789af607f74c8e0ac041fa48d3.md.jpg" alt="d68452789af607f74c8e0ac041fa48d3.md.jpg" border="0"></a>

When you click on the "Fix columns / keys" button, error 500 is displayed.

<a href="http://pic.hostme.su/image/lY"><img src="http://pic.hostme.su/images/2018/11/10/a6bb81dcb3013148f6e8e4ce7ddb910c.md.jpg" alt="a6bb81dcb3013148f6e8e4ce7ddb910c.md.jpg" border="0"></a>

In the main interface, the "Intel" "Signatures" and "System Description" fields are unavailable. The wait icon is spinning all the time and nothing can be entered.

<a href="http://pic.hostme.su/image/ll"><img src="http://pic.hostme.su/images/2018/11/10/5cb920db2ef44d22b6cb9e3644510152.md.jpg" alt="5cb920db2ef44d22b6cb9e3644510152.md.jpg" border="0"></a>

Version 1.4.2
MariaDB 10.0.37

**Comment by exodus4d** [comment]
This is a known bug in the current `1.4.2` release that is already fixed in the next one.
As as workaround try this: https://github.com/exodus4d/pathfinder/issues/701#issuecomment-429390820

I close this issue  duplicate #701
