### ISSUE TITLE
[Feature Request] Abyssal site removal

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#722]
When jumping back to and from Abyssal sites would it be possible to enable an option to auto remove an abyssal trace from the map area once a Kspace return jump is registered with location tracking on.

**Comment by exodus4d** [comment]
I think this would be possible. I have a question about Abyssal systems:
1.  Is it possible that more than one pilot active in an Abyssal site at the same time?

If you get podded in an Abyss site, the system would get removed as well, would this be OK?

**Comment by dnolen** [comment]
Yes, currently you have upto 3 people in a trace for the frigate based fleet comps. 

If you get podded out of the site due to timer/damage etc, absolutely. Once the trace is exited ideally having it removed from the map immediately would be ideal.

**Comment by mrurb** [comment]
If there is no one in an Abyssal(AS) system, it should just get removed no questions asked, having a AS system on your map gives nothing and is just annoying.

And yes more than one pilot can be in one AS pocket(Up to 3) at the same time and it is in theory also possible for two pilots going into to two different AS pockets, for those two AS pockets to land in the same AS system, in which case it should remove the system when the last pilot leaves the system.

And yes even if x person gets podded it should remove z system, as there is no way of him or anyone else to get back into that AS pocket in that AS system.

**Comment by andrewnclark** [comment]
> And it can even be discussed if there should be an option to disable AS systems completely from pathfinder.

The ability to remove them in map settings would be much appreciated. I'm forever cleaning up after myself being shouted at for the mess. They offer little/no value in being mapped.

**Comment by Kashada** [comment]
> I'm forever cleaning up after myself being shouted at for the mess. They offer little/no value in being mapped.

For now you can disable tracking before activating filaments.

**Comment by mrurb** [comment]
> > I'm forever cleaning up after myself being shouted at for the mess. They offer little/no value in being mapped.
> 
> For now you can disable tracking before activating filaments.

One should to this date still not have to disable tracking, as it is still pointless that pathfinder in any form or way maps Abyss space.

I often shout at my members because they forgot to disable tracking and made a mess and then i'll have to shout at them a bit later cause they scanned down a chain but forgot to enable tracking again,

**Comment by Kashada** [comment]
Well, I just said. I am not against this feature.

**Comment by Meganitrospeed** [comment]
I wouldnt remove them, I would just make it optional to track you in Abyssal space, you can use it to track corp abyssal runs if you have a map with just abyssal sites

**Comment by dnolen** [comment]
> I wouldnt remove them, I would just make it optional to track you in Abyssal space, you can use it to track corp abyssal runs if you have a map with just abyssal sites

As they are instanced only for the duration of the 20 minute timer/PVP arena timer duration there really isn't a point to keeping them once you exit the pocket via gate/podding etc.

**Comment by dean-groves** [comment]
I personally see no need to have abyssal space tracked in any way. It adds nothing to the usefulness of pf, and clogs the map up. Members constantly forget to turn off tracking when they jump in, and if they do remember, they constantly forget to re-enable it after they leave instead.

**Comment by infinity223** [comment]
for me - disable adding abyssals to map entire.

**Comment by dnolen** [comment]
The only reason it's useful is to know where a corp member has a filament active in case someone decides to wait at the spot for them to exit, aside from that it's not really relevant as we can't do anything else with them.

**Comment by mrurb** [comment]
Is there any plans on fixing this problem?

**Comment by exodus4d** [comment]
Tracking for "Abyss" connections/systems can now be disabled in map options

![0uwJj85](https://user-images.githubusercontent.com/9299033/66065742-67007500-e548-11e9-83c4-04ec4e18ae4b.png)
