### ISSUE TITLE
Lazy delete improvement request.

### ISSUE THREAD

**Issue by WildStrawberryEVE** [exodus4d/pathfinder#724]
We noticed a lot of accidental deletions of signatures with current UI where lazy delete is a small toggle button in the top right corner.

My best suggestion is to automatically disable it after each use.
Another approach is to make the state of active lazy delete to be more visible.

**Comment by Slivo-fr** [comment]
I'm all with you on this :)

**Comment by Bluedagger21** [comment]
Bumping. Have multiple users requesting this.
