### ISSUE TITLE
[Feature Request] Toggle Sig ID viewing for Wormhole connections

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#725]
This would be precisely the same as the "Signatures" option, but instead of showing wormhole type, it would show the Signature ID.

**Comment by exodus4d** [comment]
Signature name is now visible (on **mouseover**), in the "_endpoint overlays_" for a connection:

![sig_overlay](https://user-images.githubusercontent.com/9299033/57569478-097f5680-73f6-11e9-8403-fd861c0bb2a0.gif)

**Comment by Bluedagger21** [comment]
@exodus4d thanks for adding this! Would it be possible to "switch" what is default shown and hovered over? We would LOVE to have the sig shown at all times, type on hover!

**Comment by CalMatar** [comment]
@exodus4d When did you implement this as I am not seeing this feature on the public server?
![Screenshot_64](https://user-images.githubusercontent.com/42744905/59140235-e13d3600-8968-11e9-91a1-9fa8df91a81d.png) (I was hovered over the "Home Hole" but it does not show my mouse)

**Comment by exodus4d** [comment]
@CalMatar check the "Milestone" label. It´s `v1.5.2`. The current version is `v1.5.1`. the feature is already in the `develop` branch and will be shipped with the next release (1-2 weeks)

**Comment by CalMatar** [comment]
AH, that is why. I did not notice the tag. Thanks. I love all the development and greatly appreciate everything you do for us.

**Comment by CalMatar** [comment]
I still do not see this even now.

**Comment by exodus4d** [comment]
@CalMatar Have you checked if the "signatures overlay" (right menu) setting is active? If there are no Tooltips with e.g. "K162" rendered, it can not be "extended" with the signature name.

**Comment by CalMatar** [comment]
It is working now, thanks.
