### ISSUE TITLE
[Feature Request] Undo last paste/edit to Signature List or Intel

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#726]
As title says, having an undo of even just a single edit would be useful for accidental pastes or edits. If ctrl-z could be a shortcut, even better.

**Comment by WildStrawberryEVE** [comment]
I second this!

**Comment by jwtea** [comment]
@exodus4d Would you be happy if i made a pr for this?

**Comment by Bluedagger21** [comment]
Thanks for the attention. @exodus4d any plans here?
