### ISSUE TITLE
When selecting "Leads To", do not include the systems already selected for auto-filling "Leads To" in that system.

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#727]
If someone really wants to switch the connection, they should just remove the connection from the other first, then select it in the other Leads To.

**Comment by Bluedagger21** [comment]
Bumping this enhancement request some as it would be a big QoL time-saver for adding these connections.

**Comment by exodus4d** [comment]
Already linked systems got moved into a separat group and are no longer available for select until they get un-linked from its signature.
Auto-pre-selection is not implemented for now. This might become complex to implement. Maybe in future...

![yZxZlf7](https://user-images.githubusercontent.com/9299033/56392862-e5838780-6232-11e9-9800-81154fae72ef.png)
