### ISSUE TITLE
shattered hole mapping

### ISSUE THREAD

**Issue by gdeld** [exodus4d/pathfinder#73]
If you enter a shattered hole the map stops updating. If you go one system/hole over and go into yet another hole it starts up again.

**Comment by exodus4d** [comment]
That is interesting. Ill see what i can do.
btw: Support for "Shattered Systems" is coming in `v0.0.16` (see #72)

**Comment by exodus4d** [comment]
Should be fixed in v1.0.0RC1. Please provide feedback if there are still any problems.
