### ISSUE TITLE
Small UI Issue - Expanded Nodes Stay Expanded When Sole Inhabitant Leaves System

### ISSUE THREAD

**Issue by clangdo** [exodus4d/pathfinder#737]
Each node on the map has a little down arrow that is hoverable. This down arrow reveals the ship types and more inhabitants of the system.

When I mouse over this to expand the node for the system I'm in, it works as expected and shows the ship I'm flying, however, if I leave the system in game (say through a wormhole) while this information is shown, the area where it's shown becomes blank, but it doesn't disappear when I stop mousing over the down arrow. The node also fails to return to normal size, and remains expanded.

This is undoubtedly a small issue, and probably needn't be a priority. However, in the spirit of completeness (and partially in the hope it could be easily fixable) I reported it none the less.

Thanks for this wonderful tool!

**Comment by exodus4d** [comment]
@hootlang200 Thanks for reporting. Could you provide some more details:
1. Which installation + version do you use? (my public server)
2. Which browser do you use + version?
3. Does it happen "always" or just "sometimes"
