### ISSUE TITLE
Stats and history

### ISSUE THREAD

**Issue by gdeld** [exodus4d/pathfinder#74]
Not sure what do you think about it, but it would be interesting to have statistics about mapped chains and history

**Comment by exodus4d** [comment]
I have a large list with features that would be "nice to have". "Scanning stats" are already in my mind :)
The problem wich new features is the limited time I have.
The main priority is getting rid of the small bugs   for now before implementing more new features. 

Please do not create issues for feature requests in here, bug issues are of course very welcome! :) If there is a new feature in developing I´ll create an issue for that and everybody can track the process and comment their thoughts about it.
