### ISSUE TITLE
Jquery error

### ISSUE THREAD

**Issue by Kill4Free** [exodus4d/pathfinder#741]
I can't create a new map or load anything.
Already tried to reinstall.

`initMapWorker() rejects Promise. command: "Invalid mapAccessData"; syncStatus: "ajax", payload: {syncStatus: "ajax", command: "Invalid mapAccessData"}`

```
Uncaught Error: Syntax error, unrecognized expression: #
    at Function.st.error (jquery-3.3.1.min.js:2)
    at st.tokenize (jquery-3.3.1.min.js:2)
    at st.select (jquery-3.3.1.min.js:2)
    at Function.st [as find] (jquery-3.3.1.min.js:2)
    at C.fn.init.find (jquery-3.3.1.min.js:2)
    at new C.fn.init (jquery-3.3.1.min.js:2)
    at C (jquery-3.3.1.min.js:2)
    at HTMLAnchorElement.<anonymous> (map_settings.js:639)
    at HTMLAnchorElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLAnchorElement.g.handle (jquery-3.3.1.min.js:2)
```

This problem occurs with master and develop branch

**Comment by bomkallo** [comment]
Prosimie and syn 'ajax' means you're running ajax, not websocket, though ajax is broken, at least in my case.
Jquery is loaded from dependencies, so I presume you might have downloaded wrong pf version, on the other side, let us knw your system spec.

I used to have load of errors when I started gulp with production flag, make sure your environment is set right and is set to production for safety:P The error above doesn't tell much anyway, it looks like wrong jquery version though:)

**Comment by Kill4Free** [comment]
Yeah looked into the code and edited the issue name.

I've checked the jquery version and tried one from the https://www.pathfinder-w.space site and the original from jquery.org, but that didn't help.
The site is set to production. I've updated from 1.3.x and before all worked fine :/

**Comment by bomkallo** [comment]
/xxxn/js/lib -> jquery.3.3.1.min.js , the question is, what you've done to make that error

**Comment by bomkallo** [comment]
Server specs. please :)

**Comment by Kill4Free** [comment]
VPS
1 Core
2GB RAM

**Comment by Kill4Free** [comment]
@bomkallo Tried it on another server today (14.1.) with a freshinstall and I've got the same problem on creating first map.

Any other specs you need?

**Comment by bomkallo** [comment]
I used to install it on Debian 9, the only difference is php version and webserver (apache in my case).
The error itself will appear if you put jQuery("#"), # without any tag; some versions don't throw that (1.12.4), the 3.3.1 will. At app/ui/dialog/map_settings.js:639 there is $(tabContentId). tabContentId is href param of a button. 

Are you sure you've installed everytning properly? /setup is ok?, /vendor folder was created properly via composer etc? Ngnix routing is set right? (well, I've never used ngnix but if your routing fails it will generate wrong urls, and the line:639 I mentioned might fail badly)

**Comment by Kill4Free** [comment]
Thanks for reminding me of checking configuration @bomkallo !
Double checked configuration of the second server.. It works now! (missed one url which was leading to the old server)
So my new server which I want to switch to is working now. 👍 

/setup - of not working was ok
/vendor - of not working was ok
nginx routes - not checked by now
reinstalled with the same commands as on the working server - no difference

I will try to fix the other server in the next few days to help other ppl if they get the same issue.
Keep your fingers crossed!

**Comment by Kill4Free** [comment]
Okay after switched both servers dns entries the other one worked.
So I digged a bit deeper and tried another browser on both servers. Both worked fine.

Seems like this has been an **cache** issue.

@bomkallo thanks for you time !
