### ISSUE TITLE
Character Activity Not Updating

### ISSUE THREAD

**Issue by discoandhaze** [exodus4d/pathfinder#742]
Character activity stopped working for me sometime yesterday. The _character_log_ table is empty and I'm getting this in my nginx_error.log:

`2019/01/17 12:18:59 [error] 1255#1255: *120 connect() failed (111: Connection refused) while connecting to upstream, client: 1.2.3.4, server: pathfinder.mysite.com, request: "GET /ws/map/update HTTP/1.1", upstream: "http://127.0.0.1:8030/ws/map/update", host: "pathfinder.mysite.com"`

Also:
`root@pathfinder:/var/www/pathfinder-w.space/public_html/logs# nc -v 127.0.0.1 -z 8030
nc: connect to 127.0.0.1 port 8030 (tcp) failed: Connection refused`

From my nginx.conf:

```
upstream ws_dev_map_update {
    server 127.0.0.1:8020;
  }

  upstream ws_prod_map_update {
    server 127.0.0.1:8030;
  }
```
I'm not 100% sure what is supposed to be listening on tcp/8030 since I have fastcgi using unix sockets, so any guidance is greatly appreciated!

**Comment by bomkallo** [comment]
Lol, I haven't noticed these two but I used to pasted them into my config as well. Still, in my nginx/sites-enabled/site.xxx I changed websocket config to proxy_pass http://127.0.0.1:8020; as far as I'm running the socket server with defaults, which are 8020 and 5555. 
In original pf there is proxy_pass http://ws_prod_map_update which will try to hit 8030, but websocket starts at 8020 by default so you can try and change it. It looks like I had problem with socket that time and I've made that fix. Now I see it might be equivalent to running websocket with 8030.

You're the admin, so you should know where you're running your websocket :P

**Comment by discoandhaze** [comment]
Error message appears to be unrelated. A comma was missing from the scopes; adding missing comma has restored expected functionality.
