### ISSUE TITLE
[BUG] Corp list in Intel window will not scroll w/ mouse wheel

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#743]
In the corp selection popup box used to select the owning group a structure in the structure intel panel does not operate with the mouse scroll wheel. Only arrow keys can be used to select enteries on an extended result list. 

Version: 1.4.3

**Comment by exodus4d** [comment]
This works for me in the current stable [v1.5.1](https://github.com/exodus4d/pathfinder/releases/tag/v1.5.1) Chrome browser

![scroll_issue_743](https://user-images.githubusercontent.com/9299033/58764428-1d3a5a80-8567-11e9-9169-007e2303d69b.gif)
