### ISSUE TITLE
BASE path not respected for /api/ endpoints

### ISSUE THREAD

**Issue by jaylapham** [exodus4d/pathfinder#744]
I'm setting up a pathfinder instance and have gotten through most of the setup documentation without any issues, but I'm seeing a problem with /api/* calls. I have pathfinder running in a subdirectory - e.g. https://website.tld/pathfinder - but all of the API calls are going to https://website.tld/api/* which obviously doesn't work as the resources don't live there. 

![err](https://user-images.githubusercontent.com/4381947/51448166-347c5800-1cea-11e9-8e46-3b01684301be.jpg)

Is there another BASE-like environment property I have to set for /api/* calls specifically? I am presently able to work around the issue by re-writing these calls to go back into /pathfinder/api/* with an .htaccess file in the root directory, but I'm wondering if I missed configuring something or if these calls don't account for the BASE property at all.

Background details: I'm running Apache on Ubuntu and don't have any rewrites except to force HTTPS. The only other warnings I'm getting in the setup page is that some tables are empty in eve_universe and optional issues (redis, event extension for performance).

**Comment by exodus4d** [comment]
yeah this is an issue with subfolder installations. I know there might be some path that could have some "problems".  It is just a lack of time on my side to provide proper support (and testing) for sub-dir installations. All my instances run on top-level domains. 
I have a local sub-dir installation for development but I don´t have the time for proper testing all features on it.
