### ISSUE TITLE
[Enhancement] Show more Redis information on /setup page

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#745]
With the next release `v1.5.0`, a number of changes are made to caching in _Pathfinder_.

#### Best practice:
The default **filesystem** based cache, can already be replaced by [_Redis_](https://redis.io/) (see [wiki:cache](https://github.com/exodus4d/pathfinder/wiki/Cache#redis-setup-optional)). 
_PHP´s_ default **filesystem** Session handler, can be replaced by _Redis_ as well. Which is much more performant than _Pathfinder`s_ default **mysql** Session storage. (see [Set Up a Redis Server as a Session Handler for PHP](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-redis-server-as-a-session-handler-for-php-on-ubuntu-16-04))

#### What is new?
In  `v1.5.0` the [_exodus4d/pathfinder_esi_ ](https://github.com/exodus4d/pathfinder_esi) client can handle its own cache backend where _ESI_ responses get cached by their `Expire` HTTP header information.
If _Redis_ is already configured as Cache backend for _Pathfinder_, it will be shared with _ESI_ client.
A better solution is a **distinct** _Redis_ DB for each use case. This gives you more control over caches. - e.g. Cached ESI requests can be cleared, `Pathfinder` cache data is not.

To keep track of the _Redis_ instances (and databases), `/setup` page now shows detailed stats from all _Redis_ caches that are used.

#####  1. ❕ No _Redis_ cache configured (default) - [filesystem cache]
![awf9tlw](https://user-images.githubusercontent.com/9299033/51805780-a9fba180-2271-11e9-8f3e-1028e29493f7.png)

##### 2. ✔️ **One** _Redis_ instance (port `6379`), with **distinct** databases
![skrmjnz](https://user-images.githubusercontent.com/9299033/51805850-dcf26500-2272-11e9-8f21-b648a0c0e074.png)

##### 3. ❕  **One** _Redis_ instance (port `6379`), with **shared** db0 for "PHP Session" + "API_CACHE" data. This works but is not recommended!
![7e6qqrn](https://user-images.githubusercontent.com/9299033/51805894-6dc94080-2273-11e9-8e68-5fd87b9ead58.png)

##### 4. ✔️ **Three** _Redis_ instances (port `6379`, `6380`, `6381`), with **distinct** databases
![esnhkgt](https://user-images.githubusercontent.com/9299033/51805916-a701b080-2273-11e9-9167-9021b6358b8f.png)

**Comment by dkrotil** [comment]
Exodus in text there is version 1.5.0 , but milestone is 1.4.4 .

**Comment by exodus4d** [comment]
@dkrotil thanks! I´ll rename the milestone. The next release will be `v1.5.0`.
- The new _PHP_ `v7.1` requirement (current `v7.0`) is the reason for it.

**Comment by exodus4d** [comment]
#### More changes:
- _Redis_ databases can now be _flushed_ individually from `/setup` page: 
![gkjjhhn](https://user-images.githubusercontent.com/9299033/52481632-51040580-2baf-11e9-8583-26f5f1eff900.png)
- Cached **TEMP** files (e.g. compiled HTML templates) in dir (default: `tmp/`) can now be deleted from `/setup` page: 
![2cv1ili](https://user-images.githubusercontent.com/9299033/52481811-e1dae100-2baf-11e9-85ee-3b159200e848.png)
