### ISSUE TITLE
Parsing of pirate relic sites is inaccurate

### ISSUE THREAD

**Issue by pezz** [exodus4d/pathfinder#747]
Hey there,

Copy+pasting a sig that is a pirate faction relic site generally doesn't work as it should.

It will either:
* Just set the sig type to Relic and produce no other output on the row
* Set the sig type to Relic and add the type of site as a comment
* Paste as a Relic but put in the completely wrong name (i.e. a Ruined Guristas Whatever could be added as a Sansha Crystal Quarry)

I never see any issues with Gas sites or even with Sleeper Relic sites (i.e. Forgotten).

Cheers.

**Comment by exodus4d** [comment]
could you please past in here some example scan results that include pirate relict sides in here? Then I can see and add them.
if the type shows "as a comment" that´s the _fallback_ if no other type match, so it is just missing yet.
The name of the system would be nice as well, not each site shows up in each region,...

**Comment by pezz** [comment]
```TMQ-388	Cosmic Signature	Relic Site	Ruined Guristas Temple Site	100.0%	63.01 AU```

![screenshot_2019-02-05 pathfinder](https://user-images.githubusercontent.com/372177/52251037-f5d3d800-294e-11e9-8ac1-b5c876df6e18.png)

**Comment by pezz** [comment]
With the wormhole I just scanned, this is how all of the Relic sites pasted.

![screenshot_2019-02-05 pathfinder 1](https://user-images.githubusercontent.com/372177/52252145-db9cf880-2954-11e9-85c5-d6de4e81d657.png)

Also the Data site above is from the same wormhole.

This is out of the ordinary for what I normally see, the first example I posted, TMQ, where the name is simply wrong is what I see most often.

**Comment by pezz** [comment]
```THA-612	Cosmic Signature	Relic Site	Forgotten Frontier Quarantine Outpost	100.0%	5.10 AU```
```TQT-021	Cosmic Signature	Relic Site	Ruined Serpentis Monument Site	100.0%	11.14 AU```

![screenshot_2019-02-06 pathfinder](https://user-images.githubusercontent.com/372177/52325934-fea1d800-2a3a-11e9-9394-baff93b94d1b.png)

**Comment by pezz** [comment]
Forgottens always seem to paste fine.

Anyway, I'll stop with the comments unless you want me to keep adding things, but pretty much every pirate Relic site never pastes properly.

**Comment by pezz** [comment]
Actually, one more... :)

```VFU-907	Cosmic Signature	Relic Site	Ruined Blood Raider Science Outpost	100.0%	4.61 AU```

![screenshot_2019-02-06 pathfinder](https://user-images.githubusercontent.com/372177/52326093-90a9e080-2a3b-11e9-8708-c1fa8496ad1d.png)

**Comment by exodus4d** [comment]
@pezz Thanks, what I need to know is the **System name** (or wormhole JXXXXXX name) with your scan result information. Then I could add the missing names.

**Comment by pezz** [comment]
Hmm, nah I don't have that info now.

I live in a C4 with a C3 static, so there's a new C3 every day.

Are you sure that "missing" names are the problem? I always seem to be able to correct the info manually. Any type of pirate relic / data site can spawn in C3s and below (and C13s), so I don't understand why having the Jxxxxxx would help?

**Comment by pezz** [comment]
![pf](https://user-images.githubusercontent.com/372177/53952216-59a31980-4124-11e9-8aac-28465941e4f9.png)

To further demonstrate, what gets pasted is in the pasted field and what the site actually is I have put in the description.

Very broken.

**Comment by jmac077** [comment]
They're parsed incorrectly because x-editable does not guarantee order when converting objects to source data for lists. Even though the relic/data sites are given specific int values in /js/app/conf/signature_type.js when itemsByValue is called in /js/app/ui/module/system_signature.js

let selected = $.fn.editableutils.itemsByValue(value, sourceData);

x-editable converts the object definition to an array where it is given the next consecutive int value. The object int values used when the type is encoded are not consecutive so you get a different name when they're decoded to text due to removing the gap in the int values created in the object definitions in signature_type.js.

**Comment by exodus4d** [comment]
@pezz Thanks for your report! I could finally reproduce the issue with the scann results you posted here.

@jmac077 This was not a problem with the "_parsing_" function, or _xEditable_ plugin. The main issue here was, that I used two different function for getting the `typeId` of a pasted signature scan result and generating all available **type** select options afterwards.... my bad :(

**Comment by pezz** [comment]
This is working much, much better now - thanks a bunch for the fix.

The only quirk I noticed tonight was with this sig:

```GUL-500    Cosmic Signature    Data Site    Superior Guristas Covert Research Facility    100.0%    6.50 AU```

"Superior Guristas Covert Research Facility" was put into the description field and not the type field.

Cheers.

**Comment by pezz** [comment]
I just worked out why it pasted like that (yeah, took me longer enough heh).

It's because that ghost site spawned in my C4 and you only allow the selection of the sleeper data sites as a type for C4s.
