### ISSUE TITLE
[Feature] Basic monitoring for ESI endpoints used by Pathfinder

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#748]
The main objective in `v1.5.0` is to make _Pathfinder_ more _stable_, reduce the number of 5xx responses send to the clients that result in failed ESI api requests and implement multiple "failover" scenarios for bad responses. 
So most of the changes were made in [exodus4d/pathfinder_esi](https://github.com/exodus4d/pathfinder_esi) repository (checkout the updated [README.md](https://github.com/exodus4d/pathfinder_esi/tree/develop) for more technical information..)

I thought it might be useful, to implement some kind of _basic_ "ESI monitoring" UI for _Pathfinder_ users. There is no need to "monitor" ESI as a whole, its more important to *only* list endpoints that are used by _Pathfinder_. Those endpoints are now automatically shown in the new UI and status information is pulled from _CCPs_ "status" endpoint.
- cached for 60s
- new information in `/login` page with ESI status
- new information dialog with ESI endpoints information

##### Color codes
- **green**: Endpoint is OK
- **yellow**:  Degraded, meaning slow or potentially dropping requests
- **red**: Means most requests are not succeeding and/or are very slow (5s+) on average

![h7dwi2h](https://user-images.githubusercontent.com/9299033/52227929-43016c80-28b1-11e9-851f-71a68b40c279.png)

![rcitjuq](https://user-images.githubusercontent.com/9299033/52227933-4563c680-28b1-11e9-866f-33bb4bc9e184.png)

**Comment by CalMatar** [comment]
This system is not working.

**Comment by CalMatar** [comment]
As you can see from the screenshot, I do not show up in a ship, nor do I show up in the wormhole I am currently logged into in and I can not even get the routes to the systems from the K-Space system highlighted on the map. I have been having additional problems lately where I have even had trouble logging in where it told me I was not authorized and I am the one that created the maps.

![screenshot_19](https://user-images.githubusercontent.com/42744905/52968802-5cf48200-337c-11e9-8e34-96e2f9894cdf.png)
