### ISSUE TITLE
using xampp to host pathfinder

### ISSUE THREAD

**Issue by dynius** [exodus4d/pathfinder#749]
been having trouble getting this source to work using xampp has it been tried?

**Comment by exodus4d** [comment]
Unfortunately not. If you are on Windows, I suggest using [WinNMP - Nginx MariaDB Redis Php 7 development stack for Windows](https://winnmp.wtriple.com/) . I use this on my Windows dev VM and comes along with all the required packages for _Pathfinder_ (this includes _Redis_ which should be used as cache backend and/or PHP Session handler)
