### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by gdeld** [exodus4d/pathfinder#75]
Again, not sure what is your take on the topic; a backend where some sort of administrator can define roles for user, type of maps that a user can create/delete/share would be very useful.

**Comment by exodus4d** [comment]
Same here (#74) :)

When i started developing this tool in 2014, I thought about smaller groups using this tool some day. e.g. Day-Trippers into w-space. Small Corps up to 30 players or W-Space PI indu-chars who could need a handy mapping tool :) My vision is, that w-Space gets more populated, and more game content will be available in w-space if everyone could have an easy to use mapping tool for free.

But now a days more and more larger groups are interested in using it. I know that admin roles are required for them to protect their "intel",... Those groups are self-reliant enough with a large number of IT-Specialists and software developers. If they need some kind of "advanced" role management, they can easy program it on top of *PATHFINDER* ;) 

Some kind of "light" role management might be implemented in the future. But this is not a high priority for me.
