### ISSUE TITLE
Production Pathfinder running 1.5.0

### ISSUE THREAD

**Issue by CurryFurious** [exodus4d/pathfinder#751]
Not sure if this has been made aware, or if its planned, but the current production pathfinder seems to be having a couple of errors connecting with ESI and updating player location.
Bugs:
The Characters being tracked occasionally drop from the map, and it says there in unknown space. Then, after some amount of time, the character will appear again in the system you are in. This cycle would repeat, where characters won't be tracked for a time.

**Comment by rangvaldr** [comment]
exodus updated it today to be on the dev branch.

What are the errors?

**Comment by CurryFurious** [comment]
Looks like it was just a temporary thing, main page seems to be working now. Closing.

**Comment by CurryFurious** [comment]
Well, it momentarily worked, sorry about reopening this again. Here are what I see: 
https://i.imgur.com/tduZybB.png
My character is currently chilling in "Atlas", however it does not detect that the character is in system there.
There are no console errors, and it seems that the response body from /api/map/updateUserData seems to be functioning normally, albeit having current character location.

**Comment by Coulua** [comment]
I got the same problems.

**Comment by aalfath** [comment]
Have you guys fixed this problem? I just upgraded to v1.5 and I'm having this problem as well.

**Comment by dagoaty** [comment]
If you're running your own install of PF, it sounds like you might be hitting the same problem as #760. Try my instructions in https://github.com/exodus4d/pathfinder/issues/760#issuecomment-469082039

**Comment by CalMatar** [comment]
I am having the same issues but on the public PF server. I am in the process of trying to get a computer set up to install PF on and possibly stop some of these issues but until then I am getting frustrated by all of the "lag" time waiting for PF to catch up to where I am so I can keep adding WHs or connections. It is getting frustrating that I have to actually set up my own server just because the public server has not gotten straightened out since the ESI change. I love PF and even though I have had members in my alliance want to go back to TW I keep telling them PF is much better.

**Comment by verunightscout** [comment]
No sure , what are you trying to say. Exodus public server is free, If you send him some money to upgrade VPS, that make some noise, but till then install your own PF server like many of us !

**Comment by CalMatar** [comment]
@verunightscout IF I had the money to send him to help support the public server I would and wouldn't have to scrounge old pc's to get a computer together to set up a server to try to set up my own PF server but unlike you I am on a fixed income and have to deal with what I have so telling me to spend money is not going to fix the problems that I have already reported in another trouble ticket and as I have already noted above I AM trying to set up my own server so your keep your snide comments to yourself. If you are not going to be helpful shut up.

**Comment by exodus4d** [comment]
#### Explanation:
The issue you described is responsible for some other recently created Issues as well.
First of all, this was not an issue with the code itself. It was a bad **firewall** configuration on my public VPS.

Sorry for late response to this issue! The lack of time on my side, plus some missing _admin_ knowledge  were responsible for that.

#### What happend:
I use a mix of 3rd party tools that manage `iptables` rules/settings to ban suspect connections/ddos/...:
- _[firewalld](https://firewalld.org)_
- _APF_ ([Advanced Policy Firewall](advanced-policy-firewall))

A bad config setting for _APF_ blocks _API_ requests to _CCP´s_ primary `https://esi.evetech.net` from _time to time_ ... There are 3 IPs behind that API (=>[DNS lookup](https://www.dnsqueries.com/en/dns_lookup.php)). If **first** IP get blocked, _ESI_ requests could still use the 2nd/3rd IP which results in longer response times... then _APF_ blocked 2nd and later 3rd IP as well and no _ESI_ requests could be made... The time until _un-ban_ an IP was to long, which leads to the problem where no _ESI_ calls could not be made until first IP gets _un-banned_.

I finally fixed the _APF_ settings, and know where to look at if the problem happens again. Please retry and give feedback if you see the problem again.
