### ISSUE TITLE
[feature request] decay system within 1 hour if no wh information is entered

### ISSUE THREAD

**Issue by Solid-State-Society** [exodus4d/pathfinder#752]
To auto purge incorrect connections by jumpcloning or tollgating, how about implementing a function that deletes any system within one hour if no user has entered the corresponding wh information in said system?

**Comment by Sakata-MC** [comment]
Better solution would be to detect if player is in pod and don't create new systems or connections if they're in a pod. Would also remove the issue of podding/self-destructing causing the same problem as well.

**Comment by Solid-State-Society** [comment]
that would not address toll gates, unfortunately

**Comment by exodus4d** [comment]
@Solid-State-Society Thanks for your suggestion! Could you describe what you mean with "tollgating" please?
@Sakata-MC Connections created in case of _podding_ should now be fixed:

- New _ESI_ API endpoint for [Clones](https://esi.evetech.net/ui/#/Clones) added
- Characters home clone location (structure/station) now stored to character data on login
- New connection will **not** get added if a "pod jump" is detected:
  1. Current shipType == `capsule`
  2. Current character location (structure/station) matches home clone location
  3. Jump distance between systems > 1

There is just one case, where the new logic will fail:
- Character is in a `capsule`, sitting in a _wh_ that leads directly to your home clone system. And you manage to jump into the systems, warp to your home clone structure/station and dock within < 5s.

**Comment by Solid-State-Society** [comment]
by tollgating I just mean the new jump bridging, taking the player made gates that you have to pay a fee for

Outlook fur Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by tralafiti** [comment]
Is it possible that this issue was reintroduced? We see connections to Jita after someone podded himself on our maps on a daily basis. The capsule itself doesn't seem to trigger it, but as soon as you board a ship in Jita a connection is created. Could it be related to the addition of the jump history feature?

**Comment by exodus4d** [comment]
@tralafiti indeed, the jump history is most likely the issue. Are you able to test two code versions that might fix it under "real life" conditions? - Just temporary change a few code lines, and give me feedback it there is no new connection made after pod kill + ship change in clone location?
***
### Version A: 
_Fail-Safe_ version, flushes jump history after podding detected. (downside of this is, that jump history disappears from UI)
Replace this...
https://github.com/exodus4d/pathfinder/blob/f443e8016f4a3f79c126b661b24b637101cb69dd/app/main/controller/api/map.php#L1171-L1173
... with...
```php
if(!$route['routePossible']){
    $character->clearCacheDataWithPrefix(Pathfinder\CharacterModel::DATA_CACHE_KEY_LOG_HISTORY);
    $addConnection = false;
}
```
***
### Version B: 
More elegant but higher complexity - needs more testing. We **break out** of the loop that iterates over all historic jumps and looks for the last relevant history entry.
Replace this...
https://github.com/exodus4d/pathfinder/blob/f443e8016f4a3f79c126b661b24b637101cb69dd/app/main/model/pathfinder/charactermodel.php#L1247-L1249
... with... (add new if below the existing)
```php
if(!empty((array)$historyEntry['mapIds'])){
    $skipRest = true;
}

if(
    !$skipRest &&
    (
        'station' == $this->cloneLocationType &&
        $this->cloneLocationId == (int)$historyEntry['log']['station']['id']
    ) || (
        'structure' == $this->cloneLocationType &&
        $this->cloneLocationId == (int)$historyEntry['log']['structure']['id']
    )
){
    $skipRest = true;
}
```

**Comment by tralafiti** [comment]
@exodus4d Version B is active on our server now, will give you feedback in a few days. Thanks!

**Comment by tralafiti** [comment]
We are still seeing connections being created when someone is podded. Usually when the podded pilot leaves the station, doesn't seem to matter if he's in a ship or still in his pod

**Comment by exodus4d** [comment]
OK, thanks for feedback. I think I don´t get around making some extensive testing for this issue :(
