### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Chris-Epler** [exodus4d/pathfinder#753]
I'm unable to login to the main site at:

https://www.pathfinder-w.space/

I receive an error:

Access denied Failed to load characterData from ESI

I've cleared cache/cookies.  I've deleted and reauthed SSO...

Are there currently login issues?

**Comment by pezz** [comment]
It was broken for a while yesterday as well.

Any word from the devs on this?

**Comment by jackaryas** [comment]
Im getting this on a fresh installation of PF and sporadically on the production version, do we know if this is ESI related?

**Comment by jackaryas** [comment]
FYI - i changed the composer version of pathfinder_esi from `dev-master#v1.2.5` to `1.2.5` and it seems to be working @exodus4d , not sure if something has changed on the ESI side but this seems to be present in current master branch code (havent tried develop) 

First PF installation so not sure if this is something thats been noticed before or something new

**Comment by porowns** [comment]
Update your `environment.ini`... ` CCP_ESI_URL                 =   https://esi.evetech.net`

**Comment by pezz** [comment]
How does that help people using the public server?

**Comment by porowns** [comment]
Public server is essentially a preview dude

**Comment by tralafiti** [comment]
> FYI - i changed the composer version of pathfinder_esi from `dev-master#v1.2.5` to `1.2.5` and it seems to be working @exodus4d , not sure if something has changed on the ESI side but this seems to be present in current master branch code (havent tried develop)
> 
> First PF installation so not sure if this is something thats been noticed before or something new

yep, the version as listed in `composer.json` always installes the last commit of the master branch and since a few weeks that's the rewrite of the esi-module which is incompatible to older pathfinders. Either versioning the `compose.lock` file or removing the `dev-master#`-prefix in `composer.json` as you did fixes this.

**Comment by exodus4d** [comment]
@jackaryas @tralafiti Thanks! - I tested your fix in `composer.json`. Looks good! 
I mixed up the syntax for **#commitHash** and **gitTag**. See Stackoverflow: "[Specific tag/version with composer](https://stackoverflow.com/a/41471934/4329969)!
