### ISSUE TITLE
[HELP] Timeout 504

### ISSUE THREAD

**Issue by azunitexite** [exodus4d/pathfinder#756]
SELFHOSTED INSTALL 1.4.3

Keep getting a 504 timeout after 15-20 minutes of inactivity - I presume this may be due to token not being refreshed or something?

Another thing that is not quite as important but still annoying me is that on the home page, the characters are not saved and I need to log in each time. 

If anyone could shed some light on this I would really appreciate it! 

Cheers

From the logs:

[10:51:02] ───────────────────────────
  type:     error
  code:     504
  status:   HTTP 504: 'Gateway Timeout' | url: POST 'https://login.eveonline.com/oauth/token' | body: stdClass Object
(
    [access_token] => pqgjKUuT5QrYChzpC3XsSRrtojm6AyMeza_xX2Mh6qh0dev78PTFZ2CFizpj1NU9tZshjuyhC4kUGvdQboJ5KQ2
    [token_type] => Bearer
    [expires_in] => 1199
    [refresh_token] => Dd4_Xai22Llkizyt1wLoTEUdIluqUUTyKjeF3sWTndbpv7yvfQEeWnUTXlRwMDuc7QtCrdtHkoIMGd1pfdpXUA2
)

Seems the cookie is not getting stored or refreshed correctly.

**Comment by TilleyTech** [comment]
Im getting the same problem, anyone have any ideas?

**Comment by TilleyTech** [comment]
Just thought i would post an extract from my error log. Definitely seems like an issue refreshed. Access tokens hashed out in case its a security issue

Tue, 26 Feb 2019 23:42:39 +0000 [86.17.117.225] HTTP 504: 'Gateway Timeout' | url: POST 'https://login.eveonline.com/oauth/token' | body: stdClass Object
(
    [access_token] => ##############################
    [token_type] => Bearer
    [expires_in] => 1200
    [refresh_token] => ##############################
)

**Comment by azunitexite** [comment]
> Just thought i would post an extract from my error log. Definitely seems like an issue refreshed. Access tokens hashed out in case its a security issue
> 
> Tue, 26 Feb 2019 23:42:39 +0000 [86.17.117.225] HTTP 504: 'Gateway Timeout' | url: POST 'https://login.eveonline.com/oauth/token' | body: stdClass Object
> (
> [access_token] => ##############################
> [token_type] => Bearer
> [expires_in] => 1200
> [refresh_token] => ##############################
> )

did you ever find a fix to this?

**Comment by TilleyTech** [comment]
upgrade it to the 1.5 version. It was in the dev branch when i did it and worked perfectly.

**Comment by azunitexite** [comment]
> upgrade it to the 1.5 version. It was in the dev branch when i did it and worked perfectly.

is there any documentation on the upgrade process? or is it just a case of wiping and reinstalling from the dev branch

**Comment by exodus4d** [comment]
This is a known bug in `1.4.3` please upgrade to `1.5.x`
