### ISSUE TITLE
ESI Endpoints keep erroring and timing out causing disconnects

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#759]
As I reported in the previous thread for the #748 that the ESI endpoints monitoring was not working correctly but you closed that thread so I am opening a new thread to cover the fact that the ESI problem still exists and is leading to major headaches with Pathfinder on the main public server. I keep having extremely long time waits for the ESI lookups during which I am not connected to Pathfinder, and subsequently no one is to our maps, and they are getting frustrated and talking about leaving to move over to Tripwire. 
I do not want to do that as I have loved Pathfinder since I have found it but this "enhancement" has been anything but. It has been nothing but a headache since it was implemented. 
Is there something that and be done if Pathfinder is self hosted and not on the public server?

**Comment by CalMatar** [comment]
I have an update on this issue. The login part is working but the automatic updating when you jump into new wormholes and the populating into the map do not work correctly. When you try to add the new system manually it does not like to add it either. I am not sure if this is part of the problem but it seems to be correlating with it. 
I would like to know if this is just a problem with the public server or if this is a problem with Pathfinder as a whole. If it is only on the public server I will find a way to self host a server on my own and then we can go about correcting these issues that way. 
Please let me know one way or the other.

**Comment by CalMatar** [comment]
@exodus4d are there any updates on the issues that have been going on with this?

**Comment by exodus4d** [comment]
Yeah this was a bad config with the fiewawall setup I used. Not a problem with the Pathfinder code itself.
See: https://github.com/exodus4d/pathfinder/issues/751#issuecomment-484596383
