### ISSUE TITLE
Maps update

### ISSUE THREAD

**Issue by gdeld** [exodus4d/pathfinder#76]
It looks like that maps are separate objects and updating a personal map doesn't affect a corp or alliance map. Also updating a corp or alliance map doesn't update a personal map.

**Comment by exodus4d** [comment]
There is already an issue about that (#65).

My explanation: https://github.com/exodus4d/pathfinder/issues/65#issuecomment-157490261

I know, the current way, how maps will be updated is not very tranparent to the user. But there is a reason for that behaviour. Maybe Ill think about a new map-option, some kind of "toggle remote update". If set to true, this map will receive new systems from other maps. If you have a better idea for that let me know it ;)
