### ISSUE TITLE
405 Error after update to 1.5.0

### ISSUE THREAD

**Issue by TrinityErik** [exodus4d/pathfinder#762]
Getting this error when hitting the login button on the main page now.  Everything was good before updating.  Not sure where to look for the problem here.  Any help?

`Status: "HTTP 405 (GET /sso/ArrayArray?response_type=code&amp;redirect_uri=https%3A%2F%2Fpathfinder.example.com%2Fsso%2FcallbackAuthorization&amp;client_id=123456789123456789123456789&amp;scope=esi-corporations.read_corporation_membership.v1%20esi-location.read_location.v1%20esi-location.read_online.v1%20esi-location.read_ship_type.v1%20esi-ui.open_window.v1%20esi-ui.write_waypoint.v1%20esi-universe.read_structures.v1&amp;state=a137ac53b2588aa61873fc28?response_type=code&amp;redirect_uri=https%3A%2F%2Fpathfinder.example.com%2Fsso%2FcallbackAuthorization&amp;client_id=123456789123456789123456789&amp;scope=esi-corporations.read_corporation_membership.v1%20esi-location.read_location.v1%20esi-location.read_online.v1%20esi-location.read_ship_type.v1%20esi-ui.open_window.v1%20esi-ui.write_waypoint.v1%20esi-universe.read_structures.v1&amp;state=a137ac53b2588aa61873fc28)".
            Use your browsers Back button to navigate to the page you have previously come from.`

                            Message: Method Not Allowed

**Comment by TrinityErik** [comment]
No idea what this was about.  I pulled a fresh copy of everything down and back to normal.

**Comment by der-micky** [comment]
Same here... Still have that issue...

**Comment by der-micky** [comment]
Ok, "composer update" did the job ...

**Comment by Slivo-fr** [comment]
Yeah the composer.lock isn't under version control, upgrade guide isn't accurate.
You have to run `composer update`
