### ISSUE TITLE
Error 500 repeatedly on map

### ISSUE THREAD

**Issue by TrinityErik** [exodus4d/pathfinder#763]
Wiped out my local repo due to some problems after upgrading from 1.4.3 to 1.5.0 now everything is working great except - when a user logs in and goes to the map page, they get logged out again right away with an Error 500.

My Pathfinder error logs aren't showing anything about it but the Apache2 error.log shows the following:

`[Tue Mar 12 20:56:59.116829 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] mkdir(): Permission denied, referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116870 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/league/flysystem/src/Adapter/Local.php:375] mkdir(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116875 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/league/flysystem/src/Filesystem.php:262] League\\Flysystem\\Adapter\\Local->createDir(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116878 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/cache/filesystem-adapter/FilesystemCachePool.php:47] League\\Flysystem\\Filesystem->createDir(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116881 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [app/main/lib/api/AbstractClient.php:156] Cache\\Adapter\\Filesystem\\FilesystemCachePool->__construct(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116884 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractApi.php:737] lib\\api\\AbstractClient->lib\\api\\{closure}(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116887 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractApi.php:726] Exodus4D\\ESI\\Client\\AbstractApi->getCacheMiddlewareStorage(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116891 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractApi.php:682] Exodus4D\\ESI\\Client\\AbstractApi->getCacheMiddlewareStrategy(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116894 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractCcp.php:22] Exodus4D\\ESI\\Client\\AbstractApi->initStack(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116897 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractApi.php:634] Exodus4D\\ESI\\Client\\AbstractCcp->initStack(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116900 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Lib/WebClient.php:51] Exodus4D\\ESI\\Client\\AbstractApi->Exodus4D\\ESI\\Client\\{closure}(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116903 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractApi.php:635] Exodus4D\\ESI\\Lib\\WebClient->__construct(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116906 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractApi.php:304] Exodus4D\\ESI\\Client\\AbstractApi->initClient(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116909 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/AbstractApi.php:793] Exodus4D\\ESI\\Client\\AbstractApi->getClient(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116912 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [vendor/exodus4d/pathfinder_esi/app/Client/ESI.php:175] Exodus4D\\ESI\\Client\\AbstractApi->request(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116914 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [app/main/controller/api/map.php:882] Model\\CharacterModel->updateLog(), referer: https://pathfinder.example.com/map/MTI%3D
[Tue Mar 12 20:56:59.116927 2019] [php7:notice] [pid 16997] [client xxx.xxx.xxx.xxx:3287] [index.php:20] Base->run(), referer: https://pathfinder.example.com/map/MTI%3D`

**Comment by rangvaldr** [comment]
Looking at the stack trace, pathfinder_esi is failing to create a log directory due to a permissions denied error.

Make sure both your log and cache directories exist, and that they're writable by the webserver.

**Comment by TrinityErik** [comment]
Both directories are there, both directories have permissions and were not touched after the upgrade, where they working fine prior.

**Comment by pezz** [comment]
I had this issue and discovered that there's a missing instruction, in the root of your main pathfinder install, create a cache directory:
```drwxr-xr-x  2 http http  4096 Feb 20 14:34 cache```

This is in addition to the one that is in DOCROOT/tmp/cache

**Comment by TrinityErik** [comment]
That did the trick, thank you dude!

**Comment by exodus4d** [comment]
@TrinityErik Thanks for your report! I fixed the bug in 346209d . You can either wait for the next release, or replace the changed lines.

#### Problem
The cache backend set in `config.ini` → `API_CACHE` is used as cache backend in [pathfinder_esi](https://github.com/exodus4d/pathfinder_esi) API client. The default value `folder=tmp/cache/` defines a **filesystem** based cache backend. Unfortunately there is a default dir used (created) named 'cache' if no folder is provided. Switching to the correct dir `tmp/cache/` afterwards still remains with the default 'cache' dir.
