### ISSUE TITLE
Not tracking player locations

### ISSUE THREAD

**Issue by joshbrown50** [exodus4d/pathfinder#764]
I've just installed my own instance of pathfinder, and everything seems to be functioning correctly. Except for player tracking. I have my location settings set to on, and the task manager shows it polling map data every 5 seconds or so. I have tried for hours to figure out what I am doing wrong. There aren't any errors that I can see. Everything I can find points to it supposed to be working, but my character doesn't show up on the map and it doesn't add any systems I jump through. I don't even know what information I need to be linking here so I can be helped. So if you have any ideas, I'm all ears. And I will post whatever information you need to know.

--Edit--
I Have gone through the ESI Requests log and I'm getting a bunch of errors saying 403 Forbidden. It seems like its somehow being denied access to ESI, but I can't really tell.

[esi_requests.txt](https://github.com/exodus4d/pathfinder/files/2971742/esi_requests.txt)

**Comment by aalfath** [comment]
@joshbrown50 you might want to check this comment: https://github.com/exodus4d/pathfinder/issues/760#issuecomment-469076302

That fixed the problem for me.

**Comment by joshbrown50** [comment]
That did not fix my issue because I’m not upgrading. I’m making a fresh install. So the databases should have been set up correctly from the get go.

**Comment by joshbrown50** [comment]
That did not fix my issue because I’m not upgrading. I’m making a fresh install. So the databases should have been set up correctly from the get go.

**Comment by verunightscout** [comment]
With ESI http error 403, how looks like your application registration ? 
Do you have Client ID: , Secret Key: , Callback URL: ? If you are on non-standard https port, this need to be part of Callback URL ...

**Comment by joshbrown50** [comment]
> With ESI http error 403, how looks like your application registration ?
> Do you have Client ID: , Secret Key: , Callback URL: ? If you are on non-standard https port, this need to be part of Callback URL ...

I'm using http. And I do have client ID, Secret Key and Callback URL set up. You can log in with your character fine. Its once you log in that it won't track you.

**Comment by olanguedoc** [comment]
I am experiencing the same issue but with the Online public version. Position tracking is very laggy. I feel like the whole system is actually under a constant load....

**Comment by exodus4d** [comment]
This is a duplicate issue that should be fixed on the public installation: https://github.com/exodus4d/pathfinder/issues/751#issuecomment-484596383
