### ISSUE TITLE
[Feature Request] Automatic system positioning for wormholes

### ISSUE THREAD

**Issue by Kashada** [exodus4d/pathfinder#766]
It would be good to add an option that line up systems in a certain order when they are added, so that they do not need to be moved by hand. Tripwire works on a similar principle.
![Screenshot_1](https://user-images.githubusercontent.com/48582073/54428438-540a8c80-473f-11e9-8550-3293f6eba7a1.png)

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #201
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
