### ISSUE TITLE
Error 500 in Admin area

### ISSUE THREAD

**Issue by integral0** [exodus4d/pathfinder#768]
`PHP message: PHP Fatal error:  Declaration of Controller\Admin::getLogger($type = 'ADMIN') must be compatible with Controller\Controller::g etLogger($type = 'DEBUG'): Log in /srv/www/pathfinder/htdocs/app/main/controller/admin.php on line 19
`
Hello. Can you please tell me how to fix it?

**Comment by tralafiti** [comment]
Fixed here https://github.com/tralafiti/pathfinder/commit/e545fb7d131e04949927f75f23a10cb591d0e5d6

**Comment by integral0** [comment]
it's work. Thank you!

**Comment by rangvaldr** [comment]
This should stay open until exodus fixes it, since it is a bug.

**Comment by netmonster01** [comment]
+1

**Comment by exodus4d** [comment]
Thanks for reporting, will be fixed with this commit:
https://github.com/exodus4d/pathfinder/commit/c21e33d2314c341e71f999617ff7329c524fb99f#diff-23790c41cf23c3c5b24b709043c1d40aR351
