### ISSUE TITLE
Mac OSX Browser

### ISSUE THREAD

**Issue by cdcoutinho** [exodus4d/pathfinder#769]
I can't expand the main window of the map.
In Safari the icon to expand does not appear, in other browsers it doesn't work.
Any workaround?

**Comment by High-Lander** [comment]
Usually works in Chrome

**Comment by exodus4d** [comment]
The "resize" feature for maps is based on the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#Browser_compatibility) Web API, and is only supported by Chrome (at the time of writing this).
There is a "Polyfill" for Firefox added to enable resizing for it.
**Safare is not official supported.**
Code: https://github.com/exodus4d/pathfinder/blob/master/js/app/map/map.js#L868
