### ISSUE TITLE
Upgrade 1.4.3 to 1.5 - Composer issue

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#770]
Hi,

I upgrade my php from 7.0.33 to 7.3. And, after, I do the command "sudo composer install".

```
Loading composer repositories with package information       Updating dependencies (including require-dev)         

  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

Do you have an idea to how debug this issue?

Thanks a lot.

**Comment by DLB82** [comment]
> damien@VPS-Damien:/opt/pathfinder$ sudo composer install -vv
> Loading composer repositories with package information
> 
> Could not fetch https://api.github.com/repos/exodus4d/pathfinder_esi, please create a GitHub OAuth token to go over the API rate limit
> Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+VPS-Damien+2019-03-30+1005
> to retrieve a token. It will be stored in "/home/damien/.composer/auth.json" for future use by Composer.
> Token (hidden):
> No token given, aborting.
> You can also add it manually later by using "composer config github-oauth.github.com <token>"
> Your GitHub credentials are required to fetch private repository metadata (https://github.com/exodus4d/pathfinder_esi)
> Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+VPS-Damien+2019-03-30+1006
> to retrieve a token. It will be stored in "/home/damien/.composer/auth.json" for future use by Composer.
> Token (hidden):
> No token given, aborting.
> You can also add it manually later by using "composer config github-oauth.github.com <token>"
> 
> Could not fetch https://api.github.com/repos/exodus4d/pathfinder_esi, please create a GitHub OAuth token to go over the API rate limit
> Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+VPS-Damien+2019-03-30+1006
> to retrieve a token. It will be stored in "/home/damien/.composer/auth.json" for future use by Composer.
> Token (hidden):
> No token given, aborting.
> You can also add it manually later by using "composer config github-oauth.github.com <token>"
> 
> 
>   [Composer\Downloader\TransportException]
>   Could not authenticate against github.com
> 
> 
> Exception trace:
>  () at /usr/share/php/Composer/Util/RemoteFilesystem.php:559
>  Composer\Util\RemoteFilesystem->promptAuthAndRetry() at /usr/share/php/Composer/Util/RemoteFilesystem.php:525
>  Composer\Util\RemoteFilesystem->callbackGet() at n/a:n/a
>  file_get_contents() at /usr/share/php/Composer/Util/RemoteFilesystem.php:289
>  Composer\Util\RemoteFilesystem->get() at /usr/share/php/Composer/Util/RemoteFilesystem.php:99
>  Composer\Util\RemoteFilesystem->getContents() at /usr/share/php/Composer/Repository/Vcs/VcsDriver.php:107
>  Composer\Repository\Vcs\VcsDriver->getContents() at /usr/share/php/Composer/Repository/Vcs/GitHubDriver.php:317
>  Composer\Repository\Vcs\GitHubDriver->getContents() at /usr/share/php/Composer/Repository/Vcs/GitHubDriver.php:405
>  Composer\Repository\Vcs\GitHubDriver->fetchRootIdentifier() at /usr/share/php/Composer/Repository/Vcs/GitHubDriver.php:64
>  Composer\Repository\Vcs\GitHubDriver->initialize() at /usr/share/php/Composer/Repository/VcsRepository.php:91
>  Composer\Repository\VcsRepository->getDriver() at /usr/share/php/Composer/Repository/VcsRepository.php:119
>  Composer\Repository\VcsRepository->initialize() at /usr/share/php/Composer/Repository/ArrayRepository.php:179
>  Composer\Repository\ArrayRepository->getPackages() at /usr/share/php/Composer/DependencyResolver/Pool.php:104
>  Composer\DependencyResolver\Pool->addRepository() at /usr/share/php/Composer/Installer.php:402
>  Composer\Installer->doInstall() at /usr/share/php/Composer/Installer.php:228
>  Composer\Installer->run() at /usr/share/php/Composer/Command/InstallCommand.php:134
>  Composer\Command\InstallCommand->execute() at /usr/share/php/Symfony/Component/Console/Command/Command.php:256
>  Symfony\Component\Console\Command\Command->run() at /usr/share/php/Symfony/Component/Console/Application.php:841
>  Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Symfony/Component/Console/Application.php:189
>  Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:166
>  Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:120
>  Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:99
>  Composer\Console\Application->run() at /usr/bin/composer:44
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
>

**Comment by DLB82** [comment]
I must do something to have a token? And how set it?

**Comment by Tupsi** [comment]
read for yourself what you posted, it is all there how to do that.

**Comment by DLB82** [comment]
I close this issue. For other guy with my problem, My composer version have problem with php7.3.
With php7.2, it's better. No problem to use compose.

I close this issue but, I have an other issue with db connection.
