### ISSUE TITLE
Upgrade 1.4.3 to 1.5.0 - Error 500

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#771]
Hi,

I have an issue when I upgrade pathfinder.

> HTTP ERROR 500

Apache logs:

> syntax error, unexpected '?', expecting variable (T_VARIABLE) [/opt/pathfinder/app/main/lib/config.php:94]
> [index.php:15] spl_autoload_call()
> PHP Parse error:  syntax error, unexpected '?' in /opt/pathfinder/app/main/db/database.php on line 34
> PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0

I check my conf "environment.ini", all seems be right. An idea to help me?

Thanks a lot.

**Comment by DLB82** [comment]
```
$ php -version
PHP 7.2.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:23:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.16-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by DLB82** [comment]
I try to with php7.1. Same result.

**Comment by DLB82** [comment]
I try too with php 7.3.
Composer 1.8.4.
I try to join the slack channel, because php is not a langage, that I know...

```
$f3->set('getDateTime', function(string $time = 'now', ?\DateTimeZone $timeZone = null) use ($f3) : \DateTime {
            $timeZone = $timeZone ? : $f3->get('getTimeZone')();
           return new \DateTime($time, $timeZone);
        });
```

"?\DateTimeZone" seems the error root cause...

**Comment by DLB82** [comment]
> Package operations: 32 installs, 0 updates, 0 removals
>   - Installing psr/simple-cache (1.0.1): Loading from cache
>   - Installing psr/cache (1.0.1): Loading from cache
>   - Installing psr/log (1.1.0): Loading from cache
>   - Installing cache/tag-interop (1.0.0): Loading from cache
>   - Installing cache/adapter-common (1.1.0): Loading from cache
>   - Installing cache/hierarchical-cache (1.0.0): Loading from cache
>   - Installing cache/array-adapter (1.0.1): Loading from cache
>   - Installing league/flysystem (1.0.51): Loading from cache
>   - Installing cache/filesystem-adapter (1.0.0): Loading from cache
>   - Installing cache/namespaced-cache (1.0.0): Loading from cache
>   - Installing cache/redis-adapter (1.0.0): Loading from cache
>   - Installing doctrine/lexer (v1.0.1): Loading from cache
>   - Installing ralouphie/getallheaders (2.0.5): Loading from cache
>   - Installing psr/http-message (1.0.1): Loading from cache
>   - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
>   - Installing guzzlehttp/promises (v1.3.1): Loading from cache
>   - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
>   - Installing caseyamcl/guzzle_retry_middleware (v2.2): Loading from cache
>   - Installing cache/void-adapter (1.0.0): Loading from cache
>   - Installing exodus4d/pathfinder_esi (dev-master 34859f0): Cloning 34859f0640 from cache
>   - Installing league/html-to-markdown (4.8.1): Loading from cache
>   - Installing react/event-loop (v0.4.3): Loading from cache
>   - Installing evenement/evenement (v2.1.0): Loading from cache
>   - Installing react/zmq (v0.3.0): Loading from cache
>   - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
>   - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
>   - Installing symfony/polyfill-intl-idn (v1.11.0): Loading from cache
>   - Installing symfony/polyfill-iconv (v1.11.0): Loading from cache
>   - Installing egulias/email-validator (2.1.7): Loading from cache
>   - Installing swiftmailer/swiftmailer (v6.2.0): Loading from cache
>   - Installing monolog/monolog (1.24.0): Loading from cache
>   - Installing websoftwares/monolog-zmq-handler (0.2.2): Loading from cache

**Comment by DLB82** [comment]
Php7.3 not correctly define in the apache config.
Closed.

**Comment by porowns** [comment]
@DLB82 `Php7.3 not correctly define in the apache config.` What was your resolution? Having the same issue
