### ISSUE TITLE
zmq problem with composer

### ISSUE THREAD

**Issue by VAntico** [exodus4d/pathfinder#778]
[....]# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-zmq >=1.1.3 has the wrong version (@PACKAGE_VERSION@) installed. Install or enable PHP's zmq extension.

[.....]# php --ri zmq

zmq

ZMQ extension => enabled
ZMQ extension version => @PACKAGE_VERSION@
libzmq version => 4.1.4
[.......]# php -v
PHP 7.3.5 (cli) (built: Apr 30 2019 08:37:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
[.......]#

**Comment by VAntico** [comment]
[......]# pecl install zmq-beta
pecl/zmq is already installed and is the same as the released version 1.1.3
install failed
[.......]#

**Comment by tralafiti** [comment]
As a quick fix you can use composers `--ignore-platform-reqs` flag. 

The next version of pathfinder won't need the zmq-extension anymore and hence be compatible with php 7.3 (there is no official zmq build for php 7.3, that's why there is no version for the extensions available leading to the @PACKAGE_VERSION@ fallback)

**Comment by exodus4d** [comment]
@VAntico : ´[v1.5.1](https://github.com/exodus4d/pathfinder/releases/tag/v1.5.1) is out now. All the _ZMQ_ stuff is no longer required. 
_PHP_ `7.3` is not tested yet. Feel free to report any 7.3 related bugs. I´ll upgrade my dev-env to 7.3 the next days.
