### ISSUE TITLE
DB hostnames cannot contain hyphens or underscores

### ISSUE THREAD

**Issue by shockkolate** [exodus4d/pathfinder#780]
After updating to v1.5.1, DB hostnames can no longer contain hyphens or underscores in them, even though these are valid hostname characters.

For example, setting the host for `DB_PF_DNS` to "mariadb-pathfinder" results in it being parsed as "mariadb", which is wrong.

**Comment by exodus4d** [comment]
@shockkolate Thanks for reporting. I had to update the Regex for parsing the DNS string. Ill fix this soon!
I updated the Regex test for the new Regex with your example:
https://regex101.com/r/VWml7X/3
