### ISSUE TITLE
Systems showing 0/0 at setup

### ISSUE THREAD

**Issue by shockkolate** [exodus4d/pathfinder#781]
We’re having an issue setting up Pathfinder where the number of systems on the setup page to be built is displaying as 0/0.

Whether we click clear or build, it always goes green but remains at 0/0, and we get an internal server error when trying to actually track a user, due to something about it not being a valid system ID.

Do you have any insight on what may be causing this issue for us? We’ve looked through the existing issues but can’t seem to find anything related or similar.

**Comment by exodus4d** [comment]
It looks like you forget to import the `eve_universe` DB dump see:
https://github.com/exodus4d/pathfinder/wiki/Database#3-import-initial-eve_universesql-db-dump

0/0 means there are no systems that can be indexed... The current system count is read from the `eve_universe` DB. If the dump was loaded you should see something like 0/8235, then you can click the button for indexing.

if this does not help, please let me know.
