### ISSUE TITLE
Upgrade 1.5.0 to 1.5.1 problem : NullSocket.php:36

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#782]
Hi,

I try to upgrade Pathfinder from 1.5.0 to 1.5.1 and when I go to the setup page, I have a 500 error page.

`Status: 'Class 'React\Promise\RejectedPromise' not found [/opt/pathfinder/app/main/lib/socket/NullSocket.php:36]'`

In apache logs, I found :
```
[Wed May 15 12:26:57.851446 2019] [php7:notice] [pid 32575] [client 79.94.114.126:50009] Class 'React\\Promise\\RejectedPromise' not found [/opt/pathfinder/app/main/lib/socket/NullSocket.php:36], referer: https://pathfinder.***/
[Wed May 15 12:26:57.851511 2019] [php7:notice] [pid 32575] [client 79.94.114.126:50009] [app/main/controller/setup.php:1574] lib\\socket\\NullSocket->write(), referer: https://pathfinder.***/
[Wed May 15 12:26:57.851526 2019] [php7:notice] [pid 32575] [client 79.94.114.126:50009] [app/main/controller/setup.php:258] Controller\\Setup->getSocketInformation(), referer: https://pathfinder.***/
```

I follow instructions to upgrade with composer, etc...

Have you an idea to continue this installation?

Thanks a lot.

**Comment by DLB82** [comment]
Problem solved

**Comment by nicti** [comment]
Have the same problem. How did you fix it?
o7

**Comment by DLB82** [comment]
"composer update"
and not "composer install"
