### ISSUE TITLE
getting a 500 after update to 1.5.1

### ISSUE THREAD

**Issue by der-micky** [exodus4d/pathfinder#783]
Log shows something like:

2019/05/16 15:13:39 [error] 22332#22332: *1517 FastCGI sent in stderr: "PHP message: Declaration of Model\Pathfinder\MapModel::newLog($action = ''): lib\logging\LogInterface should be compatible with Model\AbstractModel::newLog(string $action = ''): lib\logging\LogInterface

I corrected it by commenting out the type declaration in .../main/model/abstractmodel.php

with 500 error:
 protected function newLog( **string** $action = '' ) : Logging\LogInterface{

my workaround:
 protected function newLog( /\***string**\*/ $action = '' ) : Logging\LogInterface{

Not sure if that's the intended solution but it did the trick for me :)
Thx,

-Micky

**Comment by exodus4d** [comment]
Thanks for reporting! I haven´t seen the error on my installations so far. 
I fixed it with adding the missing `string` type instead of removing it ;)
