### ISSUE TITLE
Chinese localization of Signature reader

### ISSUE THREAD

**Issue by BlueCat0** [exodus4d/pathfinder#784]
I think its would be helpful for Chinese localization

> combat site -> 战斗地点
> relic site -> 遗迹地点
> data site -> 数据地点
> gas site -> 气云地点
> wormhole -> 虫洞
> ore site -> 矿石地点
> ghost -> I cant find its translate. i think ghost sig is a type of data site. Maybe it's 幽灵站点

**Comment by exodus4d** [comment]
Thanks for providing this information. I added the Chinese translation to the signature parser
