### ISSUE TITLE
Map Share Settings - Cannot Add Newer Alliance

### ISSUE THREAD

**Issue by jjfraczek** [exodus4d/pathfinder#787]
It seems I cannot add a newer alliance to the shared map settings (At least any alliance made after February 2019).  Is this database list outdated / can you update it?

Thanks

**Comment by exodus4d** [comment]
You need to have someone with an EVE account, from that new alliance, to log into _Pathfinder_ to **activate** "map invites" for his alliance in the "account settings" modal. If this is done, the alliance can be found by others for map invites.

If this does not help, feel free to reopen this issue.

![1QXSQDz](https://user-images.githubusercontent.com/9299033/58765004-88d3f600-856e-11e9-8435-7708a6bdcdf3.png)
