### ISSUE TITLE
Redirects to the landing page are broken

### ISSUE THREAD

**Issue by tysongg** [exodus4d/pathfinder#79]
Expected result:
* Unauthorized access to existing urls should redirect you back to the landing page.

Actual result:
* You are redirected to https://www.pathfinder.exodus4d.de/www/htdocs/w0128162/www.pathfinder.exodus4d.de/

Steps to reproduce:
* Make sure you are logged out of pathfinder
* Enter https://www.pathfinder.exodus4d.de/map/ into the address bar

***
The logOut($f3) function in main/controller/controller.php calls 

    $f3->reroute('@landing');  

where @landing is a route defined in routes.ini as 

    GET|POST @landing: /= Controller\AppController->showLandingpage, 0

***
As far as I can tell this appears to all be correct but for some reason we are being returned a 302 (correct) with a location header of /www/htdocs/w0128162/www.pathfinder.exodus4d.de/ (incorrect).  /www/htdocs/w0128162/www.pathfinder.exodus4d.de/ is the current directory of the application on the server.

Initially I thought this was possibly an error with the server configuration but it is happening both my install (Nginx) as well as the official install (Apache).  Additionally the incorrect location header information is being set by the application; the server shouldn't have anything to do with this.

I've been unable to find anyone talking about this issue online.

**Comment by exodus4d** [comment]
Thanks for reporting! Sry was little bussy last week. Im aware of this bug, :) I didn´t had time to fix it.

**Comment by tysongg** [comment]
Good deal.  I attempted to find the fix myself but I guess I'm not familial enough with FFF to figure out why its not doing what I expected.
