### ISSUE TITLE
CSS / layout issue with 1.5.2 (dev)

### ISSUE THREAD

**Issue by pezz** [exodus4d/pathfinder#793]
Hi there,

It looks like the page footer is not being placed properly:

![css](https://user-images.githubusercontent.com/372177/58848141-c5b40000-86c8-11e9-9ee2-ffb99d8fe723.png)

Also, there seems to be no way to scroll the setup page, it's like the view is locked or something so only part of the page is viewable.

**Comment by exodus4d** [comment]
Thanks for reporting. This was fixed yesterday :) You don´t need to report bugs on develop because it is not intended to be "stable" at all time.

**Comment by pezz** [comment]
Sure, I get that, but what if you don't notice the issue?

Isn't it better if I report it?

**Comment by exodus4d** [comment]
yeah you are right 👍  But this one was pretty obvious because one of the side effects was that scrolling on `/setup` page did not worked, too :)
