### ISSUE TITLE
[Dev Branch] Toggle EOL colour does not persist

### ISSUE THREAD

**Issue by pezz** [exodus4d/pathfinder#794]
Hey there,

As the title says - "Toggle EOL" doesn't seem to persist, the link changes colour but after a few seconds returns back to the normal link colour.

Cheers.

**Comment by exodus4d** [comment]
Thanks for reporting! I forget to add the type to the new "whitelist" for connection types. Check out the linked comment ^^

Hint you might have noticed, that the type for `frigate` holes was changed in the **current dev branch** to `wh_jump_mass_s`. To keep the previous stored `frigate` hole types, you can run this manually:

```sql
UPDATE `connection` SET 
	`updated` = NOW(),
	`type` = JSON_REPLACE(`type`, JSON_UNQUOTE(JSON_SEARCH(`type`, 'one', 'frigate')), 'wh_jump_mass_s')
WHERE 
	JSON_SEARCH(type, 'one', 'frigate') IS NOT NULL	
```

more information about this: #568
