### ISSUE TITLE
Shared Map setting problems

### ISSUE THREAD

**Issue by BlueCat0** [exodus4d/pathfinder#795]
It seems i cant add my friend crops to the share setting because i cant search about it
i guess its because it has a point in the crop name
SKY.CYBER 
![image](https://user-images.githubusercontent.com/16792362/59153819-e8159700-8a95-11e9-948f-71c357430bc2.png)

**Comment by BlueCat0** [comment]
My fault
![image](https://user-images.githubusercontent.com/16792362/59157644-a0682d00-8ae0-11e9-8547-fb2a70ec2190.png)

**Comment by exodus4d** [comment]
Yeah, it´s also in the *manual* explained how the _map share_ works. - Some kind of a _spam protection_ for unintended invites...

**Comment by dagoaty** [comment]
I got caught by this as well. Maybe the error message should mention sharing?

E.g. 
No results found or $name is not set to accept invites
