### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by PanikJanny97** [exodus4d/pathfinder#799]
Hello there,
i keep on getting errors where my server cant seem to find the location for the /setup and /sso files.
I did everything mentioned as in the Wiki and see the landing page but afterwards the server cant seem to find any files.

This is the website i am hosting it on for better checking
http://die-burg.servegame.com/pathfinder/

![Screenshot_1](https://user-images.githubusercontent.com/12249864/59724369-d9637880-9229-11e9-91e4-62db3b67126d.png)
![Screenshot_2](https://user-images.githubusercontent.com/12249864/59724371-da94a580-9229-11e9-8851-ac1f72ee69ad.png)

**Comment by sharkbit** [comment]
Check your BASE var in   <pathfinder>/app/environment.ini  (line 12).  In your case should be:
`BASE                        =   /pathfinder`

**Comment by exodus4d** [comment]
@PanikJanny97 There are some know issues with "sub dir" installations like yours. 
I strongly suggest to use its own TLD for Pathfinder. I did´t have time to set up my own sub dir _PF_ installation for testing
