### ISSUE TITLE
Needs a documented build process, preferably integrated with composer

### ISSUE THREAD

**Issue by mglinski** [exodus4d/pathfinder#8]
I have completed a successful install of this program by reverse engineering the static database info that is needed to power the mapping system. Based on my work I would like to open some tickets for better structuring this app for public consumption. 

The first major suggestion will be to remove all dependencies that are distrubited with this application and use package managers to effectuate a build and install system around them. 

There are many issues right now with trying to use this app in a semi-production environment while keeping up with alpha/beta frequency changes to things like ini setting files that are potentially overwritten when we do a `git pull` on our local clones.

Setting up your php dependencies to use composer will greatly help get this setup and working correctly. We can write tasks to help setup the project and change the app around internally so that your not committing your production pathfinder.ini settings to this repo. 

So, to have a list of things I am suggesting with this issue:

* Download specific versions of F3, Cortex, etc with composer and use composer for autoloading your classes.
* Rename all .ini settings files to *.ini.default and create an after clone action to copy these files back to the .ini extension
* Include in the .gitignore file composer phar or package downloads. Do the same with the ini extension changes above.
* Include a script to auto-download and populate the configured SDE database with the latest mysql SDE from fuzzworks
* Include a script to insert base schema into the configured main application database from a .sql file for now
* Include a script that can be executed to pre-populate the database with cached info once the sde and main databases are installed. There are controller functions that you are using to update/populate some helper tables, that needs to be made easier to access.

I would heavily consider using the Symfony Console and Symfony Process components to build out the installer features listed above. Then we can reuse it to enable things like proper crontab executed jobs that dont block for unlucky users and helper functions to do interesting things with the site.

**Comment by exodus4d** [comment]
Great ideas! Could you help with setting up a backend-build process, I have no experience with Composer. In my opinion, die Frontend part is much more complex and has much more dependencies than the backend.
https://github.com/exodus4d/pathfinder/blob/master/js/app.js
There are about 40 3rd partie dependencies. For now all of them should be up2date but Iam sure someday we get problems with keeping them all at the latest version. Even now I have to support the IGB and wie stick with jQuery 1.X. Im currently working on a new Frontend-Build process to help keeping track of the dependencies.

**Comment by tyler274** [comment]
Should use bower to keep them updated

**Comment by tyler274** [comment]
Composer shouldn't be too difficult, https://github.com/F3Community/fatfree-composer-app/blob/master/index.php is an example for the index.php

https://gist.github.com/tyler274/fe8361da6649b2ede1b2 for composer.json

**Comment by exodus4d** [comment]
Most of the stuff mentioned in here can now be done on `/setup` page (e.g. database setup,...): I´m not planning to add more automation to the current setup process.
