### ISSUE TITLE
Plain text passwords

### ISSUE THREAD

**Issue by tremblane** [exodus4d/pathfinder#80]
I just registered for this website, and it sent me my login (username and password) via email in plain text. (see http://plaintextoffenders.com/about/ if you don't understand why this is bad)

**Comment by exodus4d** [comment]
Hi, you are totally right! This was just a temporary solution until die "password forget" feature is ready to ship (see https://forums.eveonline.com/default.aspx?g=posts&m=6162954#post6162954). The upcoming version will bring a very huge code refactoring and a lot of nice features for admins. So this will be removed then.
