### ISSUE TITLE
[Enhancement] Auto-select current location with no window focus

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#800]
Requesting the auto-select current location feature to have the option to NOT auto-focus the map window to the newly selected location. Just simply select it. Have the auto-focus as a separate option.

**Comment by exodus4d** [comment]
@Bluedagger21 Do you mean with "active window" the browser window, or the map (in case you have multiple map tabs)?

**Comment by Bluedagger21** [comment]
@exodus4d the map view (of the selected map) pans itself to have the newly selected system in the top left corner whenever I change systems. This is a mild annoyance :)

**Comment by tralafiti** [comment]
I think a good option would be if the auto-select would only move the map if the newly selected system is not within the viewport. Here a highly professional ms paint illustration:
* Moving from system C to D the viewport starts scrolling to the right till the system is visible
* Moving back from system D to C viewport keeps unchanged since the system C is already visible
![professional_illustration](https://user-images.githubusercontent.com/197687/61577536-fcaf6b00-aae8-11e9-8765-4fae68c22ab9.jpg)

**Comment by exodus4d** [comment]
@tralafiti thanks for the illustration! I´ll implement this asap ;) 

Maybe we can reduce the _auto-scroll_ for active systems even more:
- **Current state:** 
  - The map just scrolls the **minimal** distance until the new selected system becomes visible. If a new system gets mapped, its position is always `[X + 150px, Y]`. If you create a new chain by jumping from A → B → C → D → ... the map scrolls on each jump, to bring the new system in viewport.
- **New state:** 
  - If the selected system is (partial?!) visible on map viewport → **no scroll**
  - If the new system is outside the map´s viewport → **auto scroll** until selected system is **centered** on map:  
    A → B → C → D (is outside viewport → scroll and center D) → E → F → G (is outside viewport → scroll and center G)

**Comment by Bluedagger21** [comment]
Brilliant. All the upvotes for this.

**Comment by exodus4d** [comment]
#### This is now implemented

Some notes:
- If a new "auto selected" system is already 100% visible inside the map´s viewport → **no scroll**
- When ever a system gets "auto selected", either by a detected jump or clicking a systems name somewhere in the UI and is **not** 100% visible, it is now scrolled and **centered** on map.
  - If it can not be centered e.g. it is to close to the map boundaries, it gets scrolled as close as possible to the center
- Systems manually selected on the map, are already (partial) visible.  → **no scroll**
