### ISSUE TITLE
[Enhancement] Higher Contrast Fonts

### ISSUE THREAD

**Issue by rayschneider** [exodus4d/pathfinder#802]
Having fun trying out this mapper.  One thing I noticed off the bat was that the font contrast to the background is rather low, at least for people with middle aged eyes like me.  It would be really nice to have a high contract option that makes the text a bit lighter so it is easier to read.

**Comment by exodus4d** [comment]
I know that some colors don´t have a high contrast. Especially older monitors (e.g. with TN-Panel) have problems with them. 
At this point it is not planned to change the contrast across the UI. If you have just a few examples (screenshots) where contrast is extreme bad for you. Let me know, I´ll reopen this issue for those adjustments.

At the meantime I would use a Chrome extension for CSS injection where colors can be changes for individual web pages.
