### ISSUE TITLE
[Enhancement] Hover over killboard icons gives name of entity (ship/corp/alliance)

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#805]
As title says, it would be a nice QoL enhancement to show the entity name when hovering over the killboard icons. Currently, it just says "killmail", "corporation kb", and "alliance kb".

**Comment by exodus4d** [comment]
I would love to add the names as well, but this is not _possible_ at the time. Killboard requests are send by the Clients (browser) to zKillbaord´s API and character names are not part of the response. There is no round trip required to the server where _PF_ is installed.
There are 2 technical options I can think about. But both don´t make sense from a technical view:
1. Clients could request _PF_ for killmail data (ajax). _PF_ then works as a proxy and requests the data from zKillbaord. The result could then be "enriched" with character names by _PF_ . This would result in thousands of additional _ESI_ API calls when ever a user selects a system on map.
I don´t see _PF_ in the position to store/cache character data of each EVE users that ever created a KM ;)
2. We leave it as now, with the addition of requesting character information "on demand".... In case a User "hovers" over a KM (or e.g. klick  new icon "more information"). We could send a new request to _PF_ to get e.g. character names (new ESI request). This is also "much work" just to add character names ;)
