### ISSUE TITLE
Map window defaults to the corner; map size too large

### ISSUE THREAD

**Issue by UnreasonableBastards** [exodus4d/pathfinder#809]
I've been having an issue where the positioning of marked systems defaults way off into the corner. I guess a better way to explain it is that the map resizes itself as systems are added and defaults to a point that's waaaay off center every time I load the screen.

The result is that the map is pushed off-screen and I need to recenter it every time I open pathfinder and every time I jump a new system.

Since you cannot resize the map width, only the height, it's pretty frustrating. Here is an example of what I'm talking about: [https://i.imgur.com/rJeMEBb.png](https://i.imgur.com/rJeMEBb.png)

This map was centered; I entered a new system, and it jumped to that position (forcing me to move the sliders to re-position the map after every jump).

**Comment by Bluedagger21** [comment]
Related to #800 enhancement request.

**Comment by exodus4d** [comment]
@UnreasonableBastards Thanks for your suggestions.

#### Re-sizable maps:
At this point, the map can not be resized, even the **height** is fix (2500*1500px). What you can resize in **height** is the **map section** (visible part of the map/viewport). There is an other issue open for changing the **width** of the **map section**: #470
To make maps **re-sizable** there is some work to do. At this point it is not planned to add this feature, soon.
#### Auto-Scroll to top/left
As @Bluedagger21 said, this will change `v1.5.4`. See: #800
