### ISSUE TITLE
V 1.5.1 /setup page error wont open

### ISSUE THREAD

**Issue by ysm1mh** [exodus4d/pathfinder#810]
hi all,

anyone can tell me what issue this is?  i checked the logs and cant find any error.

i have to plave a screenshot of the error as i cant copy the text  for some reason.

http://prntscr.com/obqtb3

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #796
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
