### ISSUE TITLE
[Enhancement] "Leads To" pop up unnecessary majority of the time

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#815]
When a new wormhole signature is added, Type pops up, then Leads Top pops up. However, in a large amount of cases, Leads To is useless to fill in as that system typically doesn't exist on the map yet. Sometimes it does like in the case of a return wormhole or if connecting to a pre-existing system. 

I would prefer it to not automatically pop up as it requires making an extra click to remove the focus away from it.

**Comment by exodus4d** [comment]
I had the same concerns about to many popovers. My intention was to reduce the initial click to open it for edit.
AFAIK, the "Leads to" popover _auto_ opens for **existing** signatures only (check the *.gif below). 
After _submit_, the next focused cell is determined by its value. If there is no value set -> cell gets focused, popover opens. Cells where no value can be set (e.g. group `combat` can not have a `leads to` system) are skipped.

>**Hint:** You can use arrow keys `left`, `right`, `up` and `down` for navigation inside the table. `return` can be used to **open** a popover, or to **add**, **delete** a row, `esc` can be used to close a popover,
You should be able working with the signature table without any mouse interaction. Arrow keys can also be used to select options.

Example:
![keynav](https://user-images.githubusercontent.com/9299033/61576653-da175500-aadc-11e9-9914-696bf1f93198.gif)
