### ISSUE TITLE
Update signatures in "X"? This is not your current location, "X"

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#821]
Doesn't register that I'm in the system after deleting and re-adding the signature, seems to bug the entire map.

New issue in v1.5.2, doesn't appear in my v1.5.1 installations.
http://prntscr.com/oipb2e

**Comment by FangyCZ** [comment]
Same issue in our installation. Doesn't care about which WH system or which character. This happend all the time when updating signatures WHEN the signature reader is used. And I can confirm that this is new issue in 1.5.2.

**Comment by Meganitrospeed** [comment]
Same on ours installation

**Comment by eboaen** [comment]
Having this issue as well on our install.

**Comment by exodus4d** [comment]
Thanks for your report!

This will be fixed in `v1.5.3` (Hotfix release), today.
