### ISSUE TITLE
1.5.2 The wormhole jump are duplicated by the character.

### ISSUE THREAD

**Issue by integral0** [exodus4d/pathfinder#822]
Bug?

![chrome_2019-07-23_11-44-05](https://user-images.githubusercontent.com/40578300/61689171-20b8b980-ad40-11e9-9d91-2cede1fa7d49.png)

**Comment by mrurb** [comment]
We have the same problem on our 1.5.2, it seems like each user gets logged every 5 seconds for about 7-10 minutes

**Comment by exodus4d** [comment]
hmmm interesting I´ll check asap

**Comment by mrurb** [comment]
Yer this is me jumping once furth and back on the public pathfinder and just leaving it.
![image](https://user-images.githubusercontent.com/3414748/61730596-000d5580-ad7a-11e9-96e1-ada3933ca74c.png)

**Comment by exodus4d** [comment]
OK, looks like I can quick hotfix this by just replacing a single PHP file, this might also fix some issues (dublicate connections from #820). Ill do some tests...

**Comment by exodus4d** [comment]
@integral0 @mrurb I hot fixed the production server with the commit above (had to change 2 PHP files). Coud you please check if the error is gone. (I had to delete all recorded mass logs, since they are useless )

**Comment by mrurb** [comment]
@exodus4d from what i can tell this fixed the problem and also fixed the #820 problem. I'll play around with it some more, but everything seems good now.

**Comment by integral0** [comment]
> @integral0 @mrurb I hot fixed the production server with the commit above (had to change 2 PHP files). Coud you please check if the error is gone. (I had to delete all recorded mass logs, since they are useless )

The problem does not repeat. Thank you.

**Comment by exodus4d** [comment]
I replaced the _ugly_ hotfix (9da2a78) with a proper solution.
The _checked_ state for historic "_jump records_", for new system/connection that should be added, is no longer a `timestamp` stored with the user `SESSION`.
The _checked_ state is now stored with the "_jump record_" data in cache:
- The **cronjob** now has access to it


#### There will be a new **Hotfix release** `v1.5.3` available, today
