### ISSUE TITLE
New scaling feature - bug?

### ISSUE THREAD

**Issue by infinity223** [exodus4d/pathfinder#828]
https://i.imgur.com/EbxsuyX.gifv

Appears on scaling below 100% (for example 90%) - names are "jumping" when hovering over connection.

**Comment by exodus4d** [comment]
I have seen this. Unfortunately this seems to be an issue in Chrome.
CSS `translateY()` does not work well in combination with `scale()`. 
I payed around with the CSS but did not find a solution to fix this in the Code.
