### ISSUE TITLE
Feature Request: Pull EvE scout

### ISSUE THREAD

**Issue by Boot103** [exodus4d/pathfinder#829]
Hey, 

I use pathfinder and as a thera resident it would be so useful to be able to pull eve scouts mapped systems. https://www.eve-scout.com/

Is this at all possible ?

**Comment by exodus4d** [comment]
Everything is possible ;) - The question is. Is it worth the time for implementing?

I haven´t seen and information about a public API . Do you have some any information?

**Comment by Boot103** [comment]
Let me check. I know a data table can be pulled from their website. Im not sure about API.

**Comment by Boot103** [comment]
So what someone does atm is pull the data from the eve scout website and makes it into a format where you can import as a map. 

https://pastebin.com/2xvfyhca

No idea if you can do anything like that but automated?

**Comment by tralafiti** [comment]
Eve-Scout-Website pulls it's data via Ajax itself, so it should just be a matter of writing them if it's ok to pull there data :-)
https://www.eve-scout.com/api/wormholes

**Comment by Boot103** [comment]
Oh nice. I know tripwire pulls from eve scout. Its the only feature I miss. It would help so much.

**Comment by ExplodingWaffle** [comment]
any updates? this feature would be super cool for plebs living in thera. for me, this ties well with the addition of npc factions so i can see where the good explo money is

**Comment by rangvaldr** [comment]
I wrote a script to do this, and generate a map out of the data. It's pretty easy.

**Comment by exodus4d** [comment]
I pushed the first bunch of changes to a feature branch: [pathfinder-829](https://github.com/exodus4d/pathfinder/tree/pathfinder-829). I plan to merge it back into `develop`  with the `v1.5.6` release of _Pathfinder_.
The current changes are just a _POC_ of the final [eve-scout.com](https://www.eve-scout.com/) integration and other "Thera" related issues.

#### Changes made so far:
- There is a new API Client for pulling current wormhole connections to "Thera" from [eve-scout.com](https://www.eve-scout.com/)
- Changes in "Route finder" dialog:
  - New checkbox for including current wh connections to "Thera" to the scope of connections.
  - New checkbox becomes en/disabled if "wormholes" checkbox get changed (all "Thera" connections are wormholes)
  - If you are looking for the shortest route to "Thera" (closest wormhole), from any other system on map, you can now find it even if neither "Thera" or any of its current neighboring systems is mapped in _PF_.
- Changes in "Route settings" dialog:
 - You can also set "Thera" to the default target systems for route search.

![route_dialog](https://user-images.githubusercontent.com/9299033/70393823-acc93600-19ee-11ea-81ff-dafd3dc74471.gif)

![route_dialog](https://user-images.githubusercontent.com/9299033/70393824-b18dea00-19ee-11ea-8c70-06ff55bfd5d3.png)

**Comment by exodus4d** [comment]
### New stuff:
#### "Thera connections" module
There is a new module for _Thera_ wormhole connections that can be enabled. It shows a **split** table of all known _Thera_ wormhole connections.
- The **upper** part shows all connections found on the current map
- The **lower** part shows all connections pulled from [eve-scout.com](https://www.eve-scout.com/) API:
  ![thera3](https://user-images.githubusercontent.com/9299033/75633152-c00d2b80-5c02-11ea-88b0-9010267baba4.gif)
- First column shows the **sync status** of a connection:
  - **gray:** Connection exists in eve-scout response but is not mapped in PF
  - **yellow:** Connection exists in eve-scout response, and is mapped in PF
  - **orange:** Connection not exists in eve-scout response, but is mapped in PF
  - **green:** Connection exists in eve-scout response and in PF + equal data (like wh size,..)
- Connections from eve-scout can be added to map
  - The wh size of the new mapped connection is auto adjusted (data from eve-scout)
- Connections from map can be deleted (optional delete the system as well [checkbox])  
  - Multiple rows can be selected for a bulk delete
  ![thera2](https://user-images.githubusercontent.com/9299033/75633485-60fce600-5c05-11ea-8559-87dc9ec4d64b.gif)
- If a connection is mapped but some data (e.g. signature names) are missing,.. there is a "hover" for table cells that show the missing data found in the eve-scout response.
 ![thera1](https://user-images.githubusercontent.com/9299033/75633391-aa006a80-5c04-11ea-9a35-a3498ad6925f.gif)
- Table auto updates if either eve-scout data has changed (cached for 2min) or connection data was changed on map (e.g. new connection found on map; Signature data changed for a connection,...)
- If _Thera_ is not mapped, there is a button. Sync connections requires _Thera_ to be mapped first.
  ![thera4](https://user-images.githubusercontent.com/9299033/75633600-80484300-5c06-11ea-9e92-5327966f157d.gif)

#### Missing features:
- Sync a new connection from eve-scout, does not auto create a signature in source/target system
- Column "estimated lifetime":
  - **eve-scout connections:** Data from eve-scout API is shown
  - **mapped connections:** `created` timestamp of the signature, which is linked to the connection is shown
