### ISSUE TITLE
Feature Request: SSO instead of username/password/api

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#83]
Please think about implementing the EVE SSO procedure in order to identify the person trying to login, instead of the username, password, apikey you currently use.

It may sound trivial for one person to use what you currently have, but other see a major hazzle in it and it would greatly make it easier to get people to use pathfinder with SSO.

**Comment by exodus4d** [comment]
Yeah thats right. This is planed for the near feature. But i can´t give you  a date, when it will be done. There are some features that have to be finished implementing first. (Admin Panel to invite/kick/block members)

**Comment by Tupsi** [comment]
good enough for me! In the meantime I try to pull my corp mates away from siggy. The main problem of that is always that they are used to the old one and you can not really help with that one. Guess that needs more security glitches before anyway sees the real value of one own server... sadly.

**Comment by exodus4d** [comment]
Check #84 for more information. (duplicate)
