### ISSUE TITLE
[Feature Request] Log Movement

### ISSUE THREAD

**Issue by Meganitrospeed** [exodus4d/pathfinder#832]
Think it would be nice to know who moves what in the maps and save that to the Log

**Comment by exodus4d** [comment]
@Meganitrospeed If map setting "Save map changes to logfile" is activated for a map, most user actions are already logged to file. 
Changing the position (`posX`, `posX` table column) of an existing system is **not** part of the  loggable fields. This would _blow up_ the log file with a ton of data (think about moving multiple systems at once....)

If you have your own installation, you could add `'activity-log' => true,` wo both column definitions of `posX` and `posX`, to add system movement to the watched fields for logging

Example `description` field: https://github.com/exodus4d/pathfinder/blob/7d118518af40837dab0004d4fe1dddb3d248d771/app/main/model/pathfinder/systemmodel.php#L129
