### ISSUE TITLE
Routes not persistent

### ISSUE THREAD

**Issue by FangyCZ** [exodus4d/pathfinder#835]
Hello. Some of my users are reporting that their route settings are reset to default every time they close the browser. All of them are using Firefox punk software.
IndexedDB settings for maps is empty every time they open the browser. 
Does anyone know where to get it to work?

**Comment by CalMatar** [comment]
What do you mean by "Firefox punk software"?

**Comment by exodus4d** [comment]
@FangyCZ Any information about the PF version (e.g. public server)?

Client side settings are stored in _IndexDB_ thats right. But it is never cleared/reset by PF. 
If you can not find any JS error in the debug console, and general store/updating _IndexDB_ works for at least the active session, I would check installed **browser extensions**, active "**private mode**", maybe Ad-Blocker,... first.

I haven´t seen any issues with the current PF version on latest FF on my side.

**Comment by FangyCZ** [comment]
Hello,
@exodus4d Thank you for your reaction and sorry for missing details. Server is private and running 1.5.3 version.
Unfortunately I can't reproduce the problem, but more than one user was reporting it. I forced them to clear local PF data in the browser and it seems it is OK for now. (It was more than 14 days ago.)
I think we can close the ticket as the local client bug.
