### ISSUE TITLE
Issues setting up cron job

### ISSUE THREAD

**Issue by johnfromoptus** [exodus4d/pathfinder#836]
As a preface, I am not good with this stuff.

I followed this guide:   https://github.com/Selineanna/pathfinder/wiki

Everything seems to be working as intended, however when reading through the official wiki to see if there was anything else I could do, I noticed the cron section. I created a crontab and added the line below.

* * * * * cd /var/www/pathfinder/app; sudo -u root php index.php /cron >> /var/log/cron-www/pathfinder.log 2>&1

I'm not sure whether I have adjusted it correctly. The log output is below:

PHP Warning:  PHP Startup: Unable to load dynamic library 'gd2' (tried: /usr/lib/php/20170718/gd2 (/usr/lib/php/20170718/gd2: cannot open shared object fil$
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20170718/mysqli (/usr/lib/php/20170718/mysqli: cannot open shared o$
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20170718/pdo_mysql (/usr/lib/php/20170718/pdo_mysql: cannot open$
PHP Warning:  Module 'curl' already loaded in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
Could not open input file: index.php

Any help would be greatly appreciated, thank you.

**Comment by johnfromoptus** [comment]
As an update, I realised that the guide in question asked me to edit two separate php.ini files with the same data, which I think caused a conflict. I have since deleted the duplicate extension data from one of the ini's and the cron job runs without errors server side. However, if I refresh pathfinder immediately after the cron job triggers, I get a 500 error: mbstring module already loaded. Any clues or a way to avoid this considering it happens every minute?

**Comment by jajmo** [comment]
In FPM's php.ini, try commenting out the line that loads mbstring, and restart FPM.

**Comment by johnfromoptus** [comment]
> 
> 
> In FPM's php.ini, try commenting out the line that loads mbstring, and restart FPM.

Yeah that removed that error, but now it shows the same 500 for curl. Commenting out the curl extension works there too. Why does the pathfinder setup page still show that curl is installed? do I not need to load any extensions dynamically after the install is complete? As in, should I have just commented out all the extensions after finishing the install?

**Comment by jajmo** [comment]
If you look in php's configuration directory (for me, `/etc/php/7.3/fpm`, there should be a directory `conf.d` that has installed modules configuration files. If you look at them, they typically load themselves. For example, in `10-pdo.ini`, mine has `extension=pdo.so`, which is the equivalent of loading it in `php.ini`. So by uncommenting it in `php.ini`, you're effectively loading extensions twice.

**Comment by johnfromoptus** [comment]
Perfect explanation, right at my level of understanding. Thank you.
