### ISSUE TITLE
New signature "preview" table in "Signature reader" dialog 

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#839]
### Description:
Whenever the "signature module" is updated with fresh scan results from the _EVE_ client (clipboard paste), the user should get a **preview** of the parsed signatures and see **potential** changes made to the signature table **before** actually submit it.

### Features:

- New **read only** copy of the current signature table added to "signature reader" dialog
- Any change (paste) in "Scan result" <textarea> field, triggers a _redraw_ of that _preview_ table.
  - **Added** signature **rows** are highlighted (**green** background color)
  - **Changed** signature **columns** are highlighted (**orange** background color)
  - **Deleted** signature **rows** (require an active "lazy delete" checkbox) are highlighted (**red** background color)
- Any change in the underlaying **primary** signature table (e.g. from other users) will also result in a redraw of that preview table
- New info label added, shows the found/parsed signature **count**
- New counter labels added, with counts for added/changed/deleted signatures

![sig_preview4](https://user-images.githubusercontent.com/9299033/62886272-33208480-bd3b-11e9-8ebc-6ebb0d3c8203.gif)

**Comment by CalMatar** [comment]
I love love this. Can't wait for this one to be implemented.
