### ISSUE TITLE
[Enhancement] Move version to a separate configuration file

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#841]
Would it be possible to move the version from `pathfinder.ini` to a file that is often not configured? Maybe a `version.ini`? 

I maintain one of the [docker projects](https://github.com/KryptedGaming/pathfinder-docker) for Pathfinder, and it's difficult to maintain numerous pathfinder instances when it pulls the version from a file that often needs to be configured (whitelists, shared limit, etc).

**Comment by lord-carlos** [comment]
But if you put the `pathfinder.ini` file in the `config/` folder, you can overrite only the values you want, right?
You can just ignore the version setting, and let upstream handle it?

**Comment by porowns** [comment]
So you mean place `pathfinder.ini` under `conf/pathfinder.ini` and exclude the version value?

**Comment by lord-carlos** [comment]
Yes, see here: https://github.com/exodus4d/pathfinder/wiki/Configuration#custom-confpathfinderini

> DO NOT blind copy&paste the existing file. Overwrite only those values you need to. Otherwise you will not get possible config changes with future updates. Keep the existing file structure intact (add section headlines e.g. [PATHFINDER.LOGIN]).

You still want `pathfinder.ini` in the `app` folder, but then just have a minimal `pathfinder.ini` in the `conf/` dir.

**Comment by exodus4d** [comment]
@lord-carlos is right. You create a new `conf/` dir for that 
On my installations I created:
- `conf/pathfinder.ini` (can even be used to overwrite default values from `config.ini`")
- `conf/environment.ini` (must have **all** environment specific settings! - Even if some of them are not overwritten)

#### Example `conf/pathfinder.ini`:
→ Overwrite some `[globals]` vars from `config.ini` + some `[PATHFINDER]` vars from `pathfinder.ini`
```
[globals]
CACHE                           =   redis=localhost:6379:1
API_CACHE                       =   redis=localhost:6379:2
SESSION_CACHE                   =   default

[PATHFINDER]
NAME                            =   Pathfinder DEV
EMAIL                           =   test@test.de
SHOW_SETUP_WARNING              =   0
```
