### ISSUE TITLE
Make connections avoid other systems

### ISSUE THREAD

**Issue by Raldeme** [exodus4d/pathfinder#844]
Sometimes a path is taken that leads back to a previous system, and the path line goes under all the other systems. 
my request is to make this connections line collide with the least amount of systems possible for clearer vision of where the connection comes from and leads to.

**Comment by CalMatar** [comment]
Can't you just move it around on the map to make it do that?

**Comment by Raldeme** [comment]
> Can't you just move it around on the map to make it do that? That is what I do when I have the same issue.

Yeah that's what we have to do at the moment, but if you have a long line and you dont know which system it's going to it can take a few minutes to figure it out, which could be more time spent scanning

**Comment by exodus4d** [comment]
@Raldeme Adding some kind of a "collision detection" for connections is not realistic. A ton of work, with a huge risk of being buggy at the end.

I think the changes I made in https://github.com/exodus4d/pathfinder/issues/845#issuecomment-538456783 for the next release might help with your problem. 
New created systems (jump detected) are no longer created at [0,0] map coordinate. Its new position is based on the current map scroll section of that user + some collision detection for existing systems in that area.
