### ISSUE TITLE
magnetizing not working

### ISSUE THREAD

**Issue by Raldeme** [exodus4d/pathfinder#845]
Hi, with the magnetizing feature enabled systems still overlap each other when they are created
for example, i'm in j-space, i enter a connected wormhole and it creates a new system on pathfinder, i go back to the previous system and go through a different wormhole and it creates another system either on top of or underneath the previously created system.

also please make magnetizing a global setting so the 'Manager' can set it for everyone on that map

**Comment by exodus4d** [comment]
Thanks for the report. First of, this is not a bug. It works _as intended_. The features you would like to have were not implemented jet: **"magnetizing" != "prevent overlapping**
- **Magnetizing** is a just for drag&drop systems on map

Based on #570, I improved and added some features:

### Changes with the next release
- New (auto added) systems are now added at the **top left** of the current **visible** map section. (before: systems were added to 0/0 coordinate and the user had to scroll back to see them)
- New (auto added) systems should not overlap with existing systems on map. Each client now send a list with potential free map areas to the server, that could be used in case a new system should be auto added.
- New (auto added) systems with a new connection (jump detected) should also not overlap existing systems.
- New (auto added) systems will not get added outside the current map section
### Demo
Task visualization: "Find not overlapping areas for a new chain of **8** systems"
- green: found empty dimension
- red: checked area, overlapped by X%

![collision_debug](https://user-images.githubusercontent.com/9299033/66221664-c1780d80-e6cf-11e9-8c8c-7348cbfa3c7e.gif)

Without the red (invalid) debug areas
![collision](https://user-images.githubusercontent.com/9299033/66221739-f1bfac00-e6cf-11e9-88eb-2755f1f38732.gif)

Switch between "Grid snap" and "normal"
![collision_debug_grid](https://user-images.githubusercontent.com/9299033/66221763-fc7a4100-e6cf-11e9-9235-2b099b661187.gif)
