### ISSUE TITLE
Workaround needed for computers not displaying Pathfinder graphics

### ISSUE THREAD

**Issue by usertype** [exodus4d/pathfinder#846]
Two different computers, 3 different browsers, all showing the Pathfinder-w.space site as text only.  The common thread is that both computers are using ESET Antivirus.

Windows 10
ESET
Firefox
Chrome
Windows IE browser 

![image](https://user-images.githubusercontent.com/54335267/63387264-3aaae380-c362-11e9-91ae-eebd334821d2.png)

(That is a small section of the page, but EVERYTHING is displayed this way.)

**Comment by usertype** [comment]
From Firefox:  Pressing F12 for Network issues:

![image](https://user-images.githubusercontent.com/54335267/63387780-97f36480-c363-11e9-9f40-615cb7614f5c.png)

Also from Firefox:  F12 for Console errors:

![image](https://user-images.githubusercontent.com/54335267/63387857-c40ee580-c363-11e9-8e52-5ccbd66d07ff.png)

**Comment by usertype** [comment]
From Chrome F12:  

![image](https://user-images.githubusercontent.com/54335267/63387918-eacd1c00-c363-11e9-90b9-43dae2b342ae.png)

**Comment by usertype** [comment]
I found the issue.  ESET antivirus (and probably many others) are performing SSL/TLS protocol filtering.  Once I opt to not have the antivirus system filter, Pathfinder begins working again.  It was frustrating, and this should not be the final solution, but it may point the Dev to the issue.

**Comment by Meganitrospeed** [comment]
I would suggest to just whitelist pathfinder in ESET

**Comment by WildStrawberryEVE** [comment]
My ESET gives trouble with official PF site but not with with my corporation's PF (and my former too which used Letsencrypt's certificates). I had earlier the same problem with bitdefender but again only on the original pathfinder site.

**Comment by exodus4d** [comment]
@usertype I recently improved my server _Nginx_ server config settings and changed the way how "static resources" (`*.css`, `*.js`) files are send to the clients.
If you still have the same problem with _ESET_ please share a screen with the **Request/Response Headers** of a failed request (e.g. for `app.js`), from the _Chrome_ Dev tools.

![dev_tools](https://user-images.githubusercontent.com/9299033/66260097-6a9b3280-e7ba-11e9-8aab-ebad47e4fa4c.png)

**Comment by exodus4d** [comment]
### :x: Issue closed
This issue has been closed because it has been inactive for a while.

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*
