### ISSUE TITLE
[Enhancement] Allow Unicode emojis in alias

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#849]
If unicode emojis is added to the alias it errors with:
```
code: 500
message: "Internal Server Error"
status: "SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x81Ar...' for column 'alias' at row 1 [C:\inetpub\vhosts\epicentresyndicate.com\path.epicentresyndicate.com\pathgit\app\lib\db\sql.php:226]"
type: "error"
```

Would be nice if we could use the official unicode emojis 😄 
https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by exodus4d** [comment]
Nice request!  :) I had to change some _MySql_ configuration settings:
- `CHARACTER SET` from `utf8` to `utf8mb4` 
- `COLLATE` from `utf8mb4_unicode_ci` to `utf8mb4_unicode_ci` 

The existing "setup tables" button on `/setup` URL takes care about the new changes (on a DB level).  If existing tables/columns not get changes, you might have to change them manually (can be done by PhpMyAdmin in a view clicks....)

#### With the next release there is support added for **1719** Unicode emojis ;)

![utf8mb4_1](https://user-images.githubusercontent.com/9299033/66261261-5d863f80-e7ca-11e9-88bd-8ec0319cffdf.png)
![utf8mb4_2](https://user-images.githubusercontent.com/9299033/66261262-5fe89980-e7ca-11e9-9208-4fba53fab6f2.png)
![utf8mb4_3](https://user-images.githubusercontent.com/9299033/66261265-6119c680-e7ca-11e9-9b07-42bf638b9910.png)

**Comment by daschalki** [comment]
![image](https://user-images.githubusercontent.com/14867526/70984093-2d0c2d00-20ba-11ea-8ebc-0b1ca40455a7.png)

Anything I should worry about?

**Comment by exodus4d** [comment]
nope you can manually change that for all tables (e.g. within PhpMyAdmin UI)

**Comment by sharkbit** [comment]
It would be better done by the install script with:
`ALTER TABLE `eve_pathfinder`.`<table_name>` CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_unicode_ci ; `
