### ISSUE TITLE
When manually inputting wormhole as type of Sig, Pathfinder allocates the "leads to" field to first sig in list

### ISSUE THREAD

**Issue by billytheme** [exodus4d/pathfinder#850]
### Overview
When a signature has been inputted as existing, via probe scanner, but not been scanned to the point at which the type of signature is known, if the type is then manually inputted to be wormhole, the "leads to" field will be appear in the first signature of the list, regardless of type, rather than the wormhole that was inputted, until the page is reloaded

If, however, the "leads to" entry was filled, and the page then reloaded, it will stay attached to the first sig, and will be unable to be edited. The only way to remove it is to delete the sig and then re-add it

### Steps to reproduce
Copy an two unscanned sigs into a system in pathfinder
Set the second sig in that list to be a wormhole
Notice that "leads to" entry has appeared on the first sig, rather than the second sig
Reload the page
Notice that the entry has been corrected to appear on the wormhole, rather than the unscanned sig

**Comment by CalMatar** [comment]
This is a known issue and also on another ticket.

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #831
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
