### ISSUE TITLE
Type dropdown for wormholes and data sites swapped

### ISSUE THREAD

**Issue by der-micky** [exodus4d/pathfinder#851]
Hi,
got a report from corpies (at least 2) that the type-dropdown for wormholes shows data-site content and the other way around (see screenshot).
After a refresh all is fine. 
![PF_bug](https://user-images.githubusercontent.com/29451620/64550018-47ec3a00-d332-11e9-832d-b528f989974b.png)

Thank you !
-Micky

**Comment by CalMatar** [comment]
This is a repeat of SEVERAL other tickets. It is a known issue and is being fixed with the next update. It is when you attempt to manually update an unknown signature below the first signature in the signature list. You can close this ticket if you want.

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic.
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
