### ISSUE TITLE
Signatures sub windowmissing in MS Edge

### ISSUE THREAD

**Issue by eophten** [exodus4d/pathfinder#854]
Signatures sub window missing in MS Edge

![new_fghdfzgd](https://user-images.githubusercontent.com/7319297/64913757-cb7ba180-d70b-11e9-92d1-35135b6e4179.png)

**Comment by LordMrcS** [comment]
Don´t use IE or Edge. They are not supported and will not get any support in future.
-> Check the FAQ section on the login page
Please use Chrome or Firefox instead.

**Comment by eophten** [comment]
I'll inform my users not to use Edge.
