### ISSUE TITLE
[Feature Request] Allow the display of a connction ID in the signatures mask on the map

### ISSUE THREAD

**Issue by november781** [exodus4d/pathfinder#856]
This small change would be extremely useful for quick navigation and Identification of holes.
As it stands the signatures mask only show the wormhole type and not the sig ID.

**Comment by november781** [comment]
I see that they are visible when you mouse over the system, I would like an option to show them without mousing over the system and hide the wormhole type until you mouse over it

**Comment by exodus4d** [comment]
This is a duplicate report. See #725

For now it is not planned to make that tooltip "persistent" or configurable.
