### ISSUE TITLE
[Enhancement] System links to eveeye.com

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#859]
K-Space systems now have deeplinks into eveeye.com

![eveeye](https://user-images.githubusercontent.com/9299033/65901037-9d5aba80-e3b7-11e9-8526-1cb6081b6b31.gif)

**Comment by porowns** [comment]
This doesn't really seem like an enhancement.. why were useful links moved to a hidden menu that requires a hover? More actions to get what I'm sure was a highly used feature. They were great in the system header.

**Comment by exodus4d** [comment]
@porowns I was not aware that they are used that often.  I got the request for adding "eveeye.com" and then saw the problem that too many icons would clutter the UI to much. They are "dynamic":
- w-space systems don´t have a eveeye.com link but Dotlan link (to the system itself) + link to Anoik
- k-space systems have eveeye.com link + Dotlan link (to the map)
- all systems have "set destination" ingame link....

Which of those do you need frequently and what information are you looking for on that 3rd party page? - maybe we can add it to PF....

**Comment by porowns** [comment]
@exodus4d Dotlan is used by a large amount of roamers to quickly see the nullsec activity in a region. For the majority of us, we would click a nullsec system and immediately click the Dotlan icon in the header to see if it was worth roaming. Not having this forces us to keep Dotlan open and painfully type out the nullsec systems.

Out of all the EVE Online tools, I'd say Dotlan and Zkillboard are used the most for fast intel. These make up for many of the shortcomings that Pathfinder has, and they should be in easily accessible places. 

`k-space systems have eveeye.com link + Dotlan link (to the map)`, I don't see any Dotlan links at all.. have they been moved? They don't display in the gif you attached for me.

**Comment by mawburn** [comment]
Yeah, I'm just going to second @porowns here. The dotlan button was one of the most useful features of the client. It really hurts to have it gone. The placement that it was before was a really great spot UI wise too, imo. 

![Screen Shot 2019-11-04 at 3 31 00 PM](https://user-images.githubusercontent.com/2829924/68155690-29f91b00-ff18-11e9-883b-3257a4047486.png)

I am running on the same instance of @porowns but we don't have the link in there at all.

**Comment by daschalki** [comment]
Having same issues in my own deployment of 1.5.4:

![image](https://user-images.githubusercontent.com/14867526/68289676-d822d300-0086-11ea-8493-267697e9c262.png)

Not showing any links at all except the not working "Client" button.

Users are really missing the functionality.

**Comment by porowns** [comment]
@exodus4d can you reopen this?

**Comment by Sonnenwerk** [comment]
Hi, 
our corp members also miss the dotlon icon directly on main ui.
cu

**Comment by Kurti00** [comment]
I would also like to support this request.
We were using the anoik.is and dotlan links ALOT!
Was basicaly our bread and butter when gathering intel.
Would also be nice to get a "copy system name to clipboard" button, so that you can generate an ingame link very fast. <3

**Comment by exodus4d** [comment]
@mawburn @daschalki I can´t see any issues on my public installation (Chrome/FF). If this is a self hosted server, check your `pathfinder.ini` for the URLs:

**Comment by exodus4d** [comment]
BTW: I´m working on a better solution and bring the Dotlan icon back to the front...

**Comment by exodus4d** [comment]
**I reverted _most_ of the UI changes for the next release.**

- Icons for _Dotlan_, _EveEye_, _Anoik_ moved back into the panel headline (as before)
- I removed the _collapsible_ info panel (as before)
- I removed the (currently broken) "set destination" EVE-client icons

**Some ideas for further improvements:**
- Would be nice to trigger the"system contextmenu" (for e.g. "set destination", "change status",.. options) somewhere inside the "system info" panel. 
- Settings for **custom system URLs**, where users can add a `iconUrl` and `systemUrl`. _Placeholders_ are required for _dynamic_ URLs:
  - e.g. `https://www.myEvePage.com/system/{systemName}/kills`
  - e.g. `https://www.myEvePvE.net/{systemId}?filter=combat`

**Comment by exodus4d** [comment]
![system_ext_links](https://user-images.githubusercontent.com/9299033/68527357-313c7200-02e6-11ea-8fbd-1d35395c911e.gif)

**Comment by daschalki** [comment]
Adding links to the pathfinder.ini worked, might be worth noting in the Upgrade Guide (1.5.3 -> 1.5.4) since the only change noted was the version.

Changes look great, thanks for re-opening!

**Comment by mrurb** [comment]
@exodus4d Could it maybe be an idea to also add the links to the right click context menu, under a sub category?
It would make it quicker and easy to access the links.
![image](https://user-images.githubusercontent.com/3414748/68868281-8e299500-06f7-11ea-95d0-dee9c2d9aa4a.png)

**Comment by daschalki** [comment]
Did I miss any settings if the new Links don't show up in 1.5.5?

**Comment by mrurb** [comment]
@daschalki Watch out that your browser have not cached the UI elements, it quite often happens with our members after an update. If your using chrome open the dev console(f12) then right click the refresh icon next to the address bar and choose "Empty Cache and Hard Reload"
![image](https://user-images.githubusercontent.com/3414748/70985885-2df28e00-20bd-11ea-8d33-dbbc12344a76.png)
