### ISSUE TITLE
user_character.isMain does not have a default value

### ISSUE THREAD

**Issue by a-tal** [exodus4d/pathfinder#86]
when trying to add a new api key to a new install, on the page where you enter it, it doesn't allow you to go to the character select page instead giving an error about how there's no default value for isMain.

confirmed the lack of default in MySQL:

```
mysql> show columns in user_character;
+-------------+------------+------+-----+-------------------+----------------+
| Field       | Type       | Null | Key | Default           | Extra          |
+-------------+------------+------+-----+-------------------+----------------+
| id          | int(11)    | NO   | PRI | NULL              | auto_increment |
| created     | timestamp  | YES  | MUL | CURRENT_TIMESTAMP |                |
| updated     | timestamp  | YES  | MUL | CURRENT_TIMESTAMP |                |
| active      | tinyint(1) | NO   | MUL | 1                 |                |
| userId      | int(11)    | YES  | MUL | NULL              |                |
| apiId       | int(11)    | YES  | MUL | NULL              |                |
| characterId | int(11)    | YES  | MUL | NULL              |                |
| isMain      | tinyint(1) | NO   | MUL | NULL              |                |
+-------------+------------+------+-----+-------------------+----------------+
```

after running `alter table user_character modify column isMain tinyint(1) not null default 0;` I was able to input an api key and select a main.

https://github.com/exodus4d/pathfinder/blob/master/app/main/model/usercharactermodel.php#L60

**Comment by exodus4d** [comment]
Oh thanks, i forgot the default value for that column. 
Set *nullable* to `false` without providing any default value, does not make sense. Unfortunately I don´t see those errors on my installations.
To make it more consistent, i changed all default column values for `bool* fields (which are actual converted into `tinyint(1)`) from bool (true/false) into (1/0).

**Comment by a-tal** [comment]
great, thanks! I've confirmed this is now resolved in the develop branch.

(btw, if you ever want a docker container to test things with... https://github.com/a-tal/pathfinder-docker)
