### ISSUE TITLE
[BUG] Set destination not working [1.5.4]

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#862]
Can't seem to set destination in 1.5.4 on both the public and our private PF

I can not see errors in log files on our private PF

Steps:
- right click HS system -> waypoints -> set destination

Expected result:
System set as destination for autopilot in game

Current result:
No reaction in game

**Comment by infinity223** [comment]
confirming, not working here too.

**Comment by integral0** [comment]
Confirm.

**Comment by w0de** [comment]
You just took my PR and commited it without credit. I am a sad :sheep:

**Comment by AmraNiYesta** [comment]
This is not a minor bug...

**Comment by verunightscout** [comment]
I tested the patch on private PF and corp mates are saying, that it doesn´t fixed the issue.

**Comment by mrurb** [comment]
@verunightscout We have applied the fix to our private PF, which is being used on a daily basis by about 20-30 people and it works fine here for everyone. Make sure that when you apply the fix, that you also build the app, explained here: https://github.com/exodus4d/pathfinder/wiki/Build-process

**Comment by verunightscout** [comment]
Hmm, this can be the issue. Looks to much work, when official release is nearby.
