### ISSUE TITLE
500 Server Error on FastCGI

### ISSUE THREAD

**Issue by der-micky** [exodus4d/pathfinder#863]
40 FastCGI sent in stderr: "PHP message: Argument 1 passed to Model\Universe\SystemModel::Model\Universe\{closure}() must be an instance of Model\Universe\object, instance of stdClass given [/var/www/pathfinder/pathfinder/app/main/model/universe/systemmodel.php:146]

Will check details and update...

Thx,
-Micky

**Comment by der-micky** [comment]
Had to comment the "object" type in the closure definition:

           $data->shattered        = count(array_filter($planetsData, function(/*object*/ $planetData){
                return property_exists($planetData, 'type') &&
                    (strpos(strtolower($planetData->type->name), '(shattered)') !== false);
            })) == count($planetsData);

Then it worked. Maybe that helps ...

Thank you !
-Micky

**Comment by exodus4d** [comment]
@der-micky Thanks for the report. Type hints for `object` was introduced in PHP 7.2 https://blog.tekmi.nl/php-7-2-and-object-typehint/

I´ll remove the type and keep 7.1 support for the next release.
