### ISSUE TITLE
[Bug] Lost links on anoik and dotlan [1.5.4]

### ISSUE THREAD

**Issue by integral0** [exodus4d/pathfinder#867]
![screen](https://i.imgur.com/szzsGR6.png)

**Comment by CalMatar** [comment]
You did not "lose" the link. They were moved from the title bar to below the information panel. If you click the bottom of the information panel there is a drop down bar. It expands the bottom of the panel and the rest of the panel is there with the links and everything, per my screenshot.
![Screenshot_100](https://user-images.githubusercontent.com/42744905/67715286-ef373600-f99f-11e9-861b-f1d8f89616ee.png)

**Comment by integral0** [comment]
Oops, for sure. Thank.
