### ISSUE TITLE
Routes not staying populated

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#868]
I am not sure if this is an issue or not. I have been having this issue for several versions now and have just kept my routes down to below four but I have recently needed to add more routes due to things happening. I currently have five static routes that I keep track of in Pathfinder but only four of them actually track an actual route to the location while the fifth one needs to be manually checked every time the screen is reset. 
Is this normal or is this a bug? I have NEVER had this working if this is not supposed to happen as this has always been the way it has worked for me as previously mentioned I just kept the routes down to four. 
![Screenshot_99](https://user-images.githubusercontent.com/42744905/67616421-6bfec000-f7a6-11e9-91e6-7af6f3887919.png)
This is a screenshot of my current Routes layout and what I mean by this issue. 
Please let me know if this is an issue or not. 
Thanks, 
Cal Matar.

**Comment by integral0** [comment]
On the private version, pathfinder 1.5.4 is the same problem.

![Problem](https://i.imgur.com/Gx7mzBh.gif)

**Comment by exodus4d** [comment]
Not an issue. This is adjustable in your `pathfinder.ini`. These **3** values can be changed:
https://github.com/exodus4d/pathfinder/blob/aef6d4e0246dfbe240063ca41b8daa016650139d/app/pathfinder.ini#L205-L215

#### Explanation:
- ` MAX_DEFAULT_COUNT = 6` is the max number of systems, a user can set as his default search

  ![route1](https://user-images.githubusercontent.com/9299033/68076174-9574a880-fdb1-11e9-97d6-c417d036f3a9.png)

- `SEARCH_DEFAULT_COUNT = 4 ` is the max number of routes that will be checked per request (e.g. on panel gets loaded)
- Unchecked routes with "Search Now" label + "magnifier" icon man be manually checked by click on that icon. - OR by click at "refresh" icon above.

  ![route2](https://user-images.githubusercontent.com/9299033/68076214-0b790f80-fdb2-11e9-8e3b-2ff34340584b.png)

- `LIMIT = 8` is the max number of routes (`MAX_DEFAULT_COUNT` + custom routes <= `LIMIT`)
  In this example we can manually add **2** more routes 

  ![route3](https://user-images.githubusercontent.com/9299033/68076382-2187cf80-fdb4-11e9-8701-82b622e5c363.png)

- Try to add a **third** route shows a warning

  ![route4](https://user-images.githubusercontent.com/9299033/68076409-57c54f00-fdb4-11e9-9f12-34f118de7536.png)

### Why so complex?
Bevore CCP got an API endpoint for route search, _PF_ used its own algorithm, which is pretty CPU intense. To hold CPU load at an acceptable level, I added those "limits".
> Just imagine someone with 100 configured default routes, and no request limit. Every time he clicks at a system, 100 rout searches would be done...

I think this is a good trade of where users can configure more than 4 (up to 6) default routes, with the idea to move 4 most relevant systems to the front of the list (those are checked immediately) and the option to manually check the rest by one click...
... and prevent them from requesting to many routes at once.

The present state is a bit different, 95% of the route search requests are handled by _ESI_ and 5% are still handled be the old (fallback) algorithm (e.g. if ESI does not respond in time). So I could probably increase the limits a bit on my server.
