### ISSUE TITLE
[Feature Request] Update owner on multiple structures in Intel

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#869]
In the Intel section of Pathfinder when you are trying to update the structures in wormholes and you have to add the Owners of the structures and you are doing this for more than three structures this can get cumbersome and very time consuming especially when the system is lagging, as the public Pathfinder does frequently. 
It would be great if the was a way to select the structures on the list and update the owners information on all the selected at the same time if you have already added them from the D-Scan copy/paste. Any other changes would need to be made to each individual structure but when you have wormholes with five or ten or twenty or more structures in it adding the owner, when it is one singular one especially or only one or two, is very time consuming having to wait for the system to update in between each and every structure while it first has to look for the corporation then while it adds the information to the structure. Then you have to do it all over again. 
_______

A suggested idea would be to add a checkbox to the left of the "Status Indicator" which would let you select one with a box at the to to select all. When a checkbox is checked it greys out the delete option (but it would be a useful option as well but also very dangerous) Clicking on any of the Edit buttons would open up the entire list that is checked. If none are checked then the only one opened is the one clicked like normal. 
________

Is this something that can be done?

**Comment by exodus4d** [comment]
### New _bulk_ update for "Structures"

#### Row selection:
I think a checkbox per row is not necessary for "mass selection" (even through it is supported by _Datatables_: [Checkbox demo](https://datatables.net/extensions/select/examples/initialisation/checkbox.html)).
Rows can now be selected by mouse + keyboard:
- `click` (single row), 
- `ctrl` + `click` (individual rows)
- `shift` + `click` (range of rows)
- New "Toggle row select" UI button

#### Bulk update:
A _reduced_ version of the structure edit dialog is shown (if multiple rows are selected), where **corporation** can be set and overwrite existing data.
Allow more than just the corporation select would not be an issue (e.g. "online status"). But then we would have a new "problem":
If someone just wants to change **one** field (e.g. corporation) and not change "online status"... _PF_ could either interpret the empty (untouched) "online status" select to bulk clear "online status" for all selected rows **or** leave it as is.

#### Multi row select + bulk update demo:
![select_table](https://user-images.githubusercontent.com/9299033/68069782-65071d00-fd65-11e9-9531-e25d55090ee1.gif)

**Comment by CalMatar** [comment]
I love the work so far. Much simpler than my idea, although I was hoping this was possible the checkbox was my second idea honestly. The reason I was suggesting only allowing one edit was the "confusion" created when one changed and the other not. 
It could be possibly be coded to be set to default (mainly the online field) to remain in the default state if not altered. This "should" alleviate problems with changing states that were not meant to be changed wouldn't you think?

**Comment by exodus4d** [comment]
Not sure if i got you right. Let´s take an example:
You have 3 structures recorded...

|   | status            | owner corp |
|---|-------------------|------------|
| 1 | online            | **_empty_** (default)     |
| 2 | **_unknown_** (default) | corp A     |
| 3 | online            | corp B     |

... and you want to change **all 3** records to "**corp C**".

1. You probably select **all 3** rows and hit "edit".
2. The "bulk" edit dialog opens. For this example, let´s say there are fields for:
    - "status" select → value: **_uknown_**  (default)
    - "corporation" select → value: **_not set_** (default)
        Both \<select\> fields show **default** options (because current values different).

 3. You change "corporation" to new "**corp C**", and leave "status" as is (_you don´t want to change status_)
4. Click "save" and expect the corp to be changed to "**corp C**" for **all 3** rows, and "status" not to be changed, - right?

But what, if you **also** want to change "status" back to **_unknown_** for all of them? - _PF_ could not know if the _untouched_ "status" select should be interpreted as:
1. Ignore the "status" field, it was not changed by the user.
2. "status" field was not touched but maybe the user might want to save the current selected **_uknown_**  (default) option to be used for overwrite.

**Comment by CalMatar** [comment]
Correct. If no changes were made then leave as they are, just as it is now only it would be with multiple records instead of single. As previously noted you could add the Notes field in to add notes to each record as well but they would all be the same notes (which mine are all the same anyway. I add the date I change/add structures to a WH so I know the last time things were updated in that particular hole). Most of the time I personally don't use the status field as I rarely visit structures in wormholes that I go into but it does sometimes happen.
