### ISSUE TITLE
[BUG] Double signature bugs

### ISSUE THREAD

**Issue by eophten** [exodus4d/pathfinder#876]
On version v1.5.4. We are seeing behavior where the same signature will appear in the signatures list twice.

When pasting new signatures with lazy delete when two are present, one will be deleted. When pasting new signatures with lazy delete when one is present, a second will sometimes be added. 
![Double Signature](https://user-images.githubusercontent.com/7319297/69883277-074cee80-1299-11ea-9171-a08847f43a0e.PNG)
![Double Signature Paste w/ Lazy Delete](https://user-images.githubusercontent.com/7319297/69883278-07e58500-1299-11ea-9f81-136ade0b731c.PNG)
![Single Signature Paste w/ Lazy Delete](https://user-images.githubusercontent.com/7319297/69883279-07e58500-1299-11ea-9448-6175ab0f3103.PNG)

**Comment by CalMatar** [comment]
I have a question on this. Did you add the WKH signature manually? If so did you just add the letters and not the numbers? I have done this in the past and as I see it the system should see that as a different signature.

**Comment by exodus4d** [comment]
@eophten I think @CalMatar is right with his assumption.

#### Hot it works:
- The "**preview**" table matches rows by the **full name** of a signature: **WKH-190** (including numbers). This is done in JS (client side)
   - If there is a signature manually added with **WKH**, a new pasted **WKH-190** Sig is interpreted as **new**, and the current **WKH** is flagged for delete (red row)
   - Sometimes there are **two** signatures with the same letters in a system e.g. **WKH-190**, **WKH-180**, so we can not just check the first 3 letters for row matching.
- Saving the signature reader dialog, submits parsed "Scan result" (from textarea) to the server (not the content of the **preview** table)
  - The final validation and "row matching" is done in PHP (server side)
  - New sig rows now have a unique **Id** after saving them to the DB.

**Comment by eophten** [comment]
@exodus4d i was able to go back through our discord logging (this bug was bubbled up to me from my users), it looks like the WKH signature was added manually. 

From a feature enhancement perspective, would a way to disable the manual addition of signatures?  For the life of me, I cannot think of a time when I (or any other pilot) shouldn't be adding the signature from the probe scanner copy/paste directly.

If that is too heavy handed, is there a way to surface a visual cue for manually added signatures versus signature read signatures?

**Comment by exodus4d** [comment]
Adding signatures manually is fine. The issue here is, that someone forget to add the numbers to its name.
You can see the full name in the tooltip, but I agree that this is not obvious or practicable.
![sigNameTooltip](https://user-images.githubusercontent.com/9299033/69913180-bc67de00-1434-11ea-86c6-ff74cbaf130c.png)

We could think about a stronger validation (3 letters + dash + 3 numbers). This would solve the problem but would prevent users to add some temp/custom signatures to a system e.g. a "floating can" can no longer have a signature called "CAN".... (sry can´t find a better example :D)

**Comment by eophten** [comment]
Stronger validation would be great!

**Comment by exodus4d** [comment]
Signature ID (e.g. `ABC-123`) now has a stronger validation:

![sigName](https://user-images.githubusercontent.com/9299033/70339638-7bfeca80-184f-11ea-851d-775562d6c356.png)
