### ISSUE TITLE
[Enhancement] Map scroll on 'dragSelect' systems

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#879]
I thought it would be nice to "auto scroll" the map while the "dragSelect" frame is active. This would allow to select systems outside the visible map section.

#### Changes:
- The "dragSelect" frame gets updated its dimension even if the mouse cursor is _outside_ the visible map section.
- The visible map section scrolls while dragging the _select frame_ around.
- The old _jQuery_ plugin I used for "dragSelect"  is replaced with a brand new, self written lib.

#### New:
![autoScroll](https://user-images.githubusercontent.com/9299033/69900120-15217300-1370-11ea-8c1c-ce354453c1b1.gif)

#### Current:
![autoScrollOld](https://user-images.githubusercontent.com/9299033/69900121-194d9080-1370-11ea-9882-2639c831abf4.gif)

**Comment by AmraNiYesta** [comment]
Good idea, needed ♥
