### ISSUE TITLE
Installation nicht möglich.

### ISSUE THREAD

**Issue by VivianMeally** [exodus4d/pathfinder#88]
Nachdem die DB erstellt wurde und auf "Setup Table" geklickt wurde, erscheint nur eine 500 http Fehler Meldung.

Im error log des http servers steht nur
[Sun Jan 24 20:07:44.088351 2016] [mpm_winnt:notice] [pid 5756:tid 532] AH00455: Apache/2.4.9 (Win64) PHP/5.5.12 configured -- resuming normal operations
[Sun Jan 24 20:07:44.089352 2016] [mpm_winnt:notice] [pid 5756:tid 532] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:42:59
[Sun Jan 24 20:07:44.089352 2016] [core:notice] [pid 5756:tid 532] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Sun Jan 24 20:07:44.090351 2016] [mpm_winnt:notice] [pid 5756:tid 532] AH00418: Parent: Created child process 6320
[Sun Jan 24 20:07:44.365370 2016] [mpm_winnt:notice] [pid 6320:tid 452] AH00354: Child: Starting 64 worker threads.
[Sun Jan 24 20:07:48.709618 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP Fatal error:  Arrays are not allowed in class constants in C:\\wamp\\www\\app\\main\\db\\sql\\mysql\\tablemodifier.php on line 181
[Sun Jan 24 20:07:48.709618 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP Stack trace:
[Sun Jan 24 20:07:48.709618 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   1. {main}() C:\\wamp\\www\\index.php:0
[Sun Jan 24 20:07:48.709618 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   2. Base->run() C:\\wamp\\www\\index.php:19
[Sun Jan 24 20:07:48.710617 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   3. Base->call() C:\\wamp\\www\\app\\lib\\base.php:1486
[Sun Jan 24 20:07:48.710617 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   4. call_user_func_array:{C:\\wamp\\www\\app\\lib\\base.php:1655}() C:\\wamp\\www\\app\\lib\\base.php:1655
[Sun Jan 24 20:07:48.710617 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   5. Controller\\Setup->init() C:\\wamp\\www\\app\\lib\\base.php:1655
[Sun Jan 24 20:07:48.711633 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   6. Controller\\Setup->checkDatabase() C:\\wamp\\www\\app\\main\\controller\\setup.php:139
[Sun Jan 24 20:07:48.711633 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   7. spl_autoload_call() C:\\wamp\\www\\app\\main\\controller\\setup.php:379
[Sun Jan 24 20:07:48.712622 2016] [:error] [pid 6320:tid 980] [client 127.0.0.1:52332] PHP   8. Base->autoload() C:\\wamp\\www\\app\\main\\controller\\setup.php:0

Hier die fehlermeldung aus wamp.

Probiert auch unter ubuntu mit lemp und lamp. Die Meldung ist die gleiche.

Sorry, das ich hier auf Deutsch schreibe.

**Comment by Zumochi** [comment]
First of, please use English. 

Second, I'm fairly certain you get this issue because you need php 5.6 and you have 5.5. Try using xampp instead of wamp for more up to date packages.

**Comment by exodus4d** [comment]
Yeah, PHP 5.6 should fix it.

```
PHP Fatal error: Arrays are not allowed in class constants in C:\wamp\www\app\main\db\sql\mysql\tablemodifier.php on line 181
```

Check out the requirements on [wiki - Requirements](https://github.com/exodus4d/pathfinder/wiki/Requirements)

**Comment by VivianMeally** [comment]
Ok, thx. I have installed php 5.6 now.
And it was possible for me to click on "Setup Tables" and "Fix columns/keys" in the first table.
After that, i have imported CCP SDE from https://www.fuzzwork.co.uk/dump/mysql-latest.tar.bz2
But ... the second Database setup window tell me, that tables in the DB are missing, why and how can i fix it?


![ss 2016-01-25 at 10 34 23](https://cloud.githubusercontent.com/assets/8014643/12547651/d526f242-c351-11e5-868a-e5e737cf3706.png)

**Comment by exodus4d** [comment]
Check the tablenames. They are in "camelCase".

In Windows, MySQL default settings are set zu "lowerCase" (which is bad and wrong).

see #50 for more informations.

**Comment by VivianMeally** [comment]
lower_case_table_names = 2 in my.ini has solva my problem
Thx
