### ISSUE TITLE
Tooltips and menus go off window at right edge of window.

### ISSUE THREAD

**Issue by Hirmuolio** [exodus4d/pathfinder#882]
If you open right click menu near right edge of the screen and go to a submenu the submenu will go off window.

Instead of always opening the submenu to the right it should open to the left if the window edge is too close.

Similar problem also happens with tooltips. But instead of going off window they cause the window to extend (scroll bar appears at bottom). Result is same and you can't see the tooltip.

What happens:
![p](https://user-images.githubusercontent.com/22011552/69913027-4a46c780-143b-11ea-9d6b-6f88327cc75e.png)

What should happen:
![w](https://user-images.githubusercontent.com/22011552/69913029-516dd580-143b-11ea-971b-d875f02246f8.png)

**Comment by exodus4d** [comment]
Thanks for your report.

Submenus now open to the left if there is no space available at the right side.

#### Demo
- C18: (default) Menu down/right → submenu down/right
- Sarum Prime: Menu up/right → submenu down/right
- Innia: Menu up/left → submenu down/left

![contextMenuPosition](https://user-images.githubusercontent.com/9299033/69915232-1ffe0580-144d-11ea-9d0c-8e1ec832a0f9.gif)
