### ISSUE TITLE
Set destination doesn't work anymore + Need to give acces to the map for more people (individual pilotes and corporations)

### ISSUE THREAD

**Issue by AmraNiYesta** [exodus4d/pathfinder#885]
First of all, thank you for your job. I followed pathfinder from the beginning and you really improoved well pathfinder.

After 4 years of tripwire i switched for pathfinder fully. The possibility to follow 2 characters at the same time free my gameplay, I was able to dual prob and beeing followed ♥☺♥ just amazing.

But, a new patched arrived, we can share bookmarks and something is missing, I had to return on tripwire ... I am not able to add individual pilotes and i have a bad limite of who i can add to my map access list. We really need that on pathfinder, then, I think, we will have the best mapper we can find.

Some time ago  I was able to set destination from pathfinder to the game. It worked fine. Now I am not able anymore. Sad bug.

Thank you, Amra Ni-Yesta. WHPD - Wormhole Police Department ♥

**Comment by exodus4d** [comment]
@AmraNiYesta Thanks for your report.
As you correctly figured out, the "set destination" bug is known, and already fixed for the next relase: #862
The ability to "share" maps with a mix of "individual pilots" and "corporations" is also an existing feature request: #222
