### ISSUE TITLE
[Feature] Option to only add systems to map if connected to wormhole chain

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#886]
Wormhole groups typically have a ton of maps, and currently if you switch between them you'll get systems added that aren't connected to the chain. It's especially annoying when you're just looking at other chains and end up getting tons of satellite systems. 

An option for wormhole chains to only add systems to the map **if you are jumping from a system connected to the wormhole chain** would be great.

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #827
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
