### ISSUE TITLE
Error with PHP 7.4.0

### ISSUE THREAD

**Issue by pezz** [exodus4d/pathfinder#887]
Running 1.5.2 on my server but I have also tried the latest dev branch and can see the same error.

Unfortunately the error output doesn't tell me which line or file is doing it, but I can trigger it by hand when running the /cron job.

> Fatal error: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)

Cheers.

**Comment by verunightscout** [comment]
Downgrade to 7.3 ;)
