### ISSUE TITLE
Unable to enable "Private Maps" option under the "Share" submenu in the Account Settings menu.

### ISSUE THREAD

**Issue by Davak-Kateelo** [exodus4d/pathfinder#889]
I can click to switch from disabled to enabled, and click save, and then I see the "account saved" tip pop up in the bottom right.

But then I go back to the enable private maps and the condition is still set to disabled; despite just changing and saving my new configuration seconds before.  I am now unable to add my scout alt to any maps :*(

I apologize if this is already a known issue, I didn't see a solution for it anywhere.

**Comment by zap2zero** [comment]
I experience the same issue with all three share buttons on my private installation (v1.5.5).

**Comment by WladlenAlfa** [comment]
Watching the same problem

**Comment by Caffe1neAdd1ct** [comment]
Same issue will try to investigate if time allows

**Comment by Caffe1neAdd1ct** [comment]
Request form data on saving the account share tab:

```
formData[corporationSharing]: 1
formData[share]: 
formData[privateSharing]: 0
formData[allianceSharing]: 0
```

I tried enabling the share private maps which is still showing as zero, might be a javascript related issue or form html.

**Comment by nodime** [comment]
Having the same issue, which is preventing me from sharing maps with corps/alliances :(
![pathfinder_sharing](https://user-images.githubusercontent.com/37624311/72921123-924ee000-3d42-11ea-97e1-8cb5721c1adf.gif)

Do we have any solutions to this yet?

**Comment by Caffe1neAdd1ct** [comment]
Just setting up a development environment for pathfinder, if i get some more time this week i'll try and dig into this issue.

**Comment by CalMatar** [comment]
This is an issue with the Production version of the Public Pathfinder as well and I have gotten no reply from @exodus4d on here or even from a direct email so I am not sure what is going on.

**Comment by kazume** [comment]
Same issue for me *friendly bump* :)

**Comment by Caffe1neAdd1ct** [comment]
Just finished setting up the development environment for pathfinder with sass,gulp,php,mariadb etc will start having a look to see if this is something i can fix or not :+1:

**Comment by Caffe1neAdd1ct** [comment]
So looking at the post request:

```
formData[privateSharing]: 1
formData[share]: 
formData[corporationSharing]: 0
formData[allianceSharing]: 0
```

I enabled privateShare toggle which correctly posts 1 to the http://localhost:8000/api/user/saveAccount endpoint

Checked the account tab again and it was disabled, refreshing the entire page, checked again and it's green.

Interestingly on my development environment the toggles carry on working after the first click which isn't the case on the live environment

**Comment by kazume** [comment]
Maybe worth mentioning: I'm also having an issue that I can't log out or even delete the account. I get: error 403: Access denied: User not found. Might be related?

**Comment by kazume** [comment]
> This is an issue with the Production version of the Public Pathfinder as well and I have gotten no reply from @exodus4d on here or even from a direct email so I am not sure what is going on.

That's the thing wih hobby projects ^^ (I have a few of those as well myself)

**Comment by Caffe1neAdd1ct** [comment]
So further digging, it works fine with the development generated JS/CSS which isn't minified etc 

Stops working as soon as i run the production gulp task

I feel like i'm getting closer...

**Comment by Caffe1neAdd1ct** [comment]
> > This is an issue with the Production version of the Public Pathfinder as well and I have gotten no reply from @exodus4d on here or even from a direct email so I am not sure what is going on.
> 
> That's the thing wih hobby projects ^^ (I have a few of those as well myself)

Definitely, and with open source projects in general the developers can't be working on them all the time. I'm guessing exodus4d has other commitments right now.

**Comment by Caffe1neAdd1ct** [comment]
So with production:

form submits aren't submitting value of the toggles
toggles get "stuck" after the first click

development is fine

i'm guessing this is something to do with the uglification of the JS files or the order they are being included/combined.

**Comment by Caffe1neAdd1ct** [comment]
Gulp.js

```
gulp.task('task:buildJs', gulp.series(
//    'task:concatJS',
```

Disabling the concatJS and running production task is working and submitting the correct values, so its something going wrong with combining all the JS files.

**Comment by kazume** [comment]
I'm rooting for you here, just so you know!

**Comment by Caffe1neAdd1ct** [comment]
Changing
```
                findNestedDependencies: false,
```
to
```
                findNestedDependencies: true,
```

Seems to fix the bootstrapToggles and allows their values to submit on clicking save.

**Comment by Caffe1neAdd1ct** [comment]
[v1.5.5.zip](https://github.com/exodus4d/pathfinder/files/4284017/v1.5.5.zip)

Can you try replacing /public/js/1.5.5 with the attached?

**Comment by kazume** [comment]
> [v1.5.5.zip](https://github.com/exodus4d/pathfinder/files/4284017/v1.5.5.zip)
> 
> Can you try replacing /public/js/v1.5.5 with the attached?

where do I replace what? :) (sorry, noob question maybe)

**Comment by Caffe1neAdd1ct** [comment]
so on the server inside the pathfinder installation will be `public/js/v1.5.5` just move that folder to `v1.5.5_original` and unzip that new one there to test the fix

**Comment by kazume** [comment]
> so on the server inside the pathfinder installation will be `public/js/v1.5.5` just move that folder to `v1.5.5_original` and unzip that new one there to test the fix

Ah ok, that's not something I can do then. I'm just using the website interface ...

**Comment by Caffe1neAdd1ct** [comment]
Talk to the sysadmin, i'll get this raised as a pull request for @exodus4d and see if this is the right solution or not. Instead of enabling findNestedDependencies it might be a dependency needs to be listed in one of the files/modules. So need some advice first, but it works :+1:

**Comment by kazume** [comment]
> Talk to the sysadmin if yours is hosted, if your using the public one then you'll need to wait for this to be merged and updated. I'll get this raised as a pull request for @exodus4d and see if this is the right solution or not. Instead of enabling findNestedDependencies it might be a dependency needs to be listed in one of the files/modules. So need some advice first, but it works 👍

Waiting it is then ... cool stuff, thx!

**Comment by exodus4d** [comment]
@Caffe1neAdd1ct Thanks for the awesome PR! - Saves me a lot time to figure out what the problem is:

The issue only appears with "bundled/build" JS files. [_Bootstrap Toggle_](http://www.bootstraptoggle.com/) (`bootstrap-toggle.min.js`) gets loaded two times because it was bundled in two loaded JS files. 
- The main bundle `mappage.js` loads "_Bootstrap Toggle_" (which is correct)
- Later on `mappage.js` requires `datatables.loader.js` (which loads [_DataTables_](https://datatables.net/) + plugins),.. `datatables.loader.js` requires `counter.js`,  `counter.js` requires `util.js`, `util.js` requires _Bootstrap Toggle_ and initializes a 2nd time...

Unfortunately  _Bootstrap Toggle_ does not check if it was already initializes and sets some `click` event listeners on `document` a 2nd time...
https://github.com/minhur/bootstrap-toggle/blob/b76c094aca46c7d959aae991033fa578bdb0ca5d/js/bootstrap2-toggle.js#L170-L178

@Caffe1neAdd1ct PR fixes the issue indeed, but with the downside, that all bundles JS files include everything, even if the JS modules should be loaded "on demand" if they required: `findNestedDependencies: true` in `gulpfile.js`.

**Comment by Caffe1neAdd1ct** [comment]
Ahh now that makes some sense! Was very difficult to track down a reason as to why other than the fact the bundled assets didn't work and raw worked fine.

Glad you've managed to track the dependency duplication down! I had a hunch it was something along those lines :+1:

**Comment by exodus4d** [comment]
Yeah ugly bug, and invisible during development because of the unbundled JS files... I inspected the toggle DOM element and saw that it was initialized 2 times, (2nd initialize created the same DOM nodes one DOM level deeper)

**Comment by Caffe1neAdd1ct** [comment]
I'm predominately a backend developer so delving into the frontend assets and toolset isn't my speciality but I can make some progress... 

Thanks for explaining how you found the issue, helpful and good to know!

**Comment by CalMatar** [comment]
Is this also why the Management flag is not working if you are not a Director or CEO? Mine has worked sporadically since this bug started and I am not sure if they are related or not.

**Comment by exodus4d** [comment]
@CalMatar Thanks, I´ll check the management flag. What I can say is that the "map tracking" toggle was also affected by this bug.

**Comment by Lynx005F** [comment]
> [v1.5.5.zip](https://github.com/exodus4d/pathfinder/files/4284017/v1.5.5.zip)
> 
> Can you try replacing /public/js/v1.5.5 with the attached?

I replaced the [v1.5.5.zip](https://github.com/exodus4d/pathfinder/files/4284017/v1.5.5.zip)  in `public/js/v1.5.5` and the problem persists afterwards (Production enviroment). Is there a workaround until a new release is created e.g. modifying it directly in the database?

**Comment by Caffe1neAdd1ct** [comment]
@Lynx005F I just uploaded this to our hosted version and the toggles started working, the only caveat is the toggles don't update showing the saved values until you refresh the whole page and go back into the accounts section. If you save, close accounts, open accounts it will show the old value still (appearing not to have worked).

The database table can be updated, just look for the shared column on character, corporation, alliance tables.
