### ISSUE TITLE
Connect system to self.

### ISSUE THREAD

**Issue by VivianMeally** [exodus4d/pathfinder#89]
Should not be possible i think.

http://puu.sh/mKMYI/caa30e7ff1.jpg

**Comment by phneak** [comment]
I have experienced this as well, usually when attempting to click+drag to move a system and I create a loop on accident.  I do not know of a reason to allow this functionality

**Comment by exodus4d** [comment]
I added this as a new feature in `v1.0.0RC1`. I thought it would be nice to allow loopback connections. But they don´t make to much sense (for now). -> Feature removed in `v1.0.0RC2`.
