### ISSUE TITLE
Error 403: Forbidden

### ISSUE THREAD

**Issue by zap2zero** [exodus4d/pathfinder#894]
I installed v1.5.5 and everything seems to work fine except that I occasionally get an "error 403: Forbidden/Access denied: User not found".
This also happens when I click the logout button. On logout I get this error document, when I inspect the request:
`{"reroute":"https:\/\/my.hostname.com\/","error":[{"type":"error","code":403,"status":"Forbidden","message":"Access denied: User not found"}]}
`

The error logs show nothing helpful either, even with debug level 3.

Where does this come from?

PS: I use sessions in MySQL and adding an email to my account works just fine.

**Comment by zap2zero** [comment]
When I click the logout button and get the error explained above, I noticed that my logs/character_access.log looks like this:
```
Thu, 26 Dec 2019 07:55:45 +0000 [<ip>] charId: [                    ], status: NO SESSION FOUND, charName:
Thu, 26 Dec 2019 07:55:45 +0000 [<ip>] charId: [                    ], status: NO SESSION FOUND, charName:
Thu, 26 Dec 2019 08:07:11 +0000 [<ip>] charId: [                    ], status: NO SESSION FOUND, charName:
```

**Comment by exodus4d** [comment]
Thanks for reporting. The logout seems to work but instead of the error message, the user should be redirected to `/login` page.
After redirect, there is now a new "graceful" logout message shown, instead of the "error" logout message that is shown if a user gets logged out by e.g. ESI errors, or login token becomes invalid/expired:
![logout_graceful](https://user-images.githubusercontent.com/9299033/76113262-1bb12d80-5fe4-11ea-94ea-ceb77b5d4ce9.png)
![logout_error](https://user-images.githubusercontent.com/9299033/76113272-1eac1e00-5fe4-11ea-9484-217198b105cd.png)

**Comment by Caffe1neAdd1ct** [comment]
Should be as easy as returning a 200 status from controller.php function logoutCharacter line 510:

```
        if($f3->get('AJAX')){
            $status = 200;
            $f3->status($status);
```

with a 403 status returned the ajax response will call fail function instead of redirecting:

```
let logout = (params) => {
        let data = {};
        if(
            params &&
            params.ajaxData
        ){
            data = params.ajaxData;
        }

        $.ajax({
            type: 'POST',
            url: Init.path.logout,
            data: data,
            dataType: 'json'
        }).done(function(data){
            if(data.reroute){
                redirect(data.reroute, ['logout']);
            }
        }).fail(function(jqXHR, status, error){
            let reason = status + ' ' + error;
            showNotify({title: jqXHR.status + ': logout', text: reason, type: 'error'});
        });
    };
```

**Comment by Caffe1neAdd1ct** [comment]
Change working on local environment:

![image](https://user-images.githubusercontent.com/1327332/76127962-072c5f80-5ffb-11ea-9d50-423046178875.png)

vs 

![image](https://user-images.githubusercontent.com/1327332/76128023-1d3a2000-5ffb-11ea-96f1-ffb1521b4d65.png)

added to the open pull request but that does have other changes in so completely understand if you want to just fix this separately

**Comment by Caffe1neAdd1ct** [comment]
Better fix coming from @exodus4d which handles throwing a 403 for unauthorised accesses and 200 logouts by users https://github.com/exodus4d/pathfinder/commit/8f5acb2656f5a4fc26c13d2dc717c4f76669eae0
