### ISSUE TITLE
[Feature Request] View layer above maps

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#896]
It'd be nice to have a view layer above maps (tabs). 

## Example
Suppose that we have 15 maps for our corporation.
* 2 maps for primary usage
* 8 seeds
* 5 farmholes 

If we were able to switch to a view or folder for our farmholes, it'd have a lot less clutter in the top tab. Otherwise we have to host another instance of pathfinder just for them

**Comment by exodus4d** [comment]
Not sure if I get you right. Do you mean some kind of "filters"? E.g. a new option in the map settings dialog where you can "tag" maps like "formhole map", "primary map",... and then some UI context menu to filter out map tabs by their "tags"?

**Comment by porowns** [comment]
More like map folders (e.g a farm map folder), but tags could work as well for filtering. 

Use case: Some groups have tons of seeded wormholes, tons of farmholes, and multiple primary holes.
