### ISSUE TITLE
Redis not working when authentication is required

### ISSUE THREAD

**Issue by zap2zero** [exodus4d/pathfinder#897]
Pathfinder does not support Redis servers where authentication is required. F3 now supports this feature as of https://github.com/bcosca/fatfree-core/pull/287 but this alone is not enough since Pathfinder establishes its own Redis connections for caching.

**Comment by exodus4d** [comment]
Thanks for report!
I added support for `auth` parameter for _Redis_.

PHP _Redis_ Session`php.ini`:
```ini
session.save_path = "tcp://localhost:6379?database=0&persistent=1&auth=test123"
```
Pathfinder `config.ini`:
```ini
[globals]
CACHE                           =   redis=localhost:6379:1:test123
API_CACHE                       =   redis=localhost:6379:2:test123
SESSION_CACHE                   =   default
```
> **Hint:** If _Redis_ auth failed for PHP Sessions (`session.save_path`) you will probably not see `/setup` or any other page (-> check PHP error.log). If any other _Redis_ auth failed, there is now a new error row on `/setup` page:

![cache1](https://user-images.githubusercontent.com/9299033/76140563-227b8700-605c-11ea-9f44-67f7c4a79e08.png)
