### ISSUE TITLE
k-space sec status rounding

### ISSUE THREAD

**Issue by ShioR** [exodus4d/pathfinder#9]
Systems with a true sec of 0.45+ are showing as low sec, they're actually still 0.5.

I'd guess line 73 of `app/main/data/mapper/ccpsystemsmapper.php` would be where this should be changed since this is set to < 0.5 currently.

**Comment by Zumochi** [comment]
I guess it rounds up at .5, so .45 becomes .5 becomes 1.



—

**Comment by mglinski** [comment]
This issue is fixed with this PR: #12
