### ISSUE TITLE
Undefined index 'data' in abstractMessageComponent - websocket

### ISSUE THREAD

**Issue by bomkallo** [exodus4d/pathfinder#901]
Yo,

I've updated my pf instance from 1.5.0. Well, the webserver used to always have some problems, but this time i'm trying to figure out what's going on.

The error goes (or rather notice, debug level default): PHP Notice:  Undefined index: data in 
 .../socket/app/Component/AbstractMessageComponent.php on line 181

No idea, but maybe it's the fault which forces the PF to throw 500 internal from time to time.

**Comment by exodus4d** [comment]
Thanks for your report. As you said correctly: It is just a **Notice**. You can disable Notices in your `php.ini` by setting:
```ini
error_reporting = E_ALL & ~E_NOTICE
```
With my commit above, the reporting level now set automatically based on the `-debug` start option for the WebSocket.
