### ISSUE TITLE
Shattered C4 Wormhole Data Site

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#902]
I have found that a C3 data site which should have been listed in the include for all C4 shattered wormholes is not there. I am not sure if there are more but I came across this one in a wormhole I popped into today. The site is the Central Guristas Data Mining Site and is not available in a C4 list. The Sansha one is but not the Guristas one.

![Shattered C4](https://user-images.githubusercontent.com/42744905/72659529-ddf23a00-398e-11ea-909d-4f8f035e6a28.png)

**Comment by exodus4d** [comment]
Thanks for report. The missing "Central Guristas Data Mining Site" was a typo :( 

On your 2nd screenshot there are just "Combat" sites not mapped. Combat sites are a bit "out of scope. Only WH-combat sites  (no faction sites) are currently mapped. I guess there is a large amount of different sites that could spawn in shattered holes (including all the faction variations).
If you have any idea how we could verify which of those are relevant, let me know. I just don´t have the time to check every single site for every wh class :D
