### ISSUE TITLE
[Feature Request] Record of map deletion

### ISSUE THREAD

**Issue by DLuniz** [exodus4d/pathfinder#903]
Can you add a way to see who deleted a map if you had access to it?

**Comment by CalMatar** [comment]
If you have the Discord Webhook it tells you. I know this as it happened to me the other day and that is how I found out who deleted my map.
I believe there is also logging but I have not found where it is.

**Comment by exodus4d** [comment]
@DLuniz You should use the `/admin` login for this (only for "corporation" scoped maps!). 
Log in as a Corp manager, click "maps" tab and check for "deactivated" maps. If a map gets deleted it is still listed and can be activated back again. The "updated by" column should give you the character name who did the last update action which would be the "map delete".
After a few month of "deactivation", maps get deleted for ever by cronjob.
![admin_map](https://user-images.githubusercontent.com/9299033/76143928-ba3c9d80-607b-11ea-82fd-87a3134b37a7.png)

**Comment by CalMatar** [comment]
@exodus4d what about ALLIANCE maps? Has there been any traction on getting permissions for Alliance maps yet? Or for this same ability for the Alliance maps?

**Comment by exodus4d** [comment]
@DLuniz You can also disable "map delete" action for non corp managers from the `/admin` page.
@CalMatar There is currently no admin interface for alliance maps, so you can´t from the UI. But the way how maps are deleted from DB is the same, you just need someone who loggs into the DB and change the `active` column in `map` table back to `1`. 

But all this does not help you if someone clears all systems from map, and then deletes it... In this case you lost the systems + connections but you still have all the custom system descriptions/system aliases,.... available if you re-add them and "persistent system aliases" was set for it. 
If "save changes to log files" was active you can manually rebuild it from there :( 
On a private installation you can of cause load a daily DB backup file (if configured), but this can not be done on the public installation.
