### ISSUE TITLE
Connectins are showing 'Undefined'

### ISSUE THREAD

**Issue by sharkbit** [exodus4d/pathfinder#907]
After struggling with the DB updates from 1.5.3->1.5.4 I have gotten all my tables to show up as green,  and have no warning in the Database Area.  When i go the the Administration area and re import the data, the 'System data index' shows fully built then reverts to 8235/8385.

I dont know if that is causing the my Main issue 
<img width="231" alt="Undefined" src="https://user-images.githubusercontent.com/979670/72765035-7d464580-3bb8-11ea-8a89-1060bb9aa8e9.png">

There is one error in the logs:
`PHP message: [index.php:20] Base->run()" while reading response header from upstream, client: <My_client>, request: "GET /ws/map/update HT                                                                                        TP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "<My_host""
2020/01/20 18:51:13 [error] 721#721: *5724 FastCGI sent in stderr: "PHP message: HTTP 404 (GET /ws/map/update)
`  

-  I am not using 'Socket configuration'  as it is Optional

On a Side Note it would be great if you fixed the DB instead of the user. It would be better done by the install script with:
`ALTER TABLE eve_pathfinder.<table_name>CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_unicode_ci ; `

**Comment by exodus4d** [comment]
I´m pretty sure this is a either a browser cache issue after you updated to a newer PF version, or you forgot to set the new version in `pathfinder.ini`. You should also clear the backend cache after DB updates (this can be done `/setup` page).
If you stell get the "undefined" labels, please "inspect" the DOM node with your Chrome Dev-Tools and give us a screenshot of it, so I can figure which JS variable is undefined.

"System data index" does not have to be fully build, it just speeds up looking for system data. If a system is missing in the index, it will auto get added if someone wants to access its data.

The DB `CHARACTER SET` is not related to the "undefined" issue.

**Comment by sharkbit** [comment]
> or you forgot to set the new version in pathfinder.ini

Ohh...
