### ISSUE TITLE
[New] Live "Killstream" for killboard module

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#909]
### The "killboard module" now has a new feature: "**_Killstream_**"!

The idea is to auto-update the existing killboard with live killmail data without any manual "refresh" button.
Users can configure the module and subscribe to different live "_streams_".

### Example (stream: "all kills" in _EVE-Online_)
![kb3](https://user-images.githubusercontent.com/9299033/73141343-4faf3f80-4083-11ea-81d4-c2eba75bf1b6.gif)
As you can see, the killboard shows all kills in real time.... as you can see, there are many! - A subscription to "all kills" is probably not what you want, but it is a nice demonstration how it works...

### Featurs/Changes
- There are currently 4 types of _streams_ available for configuration:
![kb_filter](https://user-images.githubusercontent.com/9299033/73141422-13301380-4084-11ea-8e46-aaf4f7de5615.png)
  - **System**: Show all new kills that happen in the current selected system. (If you are not in Jita, you might wait some time for an update...)
  - **Map**: Show all new kills that happen in **any** system on the current map. (Probably the most useful stream)
  - **Maps all**: Show all new kills that happen in **any* system and **any** map you have access to
  - **All**: Shows all new kills in _EVE-Online_ (like the example above)
- More information added to each kill entry:
  - The Ship/Character/Corp/Ally of the attacker of the "final blow" was added 
  - Icons link the Char/Corp/Ally _zKillboard_ pages
  - Total number of "attackers" added as a badge counter
  - "Solo" and "NPC" badges added + a "Skull" badge if victim got podded

### Note
The feature of loading "historic" killmails of a system was not touched. There is a "divider" Headline between "historic" Kills als "live" kills:
![kb_devider](https://user-images.githubusercontent.com/9299033/73141599-1e843e80-4086-11ea-85be-7726ee1bd206.png)

#### Technical information
This is a client side "only" feature (just Javascript). Clients "subscribe" the the public **zKillboard** WebSocket and filter the incoming killstream...
src: https://github.com/zKillboard/zKillboard/wiki/Websocket

**Comment by mrurb** [comment]
Would it be possible to add Corp and/or Alliance as a filter?

**Comment by exodus4d** [comment]
From a technical perspective it is not complex. Even now, clients always subscribe to all killmails and incoming KMs are filtered in the browser and checkbox states....

The time consuming part is the new UI for something like "Corp/Ally" filter. It is not like adding a 4th checkbox. You need some input/search option for corp/allys. 

In general I´m not 100% satisfied with the current implementation of the KB module so there might be some changes in the next releases. It is not obvious for users how it works see: #932
So it is not planned to add more filters now, but might be a good enhancement in the future.
