### ISSUE TITLE
[Enhancement Request] Settings to reduce bandwidth consumption

### ISSUE THREAD

**Issue by eophten** [exodus4d/pathfinder#912]
What settings are currently built in to help reduce bandwidth consumption?  Are there settings to reduce background refresh rate (updateData/updateUserData)? 

For players who are logged off but keep pathfinder up, is there a way to reduce the refresh rate (backoff timer) or to bounce them to a static page after a certain amount of time idle? If I did my calculations correct, each user generates 134MB of traffic per hour just in updateData/updateUserData refreshes.

Edit: What i'm think with regards to static page is something like "if offline in game, and pathfinder login time is > 1 hour ago (or other configurable timeout), redirect to static page to with link to login page".

At the moment, bandwidth has become the primary cost generator for a privately hosted instance in AWS.

**Comment by exodus4d** [comment]
@eophten For a "quick fix":
- Is **Gzip** (or even better **Brotli**) compression activated on your Webserver? → Check the response HTTP headers from ajax calls. → reduced bandwidth **\~ 80-85%**
- `pathfinder.ini`:
  - `LOGGED  =   480` // max login time in min before users get logged off, you can reduce this
  - `[PATHFINDER.TIMER.UPDATE_SERVER_MAP]` section `DELAY =   5000` 
    `[PATHFINDER.TIMER.UPDATE_SERVER_USER_DATA]` section `DELAY =   5000` 
    This is the base "update" interval in ms. you can try to increase both values. e.g. set them to 8000 (8s). Hint: If the browser tab is not active, the `DELAY` is already auto set to 20000, until tab becomes active again. → reduced bandwidth **\~ 40%**
 - You could use the `WebSocket` installation (https://github.com/exodus4d/pathfinder_websocket). Users then have a persistent connection active and changed map data gets **pushed** to all users **in real time**. No delay, and no need for clients to have those periodic ajax calls. → reduced bandwidth **\~ 90%**

**Comment by exodus4d** [comment]
### :x: Issue closed
This issue has been closed because it has been inactive for a while.

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*
