### ISSUE TITLE
Updated Signatures

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#916]
With the last update to Wormholes that CCP did there are many new signatures now in C5 and C6 wormholes that were not there previously. Currently I have a V753 in my C5 WH that I have never seen before. It is a Capital Class WH going to a C6 from a C5. It is one that has been on the Anoik.is list so should have been included on the list of wandering WHs for a C5 but it is not available for selection at all so I can not account for this wormhole in my scanner results. I do not know what other changes I am going to come across but since this one is first I am posting this one and I am sure more will come.
![New Sig](https://user-images.githubusercontent.com/42744905/74268533-00e5e480-4cd6-11ea-87bd-e51c2e69a1c1.png)
![Sig Lis](https://user-images.githubusercontent.com/42744905/74268710-502c1500-4cd6-11ea-8538-d3192c48fca0.png)

**Comment by Robert-Hucks** [comment]
Same with a X877 spawning in a C4 also missing from the list of types

**Comment by Caffe1neAdd1ct** [comment]
Need to check if this is part of the eve db loaded separately or part of the pathfinder core data collected from the ESI.

I'm guessing the static data loaded into the second db inside the `types` table needs updating from the latest SDE:

`SELECT name FROM pf_uni.`type` WHERE name LIKE 'Wormhole %';`
```
Wormhole M555
Wormhole B041
Wormhole U319
Wormhole B449
Wormhole N944
Wormhole S199
Wormhole A641
Wormhole R051
Wormhole V283
Wormhole H121
```

**Comment by CalMatar** [comment]
What needs to be done is the hard coded values in the signatures table drop down availability table in Pathfinder updated to add all of the information in the Anoik.is table so that all of it is available in the particular wormhole. It is database data update if I am not mistaken but I could be wrong.

**Comment by Caffe1neAdd1ct** [comment]
@CalMatar thanks i've just run a grep over the entire code base and found the hard coded points:

./export/csv/wormhole.csv:62;V283;2.5
./js/app/ui/dialog/jump_info.js:                ['H',   'Z971', 'R943', 'X702', 'O128', 'M555', 'B041', 'A641', 'R051', 'V283', 'T458', ''],
./js/app/conf/signature_type.js:        9: 'V283 - 0.0',

I'll have a look at updating them from a new SDE :+1:

**Comment by CalMatar** [comment]
Are you one of the developers?

**Comment by Caffe1neAdd1ct** [comment]
Nope, but about to start raising pull requests to help get some of the issues fixed. I'm hosting a pathfinder for our corp so have a vested interest :)

**Comment by CalMatar** [comment]
I am kind of envious. I have had a hard time getting Pathfinder to install and run. Every time I have tried to install it I have run into problems. If I used the instructions that Mark provided I have issues with the H5BP setup when using his (modified for my setup) pathfinder.conf file when it comes to the 
  # Include the basic SSL h5bp config set
  include h5bp/directive-only/ssl.conf;

**Comment by Caffe1neAdd1ct** [comment]
@CalMatar can you raise a new issue with all the details for this? I managed to install pathfinder with reasonable ease for a live server, installing the development environment is a little harder which i'm having a look at now and attempting to lower the bar to entry :)

**Comment by CalMatar** [comment]
I have. I have a ticket in and one person suggested the docker installation with a link and I could not get that to work, kept failing. Mark answered with part of the problem but never answered with the original problem and that was months ago. I have even sent him emails but have gotten no reply so I am at a loss as to what to do. 
Did you use the h5bp setup?

**Comment by Caffe1neAdd1ct** [comment]
I used a custom CentOS 8 + Apache + PHP 7.2 FPM + MariaDB 10 setup limited to a linux user called pathfinder with most of the htaccess settings pulled into the virtualhost, can you link me to the h5bp setup docs/guide?

**Comment by CalMatar** [comment]
I am using an Ubuntu Server with Nginx PHP 7.3 (or higher can't remember)  and MariaDB (latest). I also have a limited user called pathfinder but the setup is not on VM. The h5bp setup is referenced in the main Pathfinder setup page on the Nginx page of the setup instructions.

**Comment by dnolen** [comment]
Any update on this one? Would love to see this get resolved as there are multiple connection types we cannot map in highclass space.

**Comment by exodus4d** [comment]
I´m waiting for feedback for my two comments in https://github.com/exodus4d/pathfinder/pull/924 , then I´ll merge this one. 

#### What I got out of your comments:
- _CCP_ changed the list of potential **_wandering_** WHs for (non shattered?!) systems.
- This change effects (at least?!) **C4**, **C5**, and **C6** systems.
- For those systems, there is no longer a clear distinction between WHs that only appear as "**_static_**" holes and "_**wandering**_" holes: Example from https://github.com/exodus4d/pathfinder/issues/926#issue-580844093 
  System **C4** [J213429](http://anoik.is/systems/J213429):
    - statics: **C247**→c3, **H900**→c5
    - wandering (from Anoikis):  **S047**→hs, **N290**→ls, **K329**→ns (**is nolonger valid!**)
    - **new** wandering reported: **U574**→c6
    >    ↑↑↑ Could not happen before the change because **U574** is already a static WH for **at least one** other **C4** (e.g. [J112110](http://anoik.is/systems/J112110))!

If we just add all the hole from [anoik.is/wormholes](http://anoik.is/wormholes) (see https://github.com/exodus4d/pathfinder/pull/924) we would have 2x options **U574** for those systems with static  **U574**:

![wh_changes](https://user-images.githubusercontent.com/9299033/76765409-a76e4b00-6796-11ea-8034-923d33ec4dda.png)

I think it would be best to remove dubliertes from "wandering" section if they are already in "static" section.

**Comment by CalMatar** [comment]
Correct. If the WH is already a STATIC then it does not need to be duplicated in the WANDERING.
