### ISSUE TITLE
Compass deprecated - move to libsass?

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [exodus4d/pathfinder#917]
Hi @exodus4d 

Noticed compass is being used, i've never been a fan of installing ruby etc just to compile sass for php projects. I've always reverted to using libsass and sassc as they are much lighter to install.

I'm most of the way through switching over to libsass for my development environment of pathfinder (just setting it up now) so might be a useful pull request if you'd be interested in switching over the sass compile over to libsass? 

https://github.com/compass/compass

Basic changes would be:

```
let sass                = require('gulp-sass');

let sassOptions = {
    css: 'public/css/' + CONF.TAG,      // #VERSION# will be replaced with version tag
    sass: 'sass',
    time: true,                         // show execution time
    sourcemap: true
};

/**
 * build CSS from SASS files (Compass)
 */
gulp.task('task:sass', () => {
    return gulp.src( './sass/**/*.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(bytediff.start())
        .pipe(bytediff.stop(data => {
            trackFile(data, {src: 'startSize', src_percent: 'percent', uglify: 'endSize'});
            return colors.green('Build CSS file "' + data.fileName + '"');
        }))
        .pipe(gulp.dest(PATH.ASSETS.DIST + '/css/' + CONF.TAG));
});
```

```
/*@import "compass";
@import "compass/reset";
@import "compass/css3";*/

// Compass Replacement Libraries
@import "../node_modules/compass-mixins/lib/compass";
```

```
    "compass-mixins": "^0.12.10",
    "gulp-sass": "^4.0.2",
```

**Comment by Caffe1neAdd1ct** [comment]
Looking like a good experiment so far:

![image](https://user-images.githubusercontent.com/1327332/74614550-90ddc100-5110-11ea-8a0d-f59768be8741.png)

**Comment by Caffe1neAdd1ct** [comment]
Pull request up https://github.com/exodus4d/pathfinder/pull/918

**Comment by exodus4d** [comment]
I had this on my TODO list for a long time. Thanks for the awesome PR! - But, please don´t mix up multiple issues in one PR, this makes testing difficult. That´s why I can´t merge it and took the relevant parts for this issue and changed some things.

- "compass-mixins" is no longer needed I replaced all Compass specific mixins with native SCSS mixins. The autoprefixer should do the rest of the work.
- added a new CSS reset.scss as a replacement. (Compass automatically added it´s own reset stuff)
- "gulp-uglifycss" is not needed, the `outputStyle: 'compressed'` option for "gulp-sass" does the same thing.

**Comment by Caffe1neAdd1ct** [comment]
Hi @exodus4d 

Very valid point, i'll try and keep future pull requests directly linked to one small change at a time :+1: 

Perfect summary, I'll pull the develop branch and see if there is anything else i can help with!

If you'd like me to help field the issues and reproduce and classify i'd be happy to help. I'm hosting a pathfinder for our corp so have a vested interest and it's an awesome project (so thanks a tone for making it!)

**Comment by exodus4d** [comment]
Sure! - Every help is welcome. Reproduce bugs, or improve existing stuff is fine. The only thing I´m not a fan of are PRs for custom features for specific use cases that might not be relevant to other corporations/alliances,..
