### ISSUE TITLE
[Feature Request] Banner message for a particular map

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#921]
An option for a global banner message on a map would be nice. For example, you can create a banner reminding people of war, etc.

**Comment by exodus4d** [comment]
Do you think on a temporary notification that shows up when you switch to a map that has a "banner message", and then disappears after some time? - Or more like a fix banner on top of the map tabs?

**Comment by porowns** [comment]
Sort of like bootstrap alerts is what I had in mind: https://getbootstrap.com/docs/4.0/components/alerts/

Something dismiss-able (or the option to make them static) on the actual top of the tab's map itself when you're on that tab
