### ISSUE TITLE
Sharing Returns no results

### ISSUE THREAD

**Issue by GQuantrill** [exodus4d/pathfinder#925]
Hey,

I'm attempting to share a map with a character.
They have sharing enabled, the map is private (I've tried all 3 options) and when I search for the character in the modal, I get zero results.

Any idea how to do this?

Thanks

**Comment by exodus4d** [comment]
### :grey_exclamation: Duplicate Issue
Thanks for your contribution. There is already an open Issue about this topic. #889
Feel free to participate in the discussion and share your thoughts in the comments.

#### :x: Issue closed

***
*Auto-generated response*
