### ISSUE TITLE
Missing c4 to c6 wormhole U574

### ISSUE THREAD

**Issue by jbs1** [exodus4d/pathfinder#926]
I am currently in J213429 a C4 Red giant.
I have here a U574 Wormhole going to a C6. According to http://anoik.is/wormholes that is the normal c4 to c6 wormhole, yet i can't select it in pathfinder

![pathfinder UI](https://i.imgur.com/duVULz9.png)

![eve online](https://i.imgur.com/3u4FRgp.png)

**Comment by jbs1** [comment]
Actually fixed in PR #924 
an related to  #916

**Comment by CalMatar** [comment]
I believe this can be closed as fixed.

**Comment by exodus4d** [comment]
Yes we can close this one:

![image](https://user-images.githubusercontent.com/9299033/79069781-46705f00-7cd1-11ea-934d-8d5a448e281f.png)
