### ISSUE TITLE
Killboard Streams

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#932]
Found a new issues with the Release Client. 
The new Killboard Streams system does not seam to be working the way I believe it is supposed to work. First off, I want to make sure that I have the workings correct. When you go to the filter and select the individual system that you are in it will show that KB. If you select the MAP that you are on it will show ALL KBs for ALL of the systems that are shown on THAT MAP. I did click on the ALL OF NEW EDEN one and I do not recommend that one on the public server as it just starts pulling them and the list gets long quick. The problem is the one for the Map one does not work. See the below screen shots.
This is what I see for my home system.
![Killboard Home System](https://user-images.githubusercontent.com/42744905/77456010-018f9180-6dd1-11ea-9907-e9cad85aeee0.png)
This is what I have selected.
![Killboard Streams Selection](https://user-images.githubusercontent.com/42744905/77456017-05bbaf00-6dd1-11ea-974d-c9eb095d7f37.png)
I go into my connected C5 and this is what I see.
![Killboard C5](https://user-images.githubusercontent.com/42744905/77456022-081e0900-6dd1-11ea-8188-3deb56d2db07.png)
Still the same thing selected.
![Killboard Streams Selection1](https://user-images.githubusercontent.com/42744905/77456029-09e7cc80-6dd1-11ea-9977-93c010c83c2a.png)
This is acting as if I only had the individual system selected not the map one. 

Hope this helps.

**Comment by exodus4d** [comment]
Thanks, you are right. I found the issue and will fix it before the final release.

Yeah, this is how it _should_ work. From a technical perspective, each client always subscribes to the full "killstream" of all killmails in all systems, and _PF_ then "filters" out non-relevant KMs (based on the checkboxes).
I had the idea, clients could "pre-cache" killmails that are not relevant yet, but might be relevant a second later, e.g. if someone adds a system to map, where killmails were received shortly.... (CCPs static ESI API endpoint for KM´s , would not list them because it has some minutes delay).... But this was not practicable, because you can not _predict_ what systems _might be added_ in future, and caching all KMs (even for a sort time) could be lot of data.

**Comment by exodus4d** [comment]
This should now be fixed on the public server. - To see this, please clear browser  cache.

**Comment by CalMatar** [comment]
I just checked and this is what I see after clearing cache and also closing and reopening the browser window to make sure since it did not fix it the first time.
Main WH:
![Killboard Streams Error](https://user-images.githubusercontent.com/42744905/77556905-75906f00-6e8f-11ea-97a9-8c986e734b2c.png)
Attached WH:
![Killboard Streams Error1](https://user-images.githubusercontent.com/42744905/77556943-7fb26d80-6e8f-11ea-901b-6486860eeec5.png)
I am using Firefox and the way that you said to clear the cache does not work for me but I cleared it the way I know how. I also refreshed the browser and then closed it and opened it again. I even tried opening up a completely separate browser window and just opened Pathfinder and got the same results.

**Comment by exodus4d** [comment]
Ah okay, I guess you have got me wrong. I´ll try to make it more clear what to expect from the killstrem:
1. Add "Jita" and "Amarr" to map.
2. Set killboard filter to just "map" (you have done this already)
3. Select "Amarr", you should see the last 5 kills in Amarr (no kills from any other system)
4. Wait some minutes.....

As soon as there is a new KM received from zKillboards "WebSocket" API, you will see it above the "historic" Amarr KMs. (there is a new "divider" added):

![kb_filter2](https://user-images.githubusercontent.com/9299033/77568824-878f0380-6ec9-11ea-906c-aa99e4c38c81.png)


There is no way to request killmails from more then one system. So we can not show "historic" KMs from all mapped systems, if you do not bomb ESI with one request for each mapped system.

**Comment by CalMatar** [comment]
Ok, so if you have MAP selected the only way to get KMs from all the connected maps is if they happen after you map to them before the KMs happen? You can see the historic when you link to them and see the system itself no matter what but to see them on the MAP you only will get the new ones. 
Do I understand that correctly?
