### ISSUE TITLE
[Feature Request] Signatures should be moveable to one of the separate UI containers

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#936]
Everything except signatures can be moved in Pathfinder 2.0. It would be much more effective having signatures on the right or left while you're scanning, so that you don't have to look down on the screen. 

Thera can fit, so signatures can definitely fit :)

**Comment by infinity223** [comment]
Hi.

I find this issue very troubling for me, my corporation, and two corps "affiliated". There should be an option for changing layout to get full width of map like it was before.

Imagine a map with a lot of systems, or just lower-resolution monitors.

We need it, badly.

**Comment by infinity223** [comment]
Indeed. It would speed up things like scanning a system, good request.

**Comment by CalMatar** [comment]
You do understand that the Signatures block has more information in it that the Thera block does don't you? it is a much wider block by default thus it is not able to be narrowed down to the format for the side column without making it unreadable.

**Comment by porowns** [comment]
@CalMatar It's trivial to hide information or add it to hovers based on the container size, especially when most of the information is not important. 

This is already done correctly on smaller windows, where created and updated timestamps are hidden in the signature window.

**Comment by exodus4d** [comment]
Making columns "responsive" is not the problem. They can be hidden by custom priority; from right to left;... The "problem" is indeed the min-width of the other drop-areas, which is 440px.
You need at least columns for: 
- ID
- Group
- Type
- Delete icon

The sig table is by far the most complex. You need to handle the auto-open input for the next cell because it might not be visible. Arrow key control inside the table.
It is not impossible but probably more complex than it seems.

**Comment by mrurb** [comment]
Just by squishing my window down, it goes down to 460 and does not look to bad.
Personally i think you can move the description to be on hover or hover on the pencil.
Move the filter/undo/"select all" to two lines.
And i'm pretty sure it can fit within 440px
![image](https://user-images.githubusercontent.com/3414748/79055537-251a5f00-7c4e-11ea-83bd-62087d65c01a.png)

**Comment by CalMatar** [comment]
What about those of us that utilize the time columns? What about that information? I use that in my main hole to determine what sites I run in what order and such as that. It also allows me to track what is going on with various other holes that I am working with.

**Comment by mrurb** [comment]
> What about those of us that utilize the time columns? What about that information? I use that in my main hole to determine what sites I run in what order and such as that. It also allows me to track what is going on with various other holes that I am working with.

The time is still there, all the information is still there, this would just be for when it's on the side or in a column where there is not enough space.
![image](https://user-images.githubusercontent.com/3414748/79055882-d3bf9f00-7c50-11ea-9701-6c668bbb415f.png)

**Comment by faket91** [comment]
Good request. Would love to see that.

**Comment by NormannK** [comment]
We really need that! Would be super usefull

**Comment by exodus4d** [comment]
OK, Ill check what I can do here for your.

btw. There will be additional layout settings in `v2.0.1`  that might be interesting if you just want to show the signatures panel on the right side: https://github.com/exodus4d/pathfinder/issues/935#issuecomment-614221168
1. You can switch back to the 2 column layout (old style layout) If you don´t need the extra 3rd col
2. The 'column reverse'  for each of 2/3 column layout also affects the **inner** columns (where signatures are shown)

I think with all the flexibility we already have to customize the layout (sort panels, move panels between columns, different breakpoints from mobile to 4k-Screens, responsive table columns, reverse layout order) we already cover most of the wishes. 
Next step could be a \<textarea\> where users could enter their own custom CSS and overwrite the default: [layout css](https://github.com/exodus4d/pathfinder/blob/62dc991760e3d0bfde078affde20a3fcc6ed2360/sass/layout/_map_module.scss#L156-L186) :)
