### ISSUE TITLE
If there is nothing in the side columns, they still show as empty space

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#937]
In the new layout columns, when there is nothing displayed the map is still a reduced size. If there is nothing there, the map should extend the width of the screen.

**Comment by infinity223** [comment]
Hi.

I find this issue very troubling for me, my corporation, and two corps "affiliated". There should be an option for changing layout to get full width of map like it was before.

Imagine a map with a lot of systems, or just lower-resolution monitors.

We need it, badly and asap.

**Comment by CalMatar** [comment]
This has been addressed in another report. You change the resolution of your monitor and it will get rid of the right column but that is the only way. As far as I know right now it is not changing for a little bit. I might be changing at a later date but that is yet to be seen.

**Comment by porowns** [comment]
@CalMatar Care to link the issue so that we can close this if it's redundant?

**Comment by CalMatar** [comment]
It was ticket #935 That ticket was closed. You can look it up. If you click on closed tickets it is one of the top ones.

**Comment by porowns** [comment]
Duplicates https://github.com/exodus4d/pathfinder/issues/935
