### ISSUE TITLE
Why charactersheet on API?

### ISSUE THREAD

**Issue by FooDownunder** [exodus4d/pathfinder#94]
One of the things that you mention is 'any security issues'.

Your api request states : Create a new key with an **empty** 'Access Mask (8).

Maybe you need some of this information, but you are asking for the full character sheet, which is a lot more than an 'empty' mask, including skills, implants and corporate roles.  http://games.chruker.dk/eve_online/test_eve_api.php?function=character_charactersheet&myeve_key_id=

Looking at the source code, I can see calls to /account/APIKeyInfo.xml.aspx, /map/Jumps.xml.aspx, and /map/Kills.xml.aspx

These all will be provided with an empty access mask (0) and do not require character sheet.

Do you need the access mask 8 (character sheet) for pathfinder (or other) reasons?  Is there a couple of typos on the api screen?

**Comment by exodus4d** [comment]
Access mask (0)  works of course. I don´t need any additional information. Registering with an empty mask should work fine. The (8) was just a relic from an older version. Ill fix the typo.

The support of CCPs´s XML APIs will be deprecated soon, once the CREST login is ready (#84). This will replace any user API Key. But for the next few weeks, we have to stick with those API Keys.

**Comment by exodus4d** [comment]
Issue resolved in `master` branch
