### ISSUE TITLE
websocket warning bug

### ISSUE THREAD

**Issue by ElekDragon** [exodus4d/pathfinder#941]
![socket_config_bug](https://user-images.githubusercontent.com/15607321/78987213-a8905f00-7b2d-11ea-9077-1fe043a84e28.PNG)
Did I miss something ? Because I got a warning without explicit error. Any Idea ?

**Comment by exodus4d** [comment]
Hi, thanks for your report. 
Don't worry your WebSocket config is OK. I was just to lazy to update the badge counters.
Should be fixed for the next release.

**Comment by ElekDragon** [comment]
Ho thks for this feedback.
