### ISSUE TITLE
Wiki update, missing dependencies for build

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#946]
Can you please add that the build now requires imagemagick and graphicsmagick

**Comment by exodus4d** [comment]
Thanks for the hint!
The 'image' related _Gulp_ tasks are new in `v2.0.0` and were added in the context of #917.

#### I revised the [Build-process](https://github.com/exodus4d/pathfinder/wiki/Build-process) wiki page (and all child pages):
- _Ruby_ + _Compass_ is no longer required, and is removed from wiki
- Required _Node_ + _NPM_ versions were updated
- I replaced all screenshots with up2date screenshots
- Requirement for [_GraphicsMagick_](http://www.graphicsmagick.org/README.html#installation) is added
- Revised all texts/descriptions

### Image _Gulp_ tasks:
- Auto generate/crop header background for different breakpoints: [pf-header.png](https://github.com/exodus4d/pathfinder/blob/master/img/header/pf-header.png) → [15 variations](https://github.com/exodus4d/pathfinder/tree/193204bec9126a3df013b5ef2d6a0f79dfd22e65/public/img/v2.0.0/header)
- Generate *.webp versions (~15% smaller than *.jpg + better quality)
- Optimize SVG files
