### ISSUE TITLE
[Feature Request] Make the "show regions" label clickable to display only the regions on map

### ISSUE THREAD

**Issue by faket91** [exodus4d/pathfinder#947]
For our rather big crew we require the display of the region on the map itself.

We are aware of the existence of the "show regions" label, but the amount of information displayed while hovering over it is simply overwhelming and rather distracting.  The spacing of the text in the appearing bubbles is big. 
As you can see here:
![d8fa0cdbf0](https://user-images.githubusercontent.com/63539038/79067560-72371900-7cc0-11ea-8bdc-e951216d098a.png)

For those reasons we would love to be able to click on the label itself to make the display of the region (and only the region) permanent, without the need to further hover over it. 
The more streamlined it looks, the better. We require fast overview of systemnames and regions, to speed up our navigation through connections.

At this point of time we are still partially using Siggy, which simply states the region name next to the system name. Like in this example:
![8c62d34f49](https://user-images.githubusercontent.com/63539038/79067750-03f35600-7cc2-11ea-878e-13c7f572b989.png)
Making Pathfinder show the region in a similiar way when clicking on the show regions label would make us switch over from Siggy completly.

I found this screenshot in a closed feature request from 2017 and it is, in our opinion a very good approach:
![49533041-4337b880-f8be-11e8-846b-86eb299c407d](https://user-images.githubusercontent.com/63539038/79068033-18d0e900-7cc4-11ea-83d8-023229139107.png)

The display of the holding Sov Alliance is not needed for our usecase as much as the region itself. 

Thank you for your time!

EDIT: Spelling.

**Comment by NormannK** [comment]
one way to do that:
Make the "label" button clickable. If enabled show only the region. On mouse over show like its done now.

**Comment by lord-carlos** [comment]
Hi
My corp is the one using the solution from your last screenshot, where it shows region in k-space systems.
It's a must have feature for my corp.
Sadly we don't have a large IT department and it's always iffy to maintain a separate code, even if it's just one line. We would also like to have an upstream solution.

The change for the enduser is so minimal, I would not mind if it's always there.

Here is the change: https://github.com/lord-carlos/pathfinder/commit/1e5acd5e2727dcf5c2650acc77b7d120702d7ea1
Not tested with latest version though.

**Comment by exodus4d** [comment]
OK, for better understanding, This is the current state `v2.0.0`:
|                            | k-space | w-space |
|-------------------|---------|---------|
| empty                |   ![image](https://user-images.githubusercontent.com/9299033/79645244-678fee80-81ae-11ea-8977-50fe3576335b.png)  |  ![image](https://user-images.githubusercontent.com/9299033/79645176-fe0fe000-81ad-11ea-8be4-bef1aee6a438.png)  |
| users (default)    |  ![default1](https://user-images.githubusercontent.com/9299033/79645393-55628000-81af-11ea-9bbc-9808ebc50c25.gif)   |   ![default2](https://user-images.githubusercontent.com/9299033/79645123-aa04fb80-81ad-11ea-8de2-d78e70808155.gif)  |
| users (compact) |  ![image](https://user-images.githubusercontent.com/9299033/79645450-ca35ba00-81af-11ea-8e66-316cc80e8cb7.png)   |  ![image](https://user-images.githubusercontent.com/9299033/79645426-8f338680-81af-11ea-94a2-06630d32c984.png) |

"Compact view" also has a uniquepilot/ship tooltip:
 ![image](https://user-images.githubusercontent.com/9299033/79645312-dcfbbf00-81ae-11ea-86ea-57d399939ae2.png) 

***

1. If i get you right, region names are relevant for **k-space** systems only, right? - So we can ignore the right column (no changes). Any known use case why w-space systems need a region name, too?
2. I would recommend some kind of "configuration"... maybe "on/off toggle" (like compact view). I also like @NormannK suggestion and "replace" the system name with region name (e.g. on hover).
3. I would recommend to rename "compact mode" to "inline character data" (any suggestions?)... if you have "compact mode" active, and a 2nd row is added with region name, it is no longer compact in my eyes.

Please tell me what you think 🤔

**Comment by samoneilll** [comment]
You are correct that this is only relevant for kspace connections (I cannot think of a j-space use-case, but I am from the same corp as lord-carlos). 

My suggestion would be that you simply use the space where static connections would go on a j-space system card and place the region name here.

This has the added benefit of keeping system cards a consistent height for both k- and j-space systems.

**Comment by NormannK** [comment]
![Unbenannt](https://user-images.githubusercontent.com/23198136/79672123-8b176100-81cf-11ea-8898-716dc0af671b.png)
We are using the solution by @lord-carlos now. But a build in solution would be better oc :-)
#1 i dont see a use for it in W-space
#3 call it "reduced" or "minimized" mode. But compact isn't wrong too.

**Comment by faket91** [comment]
> 1. If i get you right, region names are relevant for **k-space** systems only, right? - So we can ignore the right column (no changes). Any known use case why w-space systems need a region name, too?

Correct. We are not aware of a use case for w-space, therefor you can consider only the k-space relevant for this change.
 
>     2. I would recommend some kind of "configuration"... maybe "on/off toggle" (like compact view). I also like @NormannK suggestion and "replace" the system name with region name (e.g. on hover).

A configuration for this view would be lovely, I have to agree. 
On another issue-post, which I can't seem to find anymore, I have seen a suggestion to change the "show regions" label and make it a 3-state toggle. By clicking on it you can switch between several different modes.
![3e7690c2de](https://user-images.githubusercontent.com/63539038/80141260-9260b500-85a9-11ea-8b9d-509e7ec45ddb.png)

Depending on how the user has toggled the label, the level of information could be reduced or more detailed. In example ...
_Toggle/Mode 1 - Standard:_ Display the indicator for High (H), Low (L) or Null (0.0), the systemname, the region aswell as the numerical indicator for the amount of users in system.
_Toggle/Mode 2 - Compact:_ Display the indicator for High (H), Low (L) or Null (0.0) and the systemname.
_Toggle/Mode 3 - Detailed:_ Display the indicator for High (H), Low (L) or Null (0.0), the systemname, the region, the numerical indicator for the user amount in system aswell as the usernames when you hover over it.
 
>     3. I would recommend to rename "compact mode" to "inline character data" (any suggestions?)... if you have "compact mode" active, and a 2nd row is added with region name, it is no longer compact in my eyes.

Enabling compact mode and having another row added does not sound compact at all, you are right.
Maybe switch the modes around then? 
Have the region always displayed unless you have the compact mode active. Upon enabling compact mode the region gets removed and the additional row disappears. At least that would be my suggestion.

Thank you again for your time you are investing into this project.

**Comment by exodus4d** [comment]
#### Changes made:

1. "Map menu" has a new structure: On/Off toggle options are split into 3 groups:
    - "Map" related options (grid, magnet)
    - "System" related options (**region label**, compact view)
    - "Connection" related options (signature overlays)
    ![image](https://user-images.githubusercontent.com/9299033/80256252-c063f900-867e-11ea-8acd-9a74a037e1bd.png)
2. New option "region label" show region names for k-space systems in 2nd row (as discussed above)
    - long region names get truncated and will not increase total system with:

    |                 | k-space |
    |-----------------|---------|
    | empty           |   ![image](https://user-images.githubusercontent.com/9299033/80255382-133cb100-867d-11ea-8604-e70df0620c06.png)   |
    | users (default) |    ![toggle](https://user-images.githubusercontent.com/9299033/80255360-0750ef00-867d-11ea-8f8e-3d7bfae98085.gif)  |
    | users (compact) |    ![image](https://user-images.githubusercontent.com/9299033/80255068-85f95c80-867c-11ea-9a96-b9f1a7658b92.png)    |

3. The "old" hover icon, for "region names" has a new icon, region names are removed from the tooltips and contain sov. info only:
![image](https://user-images.githubusercontent.com/9299033/80257484-50a33d80-8681-11ea-9834-57b63de0bf40.png)

Like all the other "on/off" toggle options, "region label" is a client side view option.  Since the dimension (height) is changed if region names are shown, users with different settings will get slightly different layouts! Connection endpoints might switch from e.g. "left" to "bottom"...

![toggle](https://user-images.githubusercontent.com/9299033/80258458-9103bb00-8683-11ea-9c24-02cb1f02ad3c.gif)

**Comment by faket91** [comment]
Thank you very much. This will help alot!
Closing this issue :) <3
