### ISSUE TITLE
Delete Missing Sigs

### ISSUE THREAD

**Issue by Raykazi** [exodus4d/pathfinder#95]
Other popular mapping tools out there allow you to delete the missing sigs when you do the signature reader. Is this a feature that could be implemented in pathfinder?

**Comment by exodus4d** [comment]
Do you mean, an auto delete function that deletes all signatures from the table which are no longer available in clipboard?

The implementation of this is very easy. I´m pretty sure I have already implemented this at one point in the past. :) - But it has never made it into any release. This is a very powerful feature and lead to some problems:

- If  user accidentally forgets to copy *all* signatures in-game. Those signatures would be deleted. This can easily happen if...
  - .. a signature filter is active
  - ... your just copy some signature rows and forget the others
  - ... the scan distance is lowered
  - ... the scan angle is reduced

If you're not careful ( `CTRL`+ `A` is your friend ) you can mess up a lot. Therefore i haven´t done it yet. Maybe we could add a **checkbox** to the sig-reader dialog which enables this feature. What you thing?

**Comment by Raykazi** [comment]
On 2/7/2016 9:37 AM, Mark Friedrich wrote:
>
> Do you mean, an auto delete function that deletes all signatures from 
> the table which are no longer available in clipboard?
>
> The implementation of this is very easy. I´m pretty sure I have 
> already implemented this at one point in the past. :) - But it has 
> never made it into any release. This is a very powerful feature and 
> lead to some problems:
>
>   * If user accidentally forgets to copy /all/ signatures in-game.
>     Those signatures would be deleted. This can easily happen if...
>       o .. a signature filter is active
>       o ... your just copy some signature rows and forget the others
>       o ... the scan distance is lowered
>       o ... the scan angle is reduced
>
> If you're not careful ( |CTRL|+ |A| is your friend ) you can mess up a 
> lot. Therefore i haven´t done it yet. Maybe we could add a *checkbox* 
> to the sig-reader dialog which enables this feature. What you thing?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/exodus4d/pathfinder/issues/95#issuecomment-181024697>.
>
Yes, that is what i mean and any safety check that you deem feasible is 
fine with me.

**Comment by Zumochi** [comment]
Maybe make it so that if only one sig is copied, it gets added. 
If more are copied, ask for a confirmation from the user "Old signatures will be removed. Are you sure?"

**Comment by Calavoow** [comment]
Tripwire shows a little pop-up notification which asks to delete signatures that weren't present in your paste (`ctrl-v`). I think this is a decent solution, but it could help to include a warning if too many signatures are changed by the paste. Because it has happened to me that I pasted sigs into the wrong system and thus deleted all my scanned information.

**Comment by ZarosTenjin** [comment]
bumping this since this feature would be really useful to have. a checkbox would be enough imho

**Comment by Dessix** [comment]
Tripwire also has an "Undo" option that lets you revert changes that were not as intended.

**Comment by Calavoow** [comment]
> Tripwire also has an "Undo" option that lets you revert changes that were not as intended.
An undo would be nice yes. But it is technically a bit more challenging.

**Comment by exodus4d** [comment]
Thanks for all the feedback!
**This is now tagged for the new release (`v1.1.1`), and in progress**...

***

UI preview:

![sig_reader](https://cloud.githubusercontent.com/assets/9299033/16282396/e4a91262-38c8-11e6-94bc-b93dc0f3fe2f.png)

**Comment by Calavoow** [comment]
Excellent, was actually working on a little modification of my own to add this (seemed like a good intro to the project). Just never got to actually finishing it. Do you mind pushing the commit so I can compare?

**Comment by dnolen** [comment]
Can we confirm when this feature might be included. it seems to be a pretty frequent ask for members in my corp due to in inadvertent copy and paste errors. 

This is very much a quality of life change
