### ISSUE TITLE
can't save settings or toggle buttons

### ISSUE THREAD

**Issue by ivveh** [exodus4d/pathfinder#950]
Hello,
So this is version 1.5.5.
Currently tested with firefox, chromium and chrome.

So the toggle buttons under Menu->Account->Share, can be toggled but only once. So if it's disabled you can move it to enabled and if you press save it seems all happy and tell you that settings are saved, while in fact they are not. The same applies to the "map connection tracking" toggle. By default it is "on", if you toggle it to "off" you can't toggle it back again.

I was able to share a map since my character already had it enabled. So that works, and pretty much everything else works that I have tested. This is an installation that has existed for some 120days and been upgraded once. This has worked before as I have shared maps with a different corp. I have only tried to restart the application after checking logs when a "toggle" is performed by my own sessions or corpmembers. But nothing happens. Haven't tried enabling debug yet or restarted database as it seems to be a problem with the webapp and not the DB.

**Comment by ivveh** [comment]
Upgraded to 2.0.0 and the problem is no longer present.

**Comment by CalMatar** [comment]
So close the ticket.
