### ISSUE TITLE
Captcha Error on Sign up

### ISSUE THREAD

**Issue by DuLLSoN** [exodus4d/pathfinder#96]
I cannot create account because of an error, captcha image wont show up and a red error popup appears.
![capture](https://cloud.githubusercontent.com/assets/5316261/12963020/0b16d384-d051-11e5-95bd-a51ec13cad3b.PNG)

I looked up on traffic logs and post request on https://www.pathfinder-w.space/api/user/getCaptcha returns HTTP/1.1 500 Internal Server Error, error body has this text: {"error":[{"type":"error","code":500,"status":"Internal Server Error","message":"Class 'Image' not found"}]}

**Comment by DuLLSoN** [comment]
Made it work on another browser. Looks like this error occurs when your browser accepts a different language.

Request with this header returns error:
> Accept-Language: tr-TR,tr;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.2

While this one works:
> Accept-Language: en-US,en;q=0.8,tr;q=0.6

[detailed_log.txt](https://github.com/exodus4d/pathfinder/files/125716/2_Full.txt)

**Comment by maraaaa** [comment]
Also having this issue.  However, it doesn't seem to matter what Accept-Language I send.  By default it's:

    Firefox: accept-language 	en-US,en;q=0.5
    Chrome: accept-language	en-US,en;q=0.8

However,  when I manually set it to `en-US,en;q=0.8,tr;q=0.6` using this firefox addon: https://addons.mozilla.org/en-US/firefox/addon/quick-accept-language-switc/

I receive the same error.

I don't see anything being logged in pathfinder/logs and nginx does not record an error.

Other ideas for debugging?

Thanks!

**Comment by exodus4d** [comment]
Thats interesting. 
Pure POST or GET Requests won´t work on any API-Endpoint. Those Endpoints are supposed to be called bei AJAX and require `X-Requested-With: XMLHttpRequest` Header information to work -  [Framework Docu](http://fatfreeframework.com/routing-engine#AJAXandSynchronousRequests) - routes.ini [L.17](https://github.com/exodus4d/pathfinder/blob/master/app/routes.ini#L17).

Just testet, my accept-language looks like this: `de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4` (works fine).
The Response should look like this, which is a base64 encoded *.png image with the Captcha:
```
{
error: [],
img: "data:image/png;base64,iVBORw0KGgoAAA........."
}
```
Testet in *Chrome v.47*, *Chrome Canary v.50*, *Firefox v44*

It does not look like a PHP bug if this problem just appears, depending on the *accept-language* Header send by the client. Anyways, the Code can be found [user.php L116](https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/api/user.php#L116)

**Comment by exodus4d** [comment]
In Addition: The Captcha is removed in the next release anyway. Im working on a fully CCP-SSO based registration/login system, which does not require any user information stored by *Pathfinder* itselve. 
-> No user Registration required.
-> Corps/Allys can grant access by a configurable whiteliste.
-> Pilot Tracking is fully CREST based

**Comment by maraaaa** [comment]
Hi @exodus4d,

I think my issue may be different than @DuLLSoN...  http://i.imgur.com/wFmFucm.png

I'm not getting a 500 error, and this issue only occurs when I attempt to access the site via IP.  This morning I added an entry in /etc/hosts and am able to get past the Captcha.  I'm not sure what would cause that as the login form appears to link to #... 

I do however see a couple of images that link to `https://<mydomain>` which would indicate that there is a hardcoded call to the `URL` attribute set in app/environment.ini (as opposed to using the $request_url)

    
    <meta property="og:image" content="https://p.example.com/public/img/logo.png">
    <meta property="og:url" content="https://p.example.com">

I am running in production mode if that makes a difference.

Anyway, I've got a workaround for my issue until my DNS guy can add the proper entry.  Thanks for the assistance!  It looks like a neat tool.

**Comment by DuLLSoN** [comment]
@exodus4d I can't think of a reason for a request to fail because of language preference either but this is what I found after comparing my requests, they had required ajax headers, I [captured](http://ge.tt/9BTlozX2) them with fiddler. Some other api calls like system search has this problem too. Now, I have a workaround and ability to replicate this problem. I don't have much PHP expertise but definitely going to do some tests in hopes to find the cause.

**Comment by exodus4d** [comment]
If there is anything else I could do here, please reopen.

**Comment by Ricaz** [comment]
I also have this issue (500). Tried changing Accept-Language around a bit, nothing seemed to work (even the standard `en-US,en;q=0.8`).
I'm not sure what to do. If there's a simple way to disable Captcha, I would like to know.

**Comment by maraaaa** [comment]
When I ran into this issue I was trying to access the page via IP because
DNS hadn't propagated. Accessing the site via hostname resolved the issue.

**Comment by exodus4d** [comment]
Ok cool, thanks for the feedback
