### ISSUE TITLE
Can't assign same system to two different signatures

### ISSUE THREAD

**Issue by faket91** [exodus4d/pathfinder#960]
### **Usecase**
We are mostly mapping Drifter wormholes (Conflux, Redoubt, Sentinel, Barbican and Vidette) to find connections into k-space. 

### **Issue**
Since they have around 60 connections it is not uncommon at all to have two signatures in the same wormhole connect to the same system.
If this occurs, you can only assign the system to one signatures. If you want to assign the second signature to that system it is grayed out.

![c2131eb091](https://user-images.githubusercontent.com/63539038/80289052-4eea8000-873c-11ea-8628-7fe966dab5ee.gif)

Now if the signature which had the system assigned despawns for whatever reason your routefinding tool will not pick up the existing second connection and simply ignore it instead.
Therefor the route will not be displayed unless the users remember and manually assign the system to the second signature.

### **What would fix our problem**
Enable us to assign the same system to multiple signatures in the same wormhole.
For our usecase it is not relevant if the system gets displayed more than once on the map if it gets assigned to two signatures, but being able to toggle EOL on either of the connections would be nice.

---------------------

If you need further input, please let me know. Thank you once again for your time and effort to make this tool so awesome.

**Comment by CalMatar** [comment]
You have to have two different connections to do this. Simply drag another connection to the system and you will be able to connect a second signature to that system. I do this all the time. That is the only way to do it and he has addressed this a couple of times before.

**Comment by faket91** [comment]
I honestly did not know that and did not think of trying it on that way.
The method of dragging another connection between both systems and reassigning the "leads to" works perfectly. Thank you. 

Consider this closed.
