### ISSUE TITLE
no Setup Dashboard

### ISSUE THREAD

**Issue by Joachim1410** [exodus4d/pathfinder#964]
Hi 
I tryed the last 4 days to install pathfinder for our corp on my dedicated server but i'm not familiar with websites ...
I followed the wiki and i'm at this step https://github.com/exodus4d/pathfinder/wiki/Setup ,but i think i did something wrong , first  i know no if i have to use the DEVELOP or PRODUCTION environement in any case when i try to login i get this [in DEVELOP](https://sisilogin.testeveonline.com/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Fmaldencounty.com%2FEurekaHolding%2FMap%2FEurekaHolding%2FMap%2Fsso%2FcallbackAuthorization&client_id=17bdd1773f6a4431a2e06f8d58cb0e8f&scope=esi-clones.read_clones.v1%20esi-corporations.read_corporation_membership.v1%20esi-location.read_location.v1%20esi-location.read_online.v1%20esi-location.read_ship_type.v1%20esi-ui.open_window.v1%20esi-ui.write_waypoint.v1%20esi-universe.read_structures.v1&state=4476a203bd8d247fa28fb895) or this [in PRODUCTION](https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Fmaldencounty.com%2FEurekaHolding%2FMap%2FEurekaHolding%2FMap%2Fsso%2FcallbackAuthorization&client_id=5831bacc9e8345959b74d884984e57e4&scope=esi-clones.read_clones.v1%20esi-corporations.read_corporation_membership.v1%20esi-location.read_location.v1%20esi-location.read_online.v1%20esi-location.read_ship_type.v1%20esi-ui.open_window.v1%20esi-ui.write_waypoint.v1%20esi-universe.read_structures.v1&state=57a91567fa575ffa5f752b50) .Second i can't reach the setup with  www.[YOUR_DOMAIN]/setup ( error 404). I temporarily use the domain name during installation http://www.maldencounty.com/EurekaHolding/Map/

**Comment by Tupsi** [comment]
Please close this issue, as its not code bug and come to slack. There is a #support channel where we are happy to help you solve this.

**Comment by Joachim1410** [comment]
I dont understain how work slack , and i still stuck tanks
