### ISSUE TITLE
Ubuntu 14.04 Installation Process

### ISSUE THREAD

**Issue by maraaaa** [exodus4d/pathfinder#97]
Hello,

I have documented the installation process for Ubuntu 14.04.

Best Reagrds

    ubuntu 14.04 install process
    
	# run as root
	
	# Install ppa management utilites
	apt-get install python-software-properties
	
    # Install MariaDB repositories (Open Source, drop in replacement for MySQL)
    apt-get install software-properties-common
    apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
    add-apt-repository 'deb [arch=amd64,i386] http://ftp.utexas.edu/mariadb/repo/10.1/ubuntu trusty main'
    
    # Install nginx repositories
    add-apt-repository ppa:nginx/development
    
	# install php-5.6 repositories
	add-apt-repository ppa:ondrej/php5-5.6
	
    # Install required packages
    apt-get update
    apt-get install mariadb-server mariadb-client php5-mysql nginx php5-curl libpcre3 libpcre3-dev php5-gd php5-fpm php5 nginx git
    
    # install html 5 boiler plate
    sudo mv /etc/nginx /etc/nginx-previous
    git clone git@github.com:h5bp/server-configs-nginx.git /etc/nginx
    
    # configure database, replace password with actual password.  Should probably pick a better name for the eve static data.
    mysql -p'rootpassword' -e "create user 'pathfinder'@'localhost' IDENTIFIED BY 'password'"
    mysql -p'rootpassword' -e "create database pathfinder CHARACTER SET utf8 COLLATE utf8_general_ci"
    mysql -p'rootpassword' -e "grant all on  grant all on pathfinder.* to pathfinder@'%'"
    mysql -p'rootpassword' -e "create database eve_parallax_min CHARACTER SET utf8 COLLATE utf8_general_ci"
    mysql -p'rootpassword' -e "grant all on eve_parallax_min.* to pathfinder@'%'"
    
    # Alternatively if you don't want to type your root db password into your bash history...:
    mysql -p
    create user 'pathfinder'@'localhost' IDENTIFIED BY 'password';
    create database pathfinder CHARACTER SET utf8 COLLATE utf8_general_ci;
    grant all on  grant all on pathfinder.* to pathfinder@'%';
    create database eve_parallax_min CHARACTER SET utf8 COLLATE utf8_general_ci;
    grant all on eve_parallax_min.* to pathfinder@'%';
    
    # Setup static eve DB
    mkdir /tmp/static
    wget https://www.fuzzwork.co.uk/dump/mysql-latest.tar.bz2 -O /tmp/static
    tar xf tar /tmp/static/mysql-latest.tar.bz2 -C /tmp/static
    mysql -p eve_parallax_min < $(find /tmp/static -name '*.sql')
    
    # Create a user for pathfinder, I have persistent storage mounted on /opt, exclude the `-b /opt` if you wish to use the /home as your base
    useradd  pathfinder -b /opt -m
    
    # Clone pathfinder
    sudo -u pathfinder git clone https://github.com/exodus4d/pathfinder.git /opt/pathfinder/pathfinder
    
    # delete htaccess
    rm /opt/pathfinder/pathfinder/.htaccess
    
    # Configure site environment.ini
    1. set SERVER to PRODUCTION https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L7
    2. set database user to pathfinder https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L50 and https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L57
    3. set db name to pathfinder https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L50
    4. set DB_CCP_NAME to eve_parallax_min https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L56
    5. set database password https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L52 and https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L58
    
    # !!  probably need to set SSO_CCP_CLIENT_ID and SSO_CCP_SECRET_KEY 
    # !!  https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L60-L62
    # !!  Looks like relevant documentation https://eveonline-third-party-documentation.readthedocs.org/en/latest/sso/intro/
    
    # Requires SMTP configuration https://github.com/exodus4d/pathfinder/blob/master/app/environment.ini#L64-L72
    # Has not been vetted  https://www.digitalocean.com/community/tutorials/how-to-install-the-send-only-mail-server-exim-on-ubuntu-12-04
    
    # Set permissions on log and tmp directories, DO NOT set this to 766
    chown www-data:www-data /opt/pathfinder/pathfinder{logs,tmp}
    
    # download nginx and pathfinder config files
    wget https://gist.githubusercontent.com/exodus4d/c57064ac55e64b831a31/raw/04f4771c304b6d200433c3db71fe839099b2b49a/nginx.conf -O /etc/nginx/nginx.conf
    wget https://gist.githubusercontent.com/exodus4d/791f2742e6b2ee5ef481/raw/f0196b4e11846ed3a7b6e341fb24195c2eca37c7/pathfinder.conf -O /etc/nginx/sites-available/pathfinder.conf
    
    # "enable" site
    ln -s /etc/nginx/sites-available/pathfinder.conf /etc/nginx/sites-enabled/
    
    # generate SSL certificate 
    domain=pathfinder.example.com # replace with your domain
    mkdir /opt/${domain}/ssl
    openssl req  -newkey rsa:2048 -nodes -keyout /opt/$domain}/ssl/${domain}.key -x509 -days 365 -out /opt/$domain}/ssl/${domain}.crt
    
    # create nginx log directory
    domain=pathfinder.example.com # replace with your domain
    mkdir /opt/${domain}/log
    chown www-data:www-data mkdir /opt/${domain}/
    
    # Edit nginx.conf
    1. set user to www-data wwww-data https://gist.github.com/exodus4d/c57064ac55e64b831a31#file-nginx-conf-L5
    
    # Perform edits to pathfinder.conf
    1. Unless domain starts with www remove https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L13-L27
    2. set server_name https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L9 and https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L35
    3. If domain is www. set server_name https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L19
    4. unless domain starts with www. remove "www." from redirect https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L10
    5. set root to /opt/pathfinder/pathfinder https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L38
    6. set ssl certificate directory https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L49-L50
    7. set web log directory https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L56-L57
    8. Uncommebt setup section https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L64 and https://gist.github.com/exodus4d/791f2742e6b2ee5ef481#file-pathfinder-conf-L67-L68
    
    # verify nginx config
    service nginx configtest
    
    # restart nginx
    service nginx restart
    
    # Setup Pathfinder DB
    Navigate to http://<yorudomain>/setup
    scroll to pathfinder db and select "Setup Database"
    
    - comment out the admin section of /etc/nginx/sites-available/pathfinder.conf 
    
    # restart nginx
    service nginx restart
    
    # setup cron?
    curl -kv https://localhost/cron
    
    # setup invite system?

**Comment by exodus4d** [comment]
Awesome work! Maybe we can copy this to a [Gist](https://gist.github.com/) and I´ll link it somewhere in the Wiki. This may help others to find this guide easier than searching Issues.

**Comment by exodus4d** [comment]
This guide  is now linked in the [wiki](https://github.com/exodus4d/pathfinder/wiki). ;)

**Comment by Ulaxidor** [comment]
Hi I have followed this guys and admittantly I am not an expert but I have set up several wordpress sites, mysql databases, and have hosted eve-w-space on my own server but this is proving to be a bit more challenging.  I followed these instructions with a few appropriate modifications and I always get a connection refused error

**Comment by kiu** [comment]
> chown www-data:www-data /opt/pathfinder/pathfinder{logs,tmp}

Add a "/" before "{logs,tmp}"

**Comment by Ulaxidor** [comment]
Thanks for your response Kiu.  I've performed that step correctly and created 2 separate subdirectories within the main pathfinder directory, one called logs, and one called tmp.  I have even tried changing the permissions to 0766 on each of those directories but I still cant get it to work =./

**Comment by hybrid1969** [comment]
I have followed this but amd getting a fail at the 'sudo service nginx restart' part

Any ideas as im not a nginx user and cannot see any issue?

**Comment by Dessix** [comment]
I've got this running on Apache with little to no issue during installation with PHP7.0, but could not manage to run it from a subfolder successfully.

**Comment by hybrid1969** [comment]
Dessix would you have a guide as I am a lot more familiar with apache.

Nginx seems to collapse at the slightest issue and i have tried installing this several times and it refuse's to even acknowledge port 80 now.

**Comment by Ulaxidor** [comment]
@hybrid1969 did you move the original nginx directory to nginx-previous and download the h5bp version using the  "git clone git@github.com:h5bp/server-configs-nginx.git /etc/nginx" command?  What do you get when you type this command "sudo nginx -t" ?

**Comment by hybrid1969** [comment]
I have tried 6 times now and have followed the above while correcting the typos etc and nginx will not even respond on :80 hence the ERR_CONNECTION_REFUSED.

and as its not giving me any error logs im stuck.

Apache seems a lot more sensble option right now

**Comment by CokkocZateki** [comment]
I get the similar issue with apache if that helps lol

**Comment by Dessix** [comment]
I never downloaded h5bp, I used apache + php standard instead of doing any special mappings, and I let Let'sEncrypt / Certbot setup an HTTPS-Only redirection for my apache config. I made sure to enable `AllowOverrides All`.

**Comment by hybrid1969** [comment]
looks like I'm stuck with eve-wspace for the foreseeable future then if its that complicated to setup and that fragile a system.

**Comment by hybrid1969** [comment]
i will give that a try

**Comment by Dessix** [comment]
Admittedly, this installation guide is pretty insane compared to what it actually took.

**Comment by hybrid1969** [comment]
ive been searching for any setup guides all day and this was the only one i could find anywhere

**Comment by maraaaa** [comment]
Can you give us the output of `service nginx check`

Also what does /var/log/nginx/error.log say?

Finally what versions of ubuntu/nginx/php are you using? I doubt this
procedure will work on 16.04 version of ubuntu as many packages have
changed.

Best Regards,
Mara

**Comment by Ulaxidor** [comment]
@maraaaa If I try to use the h5bp as per your guide, I also get "ERR_CONNECTION_REFUSED."  In fact the h5bp nginx repository version refuses to host even the simplest host file on port 80 or 443.  In fact, those ports simply appear closed when using "nstat -at" or the "nmap localhost" commands.  That is why i simply abandoned the h5pb repository and have used the default version.  Is there a huge advantage to using the h5pb repository?

**Comment by Dessix** [comment]
My suggestion- make sure the expected systems for PHP are in place (MCrypt, and anything else that it claims are missing declarations) and then do `mysql --force -u USERNAME -pPASSWORD DATABASENAME < sde-*/*.sql` with the results of the extracted Fuzzworks DB dump.

**Comment by Gavin-Tremlor** [comment]
I was able to get it running but there are quite a few steps missing from the guide as written.  I found I needed to make edits to several files to get them talking to each other (www.conf, php.ini, nginx.conf, etc.)  I might pastebin them all and let you guys use them now that they are working.

**Comment by Gavin-Tremlor** [comment]
Also, you all should come join in the new Slack space (https://pathfinder-eve-online.slack.com).  Much easier to talk there.

**Comment by Ulaxidor** [comment]
@Gavin-Tremlor good idea. Invite me Ulaxidor@gmail.com

**Comment by CokkocZateki** [comment]
If anyone has a good apache conf example I can use,would be awesome.  I've
been trying for a week now to get pathfinder installed

**Comment by maraaaa** [comment]
Guys,

Seriously, post your os version and apache version. A lot has changed
between the last Ubuntu LTS and current LTS. What worked in 14.04 WILL NOT
work in 16.04.

Also, I think we need to come up with a Chef recipe to automate the
install...

Finally, I'm happy to hop on slack. Someone send me an invite at this
address please?

Happy path finding.

Mara

**Comment by Gavin-Tremlor** [comment]
@CokkocZateki 
If you give in and try it with nginx I can give you the config files I used.  I do know Apache better, but I like to learn new things.

Alternatively, I can walk you through doing it with Apache, but having not done it before it would be a bit of trial and error.  If you want to give it a shot hit me up in game (Gavin Tremlor).  I'm not busy today.

-G

**Comment by Gavin-Tremlor** [comment]
@maraaaa 

I need your email address to invite you.  Can't seem to get it from here.

**Comment by maraaaa** [comment]
Mara.arthie@gmail.com

Thanks!

**Comment by CokkocZateki** [comment]
@Gavin-Tremlor  bump me on slack and we can have a look together

**Comment by hybrid1969** [comment]
I am going to give this another try as i really do like the look of it.

Please add me to slack also hybrid1969@gmail.com

**Comment by Tupsi** [comment]
I have this running on ubuntu 14.04. So you can bug me for questions on slack as well. Although granted it's a 16. LTS since last week, but it worked! :-)

**Comment by axari** [comment]
I would like to try this as well, but I'm running into problems.

Ubuntu 14.04 LTS + Apache + PHP 5.5.9

I can't seem to get to /setup (404 error) to setup anything. I have installed the pre-req's, created the database, have the Eve SSD, etc. But I am obviously missing something.

Can someone add me to slack?  axari@live.com

**Comment by exodus4d** [comment]
@axari  The first thing I see is PHP 5.5.9 is deprecated: check https://github.com/exodus4d/pathfinder/wiki/Requirements

Looks like your .htaccess is wrong configured, please check the path for your index.php in there.

**Comment by exodus4d** [comment]
@maraaaa You know if this guide still works with the current v1.0.0 release?

**Comment by Tupsi** [comment]
it should, also I would advice just jumping to 16 LTS and be done with it. There you have all stuff relatively fresh (nginx 1.10, php 7, mariadb in the normal repo), so it makes stuff a lot easier. Granted you have to wade through the pain of getting to know systemctl, but you get over it, trust me :-)

**Comment by dnolen** [comment]
I'm stuck at installing Ngix,. I've added the repo but I'm running into permission errors 

git clone git@github.com:h5bp/server-configs-nginx.git /etc/nginx
Cloning into '/etc/nginx'...
Permission denied (publickey).
fatal: Could not read from remote repository.
