### ISSUE TITLE
Automatically populating $HTTP_RAW_POST_DATA is deprecated

### ISSUE THREAD

**Issue by maraaaa** [exodus4d/pathfinder#98]
Hello,

When logging in, I receive a 500 error and notice about emergency shutdown as shown in this screenshot:  http://i.imgur.com/ChQFnzU.png

There is a corresponding entry in the nginx log file:

    2016/02/11 13:37:49 [error] 15342#15342: *52 FastCGI sent in stderr: "PHP message: Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead" while reading response header from upstream, client: 75.166.26.243, server: pathfinder.m0ne.com, request: "POST /api/map/updateData HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "pathfinder.m0ne.com", referrer: "https://pathfinder.m0ne.com/map"

I did set `always_populate_raw_post_data` to -1 in /etc/php5/fpm/php.ini to no avail.  (I'm not sure what "the php://input stream" is... is that in instead of fastcgi://unix:/var/run/php5-fpm.sock in pathfinder.conf?)

Has anyone run into this before?

This seems to be relevant but the answer seems to be to set always_populate_raw_post_data = -1...  https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/

PHP Info
    # php -v
    PHP 5.6.18-1+deb.sury.org~trusty+1 (cli)
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

Thanks!

**Comment by Raykazi** [comment]
I've seen the error, and it worked after I set it to -1 and uncomment the line.

**Comment by maraaaa** [comment]
Interesting.  After a full system reboot it works...

I restarted nginx after making the php.ini change, ,maybe php5-fpm service needs to be restarted as well?

Anyway, thanks for the advice!

**Comment by exodus4d** [comment]
Yeah I had the same problem after switching to PHP7. Setting to -1 works for me too:
http://46.101.119.66/info.php
