### ISSUE TITLE
Signature sharing across maps 

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#980]
It'd be nice to be able to share signatures across maps.

Use case: tons of farmholes on different maps, would like to know their signatures when we roll into them.

**Comment by tralafiti** [comment]
+1 we would love this feature too :)

**Comment by CalMatar** [comment]
What I do is lock the holes I want into a corner of the map so if I suddenly have a connection going to that corner the I know I have connected to one of those holes. This is the easiest way to do it and it doesn't take anything extra other than adding the signatures to the map and pinning them. It is very effective and you can have them out of the way, for me it is the lower left corner.

**Comment by porowns** [comment]
@CalMatar that's not really what we're saying here

**Comment by CalMatar** [comment]
@porowns then what are you saying, please explain.

**Comment by porowns** [comment]
If I have wormhole A on map A, and wormhole A on map B, the signatures are not shared, despite having access to both maps. It would be nice for the signatures to be shared, or a way to share them.

**Comment by CalMatar** [comment]
I am still confused by what you mean "shared". If you have multiple maps and you enter information on one map in a signature that information is available on any other map you have that signature on. At least that was the case for the maps that I had prior to me losing my WH. I can not currently log in so I can not test anything at this time but we used to do this on both the public PF and a private server on multiple maps. We had our main hole and several "friend" holes we had pinned that we came across from time to time that the information was only entered into one map but was on all affected maps, or at least I remember it being that way.

**Comment by tralafiti** [comment]
> the information was only entered into one map but was on all affected maps

Just checked it again - it does not affect other maps ;-). We would like to share intel (structures and free text notes) between maps

**Comment by porowns** [comment]
^^ can confirm that this is the behavior we have as well.

**Comment by CalMatar** [comment]
Is this is on the Public Pathfinder or is this on a private server on separate login maps?

**Comment by NormannK** [comment]
we have that on our self hosted pf too,
if we have 2 maps and on both maps is the same WH and we add signatures on one map its not shown on the other map.

**Comment by ozzyogkush** [comment]
This issue happens when you export a map and import it into another one - signatures are not preserved. Almost defeats the purpose.
