### ISSUE TITLE
/setup

### ISSUE THREAD

**Issue by troneleck** [exodus4d/pathfinder#99]
Hi

I try to install Pathfinder on a webserver but i got some errors.

First one is i cant use www.[xyz]/setup.  (xyz is replaced with my webside)  I also used the setup link from the "Setup mode active" line.
I got a "Not Found" message (Firefox / IE).

Second is 2 404 errors  -getCaptchaImage and -logout.

Im not a skillet user...i just try to put this on a webserver folder....find after reading i have to delete the .htacces file...side is running but with this errors.

Wat i have to do to fix it? (if possible a answer for a nooblike user :) )

**Comment by exodus4d** [comment]
Do not simply delete the .htaccess file! If you are **not** planing to run Pathfinder over HTTPS, delete the .htaccess file and **rename** ".htaccess_HTTP" to ".htaccess" and use this one. This file is absolutely required for *Apache* Webservers, otherwise the URL-routing engine can not work.

**Comment by troneleck** [comment]
**Ok this fixed the setup problem.**

Now im not able to autoconfig the database. 

And the Capture error is now 500 getCaptureImag.

![path-1](https://cloud.githubusercontent.com/assets/17239456/13052626/378076ca-d400-11e5-8342-720769298a7a.png)
![path-2](https://cloud.githubusercontent.com/assets/17239456/13052629/39ce164e-d400-11e5-8bc6-fef0b76ba180.png)
![path-3](https://cloud.githubusercontent.com/assets/17239456/13052631/3cab30d6-d400-11e5-887f-74a4dba45c33.png)

**Comment by exodus4d** [comment]
The warnings in the first image can be ignored and are not a problem. In some cases the server version can not be detected.
But your MySQL version 5.5.47 is a problem. v.5.6 or higher is required for some functions. Upgrade to 5.6 or higher and you should be able to auto-setup everything correctly.
